### ISSUE TITLE
GPU Nodes: every graph looks the same 

### ISSUE THREAD

**Issue by myshzzx** [processhacker/processhacker#1003]
![snipaste20211007_161356](https://user-images.githubusercontent.com/2025090/136347350-f0ac4b3f-989e-4201-9b02-6f809d9c8a7c.jpg)

**Comment by dmex** [comment]
Try changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` setting to 1

**Comment by dmex** [comment]
> Why does the setting been disabled by default?

It requires support for perfmon counters not available on Windows 7 and 8.
