### ISSUE TITLE
[Feature request] Processes grid - Totals row

### ISSUE THREAD

**Issue by KyleKolander** [processhacker/processhacker#1005]
**Is your feature request related to a problem? Please describe.**

It's great to see rolled-up summaries for individual processes (and their respective children), but an overall system-level summary is missing and would provide a lot of value.  
<br />

**Describe the solution you'd like**

I would like to see a new fixed row at the top of the Processes grid that represents an overall system-level summary of numerical columns (similar to the rolled-up summaries for individual processes).  I think a checkbox to toggle it on/off would be great, but a setting in Options would work, too.  If this summary row is fixed/frozen as the top row, it would be unaffected by sorting and would remain at the top regardless.
<br />

**Describe alternatives you've considered**

There really isn't one.  Some system-level summary information is provided in the status bar on the Processes grid, and some summary information is available on the System information window (but that's a different window).
<br />

**Additional context**

Here's a mock-up.  For each numerical column, it's a simple numerical sum of all rows.  The CPU column is a slight exception, as I've excluded the System Idle Process from the total.  More often than not, that is the appropriate (or at least _most useful_) behavior.  I also gave the Totals row a black background so it would stand out from the rest, but this is merely cosmetic and could likely be configurable as well (time permitting).  I'm biased, but I like how it looks and believe it would provide substantial benefit.

![Process Hacker - Totals](https://user-images.githubusercontent.com/22461822/136709206-f171edd1-66ff-4073-871c-fce6de7308bf.png)

**Comment by dmex** [comment]
It could show the totals in the column headers?

![image](https://user-images.githubusercontent.com/1306177/144560728-ff303727-36dd-472c-86ae-4b9c9519c002.png)

This is what Task Manager does:
![image](https://user-images.githubusercontent.com/1306177/144560833-7ec42643-5c14-4557-ad26-0ec87b7b2984.png)

**Comment by KyleKolander** [comment]
That would be great!  Just want an easy way to see roll ups for the entire system. I use this tool every day.  Thanks for developing it and considering my feature requests!

**Comment by dmex** [comment]
This was added to recent nightly builds (searching will also filter the totals to those results) 👍

**Comment by KyleKolander** [comment]
SWEET!  Just got latest and it appears to be working.  Thanks man!

**Comment by KyleKolander** [comment]
@dmex - looks like I spoke to soon.  There is a bug with the header totals.  When you collapse, the overall total for the collapsed (visible) row includes itself and the individual totals of all its collapsed hidden rows.  It appears to be double counting the individual totals of the collapsed hidden rows.

I can supply screenshots, but you'll easily be able to reproduce this.

Do I need to open a new issue?

**Comment by dmex** [comment]
> When you expand a row, that row's value no longer includes the sum of it's child rows, but the sum of it's child rows is still "there"

Do you have 'include usage of collapsed processes` enabled?

> Do I need to open a new issue?

Yes

**Comment by KyleKolander** [comment]
Yes, I do have that enabled.

![options](https://user-images.githubusercontent.com/22461822/147119668-32ffce82-59fe-4d30-9c14-53b9851dcc11.png)

OK, I'll open a new issue.  Thanks!

**Comment by KyleKolander** [comment]
Here ya go: #1070

**Comment by dmex** [comment]
> the header total appears to be decreasing by the amount that was "lost" from the expanded row

It looks like those statistics are being duplicated/counted twice and not matching the columns? The searchbox is tied to the column headers, so launch notepad.exe and filter the processes and verify the header totals exactly match the values for notepad.exe.

> Yes, I do have that enabled.

You should probably disable that option for now as a workaround.

**Comment by MagicAndre1981** [comment]
> This was added to recent nightly builds (searching will also filter the totals to those results) +1

how can I disable it? Is there an option? Looks wired and values are wrong
 
![processhacker_cpu_column](https://user-images.githubusercontent.com/8274816/147204477-e19bcc0f-5e3a-4ab6-b705-746fc3d68ee6.png)
