### ISSUE TITLE
The backing-file for the real-time session "PhEtRundownLogger" has reached its maximum size.

### ISSUE THREAD

**Issue by n0101** [processhacker/processhacker#1009]
No idea if this is an actual problem or not, but thought I should report it.  

In Event Viewer I see the following warning generated when PH is running, even idle in the systray:

Log Name:      Microsoft-Windows-Kernel-EventTracing/Admin
Source:        Microsoft-Windows-Kernel-EventTracing
Date:          10/12/2021 11:58:56 AM
Event ID:      1
Task Category: Logging
Level:         Warning
Keywords:      Session
User:          SYSTEM
Computer:      ****
Description:
The backing-file for the real-time session "PhEtRundownLogger" has reached its maximum size. As a result, new events will not be logged to this session until space becomes available. This error is often caused by starting a trace session in real-time mode without having any real-time consumers.

```
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Kernel-EventTracing" Guid="{b675ec37-bdb6-4648-bc92-f3fdc74d3ca2}" />
    <EventID>1</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>1</Task>
    <Opcode>10</Opcode>
    <Keywords>0x8000000000000010</Keywords>
    <TimeCreated SystemTime="2021-10-12T15:58:56.9599540Z" />
    <EventRecordID>240</EventRecordID>
    <Correlation />
    <Execution ProcessID="4" ThreadID="4552" />
    <Channel>Microsoft-Windows-Kernel-EventTracing/Admin</Channel>
    <Computer>****</Computer>
    <Security UserID="S-1-5-18" />
  </System>
  <EventData>
    <Data Name="SessionName">PhEtRundownLogger</Data>
    <Data Name="ErrorCode">3221225864</Data>
    <Data Name="LoggingMode">4194560</Data>
  </EventData>
</Event>
```

**Comment by dmex** [comment]
Fixed in the latest nightly update 👍
