### ISSUE TITLE
Setting thread priority to 'Below normal' has no effect

### ISSUE THREAD

**Issue by MSxDOS** [processhacker/processhacker#1012]
Setting thread priority to 'Below normal' in process properties -> Threads menu has no effect, priority doesn't change. I don't see anything in Help -> Log.
I assume this is on PH side because [SetThreadPriority](https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreadpriority) with `THREAD_PRIORITY_BELOW_NORMAL` works fine here.

**Comment by dmex** [comment]
There was a type mismatch... These types should have been LONG instead of ULONG and THREAD_PRIORITY_BELOW_NORMAL was equal to ULONG_MAX (the error case) instead of LONG_MAX.

This has been fixed in the latest nightly update 👍
