### ISSUE TITLE
Click ‘Started services’ to restart the computer 

### ISSUE THREAD

**Issue by MeeSong** [processhacker/processhacker#1013]
**Describe the bug**
Click ‘Started services’ to restart the computer.

**To Reproduce**
![bug](https://user-images.githubusercontent.com/6848759/138050567-2fa82257-ab66-4a52-b290-d08648e75014.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1(19043.1288)
 - Version: Process Hacker 3.0.4365 (76d0057)

**Comment by dmex** [comment]
Fixed in the latest nightly update 👍
