### ISSUE TITLE
Search processes (Ctrl+K): clearing using the keyboard

### ISSUE THREAD

**Issue by d0vgan** [processhacker/processhacker#1014]
**Is your feature request related to a problem? Please describe.**
The Search processes (Ctrl+K) is a useful feature, especially using the keyboard: I just need to press Ctrl+K and then type some characters of a process name I'm interested in.
When I no more need the processes to be filtered by their names, I want to clear the Search processes field using the keyboard - and it's not straightforward. When I press Ctrl+BS (Ctrl+Backspace), it inserts an unreadable character instead of deleting the previous word. When I press Esc, it closes (hides) the whole Process Hacker window.
Also, what is the way of switching the keyboard focus between the Search processes (Ctrl+K) and the processes list below? Pressing Tab does not seem to have effect; pressing Ctrl+K again also does not seem to...

**Describe the solution you'd like**
Let's process Ctrl+BS by handling VK_BACK on WM_KEYDOWN and by handling 0x7F on WM_CHAR (yes, the latter is the reaction on pressing Ctrl+BS in an edit control. I think we all should ask Microsoft what was the reason and the purpose of such a _genious_ behavior). The desired behavior is to make Ctrl+BS to delete the previous word similarly to how Ctrl+Del deletes the next word.
Let's make Tab or repeating Ctrl+K to switch between the Search processes (Ctrl+K) and the processes list.

**Describe alternatives you've considered**
As an alternative, a subclassed version on an edit control may be presented in Process Hacker's code to make any edit control in it to handle Ctrl+BS properly - i.e. to delete a previous word instead of inserting an unreadable character.

**Comment by d0vgan** [comment]
Thank you for the Ctrl+BackSpace implementation!
Is there a separate commit to deal with the connected question? -- 
> Also, what is the way of switching the keyboard focus between the Search processes (Ctrl+K) and the processes list below? Pressing Tab does not seem to have effect; pressing Ctrl+K again also does not seem to...

**Comment by dmex** [comment]
Fixed 👍

**Comment by d0vgan** [comment]
Thank you! May these changes be included in the nightly build https://processhacker.sourceforge.io/nightly.php ?

**Comment by dmex** [comment]
> these changes be included in the nightly build

The nightly hasn't updated yet but they will be when it does.

**Comment by dmex** [comment]
> these changes be included in the nightly build

The nightly was updated with the changes.
