### ISSUE TITLE
In the cfg window of peview, the serial number starts with 2

### ISSUE THREAD

**Issue by Flyour** [processhacker/processhacker#1017]
**Describe the bug**
In the cfg window of peview, the serial number starts with 2

**To Reproduce**
1. just use peview to open a pe file，and then open the cfg window

**Expected behavior**
it should starts with 1

**Screenshots**
![image](https://user-images.githubusercontent.com/30471484/138832958-2fe06ff2-3d63-4860-abda-5f04ead228cf.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 20h2

**Additional context**
...

**Comment by dmex** [comment]
Fixed in the latest nightly update 👍
