### ISSUE TITLE
Windows 11 suppport 

### ISSUE THREAD

**Issue by dankyoulord** [processhacker/processhacker#1018]
Was wondering if it'll be updated to support Windows 11 anytime soon.

**Comment by dmex** [comment]
I've been running PH on Windows 11 without crashes or other major issues.

**Comment by krokofant** [comment]
I've been running 3.0.3771 fine since after an upgrade to Windows 11.

**Comment by dmex** [comment]
> Have to click the shortcut in the Start menu multiple times
> PH force closes after showing the main screen for me. I have all security options (including memory integrity) turned on.

I can't reproduce either of these problems with any Win11 machines.
