### ISSUE TITLE
Build error with VS 2022

### ISSUE THREAD

**Issue by xwnb** [processhacker/processhacker#1023]
As the title.

**Comment by suuhm** [comment]
same with 2019 with the newest pull

**Comment by dmex** [comment]
What's the error message?

**Comment by suuhm** [comment]
Ok found the problem, of missing Definitions in winnt.h file Windows SDK 10. Just comment out or ifdefine for windows 11 libs?
Just made a PR here for it: https://github.com/processhacker/processhacker/pull/1024

**Comment by xwnb** [comment]
> What's the error message?
@dmex  as mentioned by @suuhm (Thanks)
@suuhm If we can upgrade `CustomBuildTool` to support VS 2022/Win 11 with latest SDK as well ([CustomBuildTool/Utils.cs](https://github.com/processhacker/processhacker/blob/master/tools/CustomBuildTool/Utils.cs)) it would be better.

**Comment by dmex** [comment]
The build errors with VS 2022 were all fixed 👍
