### ISSUE TITLE
mouse overclock mode

### ISSUE THREAD

**Issue by MeKLiN2** [processhacker/processhacker#1027]
on windows 7 the threads for .dll's: cdd.dll and winsrv.dll are 'normal with an inactive winsrv.dll thread and inactive cdd.dll thread at highest and -12, and to get even the regular mouse priority of windows 10 u would need to edit it as cpu back then would actually be overloaded with all of the spyware on windowses... can you make a mode for this?

**Comment by dmex** [comment]
> get even the regular mouse priority of windows 10 u would need to edit it as cpu back then would actually be overloaded

What does this mean in english?
