### ISSUE TITLE
When trying to run Process Hacker as admin, it won't launch.

### ISSUE THREAD

**Issue by IvanHuylo** [processhacker/processhacker#1029]
Not able to launch Process Hacker 2 64bit as admin, 32bit works fine and I even reinstalled the program and restarted my PC. Also, when I try to inject a DLL with the 64bit version, it opens the file explorer to find the DLL and crashes Process Hacker.

Just tried to launch 64bit Process Hacker 2 as admin from the shortcut on desktop, which didn't work. Tried to inject a DLL as simple user, but as soon as I see the file explorer popping up, it crashes Process Hacker. Went into the folder where it is installed, running as admin didn't work too for the 64bit version, but the 32bit one worked for some reason and I was able to inject a DLL without it crashing Process Hacker.

I expected Process Hacker 2 64bit to run as admin and being able to inject a DLL into a program without crashing.

My OS is Windows 11 21H2.

As mentioned before, reinstalling didn't help and rebooting the PC didn't do it too.

**Comment by IvanHuylo** [comment]
A little update on the situation.
It fixed itself somehow, I can't explain how because I just wrote that bug report here and went watching YT videos and waiting for an answer. Then I decided to try it again and it worked.

**Comment by Biswa96** [comment]
Process Hacker 2 is old. Try the new nightly builds from here https://processhacker.sourceforge.io/nightly.php

**Comment by IvanHuylo** [comment]
> Process Hacker 2 is old. Try the new nightly builds from here https://processhacker.sourceforge.io/nightly.php

Just installed, seems to work fine out of the box, I'm going to stick with it for now. Ty for your suggestion.
