### ISSUE TITLE
Disabling kernel-mode driver doesn't work

### ISSUE THREAD

**Issue by BartiX8530** [processhacker/processhacker#1030]
Process hacker is sometimes used for hacking in online games, and some anti-cheat systems (like easy anti-cheat that Fortnite uses, or Hackshield) recognize it and require it to be turned off. The problem is that the easy anti-cheat scans for kernel driver of the process hacker which turns on every time you start up your PC. When i tried to disable kernel-mode in Process hacker options it didn't work, even after rebooting the whole PC. Reinstalling or uninstalling doesn't work. Trying to disable the service itself in cmd returns failure, beacuse the driver is redeemed as unstoppable and unpausable. You cannot delete it since it's already marked for deletion, but that doesn't do anything when rebooting the PC. The only way I've found to turn it off is by going to safe mode and deleting it from there. I used the latest recommended version of Process hacker.

**Comment by dmex** [comment]
> some anti-cheat systems (like easy anti-cheat

I play games with EAC and PH perfectly fine.

> turns on every time you start up your PC

This doesn't make sense because the driver has never been autostart and has never been configured as boot start.

> rebooting the whole PC. Reinstalling or uninstalling doesn't work

It sounds like you have a corrupted windows installation because everything you've posted makes no sense. Uninstalling and rebooting has always worked and impossible to screw up unless your machine is corrupted.

**Comment by Chaython** [comment]
> > some anti-cheat systems (like easy anti-cheat
> 
> I play games with EAC and PH perfectly fine.

Halo Infinite will crash, others will warn you/stop you from playing.

**Comment by dmex** [comment]
> Halo Infinite will crash

343 claim they're working on it: #1037 

> others will warn you/stop you from playing.

What games?

**Comment by Chaython** [comment]
> What games?

Fortnite, there was some others but I forget.
Destiny 2 banned me, for having it open...
Anyways, if you're a gamer, obviously don't leave a tool that allows script injecting/memory manipulation to run, while using an anti-cheat.
