### ISSUE TITLE
'Open file location' and 'Properties' context menu items for process modules are bugged

### ISSUE THREAD

**Issue by MSxDOS** [processhacker/processhacker#1031]
For any module on process properties -> Modules tab clicking `Open file location` always opens the user profile folder 
and clicking 'Properties' throws `PE Viewer - Unable to open the file.` message box saying that the path doesn't exist.

Both seem like recent regressions as I didn't have them until one of the latest (nightly) updates.

**Comment by dmex** [comment]
> Both seem like recent regressions

There was a regression for those menus on Windows 7 but not Win8/10/11. It's already been fixed but we have to wait for the buildbot to get updated.

**Comment by dmex** [comment]
Fixed in latest nightly build
