### ISSUE TITLE
Build error with VS 2022 Community

### ISSUE THREAD

**Issue by NexusZ001** [processhacker/processhacker#1032]
<img width="959" alt="ph2" src="https://user-images.githubusercontent.com/94359221/141759104-374ab1a5-fdac-4f0f-a333-4432bad848ce.png">

**Comment by dmex** [comment]
Install the latest Windows SDK 22000

**Comment by NexusZ001** [comment]
> Install the latest Windows SDK 22000

Thank you dmex it work
