### ISSUE TITLE
can someone help me processhacker-2.39-src cannot compile

### ISSUE THREAD

**Issue by MONIKAK2** [processhacker/processhacker#1033]
<img width="956" alt="p1" src="https://user-images.githubusercontent.com/94373938/141791362-b934f5c0-cfcd-405a-8523-f409716ca858.png">
<img width="959" alt="p2" src="https://user-images.githubusercontent.com/94373938/141791371-34d68aa5-4a76-4190-a918-08da2ab6b047.png">

**Comment by MONIKAK2** [comment]
<img width="956" alt="p1" src="https://user-images.githubusercontent.com/94373938/141791298-7aac1826-683e-45e2-8172-3cff7f2da24e.png">
<img width="959" alt="p2" src="https://user-images.githubusercontent.com/94373938/141791307-900a5a09-e8fa-4142-97a7-bf65990cc321.png">

**Comment by Biswa96** [comment]
Please use latest master branch.

**Comment by MONIKAK2** [comment]
> Please use latest master branch.
I don't like v3.0 i like v2.9 can you help me

**Comment by dmex** [comment]
You'll have to backport all the patches and fixes for newer versions of Visual Studio and newer Windows SDKs or use older versions of VS and SDKs.
