### ISSUE TITLE
Process Hacker closes almost immediately after opening the first time

### ISSUE THREAD

**Issue by danlebaron** [processhacker/processhacker#1034]
On open, most time process hacker will immediately close. I can reopen and most times it will stay launched, but frequently will randomly close after.  Any ideas, this happens over multiple systems.  We are on the current release.

**Comment by dmex** [comment]
What version of PH and which version of Windows?

You should also check for malware/rootkits since they've always targeted PH.

**Comment by dmex** [comment]
> process hacker will immediately close. I can reopen and most times it will stay launched, but frequently will randomly close after.

BTW if it were crashing then you would see the crash dialog, so unless you're seeing the crash dialog then it's getting terminated by malware/spyware:

![image](https://user-images.githubusercontent.com/1306177/142875944-c482f40a-9bd3-439a-8809-beb68d687c4e.png)
