### ISSUE TITLE
Bungie bans

### ISSUE THREAD

**Issue by C0D3-M4513R** [processhacker/processhacker#1035]
First sorry for misusing the issue section like this. This should be an issue of BattlEye, not PH.
>Process Hacker has been compatible with VAC, EAC and BattlEye since 2016[.]

>Process Hacker [is] compatible with anti-cheat and [...] VAC, EAC and BattlEye (used across thousands of games) do not consider Process Hacker a cheat.
[source](https://github.com/processhacker/processhacker/issues/646#issuecomment-671032295)

I have just gotten banned from Destiny 2, which uses BattlEye. I used Process Hacker and still am a big fan of the amount of information displayed in PH's code and interface. Could it be, that Process Hacker is getting people banned again? 

I literally had PH open for 10-15 min. (while Destiny 2 was open) to open a system command prompt, to test something.

**Comment by dmex** [comment]
BattlEye doesn't ban users for PH... Bungie does.

I tried to contact Bungie a few years ago to sort out any compatability issues and they closed the ticket without saying anything except mentioning a policy (a threat) to ban my steam account if I contacted them again.

**Comment by C0D3-M4513R** [comment]
I had one account banned. The communication consisted of: An automatic E-Mail notifying me, that they received my appeal and An automatic E-Mail notifying me, that my appeal was closed.
No Ban reason was provided. NONE.

**Comment by dmex** [comment]
> automatically VAC banned on my account

Were you banned by Valve or by Bungie? afaik destiny doesn't use VAC/steam game banning but instead uses their own account system so destiny bans don't show up on steam.

**Comment by C0D3-M4513R** [comment]
> Were you banned by Valve or by Bungie?

This is from steam.
![image](https://user-images.githubusercontent.com/28912031/142691517-b6535ba2-0235-4198-96f4-64c2fa26c905.png)
And then from Destiny in game, after pressing enter, when launching the game.
![image](https://user-images.githubusercontent.com/28912031/142691710-89c3fc6a-c010-4ee2-a8f5-47e538ac757a.png)

**Comment by Masamune3210** [comment]
From that pic it looks like its Bungie doing the banning here, I would assume Steam would tell you if it was a VAT ban if it was

**Comment by dmex** [comment]
> This is from steam

Valve removed the VAC bans for PH years ago, game bans from developers are a different story and they can't do much about those.

I did ask Valve to look into Bungie's abuse of Steam banning after threatening to ban my account (when I never owned or even play Destiny) after contacting Bungie support but I won't know when/if anything gets done about companies abusing Valve services.

> The communication consisted of: An automatic E-Mail notifying me, that they received my appeal and An automatic E-Mail notifying me, that my appeal was closed.
No Ban reason was provided. NONE.

At the end of the day, they're abusing and attacking their own customers and they've given you a lifetime reminder to never support them or purchase their products and evidence to show everyone else that Bungie are scammers. Nobody else is doing what Bungie are doing for good reason, for the simple reason that PH isn't a game cheat.

**Comment by akanealw** [comment]
Sorry to revive this but Bungie reversed the bans on people using Process Hacker.

![image](https://user-images.githubusercontent.com/651352/151639064-7b75ef33-1eaa-4ebb-bc80-edf40c5c011b.png)

**Comment by C0D3-M4513R** [comment]
@akanealw can you please state the source?
Also: can confirm.

**Comment by akanealw** [comment]
This week's Destiny update, about halfway down.
https://www.bungie.net/en/News/Article/50975

**Comment by garoto** [comment]
Holy shit, quite impressive considering the state of the so-called "gaming industry".

**Comment by technic-Angel6644** [comment]
> @ZeldrexK0DE If you got banned in jan2021, there is little you can do. Bungie will not listen to a second ban appeal, and this unban wave targeted players, who were banned by battleye. Battleye was not in use in jan 2021. Unless you manage to actually speak to a human being at bungie, there is little you can do.

This is true, I was banned around January 2021, and thus I am not part of the bans that Bungie is reversing
