### ISSUE TITLE
Right path of registry for Service DLL

### ISSUE THREAD

**Issue by LunarResearch** [processhacker/processhacker#1038]
Hello.
Presently, the path for the registry for Service DLL is:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Service_Name\Parameters\ServiceDll
But there are services that do not have a folder Parameters, and their path to Servise DLL is:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Service_Name\ServiceDll
An example is the service DoSvc:
My tools (KernelExplorer)
<a href="https://ibb.co/tpQL140"><img src="https://i.ibb.co/9HcZdNx/1.png" alt="1" border="0"></a>

Your tools (ProcessHacker)
<a href="https://imgbb.com/"><img src="https://i.ibb.co/2K1sVjh/2.png" alt="2" border="0"></a>

Please make the appropriate changes to the code.

**Comment by dmex** [comment]
> But there are services that do not have a folder Parameters, and their path to Servise DLL is:

Those keys are checked on Windows 8 but not Windows 10... Adding these checks on Windows 10 for 1 service isn't worth the performance cost.
