### ISSUE TITLE
Setting csrss affinity fails

### ISSUE THREAD

**Issue by Zusier** [processhacker/processhacker#1039]
**Describe the bug**
Trying to set an affinity to csrss.exe does not apply, even with the kernel mode driver enabled.

**To Reproduce**
1. Right click 'csrss.exe'
2. Affinity > Set Affinity
3. Set an affinity and click Ok
4. Go back to Set Affinity and see the affinity did not apply

**Expected behavior**
The affinity should apply like any other process.

**Desktop:**
 - OS: Windows 10
 - Version: 19042.631
 
 **Additional Information**
 Works on 2.x versions

**Comment by Masamune3210** [comment]
That might be a limitation of Windows since its set as a critical process, just guessing

**Comment by Zusier** [comment]
Just updated the post, it does work on 2.x versions. It's just that affinities don't save on 2.x which makes it a bit troublesome to repeat on startup

**Comment by dmex** [comment]
> it does work on 2.x versions

As a workaround disable the UserNotes plugin. It takes ownership of the Affinity dialog but then can't change affinity for system processes. Disabling the plugin will let you change the affinity but then you won't be able to save it.

Note the TODO comment:
https://github.com/processhacker/processhacker/blob/9d080f6ac952dbbfee6b6f6137deae8535734c13/plugins/UserNotes/main.c#L1296-L1301

I'm testing a patch that'll fix the issue in the next nightly build.

**Comment by Zusier** [comment]
Thank you! 👍

**Comment by dmex** [comment]
Fixed 👍
