### ISSUE TITLE
Weird font of the tabs

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#1040]
**Describe the bug**
The tabs font looks too big

**To Reproduce**
1. Open Process Hacker main window 
2. Look at the font on the tabs

**Expected behavior**
Previous behavior was better where the font was default

**Screenshots**
![123](https://user-images.githubusercontent.com/24621645/142989309-d536252b-1e9f-4710-9994-8abbf1ab5ed8.png)
![234](https://user-images.githubusercontent.com/24621645/142989699-104d3726-6ed5-4ff7-90fd-34f257ae4a2a.png)

**Desktop (please complete the following information):**
 - Windows
 - 21H2 19044.1348 x64

**Additional context**
Is it something on my side or it was planned change?

**Comment by dmex** [comment]
> Is it something on my side or it was planned change?

The version you're using hasn't been released. If you're building from source then things are going to break because not everything has been committed to github yet.
