### ISSUE TITLE
Protected Process Light (PPL)

### ISSUE THREAD

**Issue by NightRaidGamer** [processhacker/processhacker#1044]
Hello i would like to know if it is possible to protect/unprotect any process running using PPL? if not, how about implementing it?

**Comment by dmex** [comment]
> is possible to protect/unprotect any process running using PPL

It's a single bit flag in the EPROCESS structure that isn't patch-guard protected so anyone/anything can protect/unprotect PPL processes. It's especially common for kernel cheats targeting EAC and BattlEye to patch that byte and block those anti-cheats.

> how about implementing it?

This was a feature included with PH 1.x for XP and Vista but was removed about 12 years ago before Windows required driver signing - That feature won't ever be re-added to PH.

**Comment by NightRaidGamer** [comment]
> It's a single bit flag in the EPROCESS structure that isn't patch-guard protected so anyone/anything can protect/unprotect PPL processes

if i use the latest version of process hacker with all the extra plugins, how do i do it ? could you briefly explain please? 

> This was a feature included with PH 1.x for XP and Vista but was removed about 12 years ago before Windows required driver signing - That feature won't ever be re-added to PH.

if i use 1x process hacker on windows 10/11, will it work? this feature has been removed from the hacker from process 2xx onwards, does it still remain in version 1xx?

**Comment by dmex** [comment]
> if i use the latest version of process hacker with all the extra plugins, how do i do it ? could you briefly explain please?

No such thing exists.

> if i use 1x process hacker on windows 10/11, will it work? 

No, those drivers were never signed.

**Comment by Biswa96** [comment]
> This was a feature included with PH 1.x for XP and Vista but was removed about 12 years ago

May I ask in which commit it was added/removed? I have some [mischievous relationship](https://github.com/Biswa96/WslReverse) with that PPL thing.

**Comment by dmex** [comment]
> May I ask in which commit it was added/removed?

CBF digging through 5000 commits from 10 years ago. Sorry.

**Comment by masthoon** [comment]
Looks like PPL feature was not compiled on signed build (def _KPH\_CONFIG\_CLEAN_) and removed in this commit:

https://github.com/processhacker/processhacker/commit/bf88ce7d1ab04d3e5ea4365ead7caf6e6c112ef2#diff-db2e005e942f4283c5a6272b5656e568980516a86617e971cb7f9bdb1f54debf
