### ISSUE TITLE
Kernel driver not loading on Windows Release Preview (21H2)

### ISSUE THREAD

**Issue by adamaru** [processhacker/processhacker#1045]
**Describe the bug**
Recently on each startup I started to receive an error message from ProcessHacker:
```
[Window Title]
Process Hacker

[Main Instruction]
Unable to verify the kernel driver signature.

[Content]
Do usługi lub funkcji przekazano nieprawidłowy parametr.

You will be unable to use more advanced features, view details about system processes or terminate malicious software.

[Close]
```

Message in the middle in English should probably be: `An invalid parameter was passed to a service or function`.

I thought that it might be problem with new version, but I tried older one (`3.0.4373`) and it is affected as well.

It seems related to:
* https://github.com/processhacker/processhacker/issues/997 
But I don't have core isolation enabled

* https://github.com/processhacker/processhacker/issues/340
But I don't have any AV, and Windows Defender is disabled.

It seems directly related to the fact that I'm on release preview version of Windows 10.
I checked it on mainstream version of Windows 10 (20H2 build 19042.1387) and no error appears.

I think it's worth investigating now, to avoid letting it break when the update arrives to mainstream.

**To Reproduce**
1. Install newest Release preview of Windows 10 (21H2)
2. Install latest nightly version of ProcessHacker (currently v3.0.4399)
3. `Enable kernel-mode driver` in options
4. Restart system
5. See error

**Expected behavior**
Error does not appear, kernel driver loads normally.

**Screenshots**
![2021-11-29 11_22_20_082 ProcessHacker Process_Hacker](https://user-images.githubusercontent.com/11278536/143850765-0bb4718c-1507-4859-a438-0ceb73c7f045.png)

**Desktop:**
 - OS: Windows 10
 - Version: Release preview 21H2  build 19044.1387

**Comment by dmex** [comment]
> 21H2 build 19044.1387

I checked that version and there were no errors, so it would be something on your machine modifying the executable or the signature file causing the verification failure. 

There was a similar report last year about this and they found a rootkit/bitcoin miner that would suspend when running task manager or PH so it's probably that same variant - Microsoft and Antivirus companies have never once done anything to stop malicious software attacking PH, so your AV probably isn't showing the rootkit/bitcoin miner during scans... you'll have to check manually.

**Comment by adamaru** [comment]
I updated another computer to the same Windows version and it works, so you're right.. Sorry ;)

Thanks for the heads-up. I scanned my computer with all sorts of scanners (AdwCleaner, Avast (albo pre boot), Malware Anti-rootkit) and nothing came up. I'll try to isolate this issue and if I find anything I'll let you know.

**Comment by dmex** [comment]
> I'll try to isolate this issue and if I find anything I'll let you know

I've come across a few kernel caching issues with binaries containing CFG bitmaps on Windows 10 but nothing recent.

**Comment by adamaru** [comment]
I just upgraded Nvidia drivers (496.76 -> 497.09) and MsiAfterburner (4.6.3 beta -> 4.6.4) along with RivaTuner (7.3.2 beta -> 7.3.3) and the problem has gone away.

I was already thinking that RivaTuner probably could cause such issues as it hooks itself to pretty much everything, but I recently added ProcessHacker to its blacklist, so I thought I was safe.
Also I don't have MsiAfterburner and RivaTuner on my second computer, so that pretty much confirms it - **MsiAfterbuner (4.6.3 beta) or RivaTuner (beta 7.3.2) was the culprit** ;)
