### ISSUE TITLE
PH does not display heap segments

### ISSUE THREAD

**Issue by GflowerG** [processhacker/processhacker#1050]
The memory tab does not show that some private regions are used by the heap. (in the "Use" column).

The "Sysinternals VMMap" application shows that these memory regions are being used by the heaps.

The simplest example for diagnostics - memory region of the "notepad.exe" buffer. The location of this buffer should be on the heap, but if you find the entered string in memory, it will be in an unnamed private memory region. (**VMMap shows that this region is being used by the heap**).

In addition, PH does not display the "Portable Executable" sections and TEB like the VMMap does.

OS: Win11.

**Comment by dmex** [comment]
> The memory tab does not show that some private regions are used by the heap.

The memory tab shows the underlying Windows VAD layout. Heap blocks are all located within 1 VAD allocation which grows or shrinks. You would need to use the `Right click > Process > Miscellaneous > Heaps` menu to see heap information (It's somewhat limited but more could be added if needed).

> PH does not display the "Portable Executable" sections and TEB like the VMMap does.

VMMap creates fake pseudo entries for the TEBs and image sections that don't actually exist... We thought it was better to show the actual real layout, so developers can more easily check their code against PH and also review what allocations are sharing the same VAD and that they have appropriate memory protection?

**Comment by GflowerG** [comment]
> The memory tab shows the underlying Windows VAD layout. Heap blocks are all located within 1 VAD allocation which grows or shrinks. You would need to use the `Right click > Process > Miscellaneous > Heaps` menu to see heap information (It's somewhat limited but more could be added if needed).

The main issue is that VMMap displays that the my string from "notepad.exe" is located on the heap (and this is logical).

But PH displays that this region is unnamed. This is fine?

**Comment by GflowerG** [comment]
> The memory tab shows the underlying Windows VAD layout.

I used windbg **!address** command. (https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/-address)
The output of the command shows that my string entered in "notepad.exe" is located on the heap, as is shown by VMMap. PH does not display this.


windbg output:
**1ee\`47c2d000** _ `Heap       [ID: 0; Handle: 000001ee47a60000; Type: SegmentHeap Segment]`

VMMap: 
**000001EE47C2D000** _ `Heap ID: 0 (Default) [COMPATABILITY]`

PH:
**0x1ee47c2d000** _ `...`

**Comment by dmex** [comment]
> my string entered in "notepad.exe" is located on the heap, as is shown by VMMap. PH does not display this.

VMMap is showing regions which don't actually exist in the VAD:

![image](https://user-images.githubusercontent.com/1306177/146978388-0b40408b-d397-4bef-a9e1-f46d676b5491.png)

PH detects segments by checking for the heap signature at the beginning of the region which doesn't exist for these allocations.

> PH displays that this region is unnamed.

This is the same problem I mentioned with VMMap creating fake pseudo entries. If we split these regions like it does then PH won't show the actual memory layout and any code you write to loop the memory won't match what you see with PH.

Ideally these regions would still be named so you know X, Y and Z are all sharing the same region but I'm not sure how VMMap determined all these regions are part of the heap without the heap signature at this moment.

**Comment by ge0rdi** [comment]
WinDbg's `!address` command also seems to _recognize_ segment heap blocks somehow:
```
More info:              heap owning the address: !heap 0x13219920000
More info:              segment heap segment
```
It does it also for _reserved_ memory blocks, so it most likely doesn't do any signature match.
I assume it walks all heaps and enumerates their internal blocks.
But I have no technical info about how to do that :(

**Comment by dmex** [comment]
> I assume it walks all heaps and enumerates their internal blocks. But I have no technical info about how to do that :(

You can walk the blocks using `CreateToolhelp32Snapshot` but last I checked it doesn't enumerate segment heaps.

**Comment by GflowerG** [comment]
> Ideally these regions would still be named so you know X, Y and Z are all sharing the same region but I'm not sure how VMMap determined all these regions are part of the heap without the heap signature at this moment.

This is a confusing topic.

But in this question I would take **WinDbg** as a main reference. After all, VMMap is some kind of _magic_.

**Comment by dmex** [comment]
@ge0rdi 

Your PR has to be reverted, can you please send me an email so I can give you the details?

My email is: dmex04@gmail.com

**Comment by ge0rdi** [comment]
@dmex 
Email sent.

**Comment by ge0rdi** [comment]
@dmex 
Wow, looks pretty cool.

Though I have noticed one issue with it.
`RtlCreateProcessReflection` creates _cloned_ process from within target process.
And some processes have `Child process creation disabled` mitigation enabled (like some Edge processes) because they are not supposed to create any children.
And so `RtlCreateProcessReflection` fails for them :(

Maybe we can try the _clone_ way first and then just _fallback_ to original code if cloning fails?

**Comment by ge0rdi** [comment]
More info on the failure:
There is `RtlpProcessReflectionStartup` thread created in target process. It calls `RtlCloneUserProcess` which fails with:

`Error code: (NTSTATUS) 0xc000049d (3221226653) - The process creation has been blocked.`

**Comment by dmex** [comment]
This should be fixed in the latest nightly @ge0rdi

**Comment by ge0rdi** [comment]
@dmex 
I seems to be working correctly now 👍 
Thank you.
