### ISSUE TITLE
Freezes and can't be terminated

### ISSUE THREAD

**Issue by CaptainFrosty** [processhacker/processhacker#1052]
**Describe the bug**
Freezes and can't be terminated

**To Reproduce**
Random, no input

**Expected behavior**
Not crashing I guess

**Debugger output**

```
Microsoft (R) Windows Debugger Version 10.0.22473.1005 AMD64
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is: 
ModLoad: 00007ff7`2d400000 00007ff7`2d5ab000   C:\Program Files\Process Hacker 2\ProcessHacker.exe
ModLoad: 00007ffd`ed180000 00007ffd`ed387000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 00007ffd`eb0c0000 00007ffd`eb17d000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 00007ffd`ea770000 00007ffd`eaae4000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 00007ffd`e7a10000 00007ffd`e7aa1000   C:\WINDOWS\SYSTEM32\apphelp.dll
ModLoad: 00007ffd`eb840000 00007ffd`eb9ec000   C:\WINDOWS\System32\USER32.dll
ModLoad: 00007ffd`ea740000 00007ffd`ea766000   C:\WINDOWS\System32\win32u.dll
ModLoad: 00007ffd`eb6c0000 00007ffd`eb6e9000   C:\WINDOWS\System32\GDI32.dll
ModLoad: 00007ffd`eaaf0000 00007ffd`eac02000   C:\WINDOWS\System32\gdi32full.dll
ModLoad: 00007ffd`ea630000 00007ffd`ea6cd000   C:\WINDOWS\System32\msvcp_win.dll
ModLoad: 00007ffd`eac10000 00007ffd`ead21000   C:\WINDOWS\System32\ucrtbase.dll
ModLoad: 00007ffd`ebf70000 00007ffd`ec05c000   C:\WINDOWS\System32\COMDLG32.dll
ModLoad: 00007ffd`ec9f0000 00007ffd`ecd68000   C:\WINDOWS\System32\combase.dll
ModLoad: 00007ffd`ec8c0000 00007ffd`ec9e1000   C:\WINDOWS\System32\RPCRT4.dll
ModLoad: 00007ffd`ece00000 00007ffd`eceea000   C:\WINDOWS\System32\shcore.dll
ModLoad: 00007ffd`ebdf0000 00007ffd`ebe4d000   C:\WINDOWS\System32\SHLWAPI.dll
ModLoad: 00007ffd`ebe50000 00007ffd`ebef3000   C:\WINDOWS\System32\msvcrt.dll
ModLoad: 00007ffd`ec070000 00007ffd`ec81e000   C:\WINDOWS\System32\SHELL32.dll
ModLoad: 00007ffd`e3460000 00007ffd`e346a000   C:\WINDOWS\SYSTEM32\VERSION.dll
ModLoad: 00007ffd`eb610000 00007ffd`eb6bc000   C:\WINDOWS\System32\ADVAPI32.dll
ModLoad: 00007ffd`eb9f0000 00007ffd`eba8d000   C:\WINDOWS\System32\sechost.dll
ModLoad: 00007ffd`eba90000 00007ffd`ebc2a000   C:\WINDOWS\System32\ole32.dll
ModLoad: 00007ffd`e7ad0000 00007ffd`e7b7c000   C:\WINDOWS\SYSTEM32\UxTheme.dll
ModLoad: 00007ffd`eafe0000 00007ffd`eb0b6000   C:\WINDOWS\System32\OLEAUT32.dll
ModLoad: 00007ffd`d53e0000 00007ffd`d5685000   C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.22000.120_none_9d947278b86cc467\COMCTL32.dll
ModLoad: 00007ffd`e9300000 00007ffd`e9363000   C:\WINDOWS\SYSTEM32\WINSTA.dll
ModLoad: 00007ffd`e9eb0000 00007ffd`e9ebc000   C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
ModLoad: 00007ffd`eb750000 00007ffd`eb781000   C:\WINDOWS\System32\IMM32.DLL
ModLoad: 00007ffd`e9840000 00007ffd`e9858000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
ModLoad: 00007ffd`eaf60000 00007ffd`eafe0000   C:\WINDOWS\System32\bcryptPrimitives.dll
ModLoad: 00007ffd`e87e0000 00007ffd`e9047000   C:\WINDOWS\SYSTEM32\windows.storage.dll
ModLoad: 00007ffd`e8670000 00007ffd`e87d6000   C:\WINDOWS\SYSTEM32\wintypes.dll
ModLoad: 00007ffd`a29d0000 00007ffd`a29f4000   C:\Program Files\Process Hacker 2\plugins\DotNetTools.dll
ModLoad: 00007ffd`b1640000 00007ffd`b1667000   C:\Program Files\Process Hacker 2\plugins\ExtendedNotifications.dll
ModLoad: 00007ffd`bb280000 00007ffd`bb2a5000   C:\Program Files\Process Hacker 2\plugins\ExtendedServices.dll
ModLoad: 00007ffd`a12a0000 00007ffd`a12d5000   C:\Program Files\Process Hacker 2\plugins\ExtendedTools.dll
ModLoad: 00007ffd`a1180000 00007ffd`a11b1000   C:\Program Files\Process Hacker 2\plugins\HardwareDevices.dll
ModLoad: 00007ffd`a0f20000 00007ffd`a0f46000   C:\Program Files\Process Hacker 2\plugins\NetworkTools.dll
ModLoad: 00007ffd`9f6c0000 00007ffd`9f6fb000   C:\Program Files\Process Hacker 2\plugins\OnlineChecks.dll
ModLoad: 00007ffd`9e6d0000 00007ffd`9e6ee000   C:\Program Files\Process Hacker 2\plugins\SbieSupport.dll
ModLoad: 00007ffd`9e020000 00007ffd`9e061000   C:\Program Files\Process Hacker 2\plugins\ToolStatus.dll
ModLoad: 00007ffd`9ac90000 00007ffd`9acaf000   C:\Program Files\Process Hacker 2\plugins\Updater.dll
ModLoad: 00007ffd`9a830000 00007ffd`9a851000   C:\Program Files\Process Hacker 2\plugins\UserNotes.dll
ModLoad: 00007ffd`98e00000 00007ffd`98e26000   C:\Program Files\Process Hacker 2\plugins\WindowExplorer.dll
ModLoad: 00007ffd`e7bb0000 00007ffd`e7be8000   C:\WINDOWS\SYSTEM32\dxcore.dll
ModLoad: 00007ffd`ea330000 00007ffd`ea37c000   C:\WINDOWS\SYSTEM32\CFGMGR32.dll
ModLoad: 00000000`541e0000 00000000`5429c000   C:\Program Files\Sandboxie-Plus\SbieDll.dll
ModLoad: 00007ffd`ec820000 00007ffd`ec828000   C:\WINDOWS\System32\psapi.dll
ModLoad: 00007ffd`ecf50000 00007ffd`ed06e000   C:\WINDOWS\System32\MSCTF.dll
ModLoad: 00007ffd`c61e0000 00007ffd`c628e000   C:\WINDOWS\SYSTEM32\TextShaping.dll
ModLoad: 00007ffd`eb790000 00007ffd`eb83f000   C:\WINDOWS\System32\clbcatq.dll
ModLoad: 00007ffd`e9380000 00007ffd`e93ad000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
ModLoad: 00007ffd`ec8b0000 00007ffd`ec8b9000   C:\WINDOWS\System32\NSI.dll
ModLoad: 00007ffd`e3270000 00007ffd`e341e000   C:\WINDOWS\system32\windowscodecs.dll
ModLoad: 00007ffd`b0cc0000 00007ffd`b0cc9000   C:\WINDOWS\system32\IconCodecService.dll
ModLoad: 00007ffd`ea6d0000 00007ffd`ea736000   C:\WINDOWS\System32\wintrust.dll
ModLoad: 00007ffd`eadf0000 00007ffd`eaf52000   C:\WINDOWS\System32\CRYPT32.dll
ModLoad: 00007ffd`e9ef0000 00007ffd`e9f02000   C:\WINDOWS\SYSTEM32\MSASN1.dll
ModLoad: 00007ffd`e9e90000 00007ffd`e9ea8000   C:\WINDOWS\SYSTEM32\CRYPTSP.dll
ModLoad: 00007ffd`e97a0000 00007ffd`e97d5000   C:\WINDOWS\system32\rsaenh.dll
ModLoad: 00007ffd`ed070000 00007ffd`ed08f000   C:\WINDOWS\System32\imagehlp.dll
ModLoad: 00007ffd`ea010000 00007ffd`ea037000   C:\WINDOWS\SYSTEM32\bcrypt.dll
ModLoad: 00007ffd`e9ce0000 00007ffd`e9d04000   C:\WINDOWS\SYSTEM32\gpapi.dll
ModLoad: 00007ffd`e06f0000 00007ffd`e0721000   C:\Windows\System32\cryptnet.dll
ModLoad: 00007ffd`ea560000 00007ffd`ea581000   C:\WINDOWS\SYSTEM32\profapi.dll
ModLoad: 00007ffd`e23a0000 00007ffd`e23bb000   C:\WINDOWS\SYSTEM32\windows.staterepositorycore.dll
(13e8.583c): Access violation - code c0000005 (!!! second chance !!!)
SbieSupport+0x1af3:
00007ffd`9e6d1af3 8b07            mov     eax,dword ptr [rdi] ds:00000066`44400000=????????
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11 21H2 build 22000.348

**Comment by Biswa96** [comment]
Are you using older Process Hacker 2? Would you like to try the nightly build from here https://processhacker.sourceforge.io/nightly.php ?

**Comment by CaptainFrosty** [comment]
Yes the latest release version. Didn't know you had a nightly. I give it a tr y.

**Comment by CaptainFrosty** [comment]
The nightly worked better for a little while, then I got an error when I booted up earlier that the kernel driver failed a signature check or something like that. There doesn't seem to be much a difference without it though, at least for what I use it for. What is the benefit of the kernel driver?

**Comment by dmex** [comment]
> Freezes and can't be terminated

What freezes PR or something else?

**Comment by CaptainFrosty** [comment]
@dmex Hi, didn't see your reply sorry. It seems to be alright with the newer version. The kernel driver error went away after a few reboots. No idea why.

**Comment by CaptainFrosty** [comment]
I was referring to the older version of PH. It was freezing. Only issue with the later version was the temporary kernel driver error.

**Comment by CaptainFrosty** [comment]
I think my AV software's HIPS may have been preventing the driver from loading. I added to the whitelist.

**Comment by dmex** [comment]
> AV software's HIPS 

Which AV product?

**Comment by CaptainFrosty** [comment]
@dmex 
ESET. The only proprietary home security product I've ever used that isn't a heap of junk. But it has its flaws too. I added the kprocesshacker.sys driver to the "always load" list but I still intermittently get the driver signature error. It loads sometimes. I just added a manual HIPS rule giving process hacker full access to applications/files/registry and excluded it from deep behavioral inspection. Maybe that will help. I imagine I can't know for sure that it's the AV causing it without some debugging though. There isn't anything in the HIPS log about it.

Another thing, I tried to change the color for the currently selected process, because the gray is hard to see when I have a heavy blue light filter on...but when I insert a hex value and reboot the cursor disappears entirely. 

Other than that it works okay. I tend to get processes lately that get stuck in exiting phase and take forever to kill. I highly regret upgrading to Windows 11. I ran a simple routine reset with cloud download to try to fix some issues and it boot looped after the first restart. Totally ruined my secure boot; can't use it anymore despite factory resetting the keys and trying to manually enroll the EFI image (though I'm not sure which EFI file on the boot partition is supposed to be cached to the database, there are several). 

Luckily it still boots without it. I thought my edition of Windows 11 had to have secure boot but apparently not. I never had these issues on 10. Bugs are persisting through the resets; I guess they are driver or hardware related. Event log errors of all shapes and sizes. I paid $100 hoping Pro would help. It did not. I think the upgrade actually made things worse. SFC, DISM etc. report nothing is wrong.

I'm getting off subject, sorry. I don't know what to do at this point. Starting to go beyond my skill level.

**Comment by Masamune3210** [comment]
Secure Boot issues are entirely with your board, Windows has no control over it. Either your board has incorrect key database set or something is misconfigured. If everything with your board is working correctly you should never have to manually enroll a Windows image as Microsoft keys are stored in most boards as default

**Comment by CaptainFrosty** [comment]
@Masamune3210 

As I mentioned, I did nothing except a routine reset with cloud download. The only significant differences from a prior installation being both an upgrade to Windows 11 and an upgrade from Home to Pro edition. The secure boot was corrupted immediately following the cloud download and the first shutdown after starting the reset. There wasn't even time for user error. So common sense would tell us the statement "Windows has no control over it" is false. 

I never had a single issue with secure boot on Windows 10. I never touched it once. Clearly either the 11 upgrade or the change in edition, I'm guessing more toward the latter, maybe a combination of both, caused Windows PE or whatever was in control at the time to modify the secure boot database with bad results. There is even a message in my BIOS now that says VENDOR KEYS MODIFIED. 

So unless you're going to tell me that legitimate OS upgrades, one of which I paid $100 for, of presumably "stable" release builds justifies a destroyed secure boot, I'd say the blame for this lands squarely on Microsoft. And Microsoft is precisely who owns the service center to which Microsoft support wants me to lug my desktop PC. Not the motherboard manufacturer. 

This is not the only issue I have for no good reason. I'm going to try a clean USB install directly from a Win11 image. That's the last thing I'm trying before I toss the half-baked junk known as Windows 11.
