### ISSUE TITLE
broken installer

### ISSUE THREAD

**Issue by Sxtqq** [processhacker/processhacker#1054]
whenever i run the installer it runs fine but after a second or two it just closes for no reason.
i dont have any antiviruses enabled, i have tried the regular and nightly builds.

**Comment by dmex** [comment]
The setup is supposed to close when finished and start the application like the installers for firefox and chrome.

If it didn't start the application then I'd reopen the issue so it can be looked into?

**Comment by Sxtqq** [comment]
> The setup is supposed to close when finished and start the application like the installers for firefox and chrome.
> 
> If it didn't start the application then I'd reopen the issue so it can be looked into?

it was just some anti debug system closing it
