### ISSUE TITLE
Windows reports trojan on 3.0.4444

### ISSUE THREAD

**Issue by dkloke** [processhacker/processhacker#1058]
On attempting to install from processhacker-3.0.4444-setup.exe Windows 10 blocks execution, reports:
Trojan:Script/Wacatac.B!ml
Alert level: Severe
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.

Note that CertUtil also fails, so signature can't be verified:
> CertUtil -hashfile G:\Install\processhacker-3.0.4444-setup.exe
CertUtil: -hashfile command FAILED: 0x800700e1 (WIN32/HTTP: 225 ERROR_VIRUS_INFECTED)
CertUtil: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

**Comment by dmex** [comment]
> Windows 10 blocks execution
> This program is dangerous and executes commands from an attacker.

Microsoft regularly abuses its security products to attack competitors. #454
