### ISSUE TITLE
The selection of the element is unreadable

### ISSUE THREAD

**Issue by GflowerG** [processhacker/processhacker#1062]
The Process Hacker highlights some interface elements with colors. The problem is that sometimes the selection of an element is mixed with the highlighting.

Is it possible to add some kind of marker for the selected item? It may look exactly the same as the `•` ; `*` ; `→` ; `>`. Or just make a more explicit border of the selected element.

**Comment by dmex** [comment]
You can enable custom selection colors using `TreeListCustomColorsEnable` and configure the colors with `TreeListCustomColorFocus` and `TreeListCustomColorSelection` with RRGGBB color format👍
