### ISSUE TITLE
Tray monitor on Windows 11

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#1065]
**Describe the bug**
Is it possible to make it, as it was on Windows 10? It's a nice thing and I was using it a lot.

**To Reproduce**
1. Move the cursor to the PH tray icon

**Expected behavior**
It will show the tray monitor window

**Screenshots**
![process_hacker_tray_monitor](https://user-images.githubusercontent.com/24621645/146676755-d9996eb9-fd76-4e8b-9d9d-542aa3e01e80.png)
I mean this thing.

**Desktop (please complete the following information):**
 - OS: Windows
 - 11 Pro 22000.376

**Comment by dmex** [comment]
#941
