### ISSUE TITLE
Toolstatus's customization windows doesn't have proper theme support

### ISSUE THREAD

**Issue by TheEragon** [processhacker/processhacker#1069]
Toolstatus's customization window has a listbox without proper theme support

![image](https://user-images.githubusercontent.com/5801389/147088055-2a4282bd-3472-44ab-b49f-0ade7982405f.png)

I tried adding WM_CTLCOLORBTN, WM_CTLCOLORDLG and WM_CTLCOLORSTATIC but that doesn't help, maybe you'll know where the problem is, I'm not theme support expert 😅

**Comment by OrbbQ3** [comment]
`WM_CTLCOLORLISTBOX` ?

**Comment by TheEragon** [comment]
> `WM_CTLCOLORLISTBOX` ?

Thanks but no 😞, but I solved it. It's waiting for an approval.
