### ISSUE TITLE
Header totals don't include child totals

### ISSUE THREAD

**Issue by KyleKolander** [processhacker/processhacker#1070]
**Describe the bug**
When you expand a row in tree view, that row's value no longer includes the sum of it's child rows, but the sum of it's child rows is still "there", just in the individual expanded rows. When you do this, the value of the header total appears to be decreasing by the amount that was "lost" from the expanded row.

**To Reproduce**
1. Go to the Processes tab.
2. Click on the Name header until you enter tree view.
2. Click on a row to collapse it.
3. Observe the overall totals for that collapsed row.
4. Observe the header totals.
4. Expand that row.
5. Observe the header totals.

**Expected behavior**
When expanding a row in tree view, the header totals should not decrease due to the parent row no longer including the child rows in its total.

**Screenshots**
![Before expanding wininit exe](https://user-images.githubusercontent.com/22461822/147120715-18a4a621-fea8-4205-971a-777aa232276a.png)
![After expanding wininit exe](https://user-images.githubusercontent.com/22461822/147120742-82452c91-543d-4eac-9d4d-bd08c02b2fff.png)
![options](https://user-images.githubusercontent.com/22461822/147120756-00f71f92-0fd5-4a71-a1d4-0d99eea318bd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10 Pro

**Additional context**
Related to [Feature Request #1005](https://github.com/processhacker/processhacker/issues/1005)

**Comment by MagicAndre1981** [comment]
Yes, value calculation is buggy, here handle count doesn't match:

![processhacker_handle_column_diff_value_taskmgr](https://user-images.githubusercontent.com/8274816/147205249-1227a339-d32f-4754-bc6d-74920bb6b429.png)

when I expand all process/child entries that I collapse by default it is better but still not equal to Taskmgr.

Happens on Windows 10 x64 for me.

**Comment by dmex** [comment]
Fixed 👍
