### ISSUE TITLE
Add Misc. > User Object Handles capability

### ISSUE THREAD

**Issue by jasonaross81** [processhacker/processhacker#1071]
It is frustrating to observe a process with a large count of User object handles and not have count and detailed information as to the handle type (window, icon, etc.).  Having this information quickly helps one to determine what area of source code to focus on for both code scan and memory profiler purposes.

There exists a Menu > Misc. > GDI Handle capability that shows bitmap, font, etc.  I would like this capability added for User object handles.

I am not able to find an alternative method to discover this information inside of Process Hacker, Process Explorer, Bear, Windbg memory dump (user mode), google searching, etc. for 64-bit processes running on Windows.

**Comment by dmex** [comment]
> I am not able to find an alternative method to discover this information inside of Process Hacker, Process Explorer, Bear, Windbg memory dump (user mode), google searching, etc. for 64-bit processes running on Windows.

Microsoft stripped the symbols for these objects and they change too often to support this.
