### ISSUE TITLE
Small bug in the Service tab with "Timeline" enabled.

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#1072]
BAM!
https://i.imgur.com/QN3tx9N.png

So I was just testing out this Timeline column thing by enabling it, and noticed anything placed the right of this column will also gain a green highlight color as you mouse over them. Looks to me like the timeline "bar" is spilling on out over onto whatever it is next too.

Image above should show off the issue better then my words can.

So that's pretty much it, we'll need a clean up on aisle 46, no rush dmex. : P

**Comment by dmex** [comment]
Are you running an old nightly build from 6 months ago?

**Comment by ImSpecial** [comment]
3.0.4444

**Comment by dmex** [comment]
I haven't been able to reproduce it?

**Comment by ImSpecial** [comment]
Well I'm not at my machine now or until tomorrow but I'll try and make a gif of it then. All I do is toggle the timeline column to show, and so it appears on the far, far right as a new column, then I drag it past other columns to the left, now when I highlight over the columns on the right they get that green color to them.

To me it's no big deal, I won't use that timeline column in the future, it was just a "try before buy" thing I did, but figured I would report the strange behavior none the less.

**Comment by ImSpecial** [comment]
As promised, a crappy little gif, (I'm not crazy!)
https://i.imgur.com/NGPPVbV.gif

But again I'm not doing anything special here, if you cannot reproduce, welp, I will just blame this on my config or something then, I'm way to lazy to try and troubleshoot this as I won't use this timeline anyways.

**Comment by dmex** [comment]
@ImSpecial 

Can you check the Uptime value shown by Process Hacker on the System Information > CPU panel exactly matches the Uptime in Task Manager > Performance > Cpu panel? The uptime (bootstart) time determines the value of the timeline graphs.

**Comment by ImSpecial** [comment]
Oh wow, I think this/that may have been it, I've since booted my machine and cannot reproduce my issue now, but if I play with the Date & Time of Windows, I can again... So I guess this was never an issue with Process Hacker to begin with and all on "my config". Well that was a waste of time...

You a sharp guy dmex! I'm going to call you Sherlock dmex now.

**Comment by dmex** [comment]
>

**Comment by dmex** [comment]
>  if I play with the Date & Time of Windows, I can again

What did you change to reproduce it?

**Comment by ImSpecial** [comment]
Use this device (https://i.imgur.com/srQBh6s.png) to go back and meet up with Marty's mom, good luck!

**Comment by dmex** [comment]
> Use this device

Where do you find that?

**Comment by ImSpecial** [comment]
God Windows 10 sucks! I dunno, I use [Open-Shell](https://github.com/Open-Shell/Open-Shell-Menu) and it just shows up if I search for "date" also it's in the control panel. (the good one)

https://i.imgur.com/5XljoC5.png

**Comment by dmex** [comment]
> it just shows up if I search for "date" also it's in the control panel

I can't find it

**Comment by Biswa96** [comment]
The screenshot looks like of timedate.cpl.

**Comment by dmex** [comment]
Fixed

**Comment by ImSpecial** [comment]
Oh good, I'm still here.
