### ISSUE TITLE
UNKNOWN DEVICE - PLEASE REPORT ON GITHUB

### ISSUE THREAD

**Issue by robertroessler** [processhacker/processhacker#1081]
After moving my Windows 11 installation from my Core i7-7700 to my new Core i7-12700K, I see a "Disconnected RAPL Device" that lists my old processor.

I am bringing this up because the message apparently asks me to. :)

BTW, it looks like I can "just" uninstall the device - but it isn't 100% clear that will have no ill effects on my system.

**Comment by dmex** [comment]
> a "Disconnected RAPL Device" that lists my old processor.

Does it show your new processor?

>  it looks like I can "just" uninstall the device - but it isn't 100% clear that will have no ill effects on my system.

You can remove the device, nothing will happen.

**Comment by robertroessler** [comment]
Oh!  It didn't occur to me to mention the "OK" portion of this displayed list - yes, the new one is there as the sole member of the "Connected" list - and yes, I could have been more clear in my report.

**Comment by dmex** [comment]
This would be a false positive issue.

The "unknown device - report on github" message was supposed to only ever be visible for devices without 4 mandatory channels. I didn't think "disconnected" processors were possible, so the validation checks don't check if the device exists triggering the message.

I'll fix the message so it doesn't appear when the processor is missing 👍
