### ISSUE TITLE
Should there be an explorer button next to current directory?

### ISSUE THREAD

**Issue by Biswa96** [processhacker/processhacker#1082]
In General tab of any process, there is a 'jump into that path' button next to image file name. Should there be same button next to current directory also? Like this 

![image](https://user-images.githubusercontent.com/31443074/147857824-40ff2e32-f0a1-4311-86e6-b03e29b00fe2.PNG)

Just asking 😊

**Comment by dmex** [comment]
These buttons probably won't exist in a future update.

**Comment by Biswa96** [comment]
Why? It's useful though. Is there any alternative for those buttons?

**Comment by dmex** [comment]
> Why? It's useful though. Is there any alternative for those buttons?

The idea is to eventually switch the dialog to have the same layout as peviewer and right-clicking the string would have the `Open file location` menu.
