### ISSUE TITLE
TreeListEnableHeaderTotals setting does not save properly

### ISSUE THREAD

**Issue by faxx1080** [processhacker/processhacker#1086]
**Describe the bug**

**To Reproduce**
1. Start processhacker with empty settings file.
2. See that columns have header totals
3. Go to options > general, enable advanced options
4. Under advanced options set TreeListEnableHeaderTotals to 0
5. Close settings
6. Restart processhacker as suggested
7. Header totals still shown

**Expected behavior**

Header totals should not be shown anymore.
NOTE: If the setting is manually set to zero in the XML file, the header totals are not shown.

**Screenshots**
I don't think any are needed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 19044.1415

**Additional context**

Also occurs with a fresh compile-from-master.

**Comment by dmex** [comment]
The checkbox on the General tab overrides any manual changes in the advanced tab:
![image](https://user-images.githubusercontent.com/1306177/148111644-363288ec-352a-45c4-87ee-0d11b9dbdcd4.png)

This is by design since the general tab is saved last.
