### ISSUE TITLE
gpu usage issue in tray icon view  (solved)

### ISSUE THREAD

**Issue by neonramzy** [processhacker/processhacker#1098]
### Brief description of your issue

installed stable and nightly versions,same result!
in tray icon view gpu usage is now showing and always is 0%.
but when i close process hacker and delete setting file manually and re open it problem will gone temporary.
after restart windows or wakeup,issue will back again,
windows 10 x64 build 21h2 19044.1466
![Capture](https://user-images.githubusercontent.com/93700660/149887730-31b8d830-db68-404b-a08a-b0e1fbacba30.PNG)

**Comment by dmex** [comment]
Try changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` setting from 0 to 1
