### ISSUE TITLE
Windows Defender quarantines x86 ProcessHacker.exe

### ISSUE THREAD

**Issue by NgrNxk** [processhacker/processhacker#1099]
So, yesterday I installed build 4527 (30015af) and Windows Defender immediately quarantined x86/ProcessHacker.exe on my x64 Windows system upon start.

![grafik](https://user-images.githubusercontent.com/2931938/149898508-d0206eb8-ba9b-46a2-91b7-96ddb1e08618.png)

I deleted the the x86 directory to prevent it from happening again; ProcessHacker still works.

Is there anything that can be done about it? I checked the SHA2 of the setup, and it matches: so I didn't get the wrong download.

Windows Version	10.0.17134 Build 17134

**Comment by Masamune3210** [comment]
![image](https://user-images.githubusercontent.com/1053504/149944166-a02c5f28-e9ca-494d-9b9c-ae33aacd6a90.png)
All the tickets that mention the word defender, you arent alone. Report it as a false positive, remember that av companies are dumb as a box of rocks at best, and try to continue with your day

**Comment by mikamidd** [comment]
I have real-time scanning disabled but no issues when running a manual scan of Program Files\Process Hacker\ with latest WinDef ver 1.355.2164.0
So probably fixed on Microsoft's side.

**Comment by dmex** [comment]
#454
