### ISSUE TITLE
Daily download limit for nightly builds too low

### ISSUE THREAD

**Issue by Markus74a** [processhacker/processhacker#1109]
### Description of the feature, modification, idea or suggestion

ProcessHacker informs me about an available update. When I click on download, it fails.

When I go to https://processhacker.sourceforge.io/nightly.php and try to download the newest version directly, I get:

`{"message":"Artifacts download limit (1024 MB/day) exceeded."}`

I have been using ProcessHacker nightly builds for years without problems downloading, this seems to be a recent change.

1024 MB/day for a ~10MB file would mean only 100 downloads are possible every day.

According to https://sourceforge.net/projects/processhacker even the old ProcessHacker2 version has more than 1000 downloads/day, so I assume ProcessHacker3 downloads are above 100/day.

**Comment by dmex** [comment]
> this seems to be a recent change

**Comment by dmex** [comment]
> this seems to be a recent change

Appveyor seems to have started using stricter quota limits... I've migrated the nightly downloads to the github mirror 👍
