### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by VykosX** [processhacker/processhacker#1114]
Ever since an update a month or two ago, I've started having issues with Process Hacker consuming increasingly greater amounts of RAM. It just seems to keep increasing at a rate of maybe 10mb of RAM per minute and never releases the memory it allocates. I've left the computer on for a few days only to have to terminate Process Hacker manually as it was using over 10 GB of RAM on its own.

I've attached a screenshot of Process Hacker using over 5GB of RAM and that's just from leaving my computer on overnight. I prefer to have Process Hacker running as I use the tray icon graphs semi-frequently to manage and monitor my computer and memory usage. Can a dev please look into this? I can provide logs or whatever else might be necessary.

Thank you.

![ProcessHacker_mFylp9KNqy](https://user-images.githubusercontent.com/49174413/151676408-30102715-4883-4670-bf2c-e21e7ec64033.png)

![ProcessHacker_yY7AvoHITq](https://user-images.githubusercontent.com/49174413/151676630-2221746c-2020-451b-a823-bac236c6c976.png)

![ProcessHacker_c0szcQRsj7](https://user-images.githubusercontent.com/49174413/151676564-ef939349-3684-4cb9-bb89-a2f6a4a96bca.png)

**Comment by VykosX** [comment]
Another half a day and it's almost up to 10GB =\
![ProcessHacker_GmVa7UFdXV](https://user-images.githubusercontent.com/49174413/151696381-9dc964e6-6c28-4d09-8d0b-bb262f67d86d.png)
![ProcessHacker_uSGo4J7ijp](https://user-images.githubusercontent.com/49174413/151696384-88cefee1-f00b-489a-8ae0-18803b9f4fab.png)

**Comment by jdpatdiscord** [comment]
My environment has been Windows 10 Pro 20H2 for x86_64, and Windows 10 Pro for ARM64. Please provide as much as possible the details of your host machine in order to diagnose (It appears to be Windows 7.)

**Comment by VykosX** [comment]
This is indeed running on Windows 7 SP1 x64 with a Core i7 3970X, 32gb RAM (+32gb of Pagefile) and an RTX 2080. I have the Kernel mode driver and theming support enabled. Can provide logs or option files or whatever is required to help debug this issue.

**Comment by dmex** [comment]
> these issues are not present

I don't see a memory leak either. PH memory usage was maximum 77MB after two days:

![image](https://user-images.githubusercontent.com/1306177/151703475-83a71ffa-58ee-4bcf-8c13-c8725029c5d4.png)
![image](https://user-images.githubusercontent.com/1306177/151703491-e91f4f65-c7b2-423d-a13b-78a234a84fe9.png)

> Can provide logs or option files or whatever is required to help debug this issue.

@VykosX 

Can you attach your settings file?

**Comment by SeaHOH** [comment]
My system platform is also Windows 7 SP1 x64, with 16 GB RAM, CPU and GPU both use AMD. The private bytes is a bit big, but it seems did not leaked.
![p1](https://user-images.githubusercontent.com/8470820/151706434-f8d3b3a2-ad5f-4bc8-aeb5-7130506a9ca4.png)
![p2](https://user-images.githubusercontent.com/8470820/151706440-8815500f-b031-488c-9e9c-8329dc965098.png)

**Comment by VykosX** [comment]
[ProcessHacker.exe.settings.xml.txt](https://github.com/processhacker/processhacker/files/7966269/ProcessHacker.exe.settings.xml.txt)

**Comment by SeaHOH** [comment]
After 3 days, it increased. Now, I am not sure whether it would go on.
[ProcessHacker.exe.settings.xml.txt](https://github.com/processhacker/processhacker/files/7991701/ProcessHacker.exe.settings.xml.txt)

![p2](https://user-images.githubusercontent.com/8470820/152278592-6311651d-3cbf-47e5-a94b-c841eb0aa544.png)

**Comment by VykosX** [comment]
It does appear that Process Hacker is leaking memory on Windows 7, the rate of which I'm assuming is proportional to the processes that are running on the system and how heavily used it is. If it helps any, I have the tray icon graphs for CPU and Physical Memory open at all times and check those periodically.

**Comment by SeaHOH** [comment]
@VykosX When I disable FPS Monitoring (a new feature enable by default), it looks like OK. Can you reproduce this case?

**Comment by VykosX** [comment]
I'll have to leave the computer on for a bit longer to be certain, but preliminarily disabling that option does appear to prevent the memory leak, so good job on narrowing down a potential cause. What is that setting supposed to do anyway?

**Comment by dmex** [comment]
Fixed
