### ISSUE TITLE
Unable to distinguished selected "Pico processes" (WSL) with the default color (while focused)

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#1117]
Pico processes default color:
![image](https://user-images.githubusercontent.com/133706/152399087-fb7faad7-6ff9-42d5-b139-16f928c04179.png)

Selected/focused:
![image](https://user-images.githubusercontent.com/133706/152399139-a5800934-0ce8-4bff-9792-b7c92bbb79db.png)

Selected/unfocused:
![image](https://user-images.githubusercontent.com/133706/152399263-5e663749-d7c5-4d61-95a7-6f8bf72cdd0c.png)

**Comment by dmex** [comment]
You can change the color? 

Options -> Highlighting:

![image](https://user-images.githubusercontent.com/1306177/154784019-191e05d0-3037-497b-929d-c1bfe7291832.png)

**Comment by stdedos** [comment]
I know I can do it 😅 

I was wondering if that's interesting for you to fix for all users, since it sounds like a UX issue

**Comment by dmex** [comment]
> fix for all users, since it sounds like a UX issue

The WSLv1 subsystem is essentially dead, so there isn't much point changing the colors.

**Comment by Masamune3210** [comment]
just switch to WSL2, it brings a bunch of benefits over V1 anyway

**Comment by stdedos** [comment]
Nope. No HyperV, thank you very much.

**Comment by Masamune3210** [comment]
Suit yourself I guess, but why no Hyper-V?

**Comment by dmex** [comment]
> why no Hyper-V

View the latency on the System Information > CPU panel compared to machines without Hyper-V.

**Comment by Masamune3210** [comment]
Yeah the latency bump isnt exactly the best unfortunately
