### ISSUE TITLE
PH 3.0.4554 Crash

### ISSUE THREAD

**Issue by rqueizan** [processhacker/processhacker#1121]
### Brief description of your issue

Since I installed version 3.0.4554 of PH it randomly warns of an invalid access to a memory location error.

I have managed to generate a dump file, should I share it here or privately with someone?

### Steps to reproduce (optional)

I run PH as administrator from my user account.
I expect the error to occur.

### Expected behavior (optional)

It should run perpetually like in previous versions.

### Actual behavior (optional)

An error occurs, asking me to create a Normaldump, Minidump, Restart, or Exit.

### Environment (optional)

```shell
Process Hacker Nigtly Build: 3.0.4554
Windows 11 Enterprise 64 bits, 32GB RAM, Ryzem 5 4600 12 cores.
```

**Comment by rqueizan** [comment]
Running the PH as a normal user has not caused an error for 4 days and 18 hours.
It could be that the error occurs when running as administrator.
I am waiting for it to happen on another computer to capture the normal dump.

**Comment by rqueizan** [comment]
Running version 3.0.4599 3 days and 4 hours ago on a computer, since the administrator session has not given an error.
But on another computer, running from a non-administrator session as administrator the error occurred once.
However, the rate of occurrences has decreased.

**Comment by dmex** [comment]
This should be fixed in the latest nightly build r4600?
