### ISSUE TITLE
Scaling on individual process CPU usage

### ISSUE THREAD

**Issue by mdblack98** [processhacker/processhacker#1125]
### Description of the feature, modification, idea or suggestion

Would like to see scaling adjustment of the CPU usage for individual processes.

**Comment by jxy-s** [comment]
HI @mdblack98, if I'm interpreting your request correctly, I believe there is already an option for this in the nightly. `Hacker > Options... > General > Enabled fixed graph scaling (experimental)`.

**Comment by mdblack98** [comment]
Yep...that's it ...thanks
Mike

 

    On Monday, February 14, 2022, 05:56:24 PM CST, Johnny Shaw ***@***.***> wrote:  
 
 


HI @mdblack98, if I'm interpreting your request correctly, I believe there is already an option for this in the nightly. Hacker > Options... > General > Enabled fixed graph scaling (experimental).

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
