### ISSUE TITLE
Find Thread Handle with decimal value in Properties

### ISSUE THREAD

**Issue by codecheck01** [processhacker/processhacker#1129]
### Description of the feature, modification, idea or suggestion

Hello,

I would suggest to be able to find a **thread handle** with his **decimal value** in `(process_name.exe)Properties > Handles`.
(actually this is only possible using the hexadecimal value).

This is to match the actual behavior in the main screen using the function **Find handles or DLLs**.

### Find handles or DLLs (main screen):

- Find a thread handle with decimal value (**OK**)
![1](https://user-images.githubusercontent.com/98359300/154348225-26cf7ef4-29e5-4087-82da-438355f0b1bc.png)

- Find a thread handle with hexadecimal value (**OK**)
![2](https://user-images.githubusercontent.com/98359300/154348323-f90c6902-070c-486b-a9df-1c2b0b872a5c.png)

### (_process_name.exe_)Properties > Handles > Search Handles (Ctrl+K):

- Find a thread handle with decimal value (**NOT OK**)
![3](https://user-images.githubusercontent.com/98359300/154347503-7263f4b1-d5b9-4ff1-85de-beb95932d894.png)

- Find a thread handle with hexadecimal value (**OK**)
![4](https://user-images.githubusercontent.com/98359300/154347413-7f6f9af5-99d5-427c-9541-1130a153218f.png)

**Comment by dmex** [comment]
Added to latest nightly build 👍
