### ISSUE TITLE
Preference for services performed

### ISSUE THREAD

**Issue by Tarq2** [processhacker/processhacker#1130]
good greeting
I want to distinguish suspended and activated Windows services, as I lose them every time
Can services be preferred ?
For example, this service is one of the system operations. I have to search for it every time when stopping and resuming
![image](https://user-images.githubusercontent.com/100014219/154789903-8e2a0707-e690-4dca-bab8-874cc5344fb5.png)

**Comment by jxy-s** [comment]
@Tarq2 I don't fully understand your request. The "Services" tab enables you to observe the state of services on the machine and stop/restart/start where appropriate. In the "Processes" tab you can see suspended processes and resume them if desired, you can even use the search box to look for "suspended".

**Comment by Tarq2** [comment]
Every time I stop hibernating it is cumbersome because I don't keep it logged in a notebook. I want a way to distinguish it
![image](https://user-images.githubusercontent.com/100014219/154866161-01dd76ac-94db-48ba-8097-d08c6c0cad27.png)

**Comment by jxy-s** [comment]
> Do I have to enter it after every device hibernation or shutdown?

Enter what?

Apologies, I'm trying to understand, thank you for your patience with me.

I see you are observing suspended services on your system. To my knowledge it is normal for some processes to be suspended. `MsMpEnd.exe` is probably one that shouldn't be suspended. The others may end up suspended unless office is active? Even power management settings might be at relevant here? I'm not entirely sure.

I think you are you asking for Process Hacker to automatically resume processes that get suspended? I don't think automatically resuming suspended processes in process hacker is something we should support. We can certainly implement some such feature, but I'm not convinced it provides a lot of value. Whatever is suspending the process may end up doing so repeatedly causing contention or undefined behavior elsewhere. It's best for you to investigate why those processes are becoming suspended to begin with and disable whatever software or system settings that is causing it. The nature of the services that in the suspended state makes me believe some anti-virus software might be doing this, or like I mentioned the power management settings might be at play (although I find this unlikely)?

**Comment by dmex** [comment]
> I want to distinguish suspended and activated Windows services

https://processhacker.sourceforge.io/nightly.php
