### ISSUE TITLE
Visual Studio 17.1.0 and SDK 22000 Problem

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#1131]
### Brief description of your issue

Hello!
Just installed MS VS 16.11.10 (with [x] SDK 19041) and MS VS 17.1.0 (with [x] SDK 22000). Both are fresh installation on a fresh Windows 11 22000.527.
![ph](https://user-images.githubusercontent.com/24621645/154817637-d06ea10a-6031-4246-bf8d-83ed4a20ed97.png)
Looks like it can't find SDK 22000 though it's installed and checked in the VS installer.

### Steps to reproduce (optional)

- install windows 11 22000.527
- install ms vs 16.11.10 with [x] SDK 19041
- install ms vs 17.1.0 with [x] SDK 22000

### Expected behavior (optional)

I can build PH with no problems

### Actual behavior (optional)

Custom build tool can't find the latest SDK 22000

### Environment (optional)

```shell
The latest PH trunk revision from repo
Windows 11 22000.527
```

**Comment by skipik** [comment]
@dmex could you please help to investigate the problem? Thanks!

**Comment by dmex** [comment]
You need to execute `\build\build_thirdparty.cmd` and recompile the static library dependencies.

**Comment by skipik** [comment]
Thanks!
So the SDK 19041 is the right one for now?
I think the last time I built my own build of PH it was using SDK 22000. It was ~ 3 weeks ago. Di you change it in the latest commits?

**Comment by dmex** [comment]
> So the SDK 19041 is the right one for now?

No. 

The build tools use the Visual Studio API to show the latest installed SDK version... The latest Visual Studio update broke that API and it now returns identical version numbers for every Windows SDK installed and the build tools can't determine the latest SDK  because the versions are all identical.

**Comment by skipik** [comment]
Oh, thanks for the explanation! Another MS fault then :(
