### ISSUE TITLE
PorcessHacker crashed 

### ISSUE THREAD

**Issue by THEBOSS619** [processhacker/processhacker#1133]
**Describe the bug**
It simply crashed when my laptop lid is opened, It was at idle state with no work in the background running. 

**To Reproduce**
Nothing special... it was running on the background idle.

**Expected behavior**
No crash.

**Screenshots**
None

**Desktop:**
I am using Windows 10 Pro x64 Version 2009 Build 19044.1566. 

**Additional context**

Here is the dump file which might help you find the cause and fix it. Thank you
[ProcessHacker_VHLVQWFFGRTQEDT_DumpFile.zip](https://github.com/processhacker/processhacker/files/8104694/ProcessHacker_VHLVQWFFGRTQEDT_DumpFile.zip)

**Comment by dmex** [comment]
This should be fixed in the latest nightly build 👍
