### ISSUE TITLE
Start with Admin Previliges

### ISSUE THREAD

**Issue by OfflinePing** [processhacker/processhacker#1143]
Hey,
I want to start Process Hacker with Admin rights. I also know that Account has Admin (i can open for example cmd as Admin too). I tried to rightclick it and run as admin but that didnt work. I also tried to run it with an Admin CMD but it just opens normally without admin perms. I cant tell why o.O
It worked once after direktly installing it but after one reboot it just didnt wanted to open with admin
EDIT: Its because a Game called Ragnarok. After I installed it and rebooted my PC it wont open with admin anymore

**Comment by dmex** [comment]
> Game called Ragnarok. After I installed it and rebooted my PC it wont open with admin anymore

A game or malicious software?

**Comment by Mecanik** [comment]
> > Game called Ragnarok. After I installed it and rebooted my PC it wont open with admin anymore
> 
> A game or malicious software?

He just wants to "cheetoh". With ProcessHacker and Admin rights.

**Comment by dmex** [comment]
> He just wants to "cheetoh"

PH doesn't have cheat capabilities, he literally can't "cheetoh".

> Game called Ragnarok rebooted my PC it wont open with admin anymore

If you can't run programs with admin then you've probably infected with malware.

I also couldn't reproduce this issue... Ragnarok loaded fine, they're using Easy Anti-Cheat (EAC) and we're compatible with EAC.
