### ISSUE TITLE
ToolStatus build problem

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#1144]
### Brief description of your issue

ToolStatus build problem

[01:54] Building Plugins (x32)...
[ERROR] (1) D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\filter.c(592,87): error C2440: 'function': cannot convert from 'PH_STRINGREF' to 'PWSTR' [D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\ToolStatus.vcxproj]D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\filter.c(592,47): warning C4024: 'WordMatchStringZ': different types for formal and actual parameter 1 [D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\ToolStatus.vcxproj]D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\filter.c(596,76): error C2440: 'function': cannot convert from 'PH_STRINGREF' to 'PWSTR' [D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\ToolStatus.vcxproj]D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\filter.c(596,43): warning C4024: 'WordMatchStringZ': different types for formal and actual parameter 1 [D:\Dev\ProcessHacker3\src\trunk\plugins\ToolStatus\ToolStatus.vcxproj]

### Steps to reproduce (optional)

Try to build PH plugins

### Expected behavior (optional)

Success

### Actual behavior (optional)

Build problem

### Environment (optional)

```shell
VS 17.1.0
```

**Comment by dmex** [comment]
Pending commit
