### ISSUE TITLE
0xC0000017 (Not enough virtual memory or paging file quota is available to complete the specified operation.)

### ISSUE THREAD

**Issue by as-muncher** [processhacker/processhacker#1148]
### Brief description of your issue

I caused Process Hacker 3.0.4600 to crash.

### Steps to reproduce (optional)

Open this one xml file in Firefox while Process Hacker is running
![process hacker crashed](https://user-images.githubusercontent.com/33010279/157993626-edc48061-349b-4110-81f7-1cd42737123a.png)
[ProcessHacker_HPYSHADOWUWTSZW_DumpFile.zip](https://github.com/processhacker/processhacker/files/8236581/ProcessHacker_HPYSHADOWUWTSZW_DumpFile.zip)
.

### Expected behavior (optional)

I expected Process Hacker to not crash.

### Actual behavior (optional)

Process Hacker crashes.

### Environment (optional)

```shell
Process Hacker 3.0.4600
Windows x64 10.0.19044.1586
```

**Comment by dmex** [comment]
> 0xC0000017 (Not enough virtual memory or paging file quota is available

VirtualAlloc failed to allocate 292KB of memory which is not possible:

![image](https://user-images.githubusercontent.com/1306177/158106223-fb12fb1b-a728-4709-97fe-e38fbdd8bc0c.png)

> Open this one xml file in Firefox 

This DLL inserted hooks for the allocation functions and likely caused the failure:

![image](https://user-images.githubusercontent.com/1306177/158107963-17a86602-ed7d-4491-a77c-9008d3b00c23.png)

**Comment by as-muncher** [comment]
I don't know why this page says that I added the "bug" and "needs investigation" labels, because I did no such thing.
But thank you for the response @dmex.  You're saying that it's Avast's fault, eh?

**Comment by dmex** [comment]
> I don't know why this page says that I added the "bug" and "needs investigation" labels

The tags are automatically added for bug reports. Select `blank issue` from the new issue page when you don't want tags.

> You're saying that it's Avast's fault, eh?

The system heap failed to allocate ~300KB which is not possible because Windows would have crashed or used the page file. The dump file made no sense so the only logical answer is faulty hardware or something hooking system functions.
