### ISSUE TITLE
The opacity function in quick settign menu sometime not working

### ISSUE THREAD

**Issue by i-am-unknown-81514525** [processhacker/processhacker#1150]
If you click on the the item trying to change its position  , the opacity stopped and you need to open the setting button to set it again

Before:
<img width="227" alt="Screenshot_168" src="https://user-images.githubusercontent.com/74453352/158053627-a979e90b-1f33-47ad-87f1-187425e2bd26.png">

After change the position:
<img width="218" alt="Screenshot_169" src="https://user-images.githubusercontent.com/74453352/158053835-dd40054d-b208-4067-82ff-2f49ba859def.png">

**Comment by dmex** [comment]
> click on the the item trying to change its position , the opacity stopped

I wasn't able to reproduce this on my machine. Looking at the code the opacity can only be changed by the menu, not by moving the window so another program on your machine would have to be changing the window opacity or triggering the menu.

**Comment by i-am-unknown-81514525** [comment]
I mean opacity value in the menu is not changed but it did not show the opacity that I should be
Like:
I set to 40%
I moved the window
The opacity value in setting is still 40% , but it show like 100%

**Comment by dmex** [comment]
I still can't reproduce this?
