### ISSUE TITLE
CPU header total incorrectly includes dead processes

### ISSUE THREAD

**Issue by SanderBouwhuis** [processhacker/processhacker#1155]
### Brief description of your issue

The total CPU usage above the CPU column doesn't only include live processes, but also dead processes (processes which are no longer running but are still being shown).

I have set the highlight duration to 30 seconds, so it regularly shows percentages over 100% because of dead processes.

### Steps to reproduce (optional)

Have a bunch of processes which start and stop regularly, like for instance compiling C++ code.
Look at the CPU usage... it shows percentages which are incorrect (always too high).

### Expected behavior (optional)

Dead processes should be excluded from the CPU totals of course.

### Actual behavior (optional)

Dead processes are included in the CPU totals

### Environment (optional)

```shell
Process Hacker v3.0.4600 (bc8b783)
Windows 10 Pro x64 English
```

**Comment by SanderBouwhuis** [comment]
Wow, what a quick fix!

Thanks a bunch!

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
