### ISSUE TITLE
ProcessHacker sometimes doesn't start hidden during log on

### ISSUE THREAD

**Issue by rpl2020** [processhacker/processhacker#1156]
### Brief description of your issue

ProcessHacker sometimes doesn't start hidden during log on.

Enabled Options: Start hidden, Enable start as admin, Start when I log on.

At first I thought that the Windows was running ProcessHacker twice during logon causing it to appear. I disabled the option "Allow only one instance" so that it will have 2 instances when it run twice and so when the ProcessHacker window appeared during log on, there is only one instance of ProcessHacker. Therefore, the Windows didn't run the ProcessHacker twice during log on.

I also tried to manually create a task in Task Scheduler to run ProcessHacker at log on with high privileges. Using -hide argument to hide with the options "Enable start as admin", "Start hidden", and "Start when I log on" are disabled. The result still the same, sometimes it's hidden and sometimes it's not.

I'm using HDD, so read-write access is slow compared to SSD.

### Environment (optional)

```shell
Process Hacker x64 Nightly Build: 3.0.4661
Windows 10 Version 10.0.19044.1586
```

**Comment by dmex** [comment]
Do you have this option enabled in Windows settings > Accounts > Sign-in options > Scroll down to Privacy?

![image](https://user-images.githubusercontent.com/1306177/159136216-7f1ef98e-926e-4b5e-8c55-1781fb9cf4d5.png)

**Comment by rpl2020** [comment]
> Do you have this option enabled in Windows settings > Accounts > Sign-in options > Scroll down to Privacy?
> 
> ![image](https://user-images.githubusercontent.com/1306177/159136216-7f1ef98e-926e-4b5e-8c55-1781fb9cf4d5.png)

Yes, it is enabled. And I'm using local account.

**Comment by as-muncher** [comment]
For me, Process Hacker 3.0.4861 doesn't even load on startup, even though I don't have it selected to start hidden, and it has not loaded on startup for a long time.  Maybe it's a registry value that needs to be fixed in my case.

**Comment by as-muncher** [comment]
@dmex, Do you mean to uncheck the box, then restart, then check the box, then restart?  Or uncheck the box, restart Process Hacker, then check the box?  or just as you stated: uncheck then recheck the checkbox?  I've tried unchecking and rechecking and it does not fix the problem.

**Comment by dmex** [comment]
> uncheck the box, restart Process Hacker, then check the box?

this

**Comment by as-muncher** [comment]
> > uncheck the box, restart Process Hacker, then check the box?
> 
> this

I did this and Process Hacker doesn't start on log on, still.  Could you help me to get it to work?

**Comment by as-muncher** [comment]
@dmex It's okay, it now loads on log on.
