### ISSUE TITLE
Discord blocks ProcessHacker executables and portable .zip

### ISSUE THREAD

**Issue by cxmplex** [processhacker/processhacker#1157]
When uploading the process hacker zip to Discord, Discord blocks it as "containing a virus". You can upload other files with EXEs, this is a detection, not an outright ban on executables. You may want to reach out to Discord Trust and Safety, and tell them this is a false positive.

**Comment by Biswa96** [comment]
May I ask why do you want to upload it in Discord? Instead, share the download like from ProcessHacker home page.

**Comment by cxmplex** [comment]
> May I ask why do you want to upload it in Discord? Instead, share the download link from ProcessHacker home page.

That's what I ended up doing. Regardless, it's still a FP.

**Comment by Masamune3210** [comment]
There probably isnt much that reaching out will do, as they likely use something like VirusTotal which also regularly detects this incorrectly as a piece of malware

**Comment by dmex** [comment]
> There probably isnt much that reaching out will do

I reached out and they've said the system will be improved.
