### ISSUE TITLE
Last source can't build

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#1160]
### Brief description of your issue

Last source can't build

**Comment by Biswa96** [comment]
Please provide the error or build output in the issue.

**Comment by Avtroman** [comment]
> Please provide the error or build output in the issue.

Сборка начата…
1>------ Сборка начата: проект: phlib, Конфигурация: Release x64 ------
1>apiimport.c
1>appresolver.c
1>avltree.c
1>basesup.c
1>circbuf.c
1>colorbox.c
1>cpysave.c
1>data.c
1>dspick.c
1>emenu.c
1>error.c
1>extlv.c
1>fastlock.c
1>filepool.c
1>format.c
1>global.c
1>graph.c
1>guisup.c
1>handle.c
1>hexedit.c
1>hndlinfo.c
1>http.c
1>icotobmp.c
1>filestream.c
1>imgcoherency.c
1>json.c
1>kph.c
1>kphdata.c
1>lsasup.c
1>mapexlf.c
1>mapimg.c
1>maplib.c
1>md5.c
1>native.c
1>provider.c
1>queuedlock.c
1>ref.c
1>secdata.c
1>secedit.c
1>settings.c
1>sha.c
1>sha256.c
1>theme.c
1>util.c
1>svcsup.c
1>symprv.c
1>sync.c
1>treenew.c
1>verify.c
1>workqueue.c
1>wslsup.c
1>bcd.cpp
1>format_std.cpp
1>phlib.vcxproj -> D:\processhacker-master\phlib\bin\Release64\phlib.lib
2>------ Сборка начата: проект: peview, Конфигурация: Release x64 ------
3>------ Сборка начата: проект: ProcessHacker, Конфигурация: Release x64 ------
2>cfgprp.c
2>chcol.c
2>clrprp.c
2>clrtableimportprp.c
2>colmgr.c
2>attributes.c
2>debugprp.c
2>ehcontprp.c
2>exlfdynamic.c
2>exlfexports.c
2>exlfimports.c
2>exlfprp.c
2>hashprp.c
2>layout.c
2>peheaderprp.c
2>peprpwnd.c
2>options.c
2>peexceptprp.c
2>perelocprp.c
2>pesectionprp.c
2>pepogoprp.c
2>richprp.c
2>secprp.c
2>ldprp.c
2>expprp.c
3>about.c
3>actions.c
3>affinity.c
3>anawait.c
3>appsup.c
3>chcol.c
3>chdlg.c
3>chproc.c
3>colmgr.c
3>colsetmgr.c
3>dbgcon.c
3>extmgr.c
3>findobj.c
3>gdihndl.c
3>heapinfo.c
3>hidnproc.c
3>hndllist.c
3>hndlmenu.c
3>hndlprp.c
3>hndlprv.c
3>hndlstat.c
3>infodlg.c
3>itemtips.c
3>jobprp.c
3>kdump.c
3>log.c
3>logwnd.c
3>D:\processhacker-master\ProcessHacker\itemtips.c(654,23): error C2039: "vt": не является членом "tagVARIANT".
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
3>D:\processhacker-master\ProcessHacker\itemtips.c(662,31): error C2039: "lVal": не является членом "tagVARIANT".
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
3>main.c
3>mainwnd.c
3>mdump.c
3>memedit.c
2>impprp.c
2>libprp.c
2>links.c
3>memlist.c
3>memlists.c
3>memprot.c
3>memprv.c
2>main.c
2>misc.c
2>pdb.c
2>pdbprp.c
3>memrslt.c
3>memsrch.c
3>miniinfo.c
3>modlist.c
2>pedirprp.c
2>peprp.c
3>modprv.c
2>D:\processhacker-master\tools\peview\pdb.c(175,17): error C2039: "vt": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(179,66): error C2039: "bVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
3>mtgndlg.c
2>D:\processhacker-master\tools\peview\pdb.c(184,66): error C2039: "iVal": не является членом "tagVARIANT".
3>mwpgnet.c
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
3>mwpgproc.c
2>D:\processhacker-master\tools\peview\pdb.c(191,66): error C2039: "lVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(194,64): error C2039: "fltVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(197,64): error C2039: "dblVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(200,68): error C2039: "bstrVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>previewprp.c
2>processes.c
3>mwpgsrv.c
3>netlist.c
3>netprv.c
2>propstore.c
3>netstk.c
2>prpsh.c
2>resprp.c
2>searchbox.c
3>notifico.c
3>ntobjprp.c
3>options.c
3>pagfiles.c
2>settings.c
2>streams.c
2>tlsprp.c
3>clapi.c
3>svcapi.c
3>svcapiport.c
3>svcclient.c
3>svcmain.c
3>plugin.c
3>plugman.c
3>procgrp.c
3>procmtgn.c
3>procprp.c
3>procprv.c
3>procrec.c
2>Сборка проекта "peview.vcxproj" завершена с ошибкой.
Сборка была отменена.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by Avtroman** [comment]
> Please provide the error or build output in the issue.

**Thirdparty project:**


Сборка начата…
1>------ Сборка начата: проект: thirdparty, Конфигурация: Release x64 ------
1>AArch64BaseInfo.c
1>AArch64Disassembler.c
1>AArch64InstPrinter.c
1>AArch64Mapping.c
1>AArch64Module.c
1>ARMDisassembler.c
1>ARMInstPrinter.c
1>ARMMapping.c
1>ARMModule.c
1>EVMDisassembler.c
1>EVMInstPrinter.c
1>EVMMapping.c
1>EVMModule.c
1>M68KDisassembler.c
1>M68KInstPrinter.c
1>M68KModule.c
1>MipsDisassembler.c
1>MipsInstPrinter.c
1>MipsMapping.c
1>MipsModule.c
1>SparcDisassembler.c
1>SparcInstPrinter.c
1>SparcMapping.c
1>SparcModule.c
1>SystemZDisassembler.c
1>SystemZInstPrinter.c
1>SystemZMapping.c
1>SystemZMCTargetDesc.c
1>SystemZModule.c
1>X86ATTInstPrinter.c
1>X86Disassembler.c
1>X86DisassemblerDecoder.c
1>X86IntelInstPrinter.c
1>X86Mapping.c
1>X86Module.c
1>XCoreDisassembler.c
1>XCoreInstPrinter.c
1>XCoreMapping.c
1>XCoreModule.c
1>cs.c
1>MCInst.c
1>MCInstrDesc.c
1>MCRegisterInfo.c
1>SStream.c
1>utils.c
1>adler32.c
1>compress.c
1>crc32.c
1>deflate.c
1>gzclose.c
1>gzlib.c
1>gzread.c
1>gzwrite.c
1>D:\processhacker-master\tools\thirdparty\gzip\gzlib.c(232,19): error C2065: O_RDONLY: необъявленный идентификатор
1>D:\processhacker-master\tools\thirdparty\gzip\gzlib.c(233,20): error C2065: O_WRONLY: необъявленный идентификатор
1>D:\processhacker-master\tools\thirdparty\gzip\gzlib.c(233,30): error C2065: O_CREAT: необъявленный идентификатор
1>D:\processhacker-master\tools\thirdparty\gzip\gzlib.c(238,20): error C2065: O_TRUNC: необъявленный идентификатор
1>D:\processhacker-master\tools\thirdparty\gzip\gzlib.c(239,20): error C2065: O_APPEND: необъявленный идентификатор
1>infback.c
1>inffast.c
1>inflate.c
1>inftrees.c
1>ioapi.c
1>iowin32.c
1>mztools.c
1>trees.c
1>uncompr.c
1>unzip.c
1>zip.c
1>zutil.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл gzip\unzip.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл gzip\unzip.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл gzip\unzip.c)
1>arraylist.c
1>debug.c
1>json_c_version.c
1>json_object.c
1>json_object_iterator.c
1>json_pointer.c
1>json_tokener.c
1>json_util.c
1>json_visit.c
1>libjson.c
1>linkhash.c
1>printbuf.c
1>random_seed.c
1>strerror_override.c
1>data-pool.c
1>maxminddb.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл jsonc\json_util.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл jsonc\json_util.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл jsonc\json_util.c)
1>miniz.c
1>mxml-attr.c
1>D:\processhacker-master\tools\thirdparty\miniz\miniz.c(3371,20): error C2079: "t" использует не имеющую определения структуру struct "utimbuf"
1>D:\processhacker-master\tools\thirdparty\miniz\miniz.c(3374,7): error C2224: выражение слева от ".actime" должно иметь тип структуры или объединения
1>D:\processhacker-master\tools\thirdparty\miniz\miniz.c(3375,7): error C2224: выражение слева от ".modtime" должно иметь тип структуры или объединения
1>D:\processhacker-master\tools\thirdparty\miniz\miniz.c(3377,18): warning C4013: utime: нет определения; предполагается "extern" с возвратом типа "int"
1>mxml-entity.c
1>mxml-file.c
1>mxml-get.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-attr.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-attr.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-attr.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-entity.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-entity.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-entity.c)
1>mxml-index.c
1>mxml-node.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-get.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-get.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-get.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-file.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-file.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-file.c)
1>mxml-private.c
1>mxml-search.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-index.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-index.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-index.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-node.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-node.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-node.c)
1>mxml-set.c
1>mxml-string.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-private.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-private.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-private.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-search.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-search.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-search.c)
1>pcre2posix.c
1>pcre2_auto_possess.c
1>pcre2_chartables.c
1>pcre2_compile.c
1>pcre2_config.c
1>pcre2_context.c
1>pcre2_convert.c
1>pcre2_dfa_match.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл mxml\mxml-set.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-set.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл mxml\mxml-set.c)
1>pcre2_error.c
1>pcre2_extuni.c
1>pcre2_find_bracket.c
1>pcre2_jit_compile.c
1>pcre2_maketables.c
1>pcre2_match.c
1>pcre2_match_data.c
1>pcre2_newline.c
1>pcre2_ord2utf.c
1>pcre2_pattern_info.c
1>pcre2_script_run.c
1>pcre2_serialize.c
1>pcre2_string_utils.c
1>pcre2_study.c
1>pcre2_substitute.c
1>pcre2_substring.c
1>pcre2_tables.c
1>pcre2_ucd.c
1>pcre2_valid_utf.c
1>pcre2_xclass.c
1>fuzzy.c
1>D:\processhacker-master\phnt\include\ntpsapi.h(695,9): error C2061: синтаксическая ошибка: идентификатор "PROCESS_MITIGATION_REDIRECTION_TRUST_POLICY" (компилируется исходный файл ssdeep\fuzzy.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(696,5): error C2059: синтаксическая ошибка: } (компилируется исходный файл ssdeep\fuzzy.c)
1>D:\processhacker-master\phnt\include\ntpsapi.h(697,1): error C2059: синтаксическая ошибка: } (компилируется исходный файл ssdeep\fuzzy.c)
1>Сборка проекта "thirdparty.vcxproj" завершена с ошибкой.
Сборка была отменена.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by dmex** [comment]
No idea what these errors are from. You might need to repair your visual studio.

**Comment by Avtroman** [comment]
> No idea what these errors are from. You might need to repair your visual studio.
It's installed shortly when builded

**Comment by Avtroman** [comment]
> No idea what these errors are from. You might need to repair your visual studio.

Today will try reinstall

**Comment by Avtroman** [comment]
> 
reinstall **NOT** helped

Сборка начата…
1>------ Сборка начата: проект: phlib, Конфигурация: Release x64 ------
1>phlib.vcxproj -> D:\processhacker-master\phlib\bin\Release64\phlib.lib
2>------ Сборка начата: проект: peview, Конфигурация: Release x64 ------
3>------ Сборка начата: проект: ProcessHacker, Конфигурация: Release x64 ------
2>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
2>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
2>cfgprp.c
2>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
2>chcol.c
2>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
2>clrprp.c
2>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
2>clrtableimportprp.c
2>colmgr.c
2>attributes.c
2>debugprp.c
2>ehcontprp.c
2>exlfdynamic.c
2>exlfexports.c
2>exlfimports.c
2>exlfprp.c
2>hashprp.c
2>layout.c
2>peheaderprp.c
2>peprpwnd.c
2>options.c
2>peexceptprp.c
2>perelocprp.c
2>pesectionprp.c
2>pepogoprp.c
2>richprp.c
2>secprp.c
2>ldprp.c
2>expprp.c
2>impprp.c
2>libprp.c
2>links.c
3>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
3>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
3>about.c
3>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
3>actions.c
3>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
3>affinity.c
3>cl : командная строка warning D9025: переопределение "/sdl" на "/GS-"
3>anawait.c
3>appsup.c
3>chcol.c
3>chdlg.c
3>chproc.c
3>colmgr.c
3>colsetmgr.c
3>dbgcon.c
3>extmgr.c
3>findobj.c
3>gdihndl.c
3>heapinfo.c
3>hidnproc.c
3>hndllist.c
3>hndlmenu.c
3>hndlprp.c
3>hndlprv.c
3>hndlstat.c
3>infodlg.c
3>itemtips.c
3>jobprp.c
2>main.c
3>kdump.c
3>log.c
3>D:\processhacker-master\ProcessHacker\itemtips.c(654,23): error C2039: "vt": не является членом "tagVARIANT".
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>misc.c
3>D:\processhacker-master\ProcessHacker\itemtips.c(662,31): error C2039: "lVal": не является членом "tagVARIANT".
3>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>pdb.c
3>logwnd.c
3>main.c
2>pdbprp.c
3>mainwnd.c
3>mdump.c
3>memedit.c
3>memlist.c
3>memlists.c
3>memprot.c
3>memprv.c
3>memrslt.c
3>memsrch.c
3>miniinfo.c
3>modlist.c
3>modprv.c
3>mtgndlg.c
3>mwpgnet.c
3>mwpgproc.c
2>pedirprp.c
2>peprp.c
2>D:\processhacker-master\tools\peview\pdb.c(175,17): error C2039: "vt": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(179,66): error C2039: "bVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(184,66): error C2039: "iVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(191,66): error C2039: "lVal": не является членом "tagVARIANT".
3>mwpgsrv.c
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
3>netlist.c
2>D:\processhacker-master\tools\peview\pdb.c(194,64): error C2039: "fltVal": не является членом "tagVARIANT".
3>netprv.c
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(197,64): error C2039: "dblVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>D:\processhacker-master\tools\peview\pdb.c(200,68): error C2039: "bstrVal": не является членом "tagVARIANT".
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\oaidl.h(476): message : см. объявление "tagVARIANT"
2>previewprp.c
2>processes.c
3>netstk.c
3>notifico.c
3>ntobjprp.c
3>options.c
2>propstore.c
2>prpsh.c
2>resprp.c
2>searchbox.c
3>pagfiles.c
3>clapi.c
3>svcapi.c
3>svcapiport.c
2>settings.c
3>svcclient.c
2>streams.c
2>tlsprp.c
3>svcmain.c
3>plugin.c
3>plugman.c
3>procgrp.c
3>procmtgn.c
3>procprp.c
3>procprv.c
3>procrec.c
3>proctree.c
2>Сборка проекта "peview.vcxproj" завершена с ошибкой.
Сборка была отменена.
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**processhacker FROM march 16 BUILD OK**

**Comment by dmex** [comment]
> reinstall NOT helped

These errors make no sense. There's something wrong with your SDK installation.

**Comment by Avtroman** [comment]
> > reinstall NOT helped
> 
> These errors make no sense. There's something wrong with your SDK installation.
4 SDK installed from Visual Stdio 2022 17.2 Preview 2.1

**Comment by dmex** [comment]
> 2022 17.2 Preview 2.1

MSVC now defines `__STDC__` (which doesn't make sense because it's not a standards compliant C compiler) and also changed the tagvariant structure removing the nameless unions... I've added a workaround in the latest commits 👍
