### ISSUE TITLE
Attempted to kill process, pc stuck in boot loop

### ISSUE THREAD

**Issue by sabuya1** [processhacker/processhacker#1162]
Hello everyone!

I downloaded process hacker in order to kill the antimalware service executable, since it took up 43% of my RAM (8gb). I had to finish a project so I had chrome and vbox open which fricked up my memory to the point where nothing could load. I was able to use both programs when the windows process wasn’t running yesterday. I was doing a project in VBox so I didn’t have a lot of time to screw around. (I’m trying to justify my reasoning just in case this is 100% my fault).

I think a new windows update made it so I didn’t have privileges to end the antimalware process. I was able to do it before. So when I used process hacker to kill the process, all windows processes started lagging (task bar, search, file manager, task manager) and my computer became unusable so I force restarted. Now my computer is stuck in a boot loop with error code bad_sys_config_info. It does not boot into safe mode. I cannot reverse updates and my last system restore takes me back to before my project started. Boot log isn’t working either. What could have happened? What did process hacker attempt to do?

**Comment by Masamune3210** [comment]
Don't end system processes like that, you just saw why. Especially ones that close to the low levels like Defender

**Comment by dmex** [comment]
> kill the service executable

Process termination is temporary and does not prevent the process from restarting.

> all windows processes started lagging

The antimalware service is configured to automatically restart after termination and triggered system scans causing the lag. 

> I force restarted
> boot loop with error code bad_sys_config_info

Termination doesn't corrupt the registry, the force restart corrupted the registry hive: https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x74--bad-system-config-info
