### ISSUE TITLE
Process Hacker Randomly Crashed

### ISSUE THREAD

**Issue by THEBOSS619** [processhacker/processhacker#1163]
### Brief description of your issue

It crashed when I tried to open [System Information].

Here is the dump file.
[ProcessHacker_NIOVGXLXABBNKBK_DumpFile.zip](https://github.com/processhacker/processhacker/files/8335565/ProcessHacker_NIOVGXLXABBNKBK_DumpFile.zip)

### Steps to reproduce (optional)

It was running on the background and when I opened process hacker and clicked on [System Information] and then it crashed. it might not be reproduceable. 

### Expected behavior (optional)

No crash happening.

### Environment (optional)

```shell
Process hacker 3.0.4687 Nightly.
I am using Windows 10 Pro x64 Version 2009 21H2 Build 19044.1618.
```

**Comment by THEBOSS619** [comment]
Another crash happened randomly. Process hacker was minimized at tray icon while watching YouTube.

Here's the dump:-
[ProcessHacker_YVJGPZGEFXQAUJY_DumpFile.zip](https://github.com/processhacker/processhacker/files/8356678/ProcessHacker_YVJGPZGEFXQAUJY_DumpFile.zip)

**Comment by Max33Verstappen** [comment]
The reproducing process of this crash (upon opening the "system information") is quite consistent.
The crash happens when opening "system information" a couple of times with "**Show one graph per CPU**" enabled (and of course, the opening view is on the CPU tab). On my side, disabling this no longer crashes the PH upon opening the "system information".

**Comment by dmex** [comment]
Fixed in latest nightly build

**Comment by THEBOSS619** [comment]
It happened again crashing but it happened only once while booting up or during the start up OS. Here's the dump file... hopefully you can pinpoint the problem. thank you.

[ProcessHacker_UZGOBGXRPRMHZSP_DumpFile.zip](https://github.com/processhacker/processhacker/files/8692912/ProcessHacker_UZGOBGXRPRMHZSP_DumpFile.zip)
