### ISSUE TITLE
Some processes do not show memory contents

### ISSUE THREAD

**Issue by kotenok2000** [processhacker/processhacker#1169]
### Brief description of your issue

Some processes do not show memory contents

When i open memory  tab it gets stuck on loading, and another process with the same name is created.
The newly created peocess has only two threads with ntdll.dll!RtlpProcessReflectionStartup starting points

[Снимок экрана (156)](https://user-images.githubusercontent.com/8822292/160220617-0030d96a-d4d6-4740-af92-07564a3fb413.png)

### Environment (optional)

```shell
3.0.4706 (fe1ba82)
Microsoft Windows [Version 10.0.22000.556]
```

**Comment by dmex** [comment]
@ge0rdi new setting named `EnableHeapReflection` for enabling heap reflection.

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
