### ISSUE TITLE
little feature..

### ISSUE THREAD

**Issue by Socol111** [processhacker/processhacker#1171]
Dear author's ! Thank you for a really great utility ! it's really very, very good.
 Just want to ask you about to make one little feature - add a switch to turn off the popup window in a tray-window. Because it's often popup when you going toi tray window to look some other programs or processhacker itself, you want to choose it, but popup window interfere to do that.  Thank you ! :-)

**Comment by Socol111** [comment]
Hello mate ! Sure, add a screenshot.A can't find any ability to turn it off or set up some delay for popup.This one.  28.03.2022, 19:44, "Biswapriyo Nath" ***@***.***>: Can you provide a screenshot of the popup windows that you want to turn off?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Biswa96** [comment]
The screenshot is not uploaded. Please use GitHub to upload it.

**Comment by Socol111** [comment]
> The screenshot is not uploaded. Please use GitHub to upload it.

![replay abt ph2](https://user-images.githubusercontent.com/51974471/160530180-76c9dcca-61da-4334-bdfb-6b4f71838996.png)

**Comment by Socol111** [comment]
done.29.03.2022, 06:34, "Biswapriyo Nath" ***@***.***>:
The screenshot is not uploaded. Please use GitHub to upload it.

**Comment by Socol111** [comment]
Sorry, where is that ? i search seems everywhere before ask you,and cant found now too.  PH 2.39.124.  29.03.2022, 11:20, "dmex" ***@***.***>: —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dmex** [comment]
> 2.39.124

v2.39 you have to edit the settings file manually and change `MiniInfoWindowEnabled` to 0

**Comment by Socol111** [comment]
Sorry, but 2.39.124 is last version, is that mean that this option was removed from menu options ?May be better to turn it back there ?And wich settings file you mean, please exact ? Can found ? 29.03.2022, 12:06, "dmex" ***@***.***>:2.39.124v2.39 you have to edit the settings file manually and change MiniInfoWindowEnabled to 0—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dmex** [comment]
https://processhacker.sourceforge.io/nightly.php
