### ISSUE TITLE
Disk section only has one process name

### ISSUE THREAD

**Issue by PJAlley** [processhacker/processhacker#1176]
In the Disk tab, there is only one process name - the System Process.

![2022-04-04 18_40_31-Process Hacker  MSI_timmy  (Administrator)](https://user-images.githubusercontent.com/40871127/161643783-f9592fe2-5b3f-4689-9151-2d0ccb2afff3.png)

Expected Result:
There should be more than one process in the Name column when a process reads from or writes to a file.

**Comment by dmex** [comment]
Thanks fixed in latest nightly 👍
