### ISSUE TITLE
Unable to launch Processhacker from Command Prompt.

### ISSUE THREAD

**Issue by itspocx** [processhacker/processhacker#1177]
How to fix this issue?

![image](https://user-images.githubusercontent.com/12825025/161973234-f1784678-c6b5-4f07-9c5c-9e078700bd5d.png)

**Comment by Biswa96** [comment]
Would you like to try the nightly builds from here https://processhacker.sourceforge.io/nightly.php ?

**Comment by itspocx** [comment]
Same issue with Latest Night build 3.0.4706

**Comment by dmex** [comment]
Works for me.

> How to fix this issue?

You have some sort of folder permissions issue and need to allow the user access to the folder.

**Comment by itspocx** [comment]
Yes, when I tested from virtual machine it is working. 
But it is definitely something else protecting from launching from command prompt in my machine but it is not folder permission.
Will do some diagnose from my side.
