### ISSUE TITLE
Unable to install process hacker

### ISSUE THREAD

**Issue by tcraigcouncil** [processhacker/processhacker#1178]
### Brief description of your issue

When trying to install Process Hacker, the exe exits with "Setup failed with an error" error. No other information provided. 

BitDefender did detect the download and files as malware. The setup file was added to an allow list using the hash provided. The default folder (C:\Program Files\Process Hacker) was added as a specific exclusion along with other files detected in BitDefender. It seems after uninstalling the program, adding the default folder to an exceptions list in BitDefender and attempting to reinstall causes the issue. BitDefender does not log subsequent issues with the program. 

### Steps to reproduce (optional)

1. Install
2. Have files removed by antivirus
3. Uninstall
4. Add exceptions
5. Attempt to reinstall to same location

### Expected behavior (optional)

For it to install

### Environment (optional)

```shell
Stable, Windows 10 21H1, BitDefender
```

**Comment by tcraigcouncil** [comment]
The workaround is to install in a different location. I'm not sure exactly where the "you can't do this" message is coming from (could not locate anything in the registry) but if I add the exception in BitDefender before installing, it works.

**Comment by dmex** [comment]
Uninstalling the program removes the directory, this probably causes BitDefender to ignore your whitelisting preferences because the directory no longer exists.

**Comment by as-muncher** [comment]
It's also Kaspersky Free that does this, possibly, but disabling it and then manually downloading the full copy and installing that doesn't work either.  @dmex Could you please at least make the error message more specific, like say what the error is.  Not just that installation failed with an error, but specifically what error.  I find I can't autoupdate and I can't manually update.

**Comment by dmex** [comment]
@as-muncher 

https://github.com/processhacker/processhacker/issues/1245

**Comment by as-muncher** [comment]
I have Kaspersky Free and I can't upgrade Process Hacker when it prompts to, and also when I download the process hacker nightly build, and try to install it manually, it still won't install, even if Kaspersky Free's protection is paused.  So what I have to do is use Revo Uninstaller, and not just uninstall it, but also to remove all the registry settings, then reboot, and then install the downloaded nightly build and then it works.
