### ISSUE TITLE
Missing handles from Handles menu

### ISSUE THREAD

**Issue by paulkermann** [processhacker/processhacker#1179]
### Brief description of your issue

Without the kernel driver you can't see the `File` object handle for processes you don't have access to (IE protected processes) even though you can see other types of handles (Events, Semaphores and more).

### Steps to reproduce (optional)

`wininit.exe` has handles to several files.
Without the driver you can see handles to several events, keys and semaphores however no file handles are found.
When you enable the driver you can see the file object handles.

### Expected behavior (optional)

I expect to see the file handle without the file name (similar to what happens with events).
With the `ObjectTypeIndex` you can tell that it is a `File`.

### Actual behavior (optional)

The file handles **don't** appear at all. It's like they don't exist.

### Environment (optional)

```shell
I have used the Process Hacker Nightly build.
```

**Comment by dmex** [comment]
Good catch fixed in latest nightly 👍
