### ISSUE TITLE
GeoIP file not created

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#1184]
### Brief description of your issue

PH cannt create GeoIP DB file

### Steps to reproduce (optional)

1. Delete *.mmdb file from settings folder.
2. Tools - Network tools - GeoIP update.

### Expected behavior (optional)

GeoLite2-Coutry.mmdb must be created in settings folder.

### Actual behavior (optional)

After downloading PH shows error:
![image](https://user-images.githubusercontent.com/8224786/163661067-c4248a0c-5221-4d41-8977-502666cf2b4a.png)

### Environment (optional)

```shell
PH 3.0.4754 and below
Windows 10.0.19044.1645
```

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
