### ISSUE TITLE
DoH keeps turning itself back on

### ISSUE THREAD

**Issue by CaptainFrosty** [processhacker/processhacker#1188]
### Brief description of your issue

Hi, I have the latest alpha version. The DoH advanced option keeps turning itself on. I need the DNS to stay plain to work with my proxy.

### Steps to reproduce (optional)

Set DoH setting to 0

### Expected behavior (optional)

Regular DNS

### Actual behavior (optional)

Queries to 1.1.1.1 appear in my logs and I find the option has changed 

### Environment (optional)

```shell
3.0.4780
latest Windows (11 21H2 build 22000.613)
```

**Comment by dmex** [comment]
The DoH setting is a checkbox on the General settings tab. If you're manually changing this elsewhere then it'll get overwritten by the General tab, so disable the option by unchecking the checkbox:

![image](https://user-images.githubusercontent.com/1306177/164309014-7e862059-abd1-4b97-baff-ff392287f8c6.png)

**Comment by CaptainFrosty** [comment]
@demex Oh. I guess I just forgot it was in the standard settings.
