### ISSUE TITLE
Can't setup process hacker

### ISSUE THREAD

**Issue by mori-0** [processhacker/processhacker#1189]
I go to launch the setup and it opens the windows message saying its not by them and install it anyway but then it comes up with an error message. 
"Windows cannot access the specified device, path, or file. You may not have the appropriate permission to access the item."

**Comment by dmex** [comment]
Very likely caused by security/antivirus software.

**Comment by mori-0** [comment]
> 

I looked through all of those and cant figure it out

**Comment by dmex** [comment]
> cannot access the specified device, path, or file.

Known issue is blocked by your security software.

**Comment by mattjaf** [comment]
im getting the same issue with the official version on windows 7. I don't really have an AV installed? is it cuz of windows defender??

**Comment by mori-0** [comment]
> im getting the same issue with the official version on windows 7. I don't really have an AV installed? is it cuz of windows defender??

No idea and just saying it’s a known issue didn’t help me so I was never able to fix it.

**Comment by TheDopeGuy1** [comment]
I know this is old but for future reference that error means that you need to go into the file properties and then go to security and click the edit button make sure that you have full control as your user and as admin. Then hit apply and ok to close it should fix it.
