### ISSUE TITLE
Image coherency column is always empty

### ISSUE THREAD

**Issue by Cheatoid** [processhacker/processhacker#1190]
### Brief description of your issue

This column has worked fine in some earlier 3.0 version (few months ago), but then it got broken after an update.

### Steps to reproduce (optional)

1. Open Process Hacker.
2. Right click column header, and then choose columns.
3. Add image coherency to active columns list. Click OK.
4. Observe that this column is always empty (for all processes).

### Expected behavior (optional)

The column should display coherency value (in percentage).

### Actual behavior (optional)

The column is always empty.

### Environment (optional)

```shell
Process Hacker latest nightly
Windows 10 x64 (version 1909, build 18363)
```

**Comment by Cheatoid** [comment]
I have figured out which version has broken it:
3.0.4365 ✔ works
3.0.4373 ✔ works
3.0.4399 ✔ works
3.0.4444 ❌ broken

**Comment by dmex** [comment]
> then it got broken after an update

The coherency feature is disabled by default unless you've enabled the option:

![image](https://user-images.githubusercontent.com/1306177/164993777-8f1dc934-5cfc-4343-a18a-1dbd2da7e8c5.png)

**Comment by dmex** [comment]
I've added a status message when it's disabled so it's easier to know why it's not working 👍
