### ISSUE TITLE
System.NullReference Exception

### ISSUE THREAD

**Issue by CaptainFrosty** [processhacker/processhacker#1191]
### Brief description of your issue

![image_2](https://user-images.githubusercontent.com/8523498/165144238-bd13b60f-a03f-4f59-805a-44aa3170f690.png)

I get this on boot. I think it started when I updated to the insider build so full disclosure. I have the kernel driver revocation with it too obviously. It does not occur when starting PH post-boot.

### Steps to reproduce (optional)

No action required aside from having the boot option on

### Actual behavior (optional)

See image

### Environment (optional)

```shell
PH 3.0.4801
Windows 11 22H2 build 22598.200
```

**Comment by dmex** [comment]
That's not an error dialog from this project.

**Comment by CaptainFrosty** [comment]
@dmex I apologize, it was a case of mistaken boot process identity. Should have used [Process Hacker](https://github.com/processhacker/processhacker) to check it before I posted the issue.
