### ISSUE TITLE
Can't select misc->collapse by default" for system idle process

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#1195]
### Brief description of your issue

I got an update for PH, which reseted the collapse settings and now I can't select misc->collapse by default" for system idle process any longer. It is grayed out like most other settings, but I want to collapse it all time.

I was able to do it in the past, but now it no longer works.

### Steps to reproduce (optional)

Do a rightclick in process tree on "system idle process", the misc entry is grayed out 

### Expected behavior (optional)

Do a rightclick in process tree on "system idle process" and be able to access misc entry to collapse idle process 

### Environment (optional)

```shell
Process Hacker Version: 3.0.4801 (078a905)
Windows 8.1 x64 German
```

**Comment by dmex** [comment]
Fixed in latest nightly

**Comment by MagicAndre1981** [comment]
thanks it works as expected in 3.0.4851
