### ISSUE TITLE
Missing ordinal 345 when installung any nightly version ?

### ISSUE THREAD

**Issue by petesky** [processhacker/processhacker#1196]
### Brief description of your issue

Missing ordinal 345 when installung any nightly version ?

### Expected behavior (optional)

Install over existing version.

**Comment by Biswa96** [comment]
Please add the environment details in the issue template. For example, Windows version, ProcessHacker version, any other antivirus or antimalware software etc.

**Comment by dmex** [comment]
ordinal 345 is TaskDialogIndirect so either you're trying to run nightly builds on Windows 2000 or your Windows installation is corrupted.
