### ISSUE TITLE
Use exact size when querying MemoryWorkingSetInformation

### ISSUE THREAD

**Issue by TYoung86** [processhacker/processhacker#1197]
Just noticed that PH tries to just grow an alloc when grabbing `MemoryWorkingSetInformation`. On the first call, `NumberOfEntries` is written which can then be used to determine the full size of the allocation necessary.

https://github.com/processhacker/processhacker/blob/ec12f8b95990466f1d9d335a392b57b0a95b87c3/phlib/native.c#L1612-L1632

e.g.
```cpp
    const size_t firstInfoSize = sizeof(MEMORY_WORKING_SET_INFORMATION); // can be a struct on stack
    NtQueryVirtualMemory( ... MemoryWorkingSetInformation, ... firstInfoSize, ...); // STATUS_INFO_LENGTH_MISMATCH
    size_t actualInfoSize = firstInfoSize + firstInfo.NumberOfEntries * (sizeof(MEMORY_WORKING_SET_BLOCK) + 1); // allocate this size for the actual info
    NtQueryVirtualMemory( ... MemoryWorkingSetInformation, ... actualInfoSize, ...);
```

**Comment by dmex** [comment]
> size_t actualInfoSize = firstInfoSize + firstInfo.NumberOfEntries * (sizeof(MEMORY_WORKING_SET_BLOCK) + 1);

You should use the built-in macros to calculate the correct array size (note the use of [ ] here)
`SIZE_T bufferSize = UFIELD_OFFSET(MEMORY_WORKING_SET_INFORMATION, WorkingSetInfo[firstInfo->NumberOfEntries]);`

> PH tries to just grow an alloc when grabbing MemoryWorkingSetInformation.

The number of working set pages changes hundreds of times a second for some processes (i.e. browsers/games/media players) and to minimize the number of system calls/query attempts (and improve performance) the buffer size is multiplied.

> On the first call, NumberOfEntries is written which can then be used to determine the full size of the allocation

Each time the process touches a page the number of entries becomes invalid and it'll still have to loop X attempts (especially with Chrome and Explorer).

**Comment by TYoung86** [comment]
So your intimation is that in the time between the first call and the second many pages could be allocated or that the buffer is reused?

**Comment by dmex** [comment]
> the time between the first call and the second many pages could be allocated

Yes

> you can use the number of entries as a minimum bound.

It'll make a few attempts before falling back to the previous code 👍
