### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by dzw13579** [processhacker/processhacker#1198]
### Brief description of your issue

when update sent the download request, the result return "error downloading the update",error code 12175,please help, thanks
![image](https://user-images.githubusercontent.com/59822418/166943841-7ee2c627-fceb-4bea-be5d-d87c6e79afc0.png)

### Environment (optional)

nightly version:3.0.4527

**Comment by dmex** [comment]
`12175: One or more errors were found in the certificate sent by the server.`

Your network provider is trying to hijack the Clowdflare certificate for sourceforge.net

**Comment by dzw13579** [comment]
> `12175: One or more errors were found in the certificate sent by the server.`
> 
> Your network provider is trying to hijack the Clowdflare certificate for sourceforge.net

all right, it's nothing I can do, Thank you for reply!

**Comment by dmex** [comment]
You need to use a VPN or switch internet provider.
