### ISSUE TITLE
How to setup Bitdefender AV which marks Process Hacker as potentially unwanted or dangerous application

### ISSUE THREAD

**Issue by MikePoppy** [processhacker/processhacker#1199]
Hi all,
As I can see in other threads and in all my PCs, they did it again. So here is how to prevent BD to kill PH (supposing you have full control over the BD=Bitdefender):

1) If you plan to do new installation of the PH, add AV exception for a folder where PH will be downloaded: Protection->Antivirus
->Settings->Manage Exception. Add exception, select the folder you wisely created before for this purpose only (!), check **Antivirus**, Save.

2) Repeat for the program folder, usually DRIVELETTER:\Program Files\Process Hacker 2. The folder must be created manually, PH installation reuses it. Other - more painfull - way is to install PH even if BD breaks the installation, program folder will be created by setup.

3) Install PH. If Bitdefender would confiscate some part (well shouldnt with the exception, but I've seen it already), just turn it off for five minutes. _For those who are afraid to do it and don't understand the details: Process Hacker is open source software so anybody can check sources; malware wouldn't be exposed this way, because the community would never allow such modifications. For the same reason, download PH only from Sourceforge to be sure you have the original version. AV companies tends to mark PH as dangerous because of its potential power as they're suspicious (which is their job in fact)_.

4) Switch to BD again, add exception for "DRIVELETTER:\Program Files\Process Hacker 2\ProcessHacker.exe". Be sure to check both "**Antivirus**" and "**Advanced Thread Defence**" this time.

You've done for basic usage. If you need to use kernel driver (if you're not sure, you don't need it probably), repeat step 4 with file "kprocesshacker.sys". It uses plugin extensions from subfolder "plugins", if BD tends to quarantine them, repeat step 2 with full path to this folder. If BD is still making problems, report it to the Bitdefender.

Actually, report it to the Bitdefender anyway. More reports = better chance they wake up again.

Bitdefender has one of best antivirus softwares around IMO, but this drives me crazy every time they do it again :-|

Mike

**Comment by Biswa96** [comment]
> So here is how to prevent BD to kill PH (supposing you have full control over the BD=Bitdefender)

Another ways is to uninstall BitDefender (supposing you have full control over the BD=Bitdefender).

BTW, it seems that you are using older ProcessHacker version. Use the latest one from here https://processhacker.sourceforge.io/nightly.php

**Comment by MikePoppy** [comment]
> Another ways is to uninstall BitDefender (supposing you have full control over the BD=Bitdefender).

This is not going to advice ordinary users (who came here by blind searching) what to do. They've learned that if a cracked app setup instruction tell them "ignore AV warning and disable AV", it's not good idea to follow. In their eyes you're assigning yourself in the same line with those "ugly hackers". Correct advice is: _uninstall BitDefender (which I still think IS one of best solutions regardless of this issue) **and install another AV which doesn't evaluate PH as harmful**_.

> it seems that you are using older ProcessHacker version

Thnx 4 notice.

**Comment by Masamune3210** [comment]
The problem is they almost all do, because a combination of reliance on machine learning and just plain stigma has caused most to treat it as a PUP at best and malware at most

**Comment by LucasD3** [comment]
For my purposes, the portable version of Process Hacker is sufficient, and it's easier to install on a Bitdefender-protected machine.

**Comment by dmex** [comment]
> this drives me crazy every time they do it again

The solution is uninstalling Bitdefender.

> Correct advice is: uninstall BitDefender (one of best solutions regardless of this issue) and install another AV

Their software has gone rouge overriding your preferences and doing whatever they feel like. There are 100 other security vendors and products who respect their customers, do the right thing and and are more deserving of your business. 

Uninstall BitDefender and find something better 👍
