### ISSUE TITLE
Can open file location support third-party file managers

### ISSUE THREAD

**Issue by vvyoko** [processhacker/processhacker#1200]
### Description of the feature, modification, idea or suggestion

I use online translation to communicate

like Total Commander or Directory Opus  etc...
They can take over the SHOpenFolderAndSelectItems

Here is the relevant documentation
https://docs.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems

Finally, thank you for developing the software

**Comment by dmex** [comment]
1) open `settings.xml`
2) update `FileBrowseExecutable`

Example:

![image](https://user-images.githubusercontent.com/1306177/167231290-ab4399ae-027b-417c-bdb1-f9b7dc16c047.png)

**Comment by vvyoko** [comment]
> 1. open `settings.xml`
> 2. update `FileBrowseExecutable`
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/1306177/167231290-ab4399ae-027b-417c-bdb1-f9b7dc16c047.png)


Thank you very much
Just recently found the time to deal with this
I just downloaded the last beta portable version
and changed it in ProcessHacker.exe.settings.xml

The third-party file manager is now called normally

But I don't have the option to show advanced in the settings here

**Comment by dmex** [comment]
> the option to show advanced

Options > General > select checkbox

![image](https://user-images.githubusercontent.com/1306177/167416788-d719404f-26f0-4bfc-ad0e-862a663c2a46.png)
