### ISSUE TITLE
process hacker wont stay open

### ISSUE THREAD

**Issue by wolfhunter56** [processhacker/processhacker#1201]
everytime i open my pc i can open process hackerr but not for longer than 20 seconds or when i try and play a game it not in that arrow thing with other apps in the cornor but it doesnt reopen after i open within 20 seconds of my pc being on

**Comment by dmex** [comment]
Autorun entries have a 20 second delay. You probably have some malware or bitcoin miner starting from autorun and terminating the process so rename the executable and run antivirus checks,
