### ISSUE TITLE
Middle click (MOUSE3) causes crash

### ISSUE THREAD

**Issue by ponei** [processhacker/processhacker#1202]
### Brief description of your issue

Clicking with the middle mouse button (MOUSE3) on nothing crashes Process Hacker

https://user-images.githubusercontent.com/28790957/167317175-9f20f79f-f075-44cc-b974-af3d7b171831.mp4

### Steps to reproduce (optional)

Click with the middle mouse button :D

### Expected behavior (optional)

Nothing :D

### Actual behavior (optional)

Crashes :DDDDDDDDDDDDDDD

### Environment (optional)

```shell
Process Hacker Nightly 3.0.4851
Windows 10
```

**Comment by dmex** [comment]
@TheEragon The crash was introduced in PR https://github.com/processhacker/processhacker/pull/1080 

It just needs null checks for `mouseEvent->Node`. Did you want to add them or want me to?

**Comment by TheEragon** [comment]
> @TheEragon The crash was introduced in PR #1080
> 
> It just needs null checks for `mouseEvent->Node`. Did you want to add them or want me to?

Done, sorry...I missed this :(

**Comment by dmex** [comment]
> Done, sorry...I missed this :(

All good, happens to the best of us 😘
