### ISSUE TITLE
Regional settings conflict with CSV export because of comma for decimals

### ISSUE THREAD

**Issue by ricardosalta** [processhacker/processhacker#1207]
### Brief description of your issue

If I export the process list, it generates a comma-separated values block of text.

Now in my case, my regional settings say that a number with decimals goes with comma, so for example, 8,92

This creates a small problem if importing to Excel to run a Text-to-Columns operation

Not enough to get much attention, but I couldn't go without reporting

Thanks

**Comment by dmex** [comment]
I've updated the nightly build so it'll format numbers using full stop instead. There doesn't seem to be a reliable way of escaping commas in CSV files that works for all programs. The only way seems to be removing commas from the CSV.

**Comment by ricardosalta** [comment]
Great, thanks
