### ISSUE TITLE
new intel 12700k

### ISSUE THREAD

**Issue by pakosanz** [processhacker/processhacker#1208]
Hello i just update my pc to the 12700k and its showing just 1 core usage, 
also the gpu wast 0% but this was on the previous CPU too
and i cant handle some process to idle in windows 11

**Comment by dmex** [comment]
You probably need to reset settings to defaults. Select Reset from the options window:
![image](https://user-images.githubusercontent.com/1306177/168416265-ea40c476-5849-4abe-8566-5753cc8ff16d.png)
