### ISSUE TITLE
ntpsapi.h macros with NtCreateUserProcess

### ISSUE THREAD

**Issue by odzhan** [processhacker/processhacker#1209]
For at least one (or possibly more) of the macros in ntpsapi.h is wrong and when used with NtCreateUserProcess returns STATUS_INVALID_PARAMETER.

```
#define PS_ATTRIBUTE_MITIGATION_OPTIONS \
    PsAttributeValue(PsAttributeMitigationOptions, FALSE, TRUE, TRUE)
```

Equates to 0x00060010 when it should be 0x0x00020010 using:

```
#define PS_ATTRIBUTE_MITIGATION_OPTIONS \
    PsAttributeValue(PsAttributeMitigationOptions, FALSE, TRUE, FALSE)
```

[Reference 1](https://twitter.com/passthehashbrwn/status/1524133299370790913)
[Reference 2](https://offensivedefence.co.uk/posts/ntcreateuserprocess/)

**Comment by dmex** [comment]
@diversenok

**Comment by dmex** [comment]
@diversenok 

I think all of them have been fixed?

**Comment by diversenok** [comment]
Yes, just double-checked – all values from the latest commit match the ones expected by the OS. Both in the case of native and Win32 attributes. 👍

**Comment by odzhan** [comment]
Thanks!
