### ISSUE TITLE
Setup doesn't work from an ImDisk volume

### ISSUE THREAD

**Issue by benrg** [processhacker/processhacker#1211]
Installing 3.0 nightlies fails (with "an error") after choosing the installation folder if the setup .exe is located on an ImDisk virtual disk volume.

ImDisk volumes aren't registered with the volume manager, which confuses some Win32 API functions. The drive where the volume is mounted is a DosDevices symlink to `\Device\ImDisk#` where `#` is 0, 1, ...

Using Process Monitor I can see that the setup program is trying to find itself at `D:\Device\ImDisk0\path\setup.exe` when its actual path is `D:\path\setup.exe`.

This is arguably ImDisk's fault for not playing by the rules, but most setup programs do work from an ImDisk RAM disk and it would be nice if PH's did too.

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
