### ISSUE TITLE
Don't base64-encode the setup data

### ISSUE THREAD

**Issue by benrg** [processhacker/processhacker#1212]
The bulk of the setup .exe is a base64-encoded zip file in a RCDATA resource.

Skipping the encoding and decoding steps would simplify the code of the build tool and the setup tool, and would shave several megabytes off of every installer download, and I don't see a downside.

The encoding was added in b9582f8b75ed61243bae824117344257ebafed48 with the comment "Improve caching". I don't see how it would improve the caching of anything, unless it's a workaround for some bug – in which case, perhaps the bug has since been fixed?

**Comment by dmex** [comment]
> The encoding was added in ... with the comment "Improve caching". I don't see how it would improve the caching of anything


The updater uses a function called `PhCreateCacheFile` and `PhClearCacheDirectory` for managing downloads with custom caching support.

Security software detects the .zip resource and automatically blocks the download. So encoding the .zip as base64 prevents the setup from getting deleted during download and thus improves the caching.

> The bulk of the setup .exe is a base64-encoded zip file in a RCDATA resource.
> several megabytes off of every installer download

Removing the base64 will only save 2mb of data from the bin-zip/setup.exe.

> I don't see a downside.

base64 encoding helps detect/prevent corruption and also significantly reduces the false positive rate?
