### ISSUE TITLE
crash 0xC0000005 tried to wread or write memory without permission

### ISSUE THREAD

**Issue by Janmm14** [processhacker/processhacker#1214]
### Brief description of your issue

[ProcessHacker_OQJETLIAXYHVORQ_DumpFile.zip](https://github.com/processhacker/processhacker/files/8692687/ProcessHacker_OQJETLIAXYHVORQ_DumpFile.zip)

### Environment (optional)

```shell
Process Hacker
Version: 3.0.4851 (230e539)
```

**Comment by dmex** [comment]
You need to update to the latest nightly build r4861
