### ISSUE TITLE
bypass avast

### ISSUE THREAD

**Issue by UnrealKaraulov** [processhacker/processhacker#1216]
### Description of the feature, modification, idea or suggestion

need reenable process hacker as default task manager when it disable (auto, for example via task)

**Comment by dmex** [comment]
The solution is uninstalling Avast.

**Comment by Masamune3210** [comment]
There is no way to bypass it, that's the point. If the security software isn't listening to what you want it to do and is reverting the change back to stock without you wanting to, the solution really is to just uninstall Avast and either find a security software that actually listens to its users requests, or just go with Windows Defender and don't use third-party security software
