### ISSUE TITLE
c2220 Error procprv.c

### ISSUE THREAD

**Issue by IgorShishkin12** [processhacker/processhacker#1218]
### Brief description of your issue

while building it throw errors: 
![image](https://user-images.githubusercontent.com/93098657/168489910-0c19f321-a217-4d98-a944-63e60bd2d65d.png)
visual studio 2022
windows 11

i commented functions that throw errors and it was build and launched but it throw more errors(but still running)
![image](https://user-images.githubusercontent.com/93098657/168490068-78c38bda-1583-4414-bc10-64152fef9b59.png)

**Comment by dmex** [comment]
Fixed
