### ISSUE TITLE
"WMI Providers" tab crashes Process Hacker.

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#1223]
### Brief description of your issue

"WMI Providers" tab crashes Process Hacker.

https://i.imgur.com/vOuQPgn.png

### Steps to reproduce (optional)

Click the tab.

### Expected behavior (optional)

Not Crash

### Environment (optional)

```shell
Version 4900

https://i.imgur.com/hjDcnB3.png
```

**Comment by diversenok** [comment]
This issue was already fixed in https://github.com/processhacker/processhacker/commit/143f9d02ab7db89289e025d8a624fba43ef6f00d, you need to update to version 3.0.4902
