### ISSUE TITLE
Affinity

### ISSUE THREAD

**Issue by itzhexen** [processhacker/processhacker#1225]
Could you add a feature so that I can save Affinity per application? I used this for Quake 2 and when I exited and ran the application again the Affinity was reset. I'm not sure if it saves affinity or not. But it didn't work for Quake 2. Thank you.

**Comment by dmex** [comment]
This was added to the nightly builds a few years ago?

https://processhacker.sourceforge.io/nightly.php

**Comment by itzhexen** [comment]
Ok thanks. That’s good to know. I’ve switched to using Process Lasso instead. But maybe I’ll go back and test it out again. Maybe I just didn’t think I was seeing it save the settings.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
