### ISSUE TITLE
can't make "Start when I log on" stay uncheckmarked

### ISSUE THREAD

**Issue by as-muncher** [processhacker/processhacker#1226]
3.0.4902 on Windows 10 x64

I uncheck "Start when I log on", and the box is unchecked, then close Process Hacker, then start it again, and find that the checkbox is still checked.

**Comment by dmex** [comment]
> the checkbox is still checked.

I tested 3 machines and this option works fine. In your case something (e.g. security software) is probbaly blocking changes to the autorun entry in the registry. That checkbox depends on the registry so you'll have to delete the key manually:

1) open regedit.exe
2) navigate `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`
3) right-click delete "Process Hacker"

![image](https://user-images.githubusercontent.com/1306177/169197530-34ff0754-2894-4618-b410-c4936a02c035.png)

**Comment by as-muncher** [comment]
@dmex Thank you.
