### ISSUE TITLE
Command line parameters that work?

### ISSUE THREAD

**Issue by worm001** [processhacker/processhacker#1230]
Stubborn processes such as 'Alibabaprotect.Exe', conventional methods cannot end it! You can end it with 'process hacker' under the GUI, but not on the command line? "ProcessHacker. Exe - C - ctype process - CObject "PID" - caction terminate", is the parameter insufficient? What should I do?

**Comment by dmex** [comment]
> but not on the command line?

The command line actions have been deprecated since 2015 to comply with security requirements.

> What should I do?

Uninstall Alibabaprotect.
