### ISSUE TITLE
I can't select processes if i selection begins with text

### ISSUE THREAD

**Issue by kotenok2000** [processhacker/processhacker#1233]
### Brief description of your issue

When i try to select multiple processes selection fails if  i start highlighing with field thaqt has text in it.

### Steps to reproduce (optional)

1. mouse highlight multiple processes starting with field that has text in it
2. it doesn't work.

### Environment (optional)

```shell
Version: 3.0.4905 (2b70d0a)
Microsoft Windows [Version 10.0.22000.675]
```

**Comment by dmex** [comment]
You need to use the control key+click or shift key+click selection methods. The drag select won't work in a number of cases.
