### ISSUE TITLE
Cropped text of toolbar button

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#1234]
### Brief description of your issue

Cropped text of toolbar button Show details for all processes:
1) when I add this button to toolbar - all OK
![screenshot 2022-05-25 17-35-56 001.png](https://i1.imageban.ru/out/2022/05/25/45e032fae1caaf639dc385da204b5d90.png)
2) after restart of PH - cropped
![screenshot 2022-05-25 17-37-25 002.png](https://i7.imageban.ru/out/2022/05/25/ffd6cdeece8c1b1539895efcf8c03a2c.png)
3) and still cropped next launches
4) when I remove and add this button - all OK again until restart

```shell
PH 3.0.4905
Windows 10 21h2 x64 + all updates

Only when started as admin (or restarted via this button). As user all fine.
```

**Comment by dmex** [comment]
Looks like it's a bug from 2005:
https://forums.codeguru.com/showthread.php?346319-Disabling-a-toolbar-button-with-longish-text

**Comment by pasha-zzz** [comment]
Maybe hide this button if already started as admin?

**Comment by pasha-zzz** [comment]
Or when started as admin change this button text (and maybe an icon) to "Start as user"? Not disabled and not cropped.

**Comment by dmex** [comment]
> Maybe hide this button if already started as admin?

Old versions used to hide the button but this ends up breaking layouts/customization.

> Or when started as admin 

I've fixed the issue 👍 

> change this button text (and maybe an icon) to "Start as user"? Not disabled and not cropped.

That's a good idea since I run everything as standard but does anyone else?

**Comment by dmex** [comment]
> change this button text "Start as user"

This should be a separate feature request.

>Cropped text of toolbar button

Fixed in latest nightly build 👍
