### ISSUE TITLE
PH3 doesn't display memory reduction (where PH2 does) from https://github.com/henrypp/memreduct  

### ISSUE THREAD

**Issue by davidmbesonen** [processhacker/processhacker#1246]
### Brief description of your issue

While running PH3, after reducing memory usage with Mem Reduct's (https://github.com/henrypp/memreduct) default "Clean memory..." command, PH3's "System Information" Memory status does not change.  

### Steps to reproduce (optional)

Download and run Mem Reduct (https://github.com/henrypp/memreduct/releases).  

Issue the default Mem Reduct "Clean Memory..." command with PH2 running then again with PH3 running.  

Observe that "System Information" Memory status **does** change with PH2 and **does not** change with PH3.  

### Expected behavior (optional)

I expected PH3's "System Information" to display a reduction in memory (from Mem Reduct) in the same manner as PH2.  

### Environment (optional)

```shell
Tested on Windows 7 and Windows 10.
```

**Comment by dmex** [comment]
Works for me?

**Comment by jxy-s** [comment]
I also confirmed this appears to be working for me:

![image](https://user-images.githubusercontent.com/11687482/173164754-a03287f2-fd79-4eb6-a000-d8df9e400127.png)

Is there something more specific you're not seeing change that you expect to @davidmbesonen?
