### ISSUE TITLE
Where is the last information about the launch arguments PH?

### ISSUE THREAD

**Issue by Zymlex** [processhacker/processhacker#1249]
`/?` `--help` `-?` `/help` and others - not works...

**Comment by dmex** [comment]
The command line options were deprecated and removed.

**Comment by dmex** [comment]
Some security companies classify tools with command line options as PUA.

**Comment by Biswa96** [comment]
Is it possible to add the command line feature in a different executable but not in official release? Or maybe in a different vs project configuration of PH?

**Comment by dmex** [comment]
This is what the CustomCommandTool project does. There are no compiled binaries and not updated:
https://github.com/processhacker/processhacker/tree/master/tools/CustomCmdTool
