### ISSUE TITLE
Tray icon no longer shows history (nighly build)

### ISSUE THREAD

**Issue by David-Hari** [processhacker/processhacker#1250]
### Brief description of your issue

Process Hacker 2 used to show a history graph of CPU in the tray icon. Nightly build just shows a bar indicating current usage.

Even when I select "CPU History" in the settings, it still does not show.

https://i.postimg.cc/5NjB0fZg/before.png
https://i.postimg.cc/rsZ5JHt5/after.png
https://i.postimg.cc/BZm54jwt/settings.png

### Steps to reproduce (optional)

Install nightly build of Process Hacker and run it.
Observe tray icon

### Environment (optional)

```shell
PH: nightly 3.0.4945 (55259f6)
Windows: 10, version 21H2 (OS Build 19044.1706)
```

**Comment by jxy-s** [comment]
This appears to be working fine for me on the latest nightly:

![image](https://user-images.githubusercontent.com/11687482/173259961-262705e0-8ca7-4ee1-b2af-6ce517e91ee3.png)

This setting was moved to `View > Tray icons > ...`. You can have multiple try icons. Please make sure you're viewing the correct one in the tray. The `CPU history` does look similar to `CPU usage`. Is it possible both are selected and the history is in the overflow?

![image](https://user-images.githubusercontent.com/11687482/173260001-30805996-676f-4dc0-b0b9-a9dab98bdce9.png)

**Comment by David-Hari** [comment]
Thanks, that did it.

I looked everywhere in settings for some way to get the old behaviour back, but I didn't think to look under the View menu.
