### ISSUE TITLE
PH2 Does not display some general information about WSL processes

### ISSUE THREAD

**Issue by Sidneys1** [processhacker/processhacker#153]
For example, opening the properties panel for a Windows Subsystem for Linux process shows `N/A` for:
* Image file name
* Command Line
* Current Directory
* Parent process (gets PID correct but does not resolve: "Non-existent process")

Probably more

**Comment by dmex** [comment]
Windows 10 doesn't have any process information classes for querying WSL process information. 

The only other alternative is parsing the strings from the /proc directory the same way Task Managers on Linux query process information: https://unix.stackexchange.com/questions/340834/is-it-possible-to-query-process-information-from-linux-kernel-directly

No API means having to launch bash.exe with an embedded script "cat /proc/%lu/cmdline" or using a Helper process (optional) for finding the Linux process PID and querying the process information.

**Comment by poizan42** [comment]
The parent process is correct as far as I can tell from the point of view of Windows. What seems to happen is that one process object is allocated when the process forks. Then a new process object is allocated on exec, but still linked to the same WSL process. So the parent pid is the short lived process that immediately forks.

**Comment by dmex** [comment]
@Sidneys1 

The missing Image file name was fixed in the latest nightly build but querying the other properties is problematic due to the current WSL implementation. 

I've emailed Microsoft about those problems to see if we can get those issues fixed and I'll update this issue when more information is available.

**Comment by dmex** [comment]
@Sidneys1 @poizan42 

The latest nightly now includes version information for WSL processes. If it's not working then let me know which distro you're using 👍

![image](https://user-images.githubusercontent.com/1306177/51779593-93860680-2108-11e9-8f8c-8c0e728aaa05.png)

**Comment by Biswa96** [comment]
Issue. Does ProcessHacker create new wsl.exe processes? It's annoying when I enable "Scroll to new processes".

**Comment by dmex** [comment]
@Biswa96 

Process hacker uses the WslLaunch function to start dpkg-query and query the linux process versioninfo. 

The unfortunate thing is that WSL creates **5** extra Windows processes for every call to WslLaunch... wsl.exe, wslhost.exe,  consthost.exe for wsl.exe, conhost.exe for wslhost.exe, svchost.exe for LxssManager and this doesn't even include the actual process specified in the WslLaunch commandline, the processes launched by that command or even the /init process...

The call stack is something like this: 
WslLaunch -> CreateProcess -> SYSCALL -> ntoskrnl.exe -> APC -> wsl.exe -> *** *** -> CoCreateInstance(IWslSession) -> RPC -> svchost.exe(LxssManager) -> DeviceIoControl(\Device\lxss) -> SYSCALL-> LXCORE.SYS

*** This step launches four additional conhost/wslhost processes with the exact same callstack above.

WslLaunch also has some other major issues including calling CopyFileW for /init and /bin/wslpath both of which cause more serious issues when creating WSL processes.

I have a ticket open for that issue at least but who knows when Microsoft will actually do anything to fix those implementation problems: https://github.com/Microsoft/WSL/issues/3811

As a temporary workaround you can disable the Options > Check images for digital signatures option to disable querying WSL process versioninfo.

**Comment by Biswa96** [comment]
If you have some kernel mode magic [this](https://github.com/Biswa96/WslReverse/commit/729bbee8ba5692043a66f8460ed4d2e955a707b6) may help. Your EPROCESS tip gave me this idea. This IOCTL gets PID from `PsGetProcessId(PEPROCESS)` in LxCore.

**Comment by dmex** [comment]
> If you have some kernel mode magic [this](https://github.com/Biswa96/WslReverse/commit/729bbee8ba5692043a66f8460ed4d2e955a707b6) may help.

The "ProcessHandle" is incorrect. It's a 'pseudo' process handle which is internally a file handle made to look like a process handle.

> This IOCTL gets PID from `PsGetProcessId(PEPROCESS)` in LxCore.

You can't use process handles with ZwDeviceIoControlFile so it would be getting the PID from the PicoContext.

**Comment by dmex** [comment]
Closing since this will be obsolete with WSLv2.

**Comment by Biswa96** [comment]
WSL1 will not be removed.

**Comment by dmex** [comment]
@Biswa96 

Microsoft hasn't updated or fixed hundreds of WSLv1 issues in the last year or even fixed basic issues... I seriously doubt they're going to continue working on v1 now they're using a hyper-v virtual-machine with a real kernel for v2.

**Comment by Biswa96** [comment]
Agreed. Those issues are mostly what Linux kernel can do but WSL1 can't. Spoiler alert: WSL2 may use some kind of sockets. So it may be easier for KPH.
