### ISSUE TITLE
[enhancement] Add support for listing all windows on other desktops on all window stations

### ISSUE THREAD

**Issue by poizan42** [processhacker/processhacker#159]
Including listing windows stations in each session, listing desktops on each window station and windows on each desktop.

**Comment by dmex** [comment]
Try enabling the ProcessHacker.WindowExplorer.ShowDesktopWindows setting in the settings file (remember to close Process Hacker before changing the settings).

That option enables the 'Desktop Windows...' option on the view menu for selecting different desktops to enumerate.... It should already enumerate all window stations and list all desktops on different sessions?

**Comment by poizan42** [comment]
I can see Default and Winlogon. It doesn't show any windows on the Winlogon desktop. I can see that there is at least one other desktop on the winsta - "Disconnect" which winlogon.exe has an open handle to but that isn't listed.

It does not show anything about any other windows stations, not even in the same session. E.g. Chrome creates a window station with a default name such as \Sessions\1\Windows\WindowStations\Service-0x0-8726b with a desktop called something like sbox_alternate_desktop_0x2D1C, but this isn't shown anywhere.

**Comment by poizan42** [comment]
It may be worth pointing out that the documented win32 apis requires you to have a window station active for the process to enumerate the top level windows of any desktop on it with EnumDesktopWindows, and you need to actually set the current desktop for the thread to enumerate their child windows.

Oh, and doing anything with desktops belonging to window stations in other sessions seems to be impossible with documented apis. Even attempting to DuplicateHandle them from another process fails if they belongs to another sessions - curiously it fails with ACCESS_DENIED even though the process has been opened with PROCESS_DUP_HANDLE access.

So besides peeking into private User structs from kprocesshacker (which is probably quite fragile), I imagine the way to implement this is to use a helper process per session since that can freely change its window station.

**Comment by dmex** [comment]
I've been playing around with this but its very problematic doing it the way you suggest... It might be more useful to show what the current user can enumerate without showing the other objects?

You can run Process Hacker as System and it can show/view the desktops and sessions available to services and when run as the current user it'll show what that user can access.

> doing anything with desktops belonging to window stations in other sessions seems to be impossible

The security on other desktops is based on the process token "LogonSessionId" that has the "Logon ID" flag and the subsequent checks are based on the DACL of the window station and the DACL of the desktop... Right now you need to change the DACL of these objects to grand the current user access before you can use the "documented" API.

The EnumWindowStations function also only enumerates window stations located in the "\Sessions\<UserSessionId>\Windows\WindowStations" directory object (you can see them using Winobj) but there are more window stations available in the "\Windows\WindowStation" directory.

Another method for querying every window station and desktop is by enumerating every process and reading the PEB->ProcessParameters->DesktopInfo string.
