### ISSUE TITLE
Hang on startup

### ISSUE THREAD

**Issue by Skibicki** [processhacker/processhacker#170]
Windows 8.1 x64
Process Hacker hangs and shows 100% cpu usage for a few seconds during startup.
Occurs between master 76a4dac2 and 7879df7b

**Comment by dmex** [comment]
It's probably the service signature verification... Can you try disabling signature verification so I know for sure that's whats causing the problem?

Options window > Advanced > Uncheck the "Check images for digital signatures and packing" option and restart Process Hacker.

**Comment by Skibicki** [comment]
That works.

**Comment by dmex** [comment]
I can't reproduce this issue on Windows 8... are you able to email me the list of services installed on your machine?

1. Add every column to the services tab (you don't need to enable signature checking or other stuff - just add the columns)
2. Select the Hacker menu > Save option (while the services tab is selected).
3. Email the text file to dmex04 at gmail.com

**Comment by dmex** [comment]
Thanks for the email! I wasn't able to recreate the issue but as I understand it's related to some specific Windows Updates that are no longer publicly available. 

I've disabled service verification by default so this won't be an issue going forward 👍

**Comment by Skibicki** [comment]
@dmex I think a recent Windows update fixed it. Need others to try it.

**Comment by dmex** [comment]
I've re-enabled the service verification and haven't seen any issues 👍
