### ISSUE TITLE
Feature Request: Option to focus the Search box

### ISSUE THREAD

**Issue by Kobus-Smit** [processhacker/processhacker#178]
Would it be possible to add an option to click the Processes tab and focus the Search box (and clear it) when the Process Hacker window is shown? Or would the above be possible by writing a plugin?

I've found that many times I wanted to quickly launch PH and then use the search functionality to find a process and then press Del to kill it or other times press Enter to view its properties, just using the keyboard.

My current hack is this AutoHotkey script where I've assigned it to the Win+H key and mapped it to a dedicated M5 key on my Roccat Isku keyboard.
```
;Show Process Hacker, focus the Processes tab and focus the Search textbox
#h::
Run "C:\Program Files\Process Hacker\ProcessHacker.exe"
Sleep 100
if (WinActive("ahk_exe ProcessHacker.exe"))
{
	SendMessage, 0x1330, 0,, SysTabControl321  ; 0x1330 is TCM_SETCURFOCUS.
	Sleep 0  ; This line and the next are necessary only for certain tab controls.
	SendMessage, 0x130C, 0,, SysTabControl321  ; 0x130C is TCM_SETCURSEL.	 
	SendInput ^k
	Sleep 10
	Send {Delete}
}    
Return
```
It works most of the times.

Another related question is how do I use the keyboard to change the focus from the Search textbox to the main results grid? It would be great if pressing Enter or Tab would do that.

PS: Thank you very much for this great tool!

**Comment by dmex** [comment]
This was added a few years ago. You can enable the auto-focus using the Options > ToolStatus > Enable autofocus checkbox 

![image](https://user-images.githubusercontent.com/1306177/113009561-ca15ab00-91c3-11eb-923a-e7a5342f51d8.png)

**Comment by Kobus-Smit** [comment]
I've enabled the auto focus checkbox and it works when I click on Process Hacker in the tray 👍
but it does not work when I open Process Hacker via the AutoHotkey shortcut?

Reproduce steps:
1. When ProcessHacker.exe is already running minimized in the tray and the above mentioned checkbox is checked,
2. Run ProcessHacker.exe again via AutoHotkey or  `Win+R`, to bring the window to the front
3. The search box is not focussed


![image](https://user-images.githubusercontent.com/11263864/113459023-02391a00-9460-11eb-8704-5e943a28deb8.png)
![image](https://user-images.githubusercontent.com/11263864/113459142-475d4c00-9460-11eb-806c-611e2311c5c1.png)

**Comment by dmex** [comment]
Fixed in the latest nightly update 👍
