### ISSUE TITLE
[Request] System information Tab

### ISSUE THREAD

**Issue by sick13** [processhacker/processhacker#191]
An option to enable System Information windows to put it in with the other tabs and not as a separate window

**Comment by VictorVG** [comment]
Use Ctrl-I shortcut for open this window. Is very simple...

**Comment by sick13** [comment]
i understand that, but what i am saying is to put "that" window in with the other tabs (Processes,Services,Network,Disk) and not as a separate window

**Comment by VictorVG** [comment]
This is understandable, I look at it differently - the SI window has to be called very rarely, so why change it into a tab? Moreover, there are more priority tasks - confirmed errors that need to be eliminated.

**Comment by sick13** [comment]
Agreed,sure, just making a request i did not say it has to be immediately :) just giving an idea so we who are used to Win task manager have that option to

**Comment by VictorVG** [comment]
Here, as it seems to me, it is necessary to weigh all the pros and cons in the sense of whether the ovchinka is worth the candle.

**Comment by TETYYS** [comment]
please do not copy and paste text from google translate without proof reading it
