### ISSUE TITLE
Select / Deselect all button on GPU nodes

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#208]
![image](https://user-images.githubusercontent.com/133706/34078982-ad48436e-e32c-11e7-8699-5ece19062c10.png)

Is there any logic on the "selected by default" nodes? I had 5,7,11 only selected (instead of all)

**Comment by dmex** [comment]
> Is there any logic on the "selected by default" nodes?

@stdedos 

Yes. 

If the last known gpu node count changed (first install, driver update etc...) the default nodes  are  based on the node "RunningTime != zero" and "ContextSwitch > 10000" which determine if the node is in-use:
https://github.com/processhacker/processhacker/blob/master/plugins/ExtendedTools/gpumon.c#L117

It's not always accurate but it was better than what we had previously 🤔

**Comment by stdedos** [comment]
I forgot to add my request in the text (and left it on the title); however since there is a logic, you did good on closing it.

Kudos for slowly getting through all the tickets 😃
