### ISSUE TITLE
What is the use of "/partners/sysinternals/file-reports" ?

### ISSUE THREAD

**Issue by BAM0S2** [processhacker/processhacker#240]
Hello,

What is the use of (from [here](https://github.com/processhacker2/processhacker/blob/ba5be2bc43b6556361ec924edfc3187d06dcbd37/plugins/OnlineChecks/virustotal.c#L317
)): 
```
L"/partners", 
L"/sysinternals", 
L"/file-reports", 
```

I noticed that also `autoruns.exe` is using this HTTP POST command but I couldn't understand what it is provides me.  
Because you I have been told [here](https://github.com/processhacker2/processhacker/issues/230) that I can use the GET respond to receive that report on a file.

**Comment by dmex** [comment]
> What is the use of /sysinternals/file-reports 

The sysinternals API is for advanced telemetry not available via the public API.

> I couldn't understand what it is provides me.

You don't get anything unless you have access to the VirusTotal portal.

> Because you I have been told here that I can use the GET respond to receive that report on a file.

No. You need to use "https://www.virustotal.com/en/file/upload/?sha256=HASH" for GET requests. The sysinternals API is for telemetry information... contact VirusTotal if you need access.

FYI this issue tracker is for bugs and not general programming questions about random 3rd party services... If you have questions about code then use the forums: https://wj32.org/processhacker/forums/
