### ISSUE TITLE
Command line option -hide is broken between v3.0.5853.1326 and v3.0.5860.1333

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#241]
[**Command line option -hide is broken between v3.0.5853.1326 and v3.0.5860.1333**](https://github.com/VictorVG/PH/issues/3) quote:

> The process of the "Start hidden" option broken off between build 1326 and 1332: if earlier (on r1326) at the start of Windows PH, it started is minimized up into a tray, but now (at r1332) it opens its window immediately. 

Step fo responds is simples:

* unload the PH;
* go to his catalog;
* give the command (depending on where)
    from the console `start /i ProcessHacker.exe -hide`
    from GUI it is even easier - `Win-R - browse - ProcessHacker_dir - ProcessHacker -hide - Enter`

what we expect - the Process Hacker startup as Minimized;

that we see - the Process Hacker window is opened as Normal and it has minimize is manually.

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Big thanks!
