### ISSUE TITLE
Questions/clarification of program license for Process Hacker plugins

### ISSUE THREAD

**Issue by mologie** [processhacker/processhacker#245]
Hello,

PH is licensed under GPLv3 with a clause that allows linking it dynamically with non-GPL code ("link exception".) This clause says that "[a]n independent module is a module which is not derived from or based on this program."

1. Do you consider the plugin API to implement dynamic linking, i.e. does the link exception apply to the plugin API at all?

2. Assume I were to write a Process Hacker plugin that makes use of PH's public API and run it under an unmodified, official build of Process Hacker. Furthermore I do not compile any Process Hacker code into the plugin apart from required header files. Is the plugin an independent module or do you consider it a derived work?

3. Assume now that Process Hacker is no longer maintained by the copyright holders and the plugin depends on the plugin API of a fork. Is the plugin still an independent module, i.e. does the answer to (2) remain unchanged?

Thanks,

Oliver

(I'm bringing these points up because I'm evaluating Process Hacker as platform for software that helps in malware and cheat analysis. The questions are important to me because they decide whether plugins must be GPL-compatible and whether distribution of non-GPL-compatible plugins is still possible if PH were ever to become unmaintained by you as the 'copyright holders.')

**Comment by wj32** [comment]
1. Yes, the exception was actually intended for plugins.
2. In that case, it is an independent module.
3. If you are using a fork of Process Hacker, then the exception does not apply unless the original copyright holders have granted the exception for the specific fork. If they do not, you are still free to distribute non-GPL plugins for use with binaries from the original project.

Once granted for a particular version of Process Hacker, the exception will never be revoked. So if the original project is abandoned and someone creates a fork, you are still free to use binaries from the original project with your non-GPL plugins.

Do you intend to distribute your non-GPL plugin publically?

**Comment by mologie** [comment]
Thank you for the very clear answers.

> Do you intend to distribute your non-GPL plugin publically?

Yes, but not necessarily as non-GPL plugin.

Initially there's a small, closed team of users which does not receive the source code (hence my question here as the GPL applies to any kind of distribution.) At a later stage the software is published under either a proprietary or GPL-compatible license - most likely the latter. I'll make a post on your forum if the plugin reaches that stage!
