### ISSUE TITLE
Excessive items in System Information makes some information to be not displayed

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#25]
![Excessive items in System Information makes some information to be not displayed](https://u.pomf.is/pgagch.jpg)

All items with more than two labels of information chops off

**Comment by wj32** [comment]
I'm working on a scrolling based solution for the next release. This will take some time though.

**Comment by dmex** [comment]
@wj32 Can you also change the PH_SYSINFO_GRAPH_PADDING from **9** to **5**? It reduces a lot of empty space when there are +8 graphs while still looking good :+1:
