### ISSUE TITLE
Virus Scan

### ISSUE THREAD

**Issue by top-master** [processhacker/processhacker#251]
there are some websites that allow scan of "`*.exe`, `*.dll` and ..." files and I do have an antivirus that does use such server to check  a file hash or even upload it for scan anyway it does not have any option for scan of all/single "`*.dll`" file(s) that are loaded by that process but it just checks the "`*.exe`" alone so any injection is ignored.

it would be a nice tool if something like that web API could be implemented to check if we can trust a "`*.dll`" file, and it should be easy:
1. first take hash of file
2. send to server and get answer
3. provide option to upload it if the answer was "no existing entry"

**Comment by TETYYS** [comment]
This is already implemented in process context menu -> "Send to" option

**Comment by top-master** [comment]
Oh,  now I see ;-)
so, the only problem is when we do not know any of the *.dll files then
when we select multiple *.dll files in the module list tab the **Send To** does get disabled.

but still very good thanks
