### ISSUE TITLE
Feature request: limit internet bandwidth per process

### ISSUE THREAD

**Issue by lppedd** [processhacker/processhacker#252]
It would be really useful. I'd no longer have to use a separate tool.
What do you think about that?

**Comment by TETYYS** [comment]
I don't think this is something that Windows has natively, so I think the tool you are using is injecting code into processes and hooking networking calls. This would require building a separate plugin, much more than a features

**Comment by lppedd** [comment]
Yeah, you're right. I had a look at the Windows API, and it seems there is little information. I read about the TC and QoS API, but I'd like to try them on my own also. I don't think they're really a good fit for the job.

**Comment by tigros** [comment]
have you tried netlimiter? www.netlimiter.com

i use version 3 under win7 for many years no probs at all. and ya that's a whole app so putting that in hacker's a whole lot of work, netlimiter involves drivers too.

**Comment by lppedd** [comment]
I knew driver level code was involved. But I think it is at the user level, not the kernel level luckily.
The thing is ProcessHacker is so handy that having eveything integrated woud be awesome, but I understand your point.

I'm not an expert when it comes to pure Windows development so I'm not even judging. I'll respect what you choose to do, and I'll look at NetLimiter

**Comment by dmex** [comment]
I'm not sure how to implement per-connection bandwidth control. Years ago NetLimiter used a Winsock LSP to intercept/control connection speeds but I think they're using kernel routines now?

Job objects previously allowed control of IO rates but that's now deprecated and the IOCTL_NDIS_RESERVED8 can also be used to limit the bandwidth for a specific adapter and might have something for per-connection limiting but I can't find many references about this 😕

**Comment by lppedd** [comment]
@dmex are you trying to disassemble NetLimiter?
Prior to open this feature request I tried searching the internet and I couldn't find much info either.
The only decent answer I found is this https://cboard.cprogramming.com/windows-programming/91366-how-throttle-internet-bandwidth.html#post654757 which is basically the socket interception you mentioned

**Comment by dmex** [comment]
@lppedd 

I only know what Netlimiter was doing about 6 year ago (the last time I last used it). The NDIS stuff because we reversed a bunch of stuff for the HardwareDevices plugin which queries network adapter information directly from the NDIS driver: https://github.com/processhacker/processhacker/blob/master/plugins/HardwareDevices/ndis.c#L45

There are some other methods such as the Traffic Control interface but no idea if it works: https://msdn.microsoft.com/en-us/library/windows/desktop/aa374469.aspx

**Comment by lppedd** [comment]
@dmex 
Yeah I had read the QoS page over the Microsoft site. There are certian parts of the description which make me think it is applicable to this needs:
> ... taming the traditional TCP approach of "send all of it out as fast as possible" and its associated clogging effects ...

> Familiarity with Windows networking and Windows Sockets 2 programming is required

But here is where I lose hope:

> By writing QOS-enabled applications, programmers can ...

**Comment by TETYYS** [comment]
Can someon test if this works on all applications `powershell.exe New-NetQosPolicy -Name "Name" -AppPathNameMatchCondition Program.exe -ThrottleRateActionBitsPerSecond 8175` ?

**Comment by dmex** [comment]
@TETYYS 

Doesn't work for me :(

**Comment by gvanem** [comment]
Looks like the *Windows Connection Manager* has some feature to limit the speed. Check out this [sample](https://github.com/Microsoft/Windows-classic-samples/blob/master/Samples/ConnectionManagerCost/cpp/Wcmcostsample.cpp#L215).

**Comment by lppedd** [comment]
@dmex was this closed as a "won't do"? Anyway, thanks for the effort :)

**Comment by dmex** [comment]
@lppedd 

Yep :(
