### ISSUE TITLE
Heap corruption on HardwareDevices/ToolStatus plugin?

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#256]
Just got an `Unhandled exception at 0x00007FFB9698880B (ntdll.dll) in ProcessHacker.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFB969EC6E0).` message while Process hacker was idling, here's the backtrace:

```
>	ntdll.dll!00007ffb9698880b()	Unknown	Non-user code. Cannot find or open the PDB file.
 	ntdll.dll!00007ffb9698fd4a()	Unknown	Non-user code. Cannot find or open the PDB file.
 	ntdll.dll!00007ffb9692fa02()	Unknown	Non-user code. Cannot find or open the PDB file.
 	ntdll.dll!00007ffb96943e08()	Unknown	Non-user code. Cannot find or open the PDB file.
 	ProcessHacker.exe!00007ff7680fcc6e()	Unknown	No symbols loaded.
 	ProcessHacker.exe!00007ff7680f9056()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame
 	HardwareDevices.dll!00007ffb774f4f92()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame
 	ToolStatus.dll!00007ffb5e1568b0()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame
 	ProcessHacker.exe!00007ff7680f62bf()	Unknown	No symbols loaded.
 	ProcessHacker.exe!00007ff7680f6183()	Unknown	No symbols loaded.
 	ProcessHacker.exe!00007ff7681de4f6()	Unknown	No symbols loaded.
 	[External Code]		Annotated Frame
```

**Comment by dmex** [comment]
ToolStatus and HardwareDevices subclass the main window procedure hence why they're showing up in that stacktrace... Something generated or sent a window message that caused the crash - Your stacktrace doesn't help much more than that.

I've been testing the latest build for 21 hours and 46 minutes and it hasn't crashed... You'll need to run a debug build with symbols so I can see what functions were called on that stacktrace.

**Comment by TETYYS** [comment]
I've been running it with debug symbols for weeks and it didn't crash, pretty strange
