### ISSUE TITLE
[ProcessHacker-setup.exe] Missing oridinal 380 

### ISSUE THREAD

**Issue by gvanem** [processhacker/processhacker#260]
I've noticed that if linking `ProcessHacker-setup.exe` without any manifest, I get this error-dialogue when starting the program:
![processhacker-setup-error](https://user-images.githubusercontent.com/945271/38854391-9a1b7312-4220-11e8-94a2-441e6136fd6d.png)

And using `pedump ProcessHacker-setup.exe`, shows these imports by ordinals in `comctl32.dll`:
```
  Ordn  Name
     9  CreatePropertySheetPageW
   410
   412
   413
   133  PropertySheetW
   110  ImageList_Replace
   380
   345
   381
```
It's similar to this [issue](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/722193a4-7fba-4ed9-a41f-6629efdb2a78/loadiconmetric-corresponding-ordinal-number-380-could-not-be-located?forum=vcgeneral), but I fail to understand why adding `resources/app.manifest` should be so critical.

Is there some hidden issue/agenda with `comctl32.dll` that absolutely needs a Manifest? And what function is lurking behind these ordinals 380, 345 and 381?

*PS*. Everything is fine with `resources/app.manifest` added.

**Comment by mrsshr** [comment]
it seems side by side issue.

with common control 6.0 manifest: comctl 6.x loaded
without manifest: comctl 5.x loaded

**Comment by dmex** [comment]
>with common control 6.0 manifest: comctl 6.x loaded
without manifest: comctl 5.x loaded

This has been the standard for the last 15 years? 🤔 

Applications without a manifest receive legacy Win2k behavior including file system redirection, forced usage of legacy win2k libraries (comctl 5.x and hundreds of other compatibility hacks) and older/buggy win32 functions without bugfixes.

The setup tool doesn't support Win2k or WinXP and requires the manifest to prevent Windows applying legacy compatibility fixes to the process and instead use the latest functionality for the best reliability and performance.

**Comment by gvanem** [comment]
Thanks for clarifying.
