### ISSUE TITLE
Feature Request: add Search Symbols 

### ISSUE THREAD

**Issue by stonedreamforest** [processhacker/processhacker#261]
![tim 20180419114627](https://user-images.githubusercontent.com/16742566/38970327-65fc4536-43c7-11e8-9e38-42333aa0ed39.png)

**Comment by Biswa96** [comment]
@dmex 
* C: https://github.com/Biswa96/PDBDownloader
* C#: https://github.com/rajkumar-rangaraj/PDB-Downloader

**Comment by dmex** [comment]
Search for imports/exports added in latest nightly 👍
