### ISSUE TITLE
v3.0.6029.1502 Git-0578e362 kernel panic if used GPU have vendor modified video BIOS.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#273]
v3.0.6029.1502 Git-0578e362 kernel panic if used GPU have vendor modified video BIOS.

If hardware configuration included GPU have vendor modified video BIOS marked like "NVIDIA GeForce 610M [ASUS]", "AMD Radeon Hd R5740 [Samsung]", "NVIDIA Quadro 1000M [MSI]", "NVIDIA GeForce GT 650M [Toshiba]" e.t.c., and user install in to OS "Generic" video driver, then OS can boot failure on to kernel panic (BSoD) exception code is 0x0000003b SYSTEM_SERVICE_EXCEPTION in to possible ExtendedTools plug-in.

I see this solution:

When PH is started, we request the configuration of the video subsystem from the OS and check if it has a GPU with a modified video BIOS. If it is, we exclude it from the list of respondents because we do not have reliable means of checking that it has a driver adapted for this device, and with Generic any problems are possible, including the hang of one of the CPU cores (I came across a This phenomenon on the Samsung R27 laptop in which stood the APU E-350 with the re-branded video card in the Radeon HD R5740 [SAMSUNG] - c Generic drivers AMD every 20 - 30 minutes, and sometimes even one of the CPU cores hung up, and even Samsung's support did not I was able to fix the problem. yver for this model of the laptop from the site Samsung USA - the errors have disappeared, but to identify the fact of modification of the driver of the diagnostic program could not.

Kernel panic examples:

![win10 bsod in to ph v3 0 6029 1502 git-0578e362](https://user-images.githubusercontent.com/906886/40584032-c6938352-61a2-11e8-9d67-96d96d92e74a.jpg)

Hardware configuration report (partial) for this mashing: 

[AKR-NOTEBOOK-2018.05.26.txt](https://github.com/processhacker/processhacker/files/2042379/AKR-NOTEBOOK-2018.05.26.txt)

**Comment by mrsshr** [comment]
please upload minidump file.

i think it is windows kernel or graphic driver failure.

**Comment by VictorVG** [comment]
Well, but it was not my fault - my analysis of the situation with hardware because I already dealt with such modifications of firmware. The first message was on [**forum.ru-board.com**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2180#3) 25/05/2018 21:38 +0300 by **AKRAV**, after, 25-05-2018 22:54 +0300 the occurrence of the [**phenomenon confirmed**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2180#5) **towarish** .

[PH.zip](https://github.com/processhacker/processhacker/files/2042510/PH.zip) 

archive PH.zip file list:

_052518-43140-01.dmp
052518-43203-01.dmp
052518-44171-01.dmp
AKR-NOTEBOOK-2018.05.26.txt_

**Comment by dmex** [comment]
> 10.0.14393

14393 was released in 2016... Can you update to the latest version of Windows 10 (17134)?

I can't do anything about this unless you have the same issue on 17134.

**Comment by KarenArzumanyan** [comment]
10.0.14393 is **LTSB** v.1609 releasem new update LTSB/LTSC is expected by autumn 1809.

**Comment by VictorVG** [comment]
From Skype (the third person also informs):

> I also have a system with the Process Hacker v3.0.6032.1505 version.
> I have win 10 x64 ltsb 14393.1480
> PH portable
> here is the recording of the blue screen
> stop code system service exception
> that dkgkrnl.sys is not executed
> help what to do?
> The last working PH Process Hacker v3.0.6017.1490

**Comment by VictorVG** [comment]
[**AKRAV**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2200#20)

> By the way, on my 1607 LTSB (LTSC) in May came update KB4103723 that's something I'm beginning to suggest that the reason for the blue screens can be in it, if the hacker did not change anything. Well, or more likely, some incompatible changes have been made both in the hacker and in the Windows, which eventually led to this result.
> ZY: The update was established on May 15, 2018.

[**If OS not included this update, then kernel panic don't exists.**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2200#21)

**Comment by dmex** [comment]
I emailed the minidumps to Microsoft and they've confirmed it's a kernel bug in LTSB... I'll update the thead when I have more information.

**Comment by VictorVG** [comment]
Understood thanks! I will add new information. So far, according to AKRAV, it is known:

> _I tested it. While the last working release is 3.0.6022.1495, Windows is already crashing on 3.0.6024.1497._

**Comment by VictorVG** [comment]
Additional information:

[**qupear**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2240#2)

On another LTSB, where there is no KB4103723, I have v3.0.6034.1507 running Git-aa60c3c7 with no problems.

Checked the updates with the `wmic command qfe list brief / format: htable > "% USERPROFILE% \ hotfix.html"`

![7b21213c0f28](https://user-images.githubusercontent.com/906886/41175549-1de5d106-6b66-11e8-89a5-b993f490c36a.jpg)

**Comment by VictorVG** [comment]
> [**AKRAV**](http://forum.ru-board.com/topic.cgi?forum=5&topic=49036&start=2260#14) wrote:
> 
> Check v3.0.6086.1559 Git-6495557f - problem resolved

Error in KB4103723 the panic-causing kernel was fixed in Git 0734257e9c7e. I close this issues as **FIXED**.
