### ISSUE TITLE
bugcheck with driver verifier running against ntoskrnl

### ISSUE THREAD

**Issue by gedmurphy** [processhacker/processhacker#275]
*******************************************************************************
*                                                                             *
*                        Bugcheck Analysis                                    *
*                                                                             *
*******************************************************************************

DRIVER_VERIFIER_DETECTED_VIOLATION (c4)
A device driver attempting to corrupt the system has been caught.  This is
because the driver was specified in the registry as being suspect (by the
administrator) and the kernel has enabled substantial checking of this driver.
If the driver attempts to corrupt the system, bugchecks 0xC4, 0xC1 and 0xA will
be among the most commonly seen crashes.
Arguments:
Arg1: 000000f6, Referencing user handle as KernelMode.
Arg2: 0000036c, Handle value being referenced.
Arg3: b0e04a40, Address of the current process.
Arg4: 81717021, Address inside the driver that is performing the incorrect reference.

Debugging Details:
------------------

DUMP_CLASS: 1

DUMP_QUALIFIER: 0

BUILD_VERSION_STRING:  10586.545.x86fre.th2_release.160802-1857

DUMP_TYPE:  0

BUGCHECK_P1: f6

BUGCHECK_P2: 36c

BUGCHECK_P3: ffffffffb0e04a40

BUGCHECK_P4: ffffffff81717021

BUGCHECK_STR:  0xc4_f6

CPU_COUNT: 2

CPU_MHZ: a20

CPU_VENDOR:  GenuineIntel

CPU_FAMILY: 6

CPU_MODEL: 5e

CPU_STEPPING: 3

CPU_MICROCODE: 6,5e,3,0 (F,M,S,R)  SIG: BE'00000000 (cache) BE'00000000 (init)

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT

PROCESS_NAME:  ProcessHacker.exe

CURRENT_IRQL:  0

ANALYSIS_SESSION_HOST:  DEVSTUDIO

ANALYSIS_SESSION_TIME:  05-30-2018 17:37:14.0496

ANALYSIS_VERSION: 10.0.16299.15 amd64fre

LAST_CONTROL_TRANSFER:  from 81608973 to 8158f1b4

STACK_TEXT:  
c703d224 81608973 00000003 abf0c8e3 00000065 nt!RtlpBreakWithStatusInstruction
c703d278 81608453 8d29e340 c703d680 c703d6bc nt!KiBugCheckDebugBreak+0x1f
c703d654 8158dff2 000000c4 000000f6 0000036c nt!KeBugCheck2+0x742
c703d678 8158df29 000000c4 000000f6 0000036c nt!KiBugCheck2+0xc6
c703d698 8196bf62 000000c4 000000f6 0000036c nt!KeBugCheckEx+0x19
c703d6bc 81970f05 0000036c b0e04a40 81717021 nt!VerifierBugCheckIfAppropriate+0x36
c703d758 81836ec0 9e56f5a0 00000002 81774620 nt!VfCheckUserHandle+0x153
c703d78c 81717021 0000036c 00000000 00000000 nt! ?? ::NNGAKEGL::`string'+0x1f450
c703d7b0 81774704 0000036c 00000000 00000000 nt!ObReferenceObjectByHandle+0x21
c703d874 8159c757 0000036c 00000002 9e56f5a0 nt!NtQueryObject+0xe4
c703d874 8158c95d 0000036c 00000002 9e56f5a0 nt!KiSystemServicePostCall
c703d900 cbba4d10 0000036c 00000002 9e56f5a0 nt!ZwQueryObject+0x11
WARNING: Stack unwind information not available. Following frames may be wrong.
c703d9e0 cbba15c3 ffffffff 0000036c 00000002 kprocesshacker+0x4d10
c703da80 814b2d09 b058f140 b0fae4b8 b0fae4b8 kprocesshacker+0x15c3
c703da94 81962e69 81962c9d b058f140 bfafcf80 nt!IopfCallDriver+0x31
c703dab0 814eb256 817190c1 bfafcf80 b0fae4b8 nt!IovCallDriver+0x1cc
c703dac4 817190c1 abf0c123 000001b0 0452fca8 nt!IofCallDriver+0x66
c703dbb8 8171928a 00000000 00000000 0452fcc0 nt!IopXxxControlFile+0xda1
c703dbe4 8159c757 000001b0 00000000 00000000 nt!NtDeviceIoControlFile+0x2a
c703dbe4 77cd13f0 000001b0 00000000 00000000 nt!KiSystemServicePostCall
0452fc74 77ccfe7a 0147fe67 000001b0 00000000 ntdll!KiFastSystemCallRet
0452fc78 0147fe67 000001b0 00000000 00000000 ntdll!NtDeviceIoControlFile+0xa
0452fce0 014811c9 ffffffff 0452fd0c 77cd0710 ProcessHacker!PhGetThreadServiceTag+0x2a7
0452fd18 0143749e ffffffff 0000036c ffffffff ProcessHacker!PhGetHandleInformationEx+0xe9
0452fdb0 01437697 014fdf18 0452ff04 01489486 ProcessHacker!PhEnumProcessItems+0x82e
0452fdbc 01489486 026ea078 00000000 01489280 ProcessHacker!PhEnumProcessItems+0xa27
0452ff04 014707d0 014fdf18 01470780 01470780 ProcessHacker!PhGetGlobalWorkQueue+0x4a6
0452ff1c 772995f4 02712668 772995d0 a2a89f56 ProcessHacker!PhAutoDereferenceObject+0x2b0
0452ff30 77c6241a 02712668 c081ee6a 00000000 KERNEL32!BaseThreadInitThunk+0x24
0452ff78 77c623e9 ffffffff 77ce3a16 00000000 ntdll!__RtlUserThreadStart+0x2b
0452ff88 00000000 01470780 02712668 00000000 ntdll!_RtlUserThreadStart+0x1b

THREAD_SHA1_HASH_MOD_FUNC:  c51350ab81ea76cdcbfa8f80051d823d8c23acd0

THREAD_SHA1_HASH_MOD_FUNC_OFFSET:  a1271165838366425a567a5cb898daf46110d968

THREAD_SHA1_HASH_MOD:  709a0bc88f62455732da27242e2fb4f0c60550c6

FOLLOWUP_IP: 
kprocesshacker+4d10
cbba4d10 8945a8          mov     dword ptr [ebp-58h],eax

FAULT_INSTR_CODE:  8da84589

SYMBOL_STACK_INDEX:  c

SYMBOL_NAME:  kprocesshacker+4d10

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: kprocesshacker

IMAGE_NAME:  kprocesshacker.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  56f97607

STACK_COMMAND:  .thread ; .cxr ; kb

BUCKET_ID_FUNC_OFFSET:  4d10

FAILURE_BUCKET_ID:  0xc4_f6_VRFK_kprocesshacker!unknown_function

BUCKET_ID:  0xc4_f6_VRFK_kprocesshacker!unknown_function

PRIMARY_PROBLEM_CLASS:  0xc4_f6_VRFK_kprocesshacker!unknown_function

TARGET_TIME:  2018-05-30T16:36:57.000Z

OSBUILD:  10586

OSSERVICEPACK:  0

SERVICEPACK_NUMBER: 0

OS_REVISION: 0

SUITE_MASK:  272

PRODUCT_TYPE:  1

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 10

OSEDITION:  Windows 10 WinNt TerminalServer SingleUserTS

OS_LOCALE:  

USER_LCID:  0

OSBUILD_TIMESTAMP:  2016-08-03 05:20:40

BUILDDATESTAMP_STR:  160802-1857

BUILDLAB_STR:  th2_release

BUILDOSVER_STR:  10.0.10586.545.x86fre.th2_release.160802-1857

ANALYSIS_SESSION_ELAPSED_TIME:  144c

ANALYSIS_SOURCE:  KM

FAILURE_ID_HASH_STRING:  km:0xc4_f6_vrfk_kprocesshacker!unknown_function

FAILURE_ID_HASH:  {6bf2c934-57d4-c93f-3b59-2bcc4bdb079d}

Followup:     MachineOwner
---------

**Comment by dmex** [comment]
I'm going to close this since Process Explorer has the exact same bugcheck when verifier is enabled. 

There's a reason why this had to be done but I can't remember the specifics. You can email @wj32 for more information about it.
