### ISSUE TITLE
Version number in main window title

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#278]
Maybe add subj info? Even optional (or not).

I may receive notifications about updates from third-party sites/messages/RSS... And open About for compare (if I forgot my version number). Title version removes unneeded About calling.

**Comment by dmex** [comment]
The Windows version or the Process Hacker version?

**Comment by pasha-zzz** [comment]
PH version.
I may receive notifications about updates from third-party sites/messages/RSS... And open About for compare (if I forgot my version number).
Title version removes unneeded About calling.

**Comment by dmex** [comment]
I messed up the ticket. Can you create a new ticket? Thanks 😄
