### ISSUE TITLE
Make About window modal and on top

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#279]
Now we can open many About windows and they arent modal. Also when main window is in "Always on top" mode About shows behind main window.
Modeless About is unnessesary feature.

**Comment by dmex** [comment]
> Now we can open many About windows

Fixed.

> when main window is in "Always on top" mode About shows behind main window.

I need to add some 'window management infrastructure' that fixes this but it's blocked by some other changes required for property sheets... I'll be able to commit those fixes soon.

> Modeless About is unnessesary feature.

Someone requested that very feature: https://github.com/processhacker/processhacker/issues/201

> This feature also helps to e.g. hide PH while still keep 'About' open for other uses, move the main window "out of the way"
