### ISSUE TITLE
"Minimize on close" and tray icons

### ISSUE THREAD

**Issue by falcon4fun** [processhacker/processhacker#280]
Quite an idiotic situation. 

Steps to reproduce normal behavior:
1. Set minimize on close
2. Set default tray icon
3. Alt+F4 PH
4. Look at tasklist ( tasklist | grep Process )
5. Profit. Process exists

Steps to reproduce dumb behavior:
1. Set minimize on close
2. Disable any tray icons
3. Alt+F4 PH
4. Look at tasklist ( tasklist | grep Process )
5. Profit. Program closed and process gone

I think the program should not die even those tray icons are disabled and reopen after I press ctrl+shift+esc (or ctrl+alt+del -> task manager) by my logic :)

Win7 x64
PH ver. 3.0.1563

**Comment by dmex** [comment]
> the program should not die even those tray icons are disabled

🤔
