### ISSUE TITLE
Incorrect CPU frequency showing

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#284]
Right part of images - correct values from CPU-Z:
https://image.ibb.co/fhLtUy/image.png
https://image.ibb.co/jHQSpy/image.png

**Comment by VictorVG** [comment]
1) LGA771 CPU Xeon E5450 (FSB 1333 MHz + FSB ECC) is launched on an unsupported Intel P965 chipset (m / b ASUS P5B - iP965 + ICH8, FSB 533/800/1067 MHz, single instances with a voltage increase of 15% 20% are operational up to 1333 MHz, there is no FSB ECC) - it's strange that it generally started on this number;

2) the "proofs" are forged - in the left half of the screenshot for the mobile CPU of the T series with a nominal frequency of 2.5 GHz (FSB = 800 MHz, ratio 6), to the right, a fragment of the screenshot for the CPU Core 2 Quad with FSB 1600 MHz and a ratio of 7.5 .

**Comment by pasha-zzz** [comment]
As usual idiotic comment from VictorVG. Both sides from one screenshots: left and right sides - Q9300 overclocked to 3000 MHz.
One is idle (2400), one is on load (3000).

**Comment by VictorVG** [comment]
![1](https://user-images.githubusercontent.com/906886/42176590-22a4275e-7e32-11e8-9644-b0fcae711390.png)

Clock detected is incorrect :)

**Comment by dmex** [comment]
@pasha-zzz 

cpuz is only showing core 0 while PH shows the total.

@VictorVG 

You need to change the core number on the top left.

**Comment by VictorVG** [comment]
Ok!
