### ISSUE TITLE
Clicking "Show desktop" button does not hide Process Hacker (Hide when minimized enabled)

### ISSUE THREAD

**Issue by felixlang** [processhacker/processhacker#287]
Process Hacker 2.39.124 (stable branch)
Windows 7 Pro SP1 64-bit

With the default Windows Task Manager, if the "Hide when minimized" option is checked, then clicking the "Show desktop" Windows button will hide the Task Manager window. But with Process Hacker, the window is only hidden if it is minimized directly, by clicking on the minimize button.

**Comment by VictorVG** [comment]
**v3.0.6181.1654 Git-6b58649e** , OS Win7 SP1 x64 - this problem not exists.
