### ISSUE TITLE
Plugin incompatibilities

### ISSUE THREAD

**Issue by UCyborg** [processhacker/processhacker#288]
Opening Hacker menu crashes - [Crash dumps](https://drive.google.com/open?id=1lCIu3n1HfWJZM9880UcZfOKGQeu8ddj6)

Does anyone else get this problem? Also, let me know if full crash dumps would be preferred.

**Comment by sgeto** [comment]
> It appears the actual problem is that TrustedInstaller plugin is no longer compatible.

It can confirm. Too bad really, I loved that plugin.

--
"We are saddened by a bird's cry, but not for a fish's blood.
Blessed are those with voices."

-Mamoru Oshii

**Comment by dmex** [comment]
https://wj32.org/processhacker/forums/viewtopic.php?f=18&p=9937#p9937

**Comment by UCyborg** [comment]
That doesn't help...it crashes with the version in that archive as well...

**Comment by UCyborg** [comment]
And for the record, that's not the only issue; having Terminator plugin loaded for example makes Process Hacker hang or crash when right-clicking the process. 3.0.1594 is the last version of Process Hacker where these plugins work.

**Comment by UCyborg** [comment]
Trying out DbgView plugin for the first time, so didn't see it in action myself, but saw a screenshot on the forum.

I run PH as admin, check Capture Win32 in its options, but don't see any output from programs that use OutputDebugString API. DbgView from Sysinternals Suite shows it as expected. I did make sure I didn't run both PH and Sysinternals DbgView simultaneously.

**Comment by gvanem** [comment]
Does not crash with my own compiled version from Git Master. Give it a try.

**Comment by UCyborg** [comment]
Using an older version is an option, but the idea is that this issue gets resolved while keeping other improvements that have been made to the code.

BTW, @gvanem , you only have code in your repo, no binaries and I don't have development tools installed ATM. From the [site](https://ci.appveyor.com/project/processhacker/processhacker/history) with automatically built binaries, 3.0.1594 is the one that doesn't have the crash problems with those plugins.

**Comment by dmex** [comment]
> the idea is that this issue gets resolved while keeping other improvements that have been made to the code.

It hasn't been an issue much since almost every change has tried to maintain compatibility with older versions but after making +1700 changes over the last two years some older plugins stopped working 😃

There's some bugs with how incompatible plugins are disabled and it's not yet possible to update other plugins. The other problem is that the plugins-extra repository doesn't remain in sync with the main repository and doesn't have a dedicated maintainer 🙁

**Comment by UCyborg** [comment]
Understandable. So that issue would better fit in the plugin repo, but I guess it's good as long it's logged somewhere so it's not forgotten about.

BTW, could one of the changes in PH also affect DbgView plugin? At least back then when I opened the issue, Sysinternals DebugView worked as expected, but PH DbgView plugin didn't output anything (I made sure I wasn't also running Sysinternals tool at the time). I'm a bit out-of-the-loop, I see some commits were made in the plugin repo, though I don't have Microsoft's dev tools installed ATM to be able to compile them myself.

**Comment by dmex** [comment]
I've added a new setting `EnableSafeDefaultPlugins` which does two things:

* Only default plugins are loaded.
* Show error when default plugins are missing.

You will need to disable the setting before using non-default plugins. But that will also disable the error message when plugins are missing such as when another application deletes the plugin.

**Comment by CeruleanSky** [comment]
@dmex Please consider renaming the option to something along the lines of DisableNonDefaultPlugins  , as DefaultPlugins are enabled regardless if this option is enabled or disabled. It also seems I was not the only person confused on why non-default plugins were refusing to load as I saw some other people making issues about this over the last couple weeks.

**Comment by dmex** [comment]
> Please consider renaming the option

The name will be changed more than once so I used a dumb name since it'll be changed again. The plugin API doesn't have versioning support so even the slightest change requires recompiling every plugin. So until the versioning has been added; the setting is the 'versioning' since a new name will disable old and outdated plugins.
