### ISSUE TITLE
(question) what is this use of PsGetCurrentProcessId

### ISSUE THREAD

**Issue by adevelopcr** [processhacker/processhacker#289]
I'm new to driver development and I'm trying to learn more about process hacker
I saw PsGetCurrentProcessId is used inside KphDispatchCreate to get the connecting client pid but on microsoft IoGetRequestorProcessId  is the function that gets a handle to requestor client . Or the dispatch is running on the calling client thread behalf ?

**Comment by dmex** [comment]
You would use IoGetRequestorProcessId with minifilter callbacks:
https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/file-system-minifilter-drivers

**Comment by adevelopcr** [comment]
I mean does PsGetCurrentProcessId returns the requestor id or the kernel driver process id ?

**Comment by TETYYS** [comment]
http://www.osronline.com/showThread.cfm?link=83346 https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/nf-ntddk-psgetcurrentprocessid
