### ISSUE TITLE
v3.0.6150.1623 Git 390cee3f phlib\util.c string 5256 error C2065 - IconIndex undeclared identifier

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#290]
Version 3.0.6150.1623 Git-390cee3f CustomBuildTools console out:

Branch: master
Version: 3.0.1623 (390cee3f)

Building ProcessHacker (x32)...
[ERROR] .\trunk\phlib\util.c(5256): error  C2065: IconIndex: undeclared identifier [.\trunk\phlib\phlib.vcxproj]

and build failure after this error. Check using SHA-256 on new working copy not found any source  different.

**Comment by NSP-0123456** [comment]
replace by 0 as it is usual case for this call.

**Comment by VictorVG** [comment]
@NSP-0123456 

It is possible, but in general, the icon index is not equal to zero. Therefore it is more reasonable to define IconIndex somewhere in hiders.

**Comment by VictorVG** [comment]
I looked at the sources - you need to specify commit 662436ae4554a6a19b5e8cbf90fbacbab246fbdc

**Comment by VictorVG** [comment]
@dmex 

Big thanks!
