### ISSUE TITLE
Version 73cd50432cb8e9d634b04320dff328c066249dcf does compile in release config? (both x86 and x64)

### ISSUE THREAD

**Issue by janwilmans** [processhacker/processhacker#300]
2>------ Build started: Project: peview, Configuration: Release x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka.ms/Ofhn4c for more information.
2>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka.ms/Ofhn4c for more information.
2>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(402,5): warning MSB8038: Spectre mitigation is enabled but Spectre mitigated libraries are not found.  Verify that the Visual Studio Workload includes the Spectre mitigated libraries.  See https://aka.ms/Ofhn4c for more information.
2>Done building project "phlib.vcxproj".
2>LINK : fatal error LNK1181: cannot open input file 'noarg.obj'
2>Done building project "peview.vcxproj" -- FAILED.
1>LINK : fatal error LNK1181: cannot open input file 'noarg.obj'
1>Done building project "ProcessHacker.vcxproj" -- FAILED.

**Comment by dmex** [comment]
You need to enable the Windows SDK (Spectre) package using Visual Studio for compiling Release builds.

**Comment by ERGeorgiev** [comment]
> cool. thanks!

Hey janwilmans,

Can you describe how you fixed the issue? I have been googling about enabling the Windows SDK Spectre package but to no avail. I just need to build the code in Release, yet I am still getting the same problem.

Best,
- Ed

**Comment by dmex** [comment]
@ERGeorgiev 

You just select the spectre libraries in the Visual Studio installer. See screenshot:

![image](https://user-images.githubusercontent.com/1306177/60882644-9a34b000-a248-11e9-8928-2d61de600940.png)

**Comment by ERGeorgiev** [comment]
> @ERGeorgiev
> 
> You just select the spectre libraries in the Visual Studio installer. See screenshot:
> 
> ![image](https://user-images.githubusercontent.com/1306177/60882644-9a34b000-a248-11e9-8928-2d61de600940.png)

Found it in the C++ Development package in Visual Studio Installer for 2017 (haven't moved to 2019 yet). Thank you!
![Visual Studio Installer-000063](https://user-images.githubusercontent.com/32902048/60883173-6609c100-a241-11e9-9828-b4fe730905ed.png)
