### ISSUE TITLE
[Debug View] strange timestamps

### ISSUE THREAD

**Issue by gvanem** [processhacker/processhacker#305]
While working with `git.exe` and keeping the `Debug View` plugin *Always on Top*, I saw this strange time-stamp reported; the last (the other times are correct):
![processhacker-debugview](https://user-images.githubusercontent.com/945271/44909360-549d8180-ad1f-11e8-8e69-5e88cabc99da.png)

AFAICS, the time-stamp comes from `entry->Time` in `plugins-extra/DbgViewPlugin/dialog.c`. I'd suspect the date is bogus too. Not sure it's the fault of some system .DLL or ProcessHacker.

**Comment by dmex** [comment]
The DebugView plugin has weird issues sometimes... You should post the bug in the plugins-extra repro:
https://github.com/processhacker/plugins-extra/issues/53
