### ISSUE TITLE
phnt - Duplicate definitions

### ISSUE THREAD

**Issue by MSxDOS** [processhacker/processhacker#306]
The following functions defined in phnt are present in SDK:
## ntdbg.h
- #### minidrv.h
  ```
  DbgBreakPoint
  DbgPrint
  ```
## ntrtl.h 
- #### ip2string.h
  ```
  RtlIpv4StringToAddressW
  RtlIpv4AddressToStringW
  RtlIpv6StringToAddressW
  RtlIpv6AddressToStringW
  ```
- #### winnt.h
  ```
  RtlCrc32
  RtlCrc64
  RtlGetProductInfo
  RtlPcToFileHeader
  ```
## ntxcapi.h
- #### rtlsupportapi.h
  ```
  RtlRaiseException
  ```
---
Also, **ntrtl.h**->`RtlEqualPrefixSid` is missing `NTAPI` as per its WDK definition (**ntifs.h**)
I didn't include **winternl.h** here as this one consists of some castrated stuff compared to what you have in phnt.

**Comment by MSxDOS** [comment]
It's all up to you, I was just playing with clang and decided to put it in a good use :smile: 

Here's a bit more of what I've found:  
## Structs (not including winternl.h):
## ntsam.h
- #### NTSecAPI.h
```
_DOMAIN_PASSWORD_INFORMATION
```
- #### SubAuth.h
```
_LOGON_HOURS
_SR_SECURITY_DESCRIPTOR
_USER_ALL_INFORMATION
```
## Constants
FWIW, there's a list of constants\macros that are present in SDK but I didn't check if they're actually the same as in phnt, just the names:
<details><summary>Expand</summary>  

name: FILE_SUPERSEDE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_CREATE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_IF
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OVERWRITE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OVERWRITE_IF
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_MAXIMUM_DISPOSITION
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_DIRECTORY_FILE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_WRITE_THROUGH
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_SEQUENTIAL_ONLY
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_NO_INTERMEDIATE_BUFFERING
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_SYNCHRONOUS_IO_ALERT
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_SYNCHRONOUS_IO_NONALERT
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_NON_DIRECTORY_FILE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_CREATE_TREE_CONNECTION
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_COMPLETE_IF_OPLOCKED
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_NO_EA_KNOWLEDGE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_RANDOM_ACCESS
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_DELETE_ON_CLOSE
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_BY_FILE_ID
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_FOR_BACKUP_INTENT
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_NO_COMPRESSION
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_REQUIRING_OPLOCK
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_RESERVE_OPFILTER
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_REPARSE_POINT
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_NO_RECALL
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPEN_FOR_FREE_SPACE_QUERY
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_SUPERSEDED
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OPENED
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_CREATED
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_OVERWRITTEN
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_EXISTS
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_DOES_NOT_EXIST
PHNT: ntioapi.h
MS: um\winternl.h

name: FILE_SKIP_COMPLETION_PORT_ON_SUCCESS
PHNT: ntioapi.h
MS: um\WinBase.h

name: FILE_SKIP_SET_EVENT_ON_HANDLE
PHNT: ntioapi.h
MS: um\WinBase.h

name: FLUSH_FLAGS_FILE_DATA_ONLY
PHNT: ntioapi.h
MS: um\winnt.h

name: FLUSH_FLAGS_NO_SYNC
PHNT: ntioapi.h
MS: um\winnt.h

name: DUPLICATE_CLOSE_SOURCE
PHNT: ntobapi.h
MS: um\winnt.h

name: DUPLICATE_SAME_ACCESS
PHNT: ntobapi.h
MS: um\winnt.h

name: FLS_MAXIMUM_AVAILABLE
PHNT: ntpsapi.h
MS: um\winnt.h

name: TLS_MINIMUM_AVAILABLE
PHNT: ntpsapi.h
MS: um\winnt.h

name: DOMAIN_PASSWORD_COMPLEX
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_PASSWORD_NO_ANON_CHANGE
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_PASSWORD_NO_CLEAR_CHANGE
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_LOCKOUT_ADMINS
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_PASSWORD_STORE_CLEARTEXT
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_REFUSE_PASSWORD_CHANGE
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: DOMAIN_NO_LM_OWF_CHANGE
PHNT: ntsam.h
MS: um\NTSecAPI.h

name: USER_ACCOUNT_DISABLED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_HOME_DIRECTORY_REQUIRED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_PASSWORD_NOT_REQUIRED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_TEMP_DUPLICATE_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_NORMAL_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_MNS_LOGON_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_INTERDOMAIN_TRUST_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_WORKSTATION_TRUST_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_SERVER_TRUST_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_DONT_EXPIRE_PASSWORD
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_ACCOUNT_AUTO_LOCKED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_ENCRYPTED_TEXT_PASSWORD_ALLOWED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_SMARTCARD_REQUIRED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_TRUSTED_FOR_DELEGATION
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_NOT_DELEGATED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_USE_DES_KEY_ONLY
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_DONT_REQUIRE_PREAUTH
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_PASSWORD_EXPIRED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_TRUSTED_TO_AUTHENTICATE_FOR_DELEGATION
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_NO_AUTH_DATA_REQUIRED
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_PARTIAL_SECRETS_ACCOUNT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_USE_AES_KEYS
PHNT: ntsam.h
MS: um\SubAuth.h

name: NEXT_FREE_ACCOUNT_CONTROL_BIT
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_MACHINE_ACCOUNT_MASK
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_ACCOUNT_TYPE_MASK
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_COMPUTED_ACCOUNT_CONTROL_BITS
PHNT: ntsam.h
MS: um\SubAuth.h

name: SAM_DAYS_PER_WEEK
PHNT: ntsam.h
MS: um\SubAuth.h

name: SAM_HOURS_PER_WEEK
PHNT: ntsam.h
MS: um\SubAuth.h

name: SAM_MINUTES_PER_WEEK
PHNT: ntsam.h
MS: um\SubAuth.h

name: USER_ALL_PARAMETERS
PHNT: ntsam.h
MS: um\SubAuth.h

name: NT_SUCCESS
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\SubAuth.h
MS: um\winternl.h

name: NT_INFORMATION
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: NT_WARNING
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: NT_ERROR
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: RTL_CONSTANT_STRING
PHNT: phnt_ntdef.h
MS: shared\ntdef.h

name: RTL_BALANCED_NODE_RESERVED_PARENT_MASK
PHNT: phnt_ntdef.h
MS: shared\ntdef.h

name: RTL_BALANCED_NODE_GET_PARENT_POINTER
PHNT: phnt_ntdef.h
MS: shared\ntdef.h

name: OBJ_INHERIT
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_PERMANENT
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_EXCLUSIVE
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_CASE_INSENSITIVE
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_OPENIF
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_OPENLINK
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_KERNEL_HANDLE
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_FORCE_ACCESS_CHECK
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_IGNORE_IMPERSONATED_DEVICEMAP
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_DONT_REPARSE
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: OBJ_VALID_ATTRIBUTES
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: InitializeObjectAttributes
PHNT: phnt_ntdef.h
MS: shared\ntdef.h
MS: um\winternl.h

name: RTL_CONSTANT_OBJECT_ATTRIBUTES
PHNT: phnt_ntdef.h
MS: shared\ntdef.h

name: RTL_INIT_OBJECT_ATTRIBUTES
PHNT: phnt_ntdef.h
MS: shared\ntdef.h

name: USERNAME_LENGTH
PHNT: winsta.h
MS: um\WtsApi32.h

name: DOMAIN_LENGTH
PHNT: winsta.h
MS: um\WtsApi32.h

name: CLIENTNAME_LENGTH
PHNT: winsta.h
MS: um\WtsApi32.h

name: CLIENTADDRESS_LENGTH
PHNT: winsta.h
MS: um\WtsApi32.h

name: WINSTATIONNAME_LENGTH
PHNT: winsta.h
MS: um\WtsApi32.h

name: KBDSHIFT
PHNT: winsta.h
MS: um\kbd.h

name: KBDCTRL
PHNT: winsta.h
MS: um\kbd.h

name: KBDALT
PHNT: winsta.h
MS: um\kbd.h

name: LOGONID_CURRENT
PHNT: winsta.h
MS: um\winternl.h

name: SERVERNAME_CURRENT
PHNT: winsta.h
MS: um\winternl.h

</details>

**Comment by dmex** [comment]
These are correct as of 19H1 and the dual use of PHNT both in usermode and kernelmode.
