### ISSUE TITLE
AV in PEview x86 version after v3.0.6181.1654 Git-6b58649e then try open any files

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#307]
PEView after v3.0.6181.1654 Git-6b58649e x86 have AV (Exception 0xc0000005) in to Win SP1 x86/x64 (OS version 6.1.7601.2.1.0.256.1) try open any files. 

Debugger show string 68 `if (PvpLoadDbgHelp(&PvSymbolProvider))` on ./tools/peview/peprp.c as source for this exeception.

Code:
```
VOID PvPeProperties(
    VOID
    )
{
    PPV_PROPCONTEXT propContext;
    PH_MAPPED_IMAGE_IMPORTS imports;
    PH_MAPPED_IMAGE_EXPORTS exports;
    PIMAGE_DATA_DIRECTORY entry;

    if (!PhExtractIcon(PvFileName->Buffer, &PvImageLargeIcon, &PvImageSmallIcon))
    {
        PhGetStockApplicationIcon(&PvImageSmallIcon, &PvImageLargeIcon);
    }

    if (PvpLoadDbgHelp(&PvSymbolProvider))  /* str. 68: AV locate point in x86 */
    {
        // Load current PE pdb
        // TODO: Move into seperate thread.
        PhLoadModuleSymbolProvider(
            PvSymbolProvider,
            PvFileName->Buffer,
            (ULONG64)PvMappedImage.NtHeaders->OptionalHeader.ImageBase,
            PvMappedImage.NtHeaders->OptionalHeader.SizeOfImage
            );
    }

    if (propContext = PvCreatePropContext(PvFileName))
    {
        PPV_PROPPAGECONTEXT newPage;

        // General page
        newPage = PvCreatePropPageContext(
            MAKEINTRESOURCE(IDD_PEGENERAL),
            PvpPeGeneralDlgProc,
            NULL
            );
        PvAddPropPage(propContext, newPage);

        // Load Config page
        if (NT_SUCCESS(PhGetMappedImageDataEntry(&PvMappedImage, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG, &entry)) && entry->VirtualAddress)
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PELOADCONFIG),
                PvpPeLoadConfigDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        // Imports page
        if ((NT_SUCCESS(PhGetMappedImageImports(&imports, &PvMappedImage)) && imports.NumberOfDlls != 0) ||
            (NT_SUCCESS(PhGetMappedImageDelayImports(&imports, &PvMappedImage)) && imports.NumberOfDlls != 0))
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PEIMPORTS),
                PvpPeImportsDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        // Exports page
        if (NT_SUCCESS(PhGetMappedImageExports(&exports, &PvMappedImage)) && exports.NumberOfEntries != 0)
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PEEXPORTS),
                PvpPeExportsDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        // Resources page
        if (NT_SUCCESS(PhGetMappedImageDataEntry(&PvMappedImage, IMAGE_DIRECTORY_ENTRY_RESOURCE, &entry)) && entry->VirtualAddress)
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PERESOURCES),
                PvpPeResourcesDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        // CLR page
        if (NT_SUCCESS(PhGetMappedImageDataEntry(&PvMappedImage, IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR, &entry)) &&
            entry->VirtualAddress &&
            (PvImageCor20Header = PhMappedImageRvaToVa(&PvMappedImage, entry->VirtualAddress, NULL)))
        {
            NTSTATUS status = STATUS_SUCCESS;

            __try
            {
                PhProbeAddress(
                    PvImageCor20Header,
                    sizeof(IMAGE_COR20_HEADER),
                    PvMappedImage.ViewBase,
                    PvMappedImage.Size,
                    4
                    );
            }
            __except (EXCEPTION_EXECUTE_HANDLER)
            {
                status = GetExceptionCode();
            }

            if (NT_SUCCESS(status))
            {
                newPage = PvCreatePropPageContext(
                    MAKEINTRESOURCE(IDD_PECLR),
                    PvpPeClrDlgProc,
                    NULL
                    );
                PvAddPropPage(propContext, newPage);
            }
        }

        // CFG page
        if (PvMappedImage.NtHeaders->OptionalHeader.DllCharacteristics & IMAGE_DLLCHARACTERISTICS_GUARD_CF)
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PECFG),
                PvpPeCgfDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        // Symbols page
        if (NT_SUCCESS(PhGetMappedImageDataEntry(&PvMappedImage, IMAGE_DIRECTORY_ENTRY_DEBUG, &entry)) && entry->VirtualAddress)
        {
            newPage = PvCreatePropPageContext(
                MAKEINTRESOURCE(IDD_PESYMBOLS),
                PvpSymbolsDlgProc,
                NULL
                );
            PvAddPropPage(propContext, newPage);
        }

        PhModalPropertySheet(&propContext->PropSheetHeader);

        PhDereferenceObject(propContext);
    }
}
```
and display messages:

>An unhandled exception was raised: access violation for reading.
>
>PhCreateSymbolProvider (...) returned 0x34.
>
>If there is a handler for this exception, the execution of the program can be continued safely.

Screenshot:
![1](https://user-images.githubusercontent.com/906886/45249263-5ae6bb80-b326-11e8-89b8-dc2f2cdc446e.png)

forum.ru-board.com users **druc** and **KLASS** also  reported about this problem:

![ph-1654](https://user-images.githubusercontent.com/906886/45249286-b022cd00-b326-11e8-997b-25cd1f5efa34.jpg)

**Comment by VictorVG** [comment]
**Step by responds:**

1. Run PEView.exe x86 (x64 not have this issues) on any x86 or x64 Windows 7 or never;
2. Try open any executable;

**Result:**

Access Violation (AV) in to function PvPeProperties().

Affected:

Only x86 edition. Maybe it's worth checking out the **RamMerLabs** sent to me 20:03 07-09-2018 +0300 at forum.ru-boad.com - "_About the problem with PEView_":

> Good afternoon! It looks like the problem is with AddDllDirectory() - up to v3.0.6181.1654 Git-6b58649e inclusive it was not used.
> 
> I tried the test assembly proposed by you on a test machine - under win7sp1x64 64-bit version of peview works after installation of update 2533623.
> 
> 32-bit peview on x64 seven falls regardless of the method of launching - though through the command line, even by selecting the pe-file through the file open dialog.
> 
> Why this function? I noticed it in the import table, while MS recommends that it be accessed on win7 via GetProcAddress() or deferred import:
> 
> >"Windows 7, Windows Server 2008 R2, Windows Vista and Windows Server 2008: To get this function in an application, call GetProcAddress to retrieve the function's address from Kernel32.dll." KB2533623 "must be installed on the target platform".

**Comment by VictorVG** [comment]
**Step by responds:**

1. Run PEView.exe x86 (x64 not have this issues) on any x86 or x64 Windows 7 or never;
2. Try open any executable;

**Result:**

Access Violation (AV) in to function PvPeProperties().

**Affected:**

Only x86 edition. Maybe it's worth checking out the **RamMerLabs** sent to me 20:03 07-09-2018 +0300 at forum.ru-boad.com - "_About the problem with PEView_":

> Good afternoon! It looks like the problem is with AddDllDirectory() - up to v3.0.6181.1654 Git-6b58649e inclusive it was not used.
> 
> I tried the test assembly proposed by you on a test machine - under win7sp1x64 64-bit version of peview works after installation of update 2533623.
> 
> 32-bit peview on x64 seven falls regardless of the method of launching - though through the command line, even by selecting the pe-file through the file open dialog.
> 
> Why this function? I noticed it in the import table, while MS recommends that it be accessed on win7 via GetProcAddress() or deferred import:
> 
> >"Windows 7, Windows Server 2008 R2, Windows Vista and Windows Server 2008: To get this function in an application, call GetProcAddress to retrieve the function's address from Kernel32.dll." KB2533623 "must be installed on the target platform".

**Comment by dmex** [comment]
You should have KB2533623 installed... I've added a workaround anyway.

**Comment by VictorVG** [comment]
Ok! True, I ran into a local problem - it seems that KB2533623 only left a record in the OS Registry because WUSU says it's already installed, but the error persists. I think that my OS is corrupted, since the IDE Power Shell crashes at startup, and some other programs crash. I'll be thinking how to proceed - the OS image is loaded into VirtualBox from the server and most likely the damage has occurred there, and its correction is not available to me. As there is no desire to re-arrange BSD slices and reinstall the entire software package. :)

**Comment by dmex** [comment]
> start PEView x86 on Win7 SP1 x64 

32bit binaries do not support parsing 64bit binaries... I've added an error dialog so you won't be able to use the 32bit version on 64bit anymore (just like you can't run the 32bit version of Process Hacker on 64bit).
