### ISSUE TITLE
Can we have DPI Awareness support pre Windows 8.1?

### ISSUE THREAD

**Issue by poizan42** [processhacker/processhacker#309]
GetProcessDpiAwareness is only available from Windows 8.1. Before that you had to use IsProcessDPIAware, but that only applies to the current process.

Creating remote threads to call it in other processes is probably too expensive to be a good idea when it is shown in the process list view. The pre-Windows 8.1 version works by simply reading the global char gfDPIAware in user32.dll. The function just consists of a simple movzx, ret, so maybe we could just read the offset out of the instruction when it matches the expected pattern and then NtReadVirtualMemory it when needed.

Thoughts?

**Comment by dmex** [comment]
Continuation of #312 

The workaround for querying DPI on earlier versions of Windows is just too ugly and unstable for including with the main program. You need to implement this as a plugin and submit the PR to the plugin-extra repo:
https://github.com/processhacker/plugins-extra

A good example is the HexPidPlugin project for adding a new column to the process tree: https://github.com/processhacker/plugins-extra/blob/master/HexPidPlugin/main.c
