### ISSUE TITLE
Some string "Disabled (modifed)" truncated in screen after merge Git 3d0bf79b5aae83a8f41

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#314]
After https://github.com/processhacker/processhacker/pull/311  is truncated some string's - **KLASS** in to forum.ru-board.com wrote:

> ...there are two lines of code:
> Disabled (modified
> Disabled (modified)
> those. in the first case, the closing bracket is omitted, so this is the line with no parentheses and is displayed in properties
> svchost (not all, for example, DNS client, DHCP client, etc.) on the Token tab in the Status column

yes, a check and confirmed this confusion. Please, see  scrinshot's:

![ph-301862_win10](https://user-images.githubusercontent.com/906886/45521805-5d369300-b7c8-11e8-97dc-d672b4c662f1.jpg)

Win10 LTSB

![ph-301862-win7sp1](https://user-images.githubusercontent.com/906886/45521806-5d369300-b7c8-11e8-9091-fee084e36385.jpg)

Win 7 SP1

**Comment by dmex** [comment]
Fixed 👍

**Comment by VictorVG** [comment]
Big thanks for Your fix!
