### ISSUE TITLE
Several mapimg functions are not exported

### ISSUE THREAD

**Issue by poizan42** [processhacker/processhacker#316]
Most of the functions declared in mapimg.h are not exported. Don't know if that is intentionel, but I need the following to turn #312 into a plugin.

* PhGetDllProcedureAddress
* PhGetDllBaseProcedureAddress
* PhGetLoaderEntryDllBase
* PhGetMappedImageExportFunction
* PhGetMappedImageExports
* PhMappedImageRvaToVa

**Comment by dmex** [comment]
> Most of the functions declared in mapimg.h are not exported. 

We export functions as needed 😃 

>PhGetDllProcedureAddress
PhGetDllBaseProcedureAddress
PhGetLoaderEntryDllBase

These are internal functions. You need to use PhGetProcedureAddress, PhGetDllHandle and PhGetModuleProcAddress for plugins 👍
