### ISSUE TITLE
[Request] Add option to change the vertical size of the list view items.

### ISSUE THREAD

**Issue by alpakeno** [processhacker/processhacker#318]

**Comment by dmex** [comment]
Tried changing the `ThinRows` setting?

**Comment by alpakeno** [comment]
Yeah, it doesn't do much changes, if it's 0 it will be slightly higher than setting it to 1.

**Comment by dmex** [comment]
@alpakeno 

> Add option to change the vertical size of the list view items.

A pre-configured list of sizes or a new setting for custom values?
