### ISSUE TITLE
Feature Request: Process Properties --> Started to refresh the counter

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#319]
I needed to count the time that the process was alive.

It would be nice if the counter was refreshing.

![image](https://user-images.githubusercontent.com/133706/45975532-258fdc80-c04d-11e8-9547-49a5402a81e6.png)

**Comment by dmex** [comment]
@stdedos 

Have you tried adding the 'Relative start time' column to the processes list?

**Comment by stdedos** [comment]
Stupid of me. Thank you :-)

**Comment by dmex** [comment]
@stdedos 

I wrote a patch for adding this feature? 😢

**Comment by stdedos** [comment]
@dmex 
Awwwww. Don't cry. Patch it :cupid:

**Comment by stdedos** [comment]
No-patchy after all? 😢

Or wasn't it written "properly" in commit message?

**Comment by dmex** [comment]
> No-patchy after all?

Wasn't the patch merged for updating the time?

**Comment by stdedos** [comment]
Well, I don't see it in the ticket's flow (hence vvv)
> Or wasn't it written "properly" in commit message?

and I don't see this `5 seconds ago (12:40:11 μμ 24/11/2020)` changing interactively at all. 😕

**Comment by stdedos** [comment]
😄

**Comment by stdedos** [comment]
And it even allows selecting the text without re-doing it and canceling your selection. AWESOME
![image](https://user-images.githubusercontent.com/133706/100088506-e8a41800-2e58-11eb-85f2-a40345faaef5.png)
