### ISSUE TITLE
Memory leak in to v3.0.6395.1868 Git-a4a44007 - v3.0.6402.1875 Git-18d615d1

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#321]
I see memory leak in to v3.0.6395.1868 Git-a4a44007 ( **skipik** detected memory leak on this version, but this exist and for some oldest commits) - v3.0.6402.1875 Git-18d615d1. On example visual Private bytes size control in real time for minimized to tray copy PH after PH start time +00:03:00 up to PH start time +16:03:00:

   PH start time +00:03:00 - Private bytes 22,41 MB
   PH start time +16:03:00 - Private bytes 66,9 MB

This copy of PH is in the minimized state in the tray and is used only to monitor the value of Private bytes. In previous versions, the memory leak was more noticeable as reported by **skipik** on forum.ru-boards.com - he had on Win10 v1807 for 2.5 days since the launch of PH private size has increased from about 24 MB to 306.5 MB. About what he wrote in the subject, after which I drew attention to this phenomenon. But I had the size of Private bytes at that time was less - about 287 MB.

Pleas, see screenshots for v3.0.6395.1868 Git-a4a44007:

![ph-r1868](https://user-images.githubusercontent.com/906886/46022285-fd56bb00-c0ea-11e8-8437-197bbc22cebf.png)

![ph-r1868_monitoring_1](https://user-images.githubusercontent.com/906886/46022287-fd56bb00-c0ea-11e8-8fa7-31c8b59be34d.png)

**Comment by dmex** [comment]
I've been running builds for days and the official build doesn't have a memory leak. You need to remove any non-standard plugins you've included with your unofficial ru-board.com releases.

**Comment by VictorVG** [comment]
Pasha_ZZZ used official buld in to Windows 10 v1803 and also see memory leak:

![image](https://user-images.githubusercontent.com/906886/46075590-a1943c80-c193-11e8-8b14-4da6baa2db83.png)

I try check run PH w/o plug-ins and control it.

**Comment by VictorVG** [comment]
Test started, v3.0.6402.1875 Git-18d615d1, command line _ProcessHacker.exe -noplugins_ , startup time +00:03:00  , Private bytes == 13,74 MB

**Comment by pasha-zzz** [comment]
Screen above - off build + extra plugins. Off build + Firewall Monitor = huge leak. Off build + all extra w/o FM = no leak (or slightly leaked).

**Comment by VictorVG** [comment]
**Test:**

v3.0.6402.1875 Git-18d615d1 (my build), command prompt _ProcessHacker.exe -noplugins_ , 

Startup time +00:03:00 , Private bytes == 13,74 MB
Startup time +04:00:00 , Private bytes == 14,21 MB 

testing continue

**Comment by skipik** [comment]
@pasha-zzz I have Firewall Monitor disabled and it's still leaking.

**Comment by VictorVG** [comment]
I also check build v3.0.6402.1875 Git-18d615d1 use -noplugins key and see memory leak at 24:02:00 - startup value  13,74 MB, end value 16,91 MB. Needed long time observe for control this phenomena.
