### ISSUE TITLE
Please Create a description for each files

### ISSUE THREAD

**Issue by jhave21** [processhacker/processhacker#323]
I find all the files quite big and I got lost every time I try and read the source. I would like to know if how do you get the value that is used to show Global Total Memory Usage? The that is graphed.  What Native API do you use,  and in what file do you use it?  

Thank you,  waiting for replies...

**Comment by dmex** [comment]
> I would like to know if how do you get the value that is used to show Global Total Memory Usage?

You should use documented functions such as GlobalMemoryStatusEx:
https://msdn.microsoft.com/en-us/library/windows/desktop/aa366589.aspx

> What Native API do you use, and in what file do you use it?

You can't search the code? 🤔

**Comment by jhave21** [comment]
Well, about the "string" that your saying,  I really don't know what I am really looking for,  but I found "PhPerfInformation" as I try to read the "processshacker>sysscmem.c", I tried to look for the file that creates that window, I found out the PhPerfInformation is a SYSTEM_PERFORMANCE_INFORMATION. 

To anyone here,  does Process Hacker really use NtQuerySystemInformation(SystemPerformanceInformation, ....., ) to get the Memory Usage?

**Comment by dmex** [comment]
> What I meant was; how does the Process Hacker does it? What API does it use?

Process Hacker uses NtQuerySystemInfomation but it requires constant maintenance because of changes with every Windows update... GlobalMemoryStatusEx is guaranteed to never change and you won't ever need to update or rewrite code that uses it which is why I suggested it.

**Comment by jhave21** [comment]
Thanks, But does it uses SystemPerformanceInformation? Just wanna confirm :D

**Comment by dmex** [comment]
> Thanks, But does it uses SystemPerformanceInformation?

The source is here on Github...
