### ISSUE TITLE
[Request] Add support to manualy hide process from list by manualy selecting it.

### ISSUE THREAD

**Issue by alpakeno** [processhacker/processhacker#324]
In win 10 there is a lot of user processes running in the background, like:
svchost, RuntimeBroker, ShellExperienceHost etc.
These processes when killed it's restarting itself again, so by adding these selected process to hidden list will be a great deal.

**Comment by dmex** [comment]
> adding these selected process to hidden list

This type of functionality would be a target for malicious software and so won't be included. If you want such a feature then I'd recommend making these changes to your own local private builds.
