### ISSUE TITLE
System Information: Memory bugs + Development questions

### ISSUE THREAD

**Issue by Syst3mSh0ck** [processhacker/processhacker#330]
Hi, im using 3.0.1902 (3fd1ee8b) on Windows 8.1 x64 and there seem to be some issues with missing data via System Information > Memory for Paged/Non-Paged Pool 'Limit', Physical Memory 'Kernel WS' and Memory lists 'Modified no-write'. I have the Windows SDK installed with Process Hacker configured to use those symbols correctly.

![image](https://user-images.githubusercontent.com/4252736/46568158-363b2f00-c938-11e8-872f-6059e147fb6f.png)

Are there any plans to add monitoring for APC/DPC procedure calls and IRP/NMI interrupt metrics under the System process at any point? That would be really handy.

Also are there any plugins available / under development which would allow graphing of hardware sensor data from external applications via WMI or Shared Memory (I was thinking AIDA64).

Thanks for all the hard work. I use the program everyday :)

**Comment by Syst3mSh0ck** [comment]
> The name for these variables changed. I can't change that code without breaking Win7 support so we need to wait until more people stop using Windows 7 (which is an issue since approx 50% of downloads are still for Windows 7).

Thanks for the information. I guess it's not possible to IFDEF this as a workaround?

> I have some patches but haven't had the time to fix some other issues, clean them up and commit them.

Great news. I hope those patches are merged to master eventually once the bugs are ironed out. If you want a beta tester I'm here.

> We have a plugin for performance counters (hundreds of them on Windows) but its not included with the main repository. The plugin atricturecture is easy enough to make you own and even easier if you duplicate one of the existing plugins.

I found the PerfMonPlugin in the plugins-extra repo (https://github.com/processhacker/plugins-extra/tree/master/PerfMonPlugin).

Thanks again.

**Comment by dmex** [comment]
> I guess it's not possible to IFDEF this as a workaround?

It's a major rewrite which lots of changes every few months. We have to wait until the structure is more stable.

> I found the PerfMonPlugin in the plugins-extra repo

👍
