### ISSUE TITLE
After Git-d5f3b9c8 cannot compile only x86 ExtendedToolsd.dll.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#332]
Git-d5f3b9c8 , build/build_release.cmd, VS2017 v15.8.6

Version: 3.0.1937 (d5f3b9c8) [master]

[00:00] Building ProcessHacker (x32)...
[00:32] Building ProcessHacker (x64)...
[01:01] Building Plugins (x32)...
[ERROR]
.\plugins\extendedtools\unldll.c(261): error C2059: syntax error: }
.\plugins\extendedtools\unldll.c(287): error C2059: syntax error: }
.\plugins\extendedtools\unldll.c(313): error C2059: syntax error: }
.\plugins\extendedtools\unldll.c(339): error C2059: syntax error: }
.\plugins\extendedtools\unldll.c(365): error C2059: syntax error: }

If check use IDE, then x64 build is success, but only x86 have this errors.

**Comment by dmex** [comment]
> Source for this problem also SDK 10.0.17763

You keep blaming the SDK... It's never the SDK.

**Comment by VictorVG** [comment]
Thanks! It spent most of the night repairing the frequency meter ("Made in USA", but in fact, after a month of work at the measurement range switch, the harness flew off - all the rations turned out to be "raw" and ... fell off. I had to sort it out and re-solder this hack - the device needed, but there is no spare at hand) and mixed up correcting where everything was going. :) And then he himself laughed at this confusion - he earned, but wanted to help by correcting the assembly error.

**Comment by TETYYS** [comment]
Please refrain from commenting stories that were put through google translate, everybody wastes time to read and process it - just to understand that it's indecipherable
