### ISSUE TITLE
Wrong SAL annotation in NtQueryIoCompletion

### ISSUE THREAD

**Issue by assarbad** [processhacker/processhacker#335]
At line [1537 in ntioapi.h](https://github.com/processhacker/processhacker/blob/master/phnt/include/ntioapi.h#L1537) we have the declaration of `NtQueryIoCompletion`:

```
NTSYSCALLAPI
NTSTATUS
NTAPI
NtQueryIoCompletion(
    _In_ HANDLE IoCompletionHandle,
    _In_ IO_COMPLETION_INFORMATION_CLASS IoCompletionInformationClass,
    _Out_writes_bytes_(IoCompletionInformation) PVOID IoCompletionInformation,
    _In_ ULONG IoCompletionInformationLength,
    _Out_opt_ PULONG ReturnLength
    );
```

I believe that third parameter annotation should be `_Out_writes_bytes_(IoCompletionInformationLength)`.

Found it while trying to find other sources to verify my own native API header.

Best regards,

Oliver

**Comment by dmex** [comment]
Thanks 👍
