### ISSUE TITLE
Why the earlist commit history have log message but no real any change

### ISSUE THREAD

**Issue by ljporljp** [processhacker/processhacker#336]

**Comment by dmex** [comment]
From 2008-2016 we were hosted by SourceForge... You would have to ask Github why those commit details are no longer showing for you but they show up properly for me? If you care about old broken code then the SF repository is still available and you can still see those details over there 👍

**Comment by ljporljp** [comment]
Thanks for answering me. You can look at this commit : 
[https://github.com/processhacker/processhacker/commit/5f80f7ebf5dfea02c17eda0b97bd8d3a92a064d5]
There is no any content changed as I said, and such things are much more.Is it a problem caused by  migration? I just want to find whether this is encountered by myself or everyone.Thanks again!

**Comment by dmex** [comment]
@ljporljp 

I emailed Github support two weeks ago and they replied saying it was being looked into but they haven't replied since then. I'll update this ticket when I have more information 👍

**Comment by poizan42** [comment]
It looks the same if you clone and inspect those commits locally. It is only 2.x/trunk that was imported from svn, but it seems like commits from outside the tree got imported as well.

5f80f7e corresponds to [r2316](https://sourceforge.net/p/processhacker/code/2316/) which is a commit to the 1.x branch.

It looks ugly in the history, but it can't really be changed now without being an annoyance for anyone who has forked the repo.

**Comment by dmex** [comment]
> commits from outside the tree got imported as well just without any files

This seems to be the case from Github support.
