### ISSUE TITLE
Feature Request: Reading PEB

### ISSUE THREAD

**Issue by 1982Dmitry** [processhacker/processhacker#339]
It would be very useful if you add support of parsing PEB from a process.

**Comment by Biswa96** [comment]
PEB is 2000 bytes long structure. Iterating every member of that struct would be tedious.

**Comment by 1982Dmitry** [comment]
Maybe start parsing when a user requests it (via open tab or clicking a button)

**Comment by Biswa96** [comment]
For example, I've written this code snippet:

```c
PEB* peb = calloc(1, 1992);
PROCESS_BASIC_INFORMATION ProcInfo = { 0 };

HANDLE hProcess = OpenProcess(PROCESS_ALL_ACCESS, TRUE, pid);
NTSTATUS Status = NtQueryInformationProcess(hProcess, ProcessBasicInformation, &ProcInfo, sizeof(ProcInfo), NULL);
BOOL bRes= ReadProcessMemory(hProcess, ProcInfo.PebBaseAddress, peb, 1992, &size);
printf("build: %ld\n", peb->OSMajorVersion);
```

One have to just iterate this over whole PEB structure.
