### ISSUE TITLE
Unable to verify the kernel driver signature

### ISSUE THREAD

**Issue by l19980623** [processhacker/processhacker#340]
I have encountered a weird issue in latest PH. When launching PH in Admin mode, an error shows up and says "Unable to verify the kernel driver signature." Used to be fine but a while ago it started to do that. See attached screenshot for details. I'm running Windows 10 1809 (17763.134). Any help is appreciated. Thanks!

![snipaste_2018-11-17_15-13-52](https://user-images.githubusercontent.com/4069734/48666292-18570300-ea7c-11e8-8550-bbe21a9db6f3.png)

**Comment by l19980623** [comment]
My bad, it turns out my AV software is interfering with PH.

**Comment by dmex** [comment]
@l19980623 

Which AV are you using? I'd like to look into why they're messing with our signature files.

**Comment by l19980623** [comment]
It's Webroot SecureAnywhere. Found out that a number of dll and exe files were quarantined (the installer itself was also tagged as unsafe). After restoring them the error went away. See screenshot for a partial list of quarantined files. Thanks!

![snipaste_2018-11-17_15-48-32](https://user-images.githubusercontent.com/4069734/48666493-51917200-ea80-11e8-9085-2880efd5fff2.png)

**Comment by l19980623** [comment]
Attempted to run update (v1990) today and ran into the same issue. The setup file was marked `W32.Adware.Gen`. However it appears that program files were fine though, I ran a manual scan in PH directory and it did not report any threat.

**Comment by ddbb2017** [comment]
I saw yesterday the same error message in my Windows 8.1 VM (no third-party AV, just a built-in Windows Defender.) My guess is that any newly signed binary may produce some false-positives until that binary is downloaded and used enough times. (In case of Microsoft, until their SmartScreen filters "learn" that the file is not malicious.)

**Comment by dmex** [comment]
Closing as duplicate of #454
