### ISSUE TITLE
Using the kprochacker in a external application

### ISSUE THREAD

**Issue by radoradovan** [processhacker/processhacker#341]
This isn't really a Issue more a question.
I would like to use the kprochacker.sys in my application, to suspend a kernel thread.
How would I start with this?
Doing a connection shouldn't be a problem, since everything I need is in "kph.c", but I can't really find the function which is used to suspend/kill a kernel thread.
Any hints would be appreciated
Thanks

**Comment by dmex** [comment]
> Doing a connection shouldn't be a problem, since everything I need is in "kph.c"

The driver doesn't allow unofficial 3rd party applications to use most of the functionality. You will have to sign the driver with your own certificate and also create your own private key.

>  I can't really find the function which is used to suspend/kill a kernel thread.

Yep. We don't use the driver for suspending/terminating threads which is why you won't find anything in the driver source for doing this.

**Comment by radoradovan** [comment]
@dmex firstly thanks for your reply!
But how does processhacker suspend kernel threads then? It uses defentitly the driver module, since if I uncheck the function "Enable kernel driver", it doesn't work anymore to suspend kernel threads aka threads in the "System" process.

**Comment by radoradovan** [comment]
I will try to create a plugin which does the job.
Could you guys give me a hint which function I should use to suspend a system thread.
Something along these lines I guess:
`  NTSTATUS status;
            HANDLE threadId = 3752;
            HANDLE threadHandle;

            if( NT_SUCCESS( status = PhOpenThread( &threadHandle, THREAD_SUSPEND_RESUME, &threadId ) ) ) {
                status = NtSuspendThread( threadHandle, NULL );
                NtClose( threadHandle );
            }
`
But how do I open the right thread handle, and get the right thread ID?

**Comment by Biswa96** [comment]
This may help: https://stackoverflow.com/q/15597066/8928481

**Comment by radoradovan** [comment]
Thanks but I think this won’t help since it will only suspend the main thread from a process I give. Open processhacker and go to the System process. Double click it and go on thread page, one of these I want to suspend.

**Comment by radoradovan** [comment]
Im trying to solve this over the plugin API. Anyone who could give me a hint on how I could actually access the system process to enumerate its threads so I can actually suspend the one I need? 
Thanks

**Comment by Biswa96** [comment]
@radoradovan [MSDN: Enumerating threads in a process](https://blogs.msdn.microsoft.com/oldnewthing/20060223-14/?p=32173).

**Comment by radoradovan** [comment]
@Biswa96 thanks but I want to use the process hacker api for that. As process hacker already does all this, I just wanna call it and then do the suspend like process hacker. But I can’t find any info about either the System threads page nor the suspend system thread in process hacker API.

**Comment by mrsshr** [comment]
try PhEnumProcesses, PhFindProcessInformation, PhOpenThread, NtSuspendThread.

**Comment by dmex** [comment]
> PhEnumProcesses, PhFindProcessInformation, PhOpenThread, NtSuspendThread.

Yep. These are the correct functions.

> I will try to create a plugin which does the job.

The plugin API has very limited system access for security reasons and you won't be able to automate the suspension of system threads via the plugin API.

You'll have to use 3rd party software to automate suspension of system threads. Your best bet would be using a script with windbg and/or livekd to execute the ~n command to suspend the thread: 
https://nativecoding.wordpress.com/2016/01/10/automate-attach-to-process-on-windows-with-windbg/
