### ISSUE TITLE
Creating a plugin for PH

### ISSUE THREAD

**Issue by 1982Dmitry** [processhacker/processhacker#342]
Is there any reference how to create a plugin for PH? (other than actual plugins)

**Comment by dmex** [comment]
@1982Dmitry 

There are these reference pages but some parts are probably outdated:
https://wj32.org/processhacker/forums/viewtopic.php?f=18&t=41

**Comment by diversenok** [comment]
@1982Dmitry 
Btw, not all the plugins are listed in this repository, see also [plugins-extra](https://github.com/processhacker/plugins-extra).
