### ISSUE TITLE
Delay checking for updates

### ISSUE THREAD

**Issue by ghost** [processhacker/processhacker#344]
I want Process Hacker to check for updates, really I do, but the moment I open it, I generally need it urgently. Thus, a popup asking me to download the new update is not welcome. It's especially annoying when I'm trying to end a process, which is a popup in and of itself, and this update popup comes up in the middle of it and I press it on accident...

If it could just wait until I'm closing it to ask, that'd be nice.

**Comment by Aidolii** [comment]
I would want it to ask when I'm closing the program, not when opening the program.

**Comment by Aidolii** [comment]
Could you implement checking for update during closing, or have it check only when the program has been open for at least 30 seconds?

**Comment by dmex** [comment]
Added in latest nightly.

**Comment by dmex** [comment]
Also added new option to show update prompt before opening Process Hacker.
