### ISSUE TITLE
[Question] Whats the best way for me to contribute / add features to this main branch ?

### ISSUE THREAD

**Issue by AltF5** [processhacker/processhacker#345]
Hi. User from PH forums, and I have downloaded the code and added some items, in particular, 2 thread columns for 'Has Token' and 'Is GUI Thread'. Is it possible or is there interest in my somehow contributing these changes? I'm not too familar with Github as an SVN (only really have used TFS for most of my career), so if I can contribute, do I should take a branch, make my changes in VS, upload to github, and then post back here? 

Thanks, wanting to help add some ideas :-)

**Comment by MagicAndre1981** [comment]
fork the repository, create a new branch, add changes, commit them and create a pull request that @dmex can review and merge or ignore.

**Comment by AltF5** [comment]
Working on trying this. Trying to get visual studio to connect to my github. It appears with 2019 its easy to download a repository but I’m not too familiar with Azure Dev Ops, which appears to be needed?

Maybe I just need to upload the changed files, hmm

**Comment by TETYYS** [comment]
you definetely don't need some kind of azure dev ops, just commit to your forked repository and create a pull request.

**Comment by MagicAndre1981** [comment]
Use TortoiseGit to clone the forked repository.

**Comment by AltF5** [comment]
For committing, is this through Visual Studio GUI itself, or just manually? (Sorry for being an SVN noob :P)

**Comment by MagicAndre1981** [comment]
also use TortoiseGit to commit and push changes

**Comment by AltF5** [comment]
@dmex is it better to Clone or Fork your PH code here? I previously forked it for test purposes, but it looks like Git Desktop prefers Clone it seems.

Also is there a certain algorithm/workflow that would be good to utilize both Visual Studio and Git Desktop "together"... ie have Visual Studio "Check out" and then use Git Desktop to Commit perhaps?

**Comment by AltF5** [comment]
Thanks bro! I’ll post back if I hit any snags trying this later
