### ISSUE TITLE
where are the logfiles from process hacker?

### ISSUE THREAD

**Issue by 1sunil1** [processhacker/processhacker#346]
Hi,

Does process hacker generate any logfiles, and if so then where does it gets stored?

**Comment by dmex** [comment]
Process Hacker only creates a log file when you enable the logging feature. You need to set the path to enable it:

![image](https://user-images.githubusercontent.com/1306177/49967118-3a7c5d80-ff22-11e8-9aae-c56706e6f711.png)

**Comment by 1sunil1** [comment]
![image](https://user-images.githubusercontent.com/43957664/50002287-a6fc6880-ffc5-11e8-8cb2-6fddb2fcaad0.png)


I am getting the different options. I have installed the ProcessHacker from https://github.com/processhacker/processhacker. From where did you download your Process hacker, or if you know how to bring changes, the let me know.

**Comment by dmex** [comment]
I'm using the nightly build 👍 
https://wj32.org/processhacker/nightly.php

**Comment by 1sunil1** [comment]
![image](https://user-images.githubusercontent.com/43957664/50003657-6eab5900-ffca-11e8-9027-cca91c75c55b.png)

After installing the plugin of extended notifications. I am getting that option. But the log files are not coming up.

**Comment by 1sunil1** [comment]
> ![image](https://user-images.githubusercontent.com/43957664/50003657-6eab5900-ffca-11e8-9027-cca91c75c55b.png)
> 
> After installing the plugin of extended notifications. I am getting that option. But the log files are not coming up.

And when I open the tool again, after saving the path for log files. The log file path again gets vanished.
Could you just try that in your PC and let me know whether it is coming or not.
