### ISSUE TITLE
CustomBuildTool needs updating with this code for Preview-only Visual Studios installed

### ISSUE THREAD

**Issue by AltF5** [processhacker/processhacker#347]
Hi, I fixed CustomBuildTool locally for having only VS2017 Preview and VS2019 Previews installed, where it otherwise fails with "MsBuild not installed. Exiting." when buidling the SDK for plugins via \[PH]\Build\build_sdk.cmd

The fix was pretty straight forward. In **Utils.cs     :    GetMsbuildFilePath()**
 
 
1. "-prerelease " + needs to be added in the vswhere.exe commandline, otherwise nothing will be returned on the CLI if no non-preview-VS is installed. Found this switch from:
https://developercommunity.visualstudio.com/content/problem/80487/vswhere-returns-nothing-after-installing-vs-2017-u.html

Fix:
			string vswhereResult = Win32.ShellExecute(vswhere,
				"-latest " +
				"-prerelease " +
				"-products * " +
				"-requires Microsoft.Component.MSBuild " +
				"-property installationPath "
				);

 
 

2. As of VS 2019 MSBuild path no longer resides in '15.0' subdir, but rather 'Current':
		https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview
		[VSInstallDir]\MSBuild\15.0\Bin
		To
		[VSInstallDir]\MSBuild\Current\Bin

Fix:
		if (File.Exists(vswhereResult + "\\MSBuild\\15.0\\Bin\\MSBuild.exe"))
		{
			return vswhereResult + "\\MSBuild\\15.0\\Bin\\MSBuild.exe";
		}
		else if(File.Exists(vswhereResult + "\\MSBuild\\Current\\Bin\\MSBuild.exe"))
		{
			return vswhereResult + "\\MSBuild\\Current\\Bin\\MSBuild.exe";
		}

**Comment by dmex** [comment]
Fixed 👍

**Comment by AltF5** [comment]
Thanks bro! Saw the commit. Nice job.
