### ISSUE TITLE
Bug in hndlprv.c when KPH driver is connected, but handle enum fails [Still researching]

### ISSUE THREAD

**Issue by AltF5** [processhacker/processhacker#348]
**-- Bug --**
When the KPH driver call fails for handle enumeration, the fallback method does not work properly (for all System handles), and instead EmptyHandlesText ("There are no handles to display.") is shown for all process' Handles tab.
 
 
 
**-- Effect --**
CASE 1: PH launched as non-admin w/ driver in same directory (does not connect to driver) = Can Enumerate Handles
**CASE 2: PH launched as admin w/ driver in same directory (connects to driver) = "There are no handles to display."  << ISSUE HERE !!!**
CASE 3: PH launched as admin WITHOUT driver in the directory (does not connect to driver) = CAN enumerate handles

Tested on Windows 10 x64 1803 (don't have other OS' avaiable at the moment to see what all is affected, or if it even matters)

 
 
**-- Possible Issues---**
For CASE 2:
- KphEnumerateProcessHandles returns Access Denied (ALONG WITH MANY OTHER CALLS into KphpDeviceIoControl) when the driver IS Connected.
- hndlprv.c ! PhEnumHandlesGeneric(...) not calling PhEnumHandlesEx2 in the fail case (is isntead using PhEnumHandlesEx)
- When PhEnumHandlesEx is used (all system handles) PhHandleProviderUpdate performs a filter, but something in this code is causing "There are no handles to display." to results (Still trying to figure out why) **<< I think some bug mainly exists here.**
 
 

**-- Code Location --**
(1) Possibly need to change this to be 
hndlprv.c ! PhEnumHandlesGeneric(...)

if (KphIsConnected())
...
	if (!NT_SUCCESS(status = KphEnumerateProcessHandles2(ProcessHandle, &handles)))
		**goto FAILED;		// <----- ISSUE HERE**
		
Jumping to FAILED label calls PhEnumHandlesEx = NTQSI w/ SystemExtendedHandleInformation.
The code works to get ALL system handles, but it must be some logic bug in the handle filter method [PhHandleProviderUpdate] where its not populating the list properly (I need to do more digging as to exactly whats happening)

I believe INSTEAD the fail case needs to go to / include this logic in CASE 1 / 3, when PH is running as Admin, but NOT connected with driver (that is KphIsConnected() = false)
else if (WindowsVersion >= WINDOWS_8 && PhGetIntegerSetting(L"EnableHandleSnapshot"))
{
...
}
Here it calls PhEnumHandlesEx2 (instead of PhEnumHandlesEx), which instead uses NTQSI w/ ProcessHandleInformation. This case always works (such as when the driver is NOT connected)

 
 
**-- Bug Research - Driver call --**

KphEnumerateProcessHandles returns Access Denied (-1073741790 = 0xC0000022 = STATUS_ACCESS_DENIED ), at least in my Windows 10 1803

kph.c
        status = KphEnumerateProcessHandles(
            ProcessHandle,
            buffer,
            bufferSize,
            &bufferSize
            );
			
I am unsure why, but the call-chain is:
	KphpDeviceIoControl(PH_ENUMERATEPROCESSHANDLES,...
		NtDeviceIoControlFile(...)  		<-- returning this stats
		
It looks like all code that calls KphpDeviceIoControl (NtDeviceIoControlFile) is returning Access Denied as well, example: KphOpenProcessJob

**Comment by MagicAndre1981** [comment]
for me handles have no name. Is this the same issue like this? @dmex

**Comment by AltF5** [comment]
Gonna close this. Cannot repro in latest nightly. Maybe I fluffed something up in my modifications

**Comment by MagicAndre1981** [comment]
I still have the issue with latest nightly. All handles have no name. Please reopen

**Comment by AltF5** [comment]
Hi ok. Does it occur even with the driver being renamed (so it’s not loaded) and PH running as an Admin? 
You aren’t trying to view a Protected process are you?

Maybe you could describe the issue or provide a screenshot of this and the process trying to view.

**Comment by MagicAndre1981** [comment]
without the driver I see the names for handles, with loaded driver and running as admin, the handle names are all empty

**Comment by dmex** [comment]
@MagicAndre1981 

You need to reset the driver configuration. From an administrative command prompt:

sc stop kprocesshacker3
sc delete kprocesshacker3

or 

processhacker.exe -uninstallkph
processhacker.exe -installkph

**Comment by MagicAndre1981** [comment]
@dmex 

makes no difference. 

![Screenshot (4)](https://user-images.githubusercontent.com/8274816/60564806-5ed64500-9d61-11e9-8d54-ba3cbafec1c4.png)



Without driver I see the data:

![Screenshot (6)](https://user-images.githubusercontent.com/8274816/60564805-5ed64500-9d61-11e9-8cfd-98af34791b86.png)

**Comment by MagicAndre1981** [comment]
@dmex 

I use 1903, you have [compiled the driver against 1809 WDK](https://github.com/processhacker/processhacker/commit/3a2f95566a3fe589787de77376974d667f5ac665). Is there any breaking change in WDK area between 1809 and 1903?

**Comment by MagicAndre1981** [comment]
@dmex 

there is indeed a logic bug in your code as @AltF5 already mentioned. In case you get a failure with `KphEnumerateProcessHandles2` you don't try to call the PhEnumHandlesEx2 (which is called when starting without driver) as fallback, but jump directly to legacy PhEnumHandlesEx. Add this here:

```
if (!NT_SUCCESS(status = KphEnumerateProcessHandles2(ProcessHandle, &handles)))
{
         if (WindowsVersion >= WINDOWS_8 && PhGetIntegerSetting(L"EnableHandleSnapshot"))
              goto KFAILEDWIN8;
          else
              goto FAILED;
}
```

The KFAILEDWIN8 identifier should be before

`if (!NT_SUCCESS(status = PhEnumHandlesEx2(ProcessHandle, &handles)))`

so that PhEnumHandlesEx2 is called when driver fails and when started without driver. 

![image](https://user-images.githubusercontent.com/8274816/60595829-0fffce00-9da8-11e9-87f1-6145647b67c1.png)

But I fail to setup remote debug to debug it on the 1903 tablet

**Comment by dmex** [comment]
> you don't try to call the PhEnumHandlesEx2 (which is called when starting without driver) as fallback, but jump directly to legacy PhEnumHandlesEx.

This is the correct logic because PhEnumHandlesEx2 can also fail when the process is filtered or doesn't have administrative privileges. 

PhEnumHandlesEx uses NtQuerySystemInformation and should never ever (ever) fail or return errors. You must have some sort of rootkit hooking NtQuerySystemInformation which is causing the fallback to PhEnumHandlesEx to fail and return nothing.

*If you're using Avast they're using a hypervisor to disable PatchGuard and hook kernel routines and hundreds of syscalls. This causes more security issues because if Avast doesn't block/detect new types of rookits (anti-virus needs to have signatures to block it and so new signatures are always undetected) that rootkit can easily patch the kernel because PG was already disabled by Avast.

**Comment by MagicAndre1981** [comment]
no, I use the normal Windows Defender on 32Bit win10 1903 tablet and NOD32 on Windows 8.1 where it also fails.

**Comment by diversenok** [comment]
> PhEnumHandlesEx uses NtQuerySystemInformation and should never ever (ever) fail or return errors.

Just to point out: querying SystemExtendedHandleInformation from a process with low integrity level fails on Windows 8.1+ [because of system-wide information mitigations](http://www.alex-ionescu.com/?p=82).

**Comment by MagicAndre1981** [comment]
I now know what causes it. When I download the [prebuild nightlies](https://wj32.org/processhacker/nightly.php), enumerating the handles works fine when running as admin with driver. If I rename/delete the `ProcessHacker.sig` I get the handle enum issue again.

@dmex how do you create this `ProcessHacker.sig`?
