### ISSUE TITLE
Unable to load the kernel driver signature.

### ISSUE THREAD

**Issue by tasselffs** [processhacker/processhacker#350]
I compiled the PH from the source and prompted "Unable to load the kernel driver signature."
The end of file tag has been reached. There is no valid data after the tag in the file.". If I run your compiled PH directly, there is no such problem, thanks.
![tim 20181215133553](https://user-images.githubusercontent.com/17903740/50039588-ab7d5b80-006f-11e9-85af-153e7742aa48.png)

**Comment by dmex** [comment]
> I compiled the PH from the source and prompted "Unable to load the kernel driver signature."

The error message is intentional since some users incorrectly assume that they can use the driver in their unofficial builds.

I'll make the error message more descriptive when I have the time 👍

**Comment by pawelzwronek** [comment]
So actually why we users cant use the driver in unofficial builds? Can we rebuild and sign the driver?

**Comment by dmex** [comment]
> So actually why we users cant use the driver in unofficial builds?

It's a legal requirement.

> Can we rebuild and sign the driver?

Yes, you can recompile and use the driver. The entire source is available on here on Github under GPL3 license.

You can either enable the Windows testsigning mode and use a self signed certificate or you can even use 3rd party certificates uploaded to Github here: https://github.com/hackedteam/GeoTrust

Windows shows those certificates as revoked but Windows doesn't actually have any revocation checking whatsoever and you can load kernel drivers perfectly fine. Some other Github projects such as [Windows-Kernel-Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer) use those same certificates without any issues in their kernel drivers.

**Comment by pawelzwronek** [comment]
Thanks for comprehensive answer. I think it could be included in main README file.
