### ISSUE TITLE
I wart to modify the logfile format and data from process hacker.

### ISSUE THREAD

**Issue by 1sunil1** [processhacker/processhacker#351]
I am able to get the log files from Process Hacker, but it is not coming in the format I want.
Currently I am getting in the below manner.

12:30:03 PM 12/15/2018: Service stopped: lpasvc (Microsoft Policy Platform Local Authority)
12:30:10 PM 12/15/2018: Process terminated: svchost.exe (16248); exit status 0x0
12:30:10 PM 12/15/2018: Service stopped: WerSvc (Windows Error Reporting Service)
12:30:56 PM 12/15/2018: Process terminated: chrome.exe (11488); exit status 0x0
12:30:56 PM 12/15/2018: Process created: chrome.exe (11204) started by chrome.exe (10632)
12:30:56 PM 12/15/2018: Process created: chrome.exe (10244) started by chrome.exe (10632)
12:31:01 PM 12/15/2018: Process created: chrome.exe (10548) started by chrome.exe (10632)
12:31:02 PM 12/15/2018: Process created: chrome.exe (8884) started by chrome.exe (10632)

But I want all the information which is visible in UI of Process Hacker. How do I modify that?

**Comment by dmex** [comment]
> But I want all the information which is visible in UI of Process Hacker. 

Main menu > Hacker > Save?
