### ISSUE TITLE
ToolStatus plugin no longer working correctly. Search is broken on nightly. 

### ISSUE THREAD

**Issue by Apocalypse612** [processhacker/processhacker#352]
This plugin doesn't work correctly anymore with the latest nightly build on WIn 10 x64 1803.

The search bar only works on processes. Also, if you try changing the tab and searching services, disk, etc - It will not work and make an error sound.

After this happens, it won't even work anymore from the process tab. The only way to fix this is to restart Process hacker completely.

Any suggestions for a fix?

**Comment by dmex** [comment]
> This plugin doesn't work correctly anymore with the latest nightly build on WIn 10 x64 1803.

I can't reproduce any issues with the Searchbox.

> The search bar only works on processes. Also, if you try changing the tab and searching services, disk, etc - It will not work and make an error sound.

You might have some 3rd party software messing with the window?
