### ISSUE TITLE
why explorer.exe is the parent of the processes started as admin

### ISSUE THREAD

**Issue by adevelopcr** [processhacker/processhacker#354]
do you know which process really launch the admin processes when double clicking on them ?
I see in ProcessHacker that the parent process is explorer.exe but I'm sure it didn't start them as it's running as usual user not admin
I hooked the functions that create processes in explorer.exe and it returned failure when starting admin processes
I think it's svchost or lsass but don't know which one

**Comment by diversenok** [comment]
It is done by AppInfo service. When the user confirms UAC dialog, this service creates the required process with an elevated token and replaces its parent to the initial issuer of the request. [Here is](https://www.codeproject.com/Articles/19165/Vista-UAC-The-Definitive-Guide) an article about how it works.

**Comment by adevelopcr** [comment]
so it's svchost which has netsvc as argument

**Comment by adevelopcr** [comment]
I tested with hooking and I found that it's the real process that launch the admin processes with uac
