### ISSUE TITLE
StartAddress member in SYSTEM_THREAD_INFORMATION is the same for most threads

### ISSUE THREAD

**Issue by adevelopcr** [processhacker/processhacker#357]
I took the definition of the struct from process hacker nt headers as follows : 

`  typedef struct _SYSTEM_THREAD_INFORMATION {
	  LARGE_INTEGER KernelTime;
	LARGE_INTEGER UserTime;
	LARGE_INTEGER CreateTime;
	ULONG WaitTime;
	PVOID StartAddress;
	CLIENT_ID ClientId;
	LONG Priority;
	LONG BasePriority;
	ULONG ContextSwitches;
	ULONG ThreadState;
	ULONG WaitReason;
} SYSTEM_THREAD_INFORMATION, *PSYSTEM_THREAD_INFORMATION;`

but the StartAddress member is wrong , it's really the same for most threads or 0 for others

I use this code to get the threads info : 

`void ** ProcessCore::all_thread_full(unsigned long pid)
{
	void **all_thread_collected = nullptr;
	if (!pid) return all_thread_collected;
	void *process_buffer = nullptr;
	unsigned long required_size = 0;
	ntapi::query_sys_info(SystemProcessInformation, 0, 0, &required_size);
	if (!required_size) return all_thread_collected;
	process_buffer = HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, required_size);
	bool result = ntapi::query_sys_info(SystemProcessInformation, process_buffer, required_size, 0);
	if (!result) {
		HeapFree(GetProcessHeap(), 0, process_buffer);
		return all_thread_collected;
	}
	PSYSTEM_PROCESS_INFO pinfo = (PSYSTEM_PROCESS_INFO)process_buffer;
	while (pinfo->NextEntryOffset)
	{
		pinfo = (PSYSTEM_PROCESS_INFO)((uintptr_t)pinfo + pinfo->NextEntryOffset);
		if ((unsigned long)pinfo->ProcessId == pid) {
			if (pinfo->NumberOfThreads) {
				all_thread_collected = (void**)HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, sizeof(void*) * (pinfo->NumberOfThreads + 1));
				for (unsigned long i = 0; i < pinfo->NumberOfThreads; ++i) {
					SYSTEM_THREAD_INFORMATION *pthread = (SYSTEM_THREAD_INFORMATION *)HeapAlloc(GetProcessHeap(), HEAP_ZERO_MEMORY, sizeof(SYSTEM_THREAD_INFORMATION));
					memcpy(pthread,&pinfo->Threads[i], sizeof(SYSTEM_THREAD_INFORMATION));
					all_thread_collected[i] = pthread;
				}
			}
		}
	}
	HeapFree(GetProcessHeap(), 0, process_buffer);
	return all_thread_collected;
}

PSYSTEM_THREAD_INFORMATION *all_threads = (PSYSTEM_THREAD_INFORMATION*)ProcessCore::all_thread_full(836);
	while (*all_threads)
	{
		cout << "[*] thread id : " << (unsigned long)(*all_threads)->ClientId.UniqueThread << endl
			<< "[*] thread process : " << (unsigned long)(*all_threads)->ClientId.UniqueProcess << endl
			<< "[*] start address : " << (unsigned long long)(*all_threads)->StartAddress << endl
			<< "[*] state : " << (*all_threads)->ThreadState << endl;
		++all_threads;
	}`
the ids and pids are the same as shown in process hacker but the start address isn't as it in ph

**Comment by adevelopcr** [comment]
the code format isn't being showed right here so these are the codes as screen shots

![capture1](https://user-images.githubusercontent.com/37940026/50702024-52925900-1058-11e9-9984-f949b0957755.PNG)
![capture2](https://user-images.githubusercontent.com/37940026/50702027-54f4b300-1058-11e9-8877-c3f3c0fdefbd.PNG)

**Comment by dmex** [comment]
ThreadQuerySetWin32StartAddress
