### ISSUE TITLE
When will a new version will be released with all new commits?

### ISSUE THREAD

**Issue by TontyTon** [processhacker/processhacker#360]
![processhacker](https://user-images.githubusercontent.com/35778430/51046157-5d666400-15eb-11e9-978e-80f1b334a4a3.PNG)

**Comment by Bec-de-Xorbin** [comment]
https://wj32.org/processhacker/nightly.php

**Comment by medhefgo** [comment]
There's a huge difference between nightly and stable releases. Also, the nightlys aren't even signed.

**Comment by TontyTon** [comment]
Can I report bugs in nightly builds here? If yes, are they addressed here, solved and solved to nightly builds?
