### ISSUE TITLE
Process Hacker does not start on log in with checked "Start when I log in" checkbox

### ISSUE THREAD

**Issue by tsunamistate** [processhacker/processhacker#361]
**Environment:**

Windows 10 Pro x64
Intel Celeron N2830
8Gb RAM
Process Hacker 3.0.2054 (422e450f)

**Steps to reproduce:**
1. Download a build-3.0.2054-setup.exe from https://wj32.org/processhacker/nightly.php
2. Install Process Hacker with "Launch on system startup" checkbox checked or go to Hacker -> Options -> General and tick "Start when I log on" checkbox
4. Reboot the computer and log in

**Actual Result:** Process Hacker does not start on system startup

**Expected Result:** Process Hacker starts on system startup

**Workaround:** The issue is caused by extra slash in program path of autostart Registry entry, that is created by installer in HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run\Process Hacker `C:\Program Files\Process Hacker\\ProcessHacker.exe" -hide`
Removing the extra slash `"C:\Program Files\Process Hacker\ProcessHacker.exe" -hide` fixes autostart

**Comment by dmex** [comment]
Thanks fixed 👍

**Comment by User4716** [comment]
Still not starting
