### ISSUE TITLE
Crashing on startup after clicking "Find handles of DLLs"

### ISSUE THREAD

**Issue by drewnoakes** [processhacker/processhacker#362]
Yesterday I clicked "Find handles of DLLs" and this dialog appeared immediately:

![image](https://user-images.githubusercontent.com/350947/51184776-3353c100-18cd-11e9-851b-049994e2cec0.png)

I clicked Close and relaunched PH. Unfortunately now I see this dialog every time I launch PH. I can use PH just fine, but as soon as I dismiss this dialog it exits.

An upgrade popup appeared, so I tried upgrading to see if it might help. The version I am on now (after upgrade, assuming it succeeded) is 3.0.2046 (be5184bb).

Happy to help diagnose if you provide some pointers. 

This is a work computer so I'd need to check with my employer before providing a dump. If we can avoid that it'll be easier.

**Comment by dmex** [comment]
Are you running PH from a network share? The error code is called "STATUS_IN_PAGE_ERROR" which is related to hardware failures (disk, network and memory devices) or corrupted files.

https://blogs.msdn.microsoft.com/oldnewthing/20081204-00/?p=19963

**Comment by drewnoakes** [comment]
No, not from a network share.

![image](https://user-images.githubusercontent.com/350947/51198812-31015f00-18ed-11e9-8e0a-ce9e870c697d.png)

After restarting the PC, PH is no longer crashing. Clicking "Find handles of DLLs" does not reproduce the problem.

Feel free to close this if you feel there's no action to be taken.
