### ISSUE TITLE
RESOLVED - AV then try creat memory dump in Win7 after fix #355

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#366]
Then I try create dump or minidimp then PH crashed and press MsRClick -> _Create dump file..._ command I have AV (Access Violation) in if press _Minidump_ have new AV in to circuit cycle before not press Restart or Close button:

![ph](https://user-images.githubusercontent.com/906886/51448069-ea6c9400-1d34-11e9-9a6a-47e840a6aa16.png)

 :( I try send crashed process in to debugger, but he says whats process already close and send to OS return code is 0. Created files .dump or .minidumps have size 0 bytes and not included any data or hidden NTFS streams.

I say any users and all say whats this phenomena exists on Windows 7. Users use Win10 don't see it. I don't known whats find source for this phenomena. Also I see old problem #355 and only after recompile. I try clean all setting [PH_config.zip](https://github.com/processhacker/processhacker/files/2777304/PH_config.zip) - helps .... until the next update. I'm already completely confused in the search for the causes of the phenomenon. Obviously something simple, but slipping away ...

**Comment by VictorVG** [comment]
v3.0.6637.2110 Git-0fe27cbb - better 

![1](https://user-images.githubusercontent.com/906886/51573065-d782cc80-1eb8-11e9-92f1-61a78be529d2.png)

v3.0.6638.2111 Git-c0b2d23b again have AV.

**Comment by VictorVG** [comment]
v3.0.6651.2124 Git-b6564f3c - also crashed :(

**Comment by VictorVG** [comment]
I apologize for noticing the Issues label just now and responding ....

Well, I sort of came up with a way to bypass the lock - I took a dump through the Windows Task Manager and previously deciphered it:

![ph1-1](https://user-images.githubusercontent.com/906886/51833889-c9dea400-2309-11e9-86c8-103e4de80899.png)
![ph1-2](https://user-images.githubusercontent.com/906886/51833890-c9dea400-2309-11e9-9bc9-c25fe25d6223.png)
![ph2-1](https://user-images.githubusercontent.com/906886/51833892-c9dea400-2309-11e9-8ce5-a5d1b8f75e75.png)
![ph2-2](https://user-images.githubusercontent.com/906886/51833894-ca773a80-2309-11e9-9e20-d7bcea06e681.png)
![ph3-1](https://user-images.githubusercontent.com/906886/51833895-ca773a80-2309-11e9-87c8-b23394ae63ee.png)
![ph3-2](https://user-images.githubusercontent.com/906886/51833896-ca773a80-2309-11e9-8a0a-2386896638b6.png)
![ph4-1](https://user-images.githubusercontent.com/906886/51833898-ca773a80-2309-11e9-8ae9-39f55e818ac6.png)
![ph4-2](https://user-images.githubusercontent.com/906886/51833899-ca773a80-2309-11e9-9ad0-7a4fa53dadc3.png)
![ph5-1](https://user-images.githubusercontent.com/906886/51833900-cb0fd100-2309-11e9-916e-5b57f32dee38.png)
![ph5-2](https://user-images.githubusercontent.com/906886/51833901-cb0fd100-2309-11e9-902b-79add0452a46.png)
![ph6-1](https://user-images.githubusercontent.com/906886/51833902-cb0fd100-2309-11e9-9a1a-696dd7ca4f5c.png)
![ph6-2](https://user-images.githubusercontent.com/906886/51833903-cba86780-2309-11e9-964f-143e98b1631b.png)
![ph7-1](https://user-images.githubusercontent.com/906886/51833904-cba86780-2309-11e9-8c81-b937af43ac1b.png)
![ph7-2](https://user-images.githubusercontent.com/906886/51833905-cba86780-2309-11e9-9bb5-2cd7b149d8a9.png)
![ph8-1](https://user-images.githubusercontent.com/906886/51833906-cba86780-2309-11e9-8146-e0eb5fe95d70.png)
![ph8-2](https://user-images.githubusercontent.com/906886/51833907-cc40fe00-2309-11e9-86e0-83febd37bfb0.png)
![ph9-1](https://user-images.githubusercontent.com/906886/51833908-cc40fe00-2309-11e9-8256-0dfb7c387ad7.png)
![ph9-2](https://user-images.githubusercontent.com/906886/51833909-cc40fe00-2309-11e9-82b3-47fe46513e70.png)

[**ProcessHacker-v3.0.6654.2127-bin.tar.xz**](https://www.upload.ee/files/9488330/ProcessHacker-v3.0.6654.2127-bin.tar.xz.html) - this archive included my test-copy and have all .PDB for here.

[**ProcessHacker-v3.0.6654.2127-dump.tar.xz**](https://www.upload.ee/files/9488344/ProcessHacker-v3.0.6654.2127-dump.tar.xz.html) - ProcessHacker.DMP, unpacked size ~ 212 MB.

[**ProcessHacker-v3.0.6654.2127-debug-report.tar.xz**](https://www.upload.ee/files/9488337/ProcessHacker-v3.0.6654.2127-debug-report.tar.xz.html) - VS2015 dump decode screenshots.

**Comment by VictorVG** [comment]
Step for repro - in to Win7 SP1 x64:

RMsClick -> Create dump file... -> have AV

then click any Minidump button in to error dialog have secondary AV, Dump make after primary AV then try create dump for process Far.exe....

**Comment by VictorVG** [comment]
For users laid out such instructions for creating a dump:

1) in case of a failure in the PH, we don’t touch any buttons!
2) we call the Windows Task Manager, in it we search for the failed process, for example ProcessHacker.exe by the name of its task or image;
3) in the Windows Task Manager PCM (context menu, you can click the Apps button on KBD) -> Create a memory dump file. The dump is written for some time, has decent dimensions (I have ~ 212 MB), so he will tell us everything.
4) we pack a dump into the archive (here to choose from depending on the availability of archivers) and transfer to decryption.

I did my own for it, please look at it whenever possible - have I missed anything here? And nowhere was it wrong?

**Comment by dmex** [comment]
I checked the minidump and you should remove or disable these files that are installing hooks into Process Hacker:
'C:\Program Files (x86)\Dexpot\hooxpot64.dll'
'C:\Program Files\Far3\Far\plugins\dnd\drgndrop_x86_64.hook'

TortoiseGit, TortoiseSVN and LinkShellExtension have also injected (about 40) binaries into Process Hacker... You should disable/remove those programs then check if the crashing persists.

You also have lots of unofficial plugins that are known to cause crashes... You need to remove or disable:
plugins\AtomTablePlugin.dll
plugins\AvgCpuPlugin.dll
plugins\DbgViewPlugin.dll
plugins\DnsCachePlugin.dll
plugins\DpiAwarenessExtPlugin.dll
plugins\ExtendedNotifications.dll
plugins\FirewallMonitorPlugin.dll
plugins\FirmwarePlugin.dll
plugins\ForceShutdownPlugin.dll
plugins\LiveDumpPlugin.dll
plugins\MemoryExtPlugin.dll
plugins\NvGpuPlugin.dll
plugins\ObjectManagerPlugin.dll
plugins\PerfMonPlugin.dll
plugins\PoolMonPlugin.dll
plugins\ProductPolicyPlugin.dll
plugins\ROTViewerPlugin.dll
plugins\SecurityExplorer.dll
plugins\ServiceBackupRestorePlugin.dll
plugins\SetCriticalPlugin.dll
plugins\TaskbarExtPlugin.dll
plugins\TerminatorPlugin.dll
plugins\TrustedInstallerPlugin.dll
plugins\WaitChainPlugin.dll


I can't reproduce any crashes anywhere and I dont see anything in that minidump related to any crashes... This means either those injected binaries or those unofficial plugins caused the crash which is not something that can be fixed.

**Comment by dmex** [comment]
> "The specified procedure could not be found"

dbghelp.dll has a dependency on dbgcore.dll which is probably missing?

**Comment by VictorVG** [comment]
For sure! How did I miss it?

**Comment by VictorVG** [comment]
@dmex 

HUGE THANKS! Then I try copy dbghelp.dll and dbgcore.dll version 10.0.17763.1 form compiler  this problems is resolved - dump is work w/o AV. 

For some reason, it didn’t occur to me to have a hidden dependency on dbghelp.dll - in the ./imports section, the copy of the DLL I had had links only to kernel32.dll and msvcrt.dll and I was sure that all the dependencies it needed were in place , but just in it and there was AV. Well, on the network, I will replace it with a script in no time, and on the githaba I will now make an adjustment.

Once again, HUGE THANKS!
