### ISSUE TITLE
Get back old tray icon behavior (historical chart)

### ISSUE THREAD

**Issue by zvirja** [processhacker/processhacker#367]
Previously the tray icon showed the historical information:
![image](https://user-images.githubusercontent.com/1074182/51791315-50c43d00-21a1-11e9-8f2b-424aa7eda559.png)

But new versions of Process Hacker show the "current" information:
![image](https://user-images.githubusercontent.com/1074182/51791319-73565600-21a1-11e9-843a-5605bb17a81f.png)

I got used to the previous behavior and would like to still have it. Is there any setting to toggle to switch to the previous icon behavior?

Thanks for the great project you are doing!

**Comment by RanHum** [comment]
You just need to select "history" instead of "usage" tray icons
![default](https://user-images.githubusercontent.com/11231107/51791420-84fd2500-21c4-11e9-9cca-1232f10a8171.png)

**Comment by zvirja** [comment]
@RanHum Thanks for the fast reply! Glad that solution was so simple 😊
