### ISSUE TITLE
Themes support. Bugs

### ISSUE THREAD

**Issue by AHOHNMYC** [processhacker/processhacker#368]
Hello, I found some bugs in themes support (I know, it's experimental, but we are born to experiment with code, isn't it? :smile_cat: )
- [x] If Menu bar is hidden, through settings, it doesn't appear after pressing Alt nor F10 key
- [x] Filter doesn't work
- [x] Ctrl+K doesn't bring focus to filter bar

**Comment by Aidolii** [comment]
The filter is functional, but very finicky. If you put something in right after process hacker launches, it should work, but it'll get stuck later and you'll have to relaunch the program again.

**Comment by ImportTaste** [comment]
@dmex Could the erratic filter behavior please be fixed? I rely on the filter a lot, but I also don't like my eyes hurting.

**Comment by dmex** [comment]
These issues were fixed a while ago but the ticket wasn't updated 👍
