### ISSUE TITLE
ProcessHacker/srvprv.c PhpServiceNonPollThreadStart, OpenService result handle ignored

### ISSUE THREAD

**Issue by hfiref0x** [processhacker/processhacker#369]
The result of OpenService not assigned to any variable.

https://github.com/processhacker/processhacker/blob/d211b278e3ec4cc50a3e9555d8b5a3587981364b/ProcessHacker/srvprv.c#L1224-L1230

**Comment by dmex** [comment]
Good catch. Thanks for reporting the bug 👍
