### ISSUE TITLE
ProcessHacker/sysinfo.c, PhSipGraphHookWndProc, "then" and "else" statements are equal

### ISSUE THREAD

**Issue by hfiref0x** [processhacker/processhacker#370]
The "then" and "else" statements are equal in PhSipGraphHookWndProc. It could be misprint.

https://github.com/processhacker/processhacker/blob/0c9083c12f245c01400392fa86bca7a9b9aa32f3/ProcessHacker/sysinfo.c#L2043-L2050

**Comment by dmex** [comment]
This change was added in commit f3c8ebd3 on 13/11/2011 by @wj32 

The value should never be false in either statement and is somewhat correct 👍
