### ISSUE TITLE
RtlCreateUserProcessEx

### ISSUE THREAD

**Issue by tesla707** [processhacker/processhacker#373]
Hello!
Why in the source code there is no function prototype RtlCreateUserProcessEx?
```
NTSYSAPI
NTSTATUS
NTAPI
RtlCreateUserProcessEx(
    _In_ PUNICODE_STRING NtImagePathName,
    _In_ PRTL_USER_PROCESS_PARAMETERS ProcessParameters,
    _In_ BOOLEAN InheritHandles,
    _Reserved_ ULONG Flags,
    _Out_ PRTL_USER_PROCESS_INFORMATION ProcessInformation
);
```

**Comment by dmex** [comment]
You can't use it without CSRSS support so there wasn't much point including it?

**Comment by dmex** [comment]
> csrss notification happens during the creation process

Can you use it with processhacker.exe?

**Comment by tesla707** [comment]
> Can you use it with processhacker.exe?

By half. The program window starts, some menu bar functionality works. But the data is not drawn in window. I think this is related to specific api, since other programs quietly start after NtResumeThread.
