### ISSUE TITLE
Is there any possibility to add ARM64 support?

### ISSUE THREAD

**Issue by spainnoobperez** [processhacker/processhacker#376]

**Comment by dmex** [comment]
XDA ported Process Hacker to ARM some years ago:
https://forum.xda-developers.com/showthread.php?t=2179754

The only reason why the official builds don't support ARM is the lack of hardware (or at least someone who can submit patches).

**Comment by MagicAndre1981** [comment]
@dmex any update on this? I have deployed ARM64 Win10 1909 to my Lumia 950XL and would like to use ProcessHacker

**Comment by Biswa96** [comment]
It is possible to cross-compile in Visual Studio with MSVC. But the project files and solution files need to be modified to add ARM64 (AArch64) and ARM (AArch32) configurations and solution platforms. Also someone has to test it.

**Comment by Biswa96** [comment]
It is possible to cross-compile in Visual Studio with MSVC. But the project files and solution files need to be modified to add ARM64 (AArch64) and ARM (AArch32) configurations and solution platforms. This video may help https://www.youtube.com/watch?v=OZtVBDeVqCE.

The source code need heavy change. For example, there are some SSE X86_64 C wrappers used in phlib (`basesup.c` file). Some NT structures are hugely differs between AMD64 and ARM64 (maybe I've seen those in Mr. Alex Ionescu's blog).

**Comment by MagicAndre1981** [comment]
@Biswa96 do you want to start working on it and create a PR?

**Comment by Biswa96** [comment]
The only problem that I am not fluent in ARM assembly language and the ntoskrnl world.

**Comment by Biswa96** [comment]
The only problem that I am not fluent in ARM assembly language and the ntoskrnl world 😭

**Comment by Biswa96** [comment]
KProcessHacker driver compiles without any significant changes. Here are the list of failure of compilation in Visual Studio with ARM64 configuration:

1. phlib -- basesup.c -- PhCountStringZ -- due to usage of SSE.
2. phlib -- symprv.c -- PhpLookupFunctionEntry -- `EndAddress` absent in `_IMAGE_ARM64_RUNTIME_FUNCTION_ENTRY`.
3. phlib -- symprv.c -- PhWalkThreadStack -- `Rip` absent in `_CONTEXT`.
4. peview -- pdb.c -- `_malloca` and `_freea` absent.

**Comment by Biswa96** [comment]
Questions:

* Is there any usermode test (only C) I can do to check if the kernel mode driver loaded successfully?
* Does the kernel mode driver depend on any driver other than ksecdd driver? i.e. does it load other driver dynamically (kmode alternative of LoadLibrary)?

**Comment by dmex** [comment]
> Is there any usermode test (only C) I can do to check if the kernel mode driver loaded successfully?

The EnumDeviceDrivers function can check if the module was loaded. See this example:
https://docs.microsoft.com/en-us/windows/win32/psapi/enumerating-all-device-drivers-in-the-system

> Does the kernel mode driver depend on any driver other than ksecdd driver?

No

**Comment by Biswa96** [comment]
Here is my test case. I have Raspberry Pi 4B. I have booted Windows 10 ARM64 PE using EDK2 firmware and install kprocesshacker driver with `sc create` (test signing mode enabled). It is shown in `EnumDeviceDrivers()` as you have provided. If this peculiar environment sems to be somewhat similar with normal 500$ Windows 10 ARM laptops then I can do a PR.

**Comment by Biswa96** [comment]
Here is my test case. I have Raspberry Pi 4B. I have booted Windows 10 ARM64 PE using EDK2 firmware and install kprocesshacker driver with `sc create` (test signing mode enabled). It is shown in `EnumDeviceDrivers()` as you have provided. If this peculiar environment seems to be somewhat similar with normal 500$ Windows 10 ARM laptops then I can do a PR.

**Comment by MagicAndre1981** [comment]
@Biswa96 do you have test builds? I can test it on WIn10 1909 ARM64 on my Lumia 950XL

**Comment by Biswa96** [comment]
I have only loaded the kernel driver. I am afraid to provide any kernel mode binary. If you have latest Windows 10 and Visual Studio 2019 you can see my forked repo and the 2nd branch.

**Comment by Biswa96** [comment]
Here is a release mode build [kprocesshacker.sys.txt](https://github.com/processhacker/processhacker/files/4232469/kprocesshacker.sys.txt). Remove the .txt extension. You've to enable testsigning and nointegritychecks in bcdedit. Then add the driver as a service. For example:

```cmd
bcdedit.exe /set {default} nointegritychecks on
bcdedit.exe /set {default} testsigning on
:: Restart PC here
sc create kph binPath= "path\to\kprocesshacker.sys" type= kernel
sc query kph
```

**Comment by MagicAndre1981** [comment]
This test driver works on my 950XL:

 `sc query kph` shows running:

```
C:\Windows\system32>sc query kph

SERVICE_NAME: kph
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>
```

**Comment by Biswa96** [comment]
Will the X86 version of ProcessHacker work with ARM64 version of the driver? I am think about it like this -- Download the X86 version of processhacker ZIP file, extract it, remove the driver (sys file) in that folder, register the ARM64 driver as `kprocesshacker3` service, run the X86 ProcessHacker GUI as admin. 

The ARM64 WinPE that I'm using in Raspberry Pi4 doesn't have the X86 emulation layer.

**Comment by MagicAndre1981** [comment]
x86 processhacker doesn't start at all.

**Comment by Biswa96** [comment]
@dmex Is it possible to include `malloc.h` in pdb.c and notifico.c file for `_malloca` and `_freea`? The ARM64 config does not get the function declaration without that header file.

**Comment by Biswa96** [comment]
The `phlib-test` project can not be compiled. Errors -- The referenced project '..\..\phlib\phlib.vcxproj' does not exist. Cannot open include file: 'ph.h'.

**Comment by dmex** [comment]
@Biswa96 

phlib-test should be fixed 👍

**Comment by Biswa96** [comment]
The X64 platform is missing.

**Comment by Biswa96** [comment]
The X64 platform is missing. Could you add the X64 platform in phlib-test project? When I tried to copy the config from Win32 platform msbuild searches the phlib.lib file in Debug32 folder instead of Debug64.

**Comment by dmex** [comment]
@Biswa96 

I've added the x64 solutions. You'll have to ignore some asserts from UTF16 string length checks - they were incorrectly using UTF8 null terminators instead of UTF16 terminators and have the wrong lengths by 1 character.

**Comment by Biswa96** [comment]
Now this error is shown:

```
LINK : fatal error LNK1181: cannot open input file 'F:\processhacker\phlib\bin\Debug32\phlib.lib'
```

**Comment by Biswa96** [comment]
Now this error is shown with X64 debug, using VS 2019:

```
LINK : fatal error LNK1181: cannot open input file 'F:\processhacker\phlib\bin\Debug32\phlib.lib'
```

**Comment by dmex** [comment]
@Biswa96 

The linker tries to open both libraries and you'll need to build the 32bit processhacker.sln to fix the issue. I have no idea why but it does need both libraries present.

**Comment by Biswa96** [comment]
Is it possible to add a C alternative of PhFindCharInStringRef and PhFindLastCharInStringRef functions without Intel intrinsic? i.e. `PhpVectorLevel < PH_VECTOR_LEVEL_SSE2`

**Comment by Biswa96** [comment]
With the recent PR, peview works. But processhacker window opens with WerFault.

**Comment by Biswa96** [comment]
ProcessHacker and peview now works in ARM64 Windows 10. See my fork where the binaries can be downloaded from CI build.

**Comment by Biswa96** [comment]
Temporary link to download arm64 builds https://ci.appveyor.com/project/Biswa96/processhacker/build/artifacts

**Comment by Biswa96** [comment]
@MagicAndre1981 Could you check if the symbols tab in peview works?

**Comment by MagicAndre1981** [comment]
yes, both exe work fine. Great to have PH running as 64 Bit app  😍

![Screenshot (1)](https://user-images.githubusercontent.com/8274816/76888997-1c1fb300-6885-11ea-8205-61bead10e156.png)

![Screenshot (2)](https://user-images.githubusercontent.com/8274816/76888998-1d50e000-6885-11ea-9028-4e559ae2b012.png)

![Screenshot (3)](https://user-images.githubusercontent.com/8274816/76889494-f941ce80-6885-11ea-808d-86fd1786b762.png)

**Comment by ge0rdi** [comment]
@dmex 
Is there any plan to add ARM64 support to build scripts?
So that it is possible to easily create whole package for ARM64.

I can have a look at it.
If you are willing to do that direction.

I can also do some testing on ARM64 devices (I have Surface Pro X at hand).

**Comment by Biswa96** [comment]
I have been using these commands to build everything in ProcessHacker:

```cmd
call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64_arm64
msbuild KProcessHacker\KProcessHacker.sln -property:Configuration=Debug -property:Platform=ARM64 -verbosity:minimal
msbuild ProcessHacker.sln -property:Configuration=Debug -property:Platform=ARM64 -verbosity:minimal
mkdir sdk\lib\arm64
copy bin\DebugARM64\ProcessHacker.lib sdk\lib\arm64
msbuild plugins\Plugins.sln -property:Configuration=Debug -property:Platform=ARM64 -verbosity:minimal
```

Some catches:

* The 3rd and 4th commands are handled by tools/CustomBuildTool but it doesn't support ARM64 platform.
* The "ExtendedTools" plugin crashed with 0xC06D007F error in my WinPE ARM64 in qemu.
* The KprocessHacker driver need to be signed to work properly.

**Comment by ge0rdi** [comment]
@Biswa96 
Thank you. I know how to build ProcessHacker.
I just wanted to offer working on kind of official build support (in CustomBuildTools and scripts).

> The "ExtendedTools" plugin crashed with 0xC06D007F error in my WinPE ARM64 in qemu.

It seems to be working fine on Surface X device. I can see GPU/disk/network graphs.

> The KprocessHacker driver need to be signed to work properly.

Yup. For now I have testsigning enabled on device.
Driver seems to be working just fine.

**Comment by MagicAndre1981** [comment]
> Yup. For now I have testsigning enabled on device.
> Driver seems to be working just fine.

yes, driver also works for Lumia 950XL. I could also try the plugins. Is the ARM64 configuration already added for plugins?

**Comment by ge0rdi** [comment]
@MagicAndre1981 
Yes.
Just open `Plugins.sln` in VS, pick `ARM64` platform and rebuild whole solution.

Plugins seems to work without any issue for me.

**Comment by MagicAndre1981** [comment]
doesn't work for me. I always get this message :

`LINK : fatal error LNK1104: cannot open file 'ProcessHacker.lib'`

Win32 and x64 compile fine.  I first opened ph sln and build it for all configurations.

**Comment by Biswa96** [comment]
See my previous comment. Run the mkdir and copy command before compiling the plugins. This step is done by CustomBuildTool but ARM64 is not added there. I am not well versed in C#.

**Comment by MagicAndre1981** [comment]
ok, this is easy, in Build.cs add 2 lines:

https://github.com/processhacker/processhacker/blob/master/tools/CustomBuildTool/Build.cs#L82 add here arm64

and here copy the lib

https://github.com/processhacker/processhacker/blob/master/tools/CustomBuildTool/Build.cs#L492

**Comment by ge0rdi** [comment]
@Biswa96 @MagicAndre1981 
See PR #635.

**Comment by Biswa96** [comment]
The patch works and looks good to me. Though the patch focuses on the sdk option, I thought it would be better if arm64 platform is added as a whole in CustomBuildTool which also creates zip files and artifacts in appveyor. Maybe it is in dmex's area.

**Comment by ge0rdi** [comment]
> I thought it would be better if arm64 platform is added as a whole in CustomBuildTool which also creates zip files and artifacts in appveyor

This is what I was trying to ask @dmex here. Whether he wants to go that direction or what are his plans regarding ARM64.
I'd like to work on that if it is desired.

**Comment by MagicAndre1981** [comment]
@Biswa96 

here is now a way to get Windows 10 ARM64 running on Pi4 via USB 3.0 boot:

https://rpi4-uefi.dev/alternate-guide-running-windows-10-on-the-pi-4/

**Comment by Biswa96** [comment]
I know, have done it 4 days ago. Also tested many projects, will test many.

**Comment by joaomoreno** [comment]
Looking forward to this.

**Comment by Biswa96** [comment]
ARM64 platform is added to plugins-extra repository also.

**Comment by dmex** [comment]
> I have been using these commands to build everything in ProcessHacker

I've added the build script: https://github.com/processhacker/processhacker/commit/280fd94feb0486b4ccd11bce8ab0267468a02292  👍

**Comment by MagicAndre1981** [comment]
@dmex can you add ARM64 to nightly build?

**Comment by Biswa96** [comment]
I thought something will be added to CustomBuildTools so that the result will be seamless with other builds. Also the script doesn't handle release mode.

**Comment by paulstelian97** [comment]
Adding comment to be notified of the progress. I've got an Allview Allbook Q notebook with Snapdragon 835 so having an ARM64 port of Process Hacker (which actually works correctly -- the x86 port reports higher CPU usage than Task Manager does) would definitely be nice.

**Comment by MagicAndre1981** [comment]
> I've added the build script: [280fd94](https://github.com/processhacker/processhacker/commit/280fd94feb0486b4ccd11bce8ab0267468a02292) 👍

I get this error during build:

```
E:\processhacker\plugins\ToolStatus\taskbar.c(401,31): error C2220: the following warning is treated as an error [E:\processhacker\plugins\ToolStatus\ToolStatus.vcxproj]
E:\processhacker\plugins\ToolStatus\taskbar.c(401,31): warning C4013: '_malloca' undefined; assuming extern returning int [E:\processhacker\plugins\ToolStatus\ToolStatus.vcxproj]
E:\processhacker\plugins\ToolStatus\taskbar.c(401,61): warning C4047: '=': 'PFLOAT' differs in levels of indirection from 'int' [E:\processhacker\plugins\ToolStatus\ToolStatus.vcxproj]
E:\processhacker\plugins\ToolStatus\taskbar.c(422,11): warning C4013: '_freea' undefined; assuming extern returning int [E:\processhacker\plugins\ToolStatus\ToolStatus.vcxproj]
E:\processhacker\plugins\ToolStatus\taskbar.c(460,61): warning C4047: '=': 'PFLOAT' differs in levels of indirection from 'int' [E:\processhacker\plugins\ToolStatus\ToolStatus.vcxproj]
```

VS2019 16.8.3 /19041 SDK/WDK

**Comment by dmex** [comment]
@MagicAndre1981 

Add `#include <malloc.h>` into the \ToolStatus\taskbar.c header.

 I fixed this last week but haven't pushed it live yet.

**Comment by MagicAndre1981** [comment]
> I fixed this last week but haven't pushed it live yet.

works, I also [found the docs right now](https://docs.microsoft.com/en-US/cpp/c-runtime-library/reference/malloca?view=msvc-160#requirements)

In Sysinfo->GPU I get a assert when I click on details:

![image](https://user-images.githubusercontent.com/8274816/102989733-6883d780-4516-11eb-9f3e-8506dadfb8ca.png)

**Comment by MagicAndre1981** [comment]
Btw, the [Windows on ARM project](https://github.com/WOA-Project/Lumia-Drivers) now supports the [Lumia Dock ](https://en.wikipedia.org/wiki/Microsoft_Display_Dock), so you can add a monitor and extend the desktop. So if anyone has the old things, you can use to play with ARM64 version of Windows 10

**Comment by dmex** [comment]
@MagicAndre1981 

> In Sysinfo->GPU I get a assert when I click on details:

I'll need the stacktrace to know what caused that issue. There are more than 100,000 calls to that function which could have triggered that assert.

**Comment by MagicAndre1981** [comment]
> I'll need the stacktrace to know what caused that issue. There are more than 100,000 calls to that function which could have triggered that assert.

I struggle with the remote debugging. ph exe gets copied to the lumia, but not the plugin.

**Comment by dmex** [comment]
I'm closing this issue since the project is supported and compiles with ARM64... If there are issues/assertions running ARM64 builds then please create a new issue 👍 

-----------

@MagicAndre1981 
That issue will be fixed in the latest nightly.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981
> That issue will be fixed in the latest nightly.

ok, but please release the ARM64 as nightly. I want to remove the C++ workload to save space in my VM

**Comment by dmex** [comment]
> release the ARM64 as nightly

I don't have any ARM hardware and if something breaks it won't get fixed for days/weeks.

**Comment by MagicAndre1981** [comment]
> I don't have any ARM hardware and if something breaks it won't get fixed for days/weeks.

I'm using my old Lumia 950XL and run Win10 ARM64, you can try a Raspberry Pi 4 if you have one.

**Comment by paulstelian97** [comment]
If you want, I can (not very regularly, to be fair) test ARM64 releases myself (not enough time after my normal job to actually contribute though). Allview Allbook Q (SD835).

**Comment by MagicAndre1981** [comment]
ok, now it gets complicated @dmex  . 

You can now run x64 software on Windows 11 ARM64, so your [_ARM64_](https://github.com/processhacker/processhacker/blob/d4b4d9e081c4ac6adb7eb15732afb691a74417df/ProcessHacker/syssccpu.c#L1199) hacks fail.

I see now Virtual CPU@2.00GHz on my Raspi4 when running the x64 version because it is not the ARM64 build so it executes the cpuid command

![image](https://user-images.githubusercontent.com/8274816/130322103-2f566b33-aa7b-4621-8b6c-ce9b017c90c9.png)

So maybe it is better to check the cpu architecture at runtime

**Comment by dmex** [comment]
> when running the x64 version because it is not the ARM64 build
> maybe it is better to check the cpu architecture at runtime

You could also use the ARM build when running on ARM where the emulation won't be a problem?

**Comment by MagicAndre1981** [comment]
> You could also use the ARM build when running on ARM where the emulation won't be a problem?

as I said, I no longer install the C++ workload to save space in my VMs so I can't recompile it. And I only do what endusers do, download and run your last nightly

**Comment by Biswa96** [comment]
The build procedure changed a lot. I think the CustomBuildTool need to add something for ARM64. The phapppub.h and other sdk headers are not copied automatically to build tools.

**Comment by dmex** [comment]
@Biswa96 

Use the `\build\build_arm64.cmd` script... That script will compile the project and plugins with ARM versions. CustomBuildTool itself has never supported ARM.

There are also hundreds of places throughout the entire project which assume either System32 or Syswow64 which are not correct for ARM processes and require support for RtlReplaceSystemDirectoryInPath so even after building the project a lot of information won't be correct.

**Comment by DavidXanatos** [comment]
I just got a PI4 and need a good task manager for it :D so I may need to look into porting as much as I can.
For example i don't see yet a good way to distinguish x64 from ARM64EC processes when querying SystemSupportedProcessorArchitectures2 they look exactly the same,
mut M$'s task manager can tel them apart, I wonder how... may be reading PEB fields like ChpeV2ProcessInfo in wonder...

**Comment by Biswa96** [comment]
It is possible https://github.com/msys2/MINGW-packages/discussions/8991

**Comment by dmex** [comment]
> mut M$'s task manager can tel them apart, I wonder how

It's just using IsWow64Process2 @DavidXanatos 
https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2

>  don't see yet a good way to distinguish x64 from ARM64EC processes

It should be returning IMAGE_FILE_MACHINE_CHPE_X86 (not included in the SDK but rather the WDK ntimage.h)?

**Comment by DavidXanatos** [comment]
On my raspi 4
for a x64 process it returns 
ProcessMachine: 0x0000
NativeMachine: 0xaa64
same for ARM64EC and ARM64

IsWow64Process2 seams to work only for 32 bit processes

**Comment by DavidXanatos** [comment]
To me this decisively looks like x64 on arm64 is not longer WOW but a different interoperability mechanism.
Also there is no \Syswow6464 or something folder for x64 and no registry redirection eider.

See:
´´´
NtQuerySystemInformationEx(SystemSupportedProcessorArchitectures2, &handle, sizeof(handle), info, sizeof(info), &length);
	
	
x86 on Arm64:
Machine: ARM64;       KernelMode: 1; UserMode: 1; Native: 1; Process: 0; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 1; WoW64Container: 1
Machine: ARM-Thumb-2; KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: x64;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 0

x64 on Arm64:
Machine: ARM64;       KernelMode: 1; UserMode: 1; Native: 1; Process: 0; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: ARM-Thumb-2; KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: x64;         KernelMode: 0; UserMode: 1; Native: 0; Process: 1; WoW64Container: 0

Arm64EC on Arm64:
Machine: ARM64;       KernelMode: 1; UserMode: 1; Native: 1; Process: 0; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: ARM-Thumb-2; KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: x64;         KernelMode: 0; UserMode: 1; Native: 0; Process: 1; WoW64Container: 0

Arm64:
Machine: ARM64;       KernelMode: 1; UserMode: 1; Native: 1; Process: 1; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: ARM-Thumb-2; KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: x64;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 0

Arm on Arm64:
Machine: ARM64;       KernelMode: 1; UserMode: 1; Native: 1; Process: 0; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 1
Machine: ARM-Thumb-2; KernelMode: 0; UserMode: 1; Native: 0; Process: 1; WoW64Container: 1
Machine: x64;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 0



x64 on x64:
Machine: x64;         KernelMode: 1; UserMode: 1; Native: 1; Process: 1; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 0; WoW64Container: 0

x86 on x64:
Machine: x64;         KernelMode: 1; UserMode: 1; Native: 1; Process: 0; WoW64Container: 0
Machine: x86;         KernelMode: 0; UserMode: 1; Native: 0; Process: 1; WoW64Container: 0

´´´

**Comment by Biswa96** [comment]
compiler error in arm64 build

```
processhacker\ProcessHacker\syssccpu.c(1685,12): error C2220: the following warning is treated as an error
processhacker\ProcessHacker\syssccpu.c(1685,12): warning C4013: 'CpuIdEx' undefined; assuming extern returning int
```
