### ISSUE TITLE
v3.0.2173 ( Git 2fa2fe0b) error C2039 and error C2198

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#378]
Version: 3.0.2173 (2fa2fe0b) [master]

[00:00] Building ProcessHacker (x32) ...
[ERROR] tools\peview\exlfimports.c (51): error C2039: SectionIndex: not a member of "_PH_ELF_IMAGE_SYMBOL_ENTRY" [tools\peview\peview.vcxproj]
tools\peview\exlfimports.c (51): error C2198: PvpGetSymbolSectionName: too few arguments to call [tools\peview\peview.vcxproj]
tools\peview\exlfexports.c (55): error C2039: SectionIndex: not a member of "_PH_ELF_IMAGE_SYMBOL_ENTRY" [tools\peview\peview.vcxproj]
tools\peview\exlfexports.c (55): error C2198: PvpGetSymbolSectionName: too few arguments to call [tools\peview\peview.vcxproj]

Possible needed addition define for this entry?

**Comment by dmex** [comment]
@VictorVG 

Why do you create an issue for every build error? I've told you before that we get notified by Appveyor automatically: https://ci.appveyor.com/project/processhacker/processhacker/builds/22254235

You're just spamming my inbox with useless junk. Stop creating bug reports for build errors.

**Comment by VictorVG** [comment]
Sorry...
