### ISSUE TITLE
AV in to Updater.dll if window "Show*VersionDialog" focused and user press some KBD keys

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#379]
v3.0.6707.2180 Git-2a478755, v3.0.6710.2183 Git-faf40f07

101/102 and 105/106 keys QWERTY keyboard, OS Win7 SP1, Win10 (Ctrl confirmed **KLASS** failed when pressing Ctrl)

If the displayed Updater.dll "_Process Hacker - Updater_" window with one of the dialogs .\src\plugins\Updater\page5.c::208 "_ShowLatestVersionDialog_" or .\src\plugins\Updater\page5.c::244 "_ShowNewerVersionDialog_" is in focus, and user pressing any key _LCtrl, RCtrl, LWin, RWin, Apps,", ",". ", Del, Ins, PgUp, PgDwn, Pause/Break, Backspace, CapsLock, Scroll Lock," - ", "+", "M", "?", NumLock_ regardless of its state, or when _NumLock = Off_, and user pressing any key _NumIns, NumDel, NumPgUp, NumPgDwp_in Updater.dll fails with code 0xC000005 (Access Violation) and an display error dialog with buttons "_Minidump_ | _Restart_ | _Close_".

**P.S.**

_We had previously observed this phenomenon, but we could not identify it because the key-press event that had caused it had already ended._

**Comment by VictorVG** [comment]
Control test with unpacking processhacker-build-bin.zip Nightly Builds v3.0.6719.2192, OS Windows 7 SP x64, 4 Gb of RAM, drivers instaled only for  Intel P45 chipset, Realtec ALC888 HD Audio, NVIDIA GTX 550 Ti. The test copy was launched through the shell (Explorer).

ProcessHacker_BQAZLGPZRPEFYWP_DumpFile.dmp
ProcessHacker_ECMRYLASLAYLWPS_DumpFile.dmp
ProcessHacker_SPSSSVFQVIRJLZC_DumpFile.dmp
ProcessHacker_USHQFUGMHGCRCDT_DumpFile.dmp

Dumps obtained by checking Ctrl, left Win, "+", right Win
 attachment - [**minDumps.zip**](https://github.com/processhacker/processhacker/files/2861303/minDumps.zip)

**Comment by pasha-zzz** [comment]
Process Hacker 2192 x64 (official installer), Updater.dll only.

![image](https://user-images.githubusercontent.com/8224786/52729879-1cd37f00-2fcb-11e9-893a-f94fb3a50c18.png)

![image](https://user-images.githubusercontent.com/8224786/52729939-412f5b80-2fcb-11e9-8a84-b89a96ffb70a.png)

![image](https://user-images.githubusercontent.com/8224786/52730058-8ce20500-2fcb-11e9-8117-abfda2d13cdf.png)

**Comment by Pulgovisk** [comment]
In my machine, PH only crashes when i press some modifier key, like *ctrl* and *alt*

**Comment by dmex** [comment]
It's a comctl32.dll bug with the TaskDialogIndirect API which is triggered by sending the TDM_NAVIGATE_PAGE message from a non-gui thread to the main gui thread message loop for the dialog.

![image](https://user-images.githubusercontent.com/1306177/52732901-a2523180-2fc1-11e9-82a6-4af1f5dc7f9d.png)

**Comment by VictorVG** [comment]
Big thanks! Fixed. I test all key then list: LCtrl, RCtrl, LWin, RWin, Apps,", ",". ", Del, Ins, PgUp, PgDwn, Pause/Break, Backspace, CapsLock, Scroll Lock," - ", "+", "M", "?", NumLock regardless of its state, or when NumLock = Off, and user pressing any key _NumIns, NumDel, NumPgUp, NumPgDwp- Updater not crashed.
