### ISSUE TITLE
Properties windows for drivers and services are blank

### ISSUE THREAD

**Issue by xyx0826** [processhacker/processhacker#380]
**Windows version:** since build 17763 (up to 18836 so far)
**Process Hacker version:** since unknown (up to 3.0.2162 so far)
**Reproductible with no plugins enabled**
**Reproductible with user permission or administrator permission**

When opening the Properties window of an entry in the **Services** tab, nothing will actually show up. A "ghost window" is instead showed in the taskbar with Process Hacker main window. Properties for **Processes** work well.

**Comment by dmex** [comment]
Have you tried running services.msc and opening the properties for a service? Does it also have issues showing the properties for services?

**Comment by xyx0826** [comment]
No, services.msc has no issues.

**Comment by dmex** [comment]
Do you have the same issue with **v2.39** from the releases page?
https://github.com/processhacker/processhacker/releases

**Comment by xyx0826** [comment]
No. I did a clean install, and this version (2.39.124) does not have the issue.

**Comment by xyx0826** [comment]
Looks like the latest nightly 744b5f88 no longer have this issue. Closing this issue.
