### ISSUE TITLE
ChangeLog - "You are here" mark

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#384]
![image](https://user-images.githubusercontent.com/8224786/53713153-dc914f00-3e5a-11e9-89e2-80501b4f1963.png)
![image](https://user-images.githubusercontent.com/8224786/53713186-fdf23b00-3e5a-11e9-84e0-993987dccc45.png)
We cant see current position.
Add something like additional line ======= you are here =======, or other delimiter, or difference by color/boldness of new and old changes, or collapsed with + old changes by default.

**Comment by hjafari-could** [comment]
> ![image](https://user-images.githubusercontent.com/8224786/53713153-dc914f00-3e5a-11e9-89e2-80501b4f1963.png)
> ![image](https://user-images.githubusercontent.com/8224786/53713186-fdf23b00-3e5a-11e9-84e0-993987dccc45.png)
> We cant see current position.
> Add something like additional line ======= you are here =======, or other delimiter, or difference by color/boldness of new and old changes, or collapsed with + old changes by default.

**Comment by dmex** [comment]
This was added in the latest nightly build 👍
