### ISSUE TITLE
Memory private pages accuracy

### ISSUE THREAD

**Issue by giampaolo** [processhacker/processhacker#385]
Hello. I bumped into this:
https://dxr.mozilla.org/mozilla-central/source/xpcom/base/nsMemoryReporterManager.cpp#589-592

```c
  size_t privatePages = 0;
  for (size_t i = 0; i < entries; i++) {
    // Count shared pages that only one process is using as private.
    if (!infoArray->WorkingSetInfo[i].Shared ||
        infoArray->WorkingSetInfo[i].ShareCount <= 1) {
      privatePages++;
    }
```
I noticed that ProcessHacker calculates that value differently:
https://github.com/processhacker/processhacker/blob/a39d0f312c863ccb1c4ed927bfcd8eedac1b5fd7/phlib/native.c#L1304-L1309

What I think Firefox is aiming at is calculating the process USS (Unique Set Size), that is the memory which is unique to a process and which would be freed if the process was terminated right now. Hence why I'm not sure if I'm comparing apples and oranges here.

**Comment by dmex** [comment]
> comparing apples and oranges

Firefox is counting the same value but using an unnecessary method.

**Comment by giampaolo** [comment]
Actually the 2 values differ.

**Comment by dmex** [comment]
@giampaolo 

The private pages counted by PH equal the same values from Task Manager and Process Explorer so I would suggest Firefox is doing it wrong.
