### ISSUE TITLE
Process Explorer Crash/Minidump +questions

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#386]
Due to "some issue" [1], Process Explorer crashed, and gave me the "Minidump / Something / SomethingElse" option. First things first, here is the dump: [ProcessHacker_JRQRWJGUSVNWUNV_DumpFile.zip](https://github.com/processhacker/processhacker/files/2949814/ProcessHacker_JRQRWJGUSVNWUNV_DumpFile.zip)

Additionally, couple of questions/suggestions (please split yourself as you'd wish):
* The minidump collection goes into Desktop correctly; however it does not follow a possible relocation. (This thing, no idea how it goes in English)
![image](https://user-images.githubusercontent.com/133706/54088792-56996a80-436a-11e9-97f7-6fd4057fc8e4.png)
~~I was happily suprised though, that the program somehow created the folder with icon and everything!~~ _(it didn't, for some reason the folder was left over from the relocation)_

* The window seems to suffer from the #200 issue (i.e. even though I've set PH on-top, "small windows" do not honor it). Can it also be fixed?
* Do you think that there could be `--kill` and `--(mini)dump` options, that would do these actions exactly? (Maybe also kill PH after creating the dumps).
The window was half-working at the time the error occured, which led me to believe that I needed to kill PH. Since I have set PH as TaskManager, that meant that I needed to go terminal-style, which I am not familiar on Windows at all. I am not sure if that would work, or if it would be nice to do it (or if it would hang my system etc etc). And I definitely don't know how to `minidump` or "normal" `dump` a process outside of PH.
-------
[1]:
* The error was 0xC000005 or "looked like"
* There was an enormous number of processes dieing and spawing from WSL (for reasons yet unknown - and possibly irrelevant (?))

**Comment by dmex** [comment]
> First things first, here is the dump: 

The dump doesn't match the nightly symbols so I can't do much. I can see you're using unoffical plugins from the plugins-extra repo and you should disable/remove/recompile those plugins because they're very likely the cause of the crash.

> The minidump collection goes into Desktop correctly; however it does not follow a possible relocation. 

The API doesn't use shell functions because it would cause shell extensions/hooks/third-party DLLs to be loaded into the process after a crash which would cause additional issues and this is also the same reason why there's no save file dialog.

I'll change the dump path to use the location of the settings file (current directory or \appdata\process hacker).

> The window seems to suffer from the #200 issue (i.e. even though I've set PH on-top, "small windows" do not honor it). Can it also be fixed?

The TaskDialogIndirect API does not support changing the topmost style without using a window hook. I'll have to add some tests to know if this would be reliable from the exception callback.

> Do you think that there could be --kill and --(mini)dump options

There are three buttons; Minidump, Restart and Close. The third option closes (kills?) the application.

> There was an enormous number of processes dieing and spawing from WSL (for reasons yet unknown - and possibly irrelevant (?))

Process Hacker launches wsl.exe (which launches dpkg/rpm on WSL) to query the version information for linux processes?

**Comment by stdedos** [comment]
> I can see you're using unoffical plugins from the plugins-extra repo and you should disable/remove/recompile those plugins because they're very likely the cause of the crash.

I have tried to update at some time, but PH turned unstable, so I decided to keep the old ones instead. However, I don't remember when "some time" was. I'll try to check when can I find a build machine to do that again sometime soon.

> I'll change the dump path to use the location of the settings file (current directory or \appdata\process hacker).

* If it requires additional hooks to do so, then ...
* If you could place it next to itself (i.e. the exe file), however it would be nice.
    However, you still might hit Access Rights, so ...

... please don't. Just make it available / searchable in some help that "find minidumps here:"

> The TaskDialogIndirect API does not support changing the topmost style without using a window hook. I'll have to add some tests to know if this would be reliable from the exception callback.

If possible, please do

> There are three buttons; Minidump, Restart and Close. The third option closes (kills?) the application.

I meant something that can be done without being "at the exception handling" window. Or in my case, if you've lost the dialog and cannot find it somehow :smile: 

> There was an enormous number of processes dieing and spawing from WSL (for reasons yet unknown - and possibly irrelevant (?))

Well ... it could be that, since a lot of them have shown PH as their parent. However, process list was like a christmas tree with all the Red and Green at the time. It could be that PH was contributing to the load, but I cannot safely say if it was solely responsible for this mess.
I was running `pytube >=9.4.0` which I think has added some multi-threaded behavior. I don't know if e.g. threads die and spawn like crazy

**Comment by stdedos** [comment]
> it would cause shell extensions/hooks/third-party DLLs to be loaded into the process during the exception callback 

I might be far-fetching here, but, isn't there a way to get a "sanitized", Microsoft-christened, pure hook, without any extra shenanigans? I guess exception handling would still be "serious", but, at least you'd be using momma-Microsoft approved stuff

**Comment by dmex** [comment]
> isn't there a way to get a "sanitized", Microsoft-christened, pure hook, without any extra shenanigans?

The save file dialog does this not the window hook.

**Comment by stdedos** [comment]
`3.0.2258 (47e8b396)` crashed again today, I pressed the Minidump button, but I cannot find the file nowhere.

**Comment by stdedos** [comment]
> It could be that PH was contributing to the load, but I cannot safely say if it was solely responsible for this mess. [1]

Filed https://github.com/processhacker/processhacker/issues/393, as now I had some kind of "replicatable" behavior

**Comment by stdedos** [comment]
Straight out of the oven! [ProcessHacker_WYTUBDBTFZXYDNT_DumpFile.zip](https://github.com/processhacker/processhacker/files/2976920/ProcessHacker_WYTUBDBTFZXYDNT_DumpFile.zip)

----
The offender seems to be `LiveDumpPlugin.dll` [LiveDumpPlugin.zip](https://github.com/processhacker/processhacker/files/2977023/LiveDumpPlugin.zip)
I don't know if I have the latest version or not, but I will try to compile them again at a later time. If I verify that `master` is still broken, I'll file a bug. Maybe something changed in "Tools" menu?

I found a very nicely replicating way of doing that.
* Press `Alt` to make the menu row appear
* Try to click or keyboard-navigate-activate to "View" or "Tools"

It could be that the "WSL mumbo-jumbo" might not be relevant to this, and indeed be a plugin gone rogue. Probably the resource-hogging made it appear, since I was trying to disable "Scroll to new processes".

---

Please run the windows-equivalent of unix `mkdir -p "C:\Users\{username}\` during MiniDump generation. I know it's a very weird corner case, but the call cannot hurt that much. The reason I wasn't getting minidumps was that I deleted the folder

**Comment by dmex** [comment]
> The offender seems to be LiveDumpPlugin.dll

I'm probably going to block non-standard plugins during an update.

**Comment by stdedos** [comment]
> > The offender seems to be LiveDumpPlugin.dll
> 
> I'm probably going to block non-standard plugins during an update.

Feel free to do whatever you think is best. However, you might want to build a versioning scheme. The old plugins could bind against version `<= 2`, and warn on `=> 3`

With semantic versioning scheme, that should solve the issues.

**Comment by dmex** [comment]
> The old plugins could bind against version <= 2, and warn on => 3

It would be "< buildnumber" and  every nightly update would show a warning. If the plugins-extra plugins had someone who could help with maintenance then it wouldn't be needed. 😉

**Comment by stdedos** [comment]
> > The old plugins could bind against version <= 2, and warn on => 3
> 
> It would be "< buildnumber" and every nightly update would show a warning. If the plugins-extra plugins had someone who could help with maintenance then it wouldn't be needed. 😉

😆 I am trying to convince myself to do some serious work in "some" of the open-source projects I am _abusing_ daily for my pleasure. Any minute now 😄
