### ISSUE TITLE
Feature Request: show orphan process at the ancestor branch for process tree

### ISSUE THREAD

**Issue by kltk** [processhacker/processhacker#389]

**Comment by Biswa96** [comment]
Just click on the 'name' column twice in 'Processes' tab.

**Comment by kltk** [comment]
> Just click on the 'name' column twice in 'Processes' tab.

root
├─ancestor
│  ├─parent
│  │  └─process
----
the process show in root when parent terminated, but i think show in ancestor is appropriate choice

**Comment by dmex** [comment]
> show orphan process

This would require storing information about terminated processes for long durations and would be considered/become a memory leak. You can press F6 to pause updating if you need the parent process information.
