### ISSUE TITLE
PE Viewer doesn't pickup on delay-loaded DLLs of certain binaries

### ISSUE THREAD

**Issue by UCyborg** [processhacker/processhacker#390]
One example is dinput.dll in [this patch archive](https://www.moddb.com/games/drakan-order-of-the-flame/downloads/drakan-aio-unofficial-patch). It was compiled with Microsoft Visual C++ 6.0, which was the first version to introduce /delayload linker option. No such problem with the old Dependency Walker.

**Comment by dmex** [comment]
> compiled with Microsoft Visual C++ 6.0, which was the first version to introduce /delayload linker option

6.0 was released in **1993**.

> One example is dinput.dll in this patch archive

That binary from that site was compiled in **2016**.


It doesn't contain any delay load sections that can be parsed by other tools?

![image](https://user-images.githubusercontent.com/1306177/54399681-e0756a80-46bf-11e9-85bb-06593e045817.png)

**Comment by UCyborg** [comment]
Forgot to mention, look at the dinput.dll in Drakan directory, not Drakan Demo directory, the one in the latter is older and doesn't have any delay-loaded dependencies.

Also, Microsoft Visual C++ 6.0 was released in 1998. The latest Service Pack (6) for it was released in 2004. That binary was produced with the version patched with Service Pack 5 because Processor Pack, which is needed for inline assembly support, is not available for SP6.

**Comment by dmex** [comment]
> Microsoft Visual C++ 6.0 was released in 1998

There's a few books from 1998 about support for delay loading imports. I couldn't find anything more recent showing how they were originally implemented 😄  

> Forgot to mention, look at the dinput.dll in Drakan directory, not Drakan Demo directory, 

Thanks, I've added support for legacy delay load imports and updated the nightly release 👍
