### ISSUE TITLE
Throttle/Cache WSL version info

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#393]
Coming from #386:

I am doing `apt-get upgrade` of ~168 packages. Process launches are too much maybe from the WSL side, and, along with PH version info fetching, and they seem to be chocking "fork throughput capabilities" of Windows [1]. Closing PH during the update stabilizes the system.

[1] it could be that Avast Behavior shield might be throttling responses etc, since it's one of the few times I've seen it at ~10%, which, in conjuction with PH spawns, amount to this behavior

[2] #386: [...] maybe PH could have a 1-minute cache of SHA-256 Hashes of WSL executables with their version struct?

**Comment by stdedos** [comment]
It seems that the process load is irrelevant. I have an user-idle WSL season active (just a bash shell with an ssh-agent, nothing else called explicitly by me), and the forking rate is too big. It could very much be e.g. `cron` spawing processes, but I guess it can get extremely annoying.

**Comment by Biswa96** [comment]
See this temporary workaround 
https://github.com/processhacker/processhacker/issues/153#issuecomment-462079170

**Comment by stdedos** [comment]
@dmex 
> https://github.com/processhacker/processhacker/issues/153#issuecomment-462079170:
> As a temporary workaround you can disable the Options > Check images for digital signatures option to disable querying WSL process versioninfo.

Since this is a WSL-specific thing, and the rest of if works nicely, can we have a "dedicated" workaround setting? I don't mind if it is an Advanced setting, I'd just prefer disabling it specifically for WSL, specifically because of #153 and this issue

----

_Disclaimer:_ In full honestly, I am not sure "how useful" is `Options > Check images for digital signatures` to me. It did sound useful in some scenario though, so I've had it on since forever

**Comment by dmex** [comment]
> maybe PH could have a 1-minute cache of SHA-256 Hashes of WSL executables

WSL version info is already cached for about 50 hours. The question is why your system has issues with dpkg?

> Avast Behavior shield might be throttling

Uninstalling Avast would probably solve all the issues you're having.

> can we have a "dedicated" workaround setting?

Yeah, I was going to add one soon. The only issue is that since Linux is text-based not object oriented you won't be able to see linux process memory/environment/handles since this can only be queried from within WSL by launching a process.

**Comment by stdedos** [comment]
> > maybe PH could have a 1-minute cache of SHA-256 Hashes of WSL executables
> 
> WSL version info is already cached for about 50 hours. The question is why your system has issues with dpkg?

Interesting. Any debugs you'd like to run by me, I'd take it

> > Avast Behavior shield might be throttling
> 
> Uninstalling Avast would probably solve all the issues you're having.

I keep thinking it more and more to be honest... I just don't know which "other" devil I'd like to take in after removing this one.

**Comment by dmex** [comment]
> Interesting. Any debugs you'd like to run by me, I'd take it

dpkg -S FILENAME 
dpkg -S /usr/sbin/apache2

this returns the package name for that executable/file (apache2-bin)

dpkg-query -W -f='${Version}|${Maintainer}|${binary:Summary}' PACKAGENAME
dpkg-query -W -f='${Version}|${Maintainer}|${binary:Summary}' apache2-bin

returns 

2.4.29-1ubuntu4.5|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>|Apache HTTP Server (modules and other binary 

This procedure should succeed for every binary in your distribution?

>  I just don't know which "other" devil I'd like to take in after removing this one.

I haven't used an AV product in 15 years since they're complete junk compared to built-in protections. Use deviceguard and virtual machines for your software: 
https://docs.microsoft.com/en-us/windows/security/threat-protection/device-guard/introduction-to-device-guard-virtualization-based-security-and-windows-defender-application-control

**Comment by stdedos** [comment]
I don't have `apache2`, let's try `python`?

```bash
# dpkg -S /usr/bin/python
python-minimal: /usr/bin/python
# dpkg-query -W -f='${Version}|${Maintainer}|${binary:Summary}' python-minimal
2.7.12-1~16.04|Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>|minimal subset of the Python language (default version)
```

If I can ask PH to list all its searches, I can try to check them manually. Otherwise, it seems working I guess.

**Comment by dmex** [comment]
> If I can ask PH to list all its searches

It does this for every linux process.

**Comment by dmex** [comment]
Added setting to disable WSL support in latest nightly 👍

**Comment by stdedos** [comment]
I have some idea now of why could that be.

I am using a terminal multiplexer (https://github.com/dustinkirkland/byobu /tmux), which, for some reason, keeps spawns processes in burst, ... which makes PH spawn a lot of  processes _too_

**Comment by dmex** [comment]
@stdedos 

>byobu which, for some reason, keeps spawns processes in burst

It seems to spawn around 8 processes after you select or click on the console window?

> which makes PH spawn a lot of processes too

The version information for binaries is cached and you should never see it more than once... I will probably include a linux process with PH at some point which handles all linux process information requests so you won't even see the one-time query.

**Comment by stdedos** [comment]
Something around that number, yes. It seems to be related with starting / interacting with the window, but, sometimes it "just does it".

However, there is this "weird thing" happening with settings: I've set the WSL setting to 0, multiple times today. However, even exactly at the time that PH has restarted ... the setting is somehow reset (along with the "Show advanced settings" option) 😕 

I have no idea how did I have a "sane" version to come up with my previous comment, but there is some erratic behavior.

_Side question: Have you considered adding a case-insensitive filtering value for the advanced flag list?_

**Comment by stdedos** [comment]
@dmex where is that setting hiding nowadays?
![image](https://user-images.githubusercontent.com/133706/76910005-82242e80-68b5-11ea-866b-c7f74d5e622e.png)

**Comment by dmex** [comment]
@stdedos 

The version information is already cached for all processes. Process Hacker only launches dpkg and rpm and does not launch dash so I don't think the constant launching of dash is related to Process Hacker.

You can try disabling the linux version information support by changing the EnableLinuxSubsystemSupport setting to 0 and seeing if dash is still launching.

**Comment by stdedos** [comment]
Forking done from `byobu/tmux` is _somewhat comparable_, but I think there's something more to it.

Thank you for the flag; it's really tedious to try to search them without any wildcat filtering possible at all.

**Comment by dmex** [comment]
> tedious to try to search them without any wildcat filtering

It'll be added eventually. It requires some major changes and I haven't had time yet handling other issues :(

> I think there's something more to it.

You might need to check the parent in /proc (I haven't added support for showing WSL parenting yet).

**Comment by Biswa96** [comment]
Something is coming `https://github.com/microsoft/WSL/issues/4997`.

<sub><sup>** The GitHub issue link is intentionally made as a code to prevent auto linking,</sup></sub>
