### ISSUE TITLE
Assert fires at FirewallMonitorPlugin!RemoveFwNode

### ISSUE THREAD

**Issue by OfekShilon** [processhacker/processhacker#394]
RefCount was -1. 
Dump and symbols are here: https://1drv.ms/f/s!AqHNPYTe0WxooAW8Ic233VCECcb4

This can be hard to track but easy to solve with some RAII.  Will you consider a PR that transforms the projects to c++?  The code might benefit substantially (e.g., many hundreds of manual PhDereferenceCalls will be gone)

**Comment by dmex** [comment]
FirewallMonitor lives over here: 
https://github.com/processhacker/plugins-extra/

> Will you consider a PR that transforms the projects to c++?

FirewallMonitor needs a maintainer and if it works then yes 👍
