### ISSUE TITLE
Checking mitigations from LdrSystemDllInitBlock is not working

### ISSUE THREAD

**Issue by TheEragon** [processhacker/processhacker#396]
[This](https://github.com/processhacker/processhacker/commit/43b707369638a84e41dc4bef5b50962d3951417d) change doesn't work properly on RS5 or 19H1 (I looked only at these two versions). Mitigations are encoded as two 64bit numbers, Map[0] stores _PROCESS\_CREATION\_MITIGATION\_POLICY\_\*_ values (this is true on RS5 and 19H1 at least) and Map[1] should in theory store _PROCESS\_CREATION\_MITIGATION\_POLICY2\_\*_ but this isn't entirely true, so there are two problems here.

First you check Map[0] for _PROCESS_CREATION_MITIGATION_POLICY2\_\*_ which isn't correct, but changing the index won't work since Map[1] stores _PROCESS_CREATION_MITIGATION_POLICY2\_\*_ but they are somehow remapped.

This can be checked with Chrome which doesn't [support](https://chromium.googlesource.com/chromium/src/+/refs/heads/lkgr/sandbox/win/src/process_mitigations.cc) _PROCESS\_CREATION\_MITIGATION\_POLICY2\_LOADER\_INTEGRITY\_CONTINUITY\_ALWAYS\_ON_ or _PROCESS\_CREATION\_MITIGATION\_POLICY2\_MODULE\_TAMPERING\_PROTECTION\_ALWAYS\_ON_ yet, ProcessHacker reports them.

![image](https://user-images.githubusercontent.com/5801389/55073898-361e1f80-508f-11e9-8a03-5e0f0ae05b36.png)

**Comment by dmex** [comment]
> Map[1] should in theory store PROCESS_CREATION_MITIGATION_POLICY2_* but this isn't entirely true

Map[1] is currently unused. Some values are also not propagated to LdrSystemDllInitBlock and you also can't query these properties using NtQueryInformationProcess.

The one and only reliable method to query those other properties is by using KProcessHacker and reading EPROCESS but I don't make changes to the driver public due to attacks by so called 'anticheat' and 'antivirus' companies.

**Comment by TheEragon** [comment]
But you shouldn't check Map[0] with PROCESS_CREATION_MITIGATION_POLICY2_* either because that's incorrect and displays false information in Mitigation Policies.

**Comment by dmex** [comment]
>  you shouldn't check Map[0]

Last I checked some of the Policy2 values are set in [0] because [1] is unused. I'll run some tests and remove the others.
