### ISSUE TITLE
[Windows 10] no graphs in sysinformation Window shown in Tabletmode

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#40]
When I run Windows 10 in Tabletmode, start ProcessHacker, no graphs are shown in systeminformation window and at closing the Window, PH crashes at `VOID PhSipOnNcDestroy` (sysinfo.c line 334)

`for (i = 0; i < SectionList->Count; i++)`

**Comment by dmex** [comment]
Reproduction steps: 

1. Click the Action center icon in the system tray (right next to the clock).
2. Click the Tabet Mode button.
3. Open Process Hacker and open the System Information window.

**Comment by MagicAndre1981** [comment]
I run the latest nightly (32Bit) compiled on my own with Vs2015 Upd2

**Comment by tigros** [comment]
problem is no WM_SHOWWINDOW message sent to PhSipSysInfoDialogProc in sysinfo.c.

if you move PhSipOnShowWindow(...) to WM_INITDIALOG it works, take it or leave it :)

**Comment by dmex** [comment]
This is a Windows 10 bug or the WM_SHOWWINDOW documentation is incorrect...  We should probably be using WM_WINDOWPOSCHANGED instead of WM_SHOWWINDOW: https://blogs.msdn.microsoft.com/oldnewthing/20080115-00/?p=23813/

**Comment by MagicAndre1981** [comment]
ok, I've asked Microsoft and I got the answer, that it is by design, that the Tablet mode doesn't send WM_SHOWWINDOW message. So move it to WM_INITDIALOG. Here it works for me as @tigros figured out.

**Comment by wj32** [comment]
@MagicAndre1981 Did they tell you why it's "by design"?

**Comment by MagicAndre1981** [comment]
nope, only that it is by design.

**Comment by MagicAndre1981** [comment]
this quote was highlighted:

> When a top-level, overlapped window is created with the WS_MAXIMIZE 

so Tablet mode seams to activate this.

**Comment by tigros** [comment]
out of curiosity i looked up what reactos is doing, so for all the dirty details go to line 2426 of https://doxygen.reactos.org/d0/dcd/ntuser_2winpos_8c_source.html

cheers!

**Comment by MagicAndre1981** [comment]
@wj32  any update one this? What are your plans to fix it?

**Comment by wj32** [comment]
I'll fix it when I have time

**Comment by MagicAndre1981** [comment]
@dmex 

can you please add the fix from @tigros ?
