### ISSUE TITLE
Avast flags processhacker-build-setup.exe (Process Hacker Nightly build installer) as IDP.Generic.888444275613.3.2

### ISSUE THREAD

**Issue by Hanif1601** [processhacker/processhacker#400]
**HELP!** I can't install Process Hacker Nightly build because Avast recently blocked the installer and flags has virus on it. Here the screenshot. The checked items is the installer itself before installation or after got User Account Control prompt.

![image](https://user-images.githubusercontent.com/46013833/55459061-ca9cfa80-5618-11e9-99b8-55ba8606165d.png)

Did anyone affected this too?

**Comment by VictorVG** [comment]
This is not a bug, but a reason for you to sue the authors of AVAST who try by creating the appearance of “protection” against non-existent threats to solve their own financial problems.

**Comment by Biswa96** [comment]
Try to use the ZIP file. If it also shows same issue then you're welcome in this party at https://github.com/processhacker/processhacker/issues/388  ;)

**Comment by VictorVG** [comment]
This is "_In the power supply virus! Catch, kill!_" - Dmitry Lozinsky, AidsTest , but second edition, modernized and with a more tarnished reputation.:lol: Sent this "antivirus" in to /dev>nul

**Comment by stdedos** [comment]
> Try to use the ZIP file. If it also shows same issue then you're welcome in this party at #388 ;)

... or the party on https://github.com/processhacker/processhacker/issues/356 😄

**Comment by Hanif1601** [comment]
> Try to use the ZIP file. If it also shows same issue then you're welcome in this party at #388 ;)

Okay, I'll trying out later. Thanks for labeling my issues.

**Comment by dmex** [comment]
#388
