### ISSUE TITLE
Search process 

### ISSUE THREAD

**Issue by OzakIOne** [processhacker/processhacker#409]
![image](https://user-images.githubusercontent.com/29860391/56437570-461cce00-62e0-11e9-80cc-da8150d2fae8.png)

When using the ctrl + backspace to delete the previous word it just add square character ...

**Comment by dmex** [comment]
> using the ctrl + backspace to delete the previous word

I've been testing SHAutoComplete for the searchbox but because it's on the main window SHAutoComplete delays application startup initializing the shell.

> just add square character

This would be correct:
https://devblogs.microsoft.com/oldnewthing/20071011-00/?p=24823
