### ISSUE TITLE
update FLS_MAXIMUM_AVAILABLE to 4080 (19H1 Change)

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#410]
The [FLS_MAXIMUM_AVAILABLE](https://github.com/processhacker/processhacker/blob/af043c47d4fd4e87bf458a80bcf5ea2633490eb5/phnt/include/ntpsapi.h#L58) should be updated to 4080 like in 18362 SDK (`Include\10.0.18362.0\um\winnt.h` line 11428)

**Comment by dmex** [comment]
@MagicAndre1981 

I might remove that value since FlsCallback, FlsListHead, FlsBitmap, FlsBitmapBits and FlsHighIndex were removed from the PEB (where that definition was previously located and used).

It would be interesting to find out where they're now located since its still defined in the WDK?

**Comment by MagicAndre1981** [comment]
I have no idea. I diffed the 17763 and 18362 headers for changes and saw this change.

**Comment by dmex** [comment]
I've commented it out since its not used by known structures except NtTib.

**Comment by MagicAndre1981** [comment]
ok
