### ISSUE TITLE
Kernel driver blocked

### ISSUE THREAD

**Issue by Coruscate5** [processhacker/processhacker#412]
When I try to use kprocesshacker.sys (compiled from source) with a self-compiled version of PH, I get this: 

![kerneldriverissue](https://user-images.githubusercontent.com/17749895/56612472-54f9ce00-65c9-11e9-9cd8-a766ee3fe2f5.jpg)

This is after I removed the signature verification check (which was previously failing with "the cryptographic signature is invalid"). I've tried signing the driver myself with both SHA1 & SHA256 - is there some other special action I need to take to get this to load?

**Comment by VictorVG** [comment]
Is know "problem" - just use signed driver in to some source.:)

**Comment by mrsshr** [comment]
You have 3 options.

1. Turn off driver ditigal signature verification. (Dangerous!)
2. Turn on test signing mode and sign your driver with test signing certificate.
3. Buy EV code signing certificate and sign your driver. (Very expensive)

**Comment by mrsshr** [comment]
See:

https://github.com/processhacker/processhacker/blob/master/KProcessHacker/verify.c#L31
https://github.com/processhacker/processhacker/tree/master/tools/CustomSignTool

**Comment by Coruscate5** [comment]
Got it. I can't use the premade signed driver anymore as it is immediately removed by hash-based AV

I will look into altering the key verification code to match my custom sig (which looks like what I'd have to do in verify.c to match the new public key? Sorry I'm not too familiar with the inner workings of the driver)

I'll poke around at the CustomSignTool as well

**Comment by VictorVG** [comment]
If installed AVAST then delete it and install professional AV like McAfee Antivirus or Comodo - Avast and avast-like "super AV" always deleted KPH driver (try read VERSION_INFO: OriginalFilename : kprocesshacker.sys (?)) ignore any exclude settings - is just they have such a business. 

Familiar ran - looked at his laptop. Collected and renamed KprocessHacker.sys to drv.sys, changed part of the value in VERSION_INFO, signed it with a signature, added the catalog PH to Avast exceptions beforehand, but AVAST found and erased driver by displaying a message about "disguising the KProcessHacker.sys malware".:) 

P.S.

_They have nothing like a cat, so they fool around. A cat in this case licks its virtues, and these “enemies catch”._

**Comment by Coruscate5** [comment]
Hmm. I suppose I could try something similar (futzing around with the kprocesshacker.sys binary). I believe I am in fact being blocked by the driver enforcement (even if my code signing cert is in the Trusted Root store).

This is where I'm at:

```
[SC] StartService FAILED 

Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source
```

Comes from here: 
https://github.com/processhacker/processhacker/blob/2bb718f36a702fde6cb346e9179696bb8c758d1f/phlib/kph.c#L199

`                if (StartService(serviceHandle, 0, NULL)) {`

I'll keep working on it - is there really no way around disabling all driver sig enforcement for the whole OS?? Seems like I should be able to selectively allow certain unsigned drivers by installing the right certs

**Comment by mrsshr** [comment]
You have 3 options:

1. Buy code signing certificate
2. Enable test signing mode
3. Disable digital signature enforcement

**Comment by mrsshr** [comment]
Self signed certificate is not trusted by Windows kernel. Because it is not cross certificated by Microsoft Code Verification Root.

**Comment by Coruscate5** [comment]
Understood - I suppose that messing with the kprocesshacker.sys file itself is the only possible recourse, or interfering with the kernel signature verification process itself (I suppose I could inject a valid sig and a valid service into SCM and somehow redirect back to kph) - but both of these seem pretty difficult, the latter of which would likely be new art.

I'll work instead on finding an up-&-over solution with the AV we currently have deployed

**Comment by dmex** [comment]
> locked by the driver enforcement (even if my code signing cert is in the Trusted Root store).

@Coruscate5 

Installing the certificate into the Trusted Root store makes no difference without first enabling debug and test signing modes.

bcdedit.exe -set DEBUG ON
bcdedit.exe -set TESTSIGNING ON

> You have 3 options:
> Buy code signing certificate
> Enable test signing mode
> Disable digital signature enforcement

@mrsshr

This is not quite accurate. The Windows kernel does not check if drivers have been signed with revoked or expired certificates and so anyone can also use leaked/stolen, revoked or expired certificates to sign kernel drivers and they load perfectly fine on every version of Windows including those with HVCI (hypervisor code integrity).

**Comment by Coruscate5** [comment]
Given that I don't have any revoked Comodo root private keys readily available, I opted for the up-and-over path of working with our AV folks and getting the signed driver to pass inspection

@dmex 

Do you know where the kernel is hiding its trusted driver cert store? As an admin I'm a bit surprised that my account wouldn't have access to modify that store somehow. I'm assuming it's some pre-baked list of CAs, but given that the OS is not hard wired into the mobo, I should be able to inject something on that disk location..

**Comment by dmex** [comment]
> Do you know where the kernel is hiding its trusted driver cert store? 

It's hard-coded into the kernel and any changes will trigger patch-guard. Even if you disable PG you still can't make changes with HVCI on Win10.

> I don't have any revoked Comodo root private keys

There are dozens of signing certificates on the internet and Github (I've found about 200 leaked/revoked signing certificates in the last year). Some are expired or have been revoked but those checks by the Windows kernel can be bypassed by simply changing how you call signtool.exe when signing the driver and nothing else.

For example the [Windows-Kernel-Explorer](https://github.com/AxtMueller/Windows-Kernel-Explorer) project on Github uses the revoked certificates from the HackingTeam leak which can be downloaded here: https://github.com/hackedteam/GeoTrust


This certificate was revoked but you can still use it for driver signing and drivers will load perfectly fine on every version of Windows (including when secure-boot and HVCI are enabled):
![image](https://user-images.githubusercontent.com/1306177/58122291-95209080-7c09-11e9-9545-ba834932a5c0.png)

**Comment by DavidXanatos** [comment]
Awesome presumably working certs, many thanks 👍

**Comment by mrsshr** [comment]
@dmex Thank you for nice information :D
Tested and working

**Comment by Hanif1601** [comment]
> If installed AVAST then delete it and install professional AV like McAfee Antivirus or Comodo - Avast and avast-like "super AV" always deleted KPH driver (try read VERSION_INFO: OriginalFilename : kprocesshacker.sys (?)) ignore any exclude settings - is just they have such a business.
> 
> Familiar ran - looked at his laptop. Collected and renamed KprocessHacker.sys to drv.sys, changed part of the value in VERSION_INFO, signed it with a signature, added the catalog PH to Avast exceptions beforehand, but AVAST found and erased driver by displaying a message about "disguising the KProcessHacker.sys malware".:)
> 
> P.S.
> 
> _They have nothing like a cat, so they fool around. A cat in this case licks its virtues, and these “enemies catch”._

LOL, You're right. That's why I am getting "_Blocked by Avast self-defense: kprocesshacker.sys"_ every time when I give Administrator privilege to Process Hacker. And also I won't uninstall Avast because my laptop need strong protection against powerful malware or virus out there.

**Comment by AltF5** [comment]
> @dmex Thank you for nice information :D
> Tested and working

Could you describe the steps you took to do this? I would like to test this out on my local machine, after manually compiling the driver.
As in: 
- What did you use to sign the cert?
- What BCD changes were necessary to get loading? (if any)
- Other quirky things that were necessary to have operate and load into the kernel?

**Comment by mrsshr** [comment]
I am using "HT Srl" certificate. You can get this leaked certificate from here:

> For example the Windows-Kernel-Explorer project on Github uses the revoked certificates from the `HackingTeam` leak which can be downloaded here: https://github.com/hackedteam/GeoTrust

1. Prepare offline Windows VM
2. Copy signtool, certificate, cross certificate to VM
3. Sign driver file with signtool

Ref:
https://docs.microsoft.com/ko-kr/windows-hardware/drivers/install/cross-certificates-for-kernel-mode-code-signing
https://docs.microsoft.com/ko-kr/windows-hardware/drivers/install/release-signing-a-driver-through-an-embedded-signature

**Comment by dmex** [comment]
#388

**Comment by LusKrew** [comment]
> > locked by the driver enforcement (even if my code signing cert is in the Trusted Root store).
> 
> @Coruscate5
> 
> Installing the certificate into the Trusted Root store makes no difference without first enabling debug and test signing modes.
> 
> bcdedit.exe -set DEBUG ON
> bcdedit.exe -set TESTSIGNING ON
> 
> > You have 3 options:
> > Buy code signing certificate
> > Enable test signing mode
> > Disable digital signature enforcement
> 
> @mrsshr
> 
> This is not quite accurate. The Windows kernel does not check if drivers have been signed with revoked or expired certificates and so you can also use leaked/stolen, revoked or expired certificates to sign kernel drivers for every version of Windows.

Hey man, do you happen to know any leaked cert that doesnt get flagged by AVs? i want to sign my driver by this HT srl causes many AVs to detect it as malware, any certificate you know that has the lowest detection ? also where can i find this list of leaked certs that you said ? thanks

**Comment by Aholicknight** [comment]
@LusKrew can you post a guide or a download for this HT Srl cert? can't find a download for it anywhere

**Comment by DavidXanatos** [comment]
@Aholicknight don't bother, with a recent windows 10 update 20h1 or was ist 20h2 this cert is blacklisted in the kernel and hence sueless

**Comment by Aholicknight** [comment]
@DavidXanatos yeah, I tried to get that SbieDrv signed with HT Srl to make it run on my computer without testmode but that failed horrendously, so I just signed it with a test signature and enabled test mode. Oh well

**Comment by DARK7BEA5T** [comment]
where is the fix?
