### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gemal** [processhacker/processhacker#413]
Any chance for a new release?

![image](https://user-images.githubusercontent.com/69105/56660384-b8eec600-669f-11e9-9446-31bb83ddbcc5.png)

**Comment by dmex** [comment]
There was a release four days ago? 😃 
https://wj32.org/processhacker/nightly.php

**Comment by gemal** [comment]
I dont really consider a night build a release :(
I think a stable version should be released to here:
https://github.com/processhacker/processhacker/releases
