### ISSUE TITLE
Graphs in Process Hacker window are always empty

### ISSUE THREAD

**Issue by tsunamistate** [processhacker/processhacker#414]
**Environment:**

Windows 10 Pro x64
Intel Celeron N2830
8Gb RAM
Process Hacker 3.0.2380 (259623b1)

**Steps to reproduce:**

1. Open Process Hacker.
2. Right-click on the toolbar and enable any graph (e.g. CPU History).
3. Mouse over the graph.

**Actual Result:** Graph in Process Hacker window is always empty. Mouse-over tooltip is not displayed.

![изображение](https://user-images.githubusercontent.com/4958520/56862717-b26d9080-69b6-11e9-85a8-2def609ecf87.png)

**Expected Result:** Graph in Process Hacker window is updated according to set refresh interval. Mouse-over tooltip is displayed.

**Note:** This issue impacts only graphs in Process Hacker window, graphs in Task Panel are not affected.

**Comment by dmex** [comment]
Thanks! I fixed the bug in the latest nightly build 👍
