### ISSUE TITLE
I/O usage per thread?

### ISSUE THREAD

**Issue by tigros** [processhacker/processhacker#416]
Hi,
Is it possible to get I/O usage per thread? So in the process properties Threads tab there'd be I/O usage. Just something I could use right now.

Thanks!

**Comment by dmex** [comment]
NT doesn't have per-thread IO statistics at least any APIs for easy quick/easy information. You would have to use the Process -> Miscellaneous -> WS watch feature or various ETW events.

For example the main window -> Disk tab uses ETW events for showing Disk IO which does include the Thread but its not initialized until the disk tab is selected and EtProcessDiskEvent ignores thread events and it doesnt include other types of IO such as named pipes, sockets and alpc.

**Comment by dmex** [comment]
The KTHREAD structure includes these IO_COUNTERS values for individual threads:

ReadOperationCount
WriteOperationCount
OtherOperationCount
ReadTransferCount
WriteTransferCount
OtherTransferCount

We have to add support to the kernel driver... :(

**Comment by tigros** [comment]
looks like that's windows 10 only tho, my main os is still win7 (waaay 2 much stuff 2 migrate) plus the stability factor.. also KTHREAD changes alot so thats a problem. i'd use that in a win10 vm tho 4 sure and would help out. be glad to participate in testing or w/e.
cheers!
speaking of the driver check out the plugin i made here https://github.com/tigros/KLog i sure as heck use it, can you sign it?? i've been in test mode a loong time :) thanks!
