### ISSUE TITLE
`Reset Process Hacker settings` in nightly setup failed immediatly

### ISSUE THREAD

**Issue by yyjdelete** [processhacker/processhacker#421]
Tested with:

Build: 3.0.2451
Built: Saturday, 25th of May, 2019

**Comment by yyjdelete** [comment]
https://github.com/processhacker/processhacker/blob/0fc851095fce339dffa2e1df5d163f9a296f9718/tools/CustomSetupTool/CustomSetupTool/install.c#L42-L56

When `SetupResetSettings` is true, seems the installer just remove the output dir immediatly after create it, so the later `SetupCreateUninstallFile` always failed since the output path is no longer exists.

**Comment by dmex** [comment]
Thanks, I've fixed the copypasta 👍
