### ISSUE TITLE
Strange issue using PHlib to dump Stack Traces

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#422]
I'm using ProcessHacker's phlib to get a stack traces of various threads,
however the results I get are always different that what a self compiled process hacker gives me.

See the attached screenshot below, somehow getting the symbols from the kernel does not work properly.

any ideas what I might be doing wrong?

![stack issue](https://user-images.githubusercontent.com/3890945/58763550-4a354000-855c-11e9-81b1-2809ca3325b8.png)

**Comment by dmex** [comment]
You haven't initialized symbols for those modules using PhLoadModuleSymbolProvider.

**Comment by DavidXanatos** [comment]
Great thank you very much that was it :-)
