### ISSUE TITLE
PhpFixupLoaderEntryImageDelayImports crash on 18912

### ISSUE THREAD

**Issue by andrew-boyarshin** [processhacker/processhacker#424]
After a lengthy debugging of both official 3.0.2451 version and self-compiled one:

1. Never happened before. Just upgraded from 10.0.18898.1000 to 10.0.18912.1001, immediately noticed the failure to start PH.
2. Crash on startup with minidump creation option.
3. If I delete `WindowExplorer.dll` plugin, everything works.
4. Self-compiled build (at the same revision) helped find the offending line.
<https://github.com/processhacker/processhacker/blob/f3fd5c379971d365c0896a9c6e181f6c66d1c9df/phlib/util.c#L6316>
5. `procedureAddress` is the `PhInsertEMenuItem` pointer.
6. Exception:
```
Exception thrown: write access violation.
importThunk was 0x7FFE37246080.
```
7. All fields inside `importThunk` and variables in current scope look correct. `importThunk->u1.Function | 0x00007ffe338e7570 | unsigned __int64`
8. Doesn't happen with self-compiled WindowExplorer, only with official one.

Any ideas?

**Comment by andrew-boyarshin** [comment]
```
&importThunk->u1.Function | WindowExplorer.dll!0x00007ffe33906080 (load symbols for additional information) {0x00007ffe338e7570} | unsigned __int64 *
(unsigned long long)&importThunk->u1.Function | 0x00007ffe33906080 | unsigned __int64
```

![image](https://user-images.githubusercontent.com/3063662/59028193-22f4b080-8885-11e9-8a39-1c9d9b1ced25.png)

**Comment by andrew-boyarshin** [comment]
No DLL exports around 0x00007ffe3XXXXXXX
![image](https://user-images.githubusercontent.com/3063662/59028850-ce523500-8886-11e9-88ad-e3240a7f37bb.png)

**Comment by andrew-boyarshin** [comment]
@dmex I can confirm that 3.0.2464 is working OK with the plugin enabled.

**Comment by dmex** [comment]
> P.S. I'd be interested in learning a bit more about the issue if it is related to changes in Windows (NTDLL LDR?). I'm somewhat fascinated by such architectural changes. Did Windows change the protection on pages it allocates for IAT?

ZwCreateSection previously allocated the delayload header and delayload address table sequentially in memory identical to the import table. 20H1 seems to allocate the ImportAddressTable for the delayload in a separate allocation from the header (which is no longer sequential from the header allocation) and my code was relying on that implementation detail which was the cause of the crash.

The CRT in dloadsup.h queries the section of the ImportAddressTableRVA while my code queried the address for the IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT section. 20H1 doesn't allocate these two structures sequentially and so PH crashed trying to change the import address for a region of memory which was read only and located in a different section than what was read_write. 

I've updated the code to query the section for the ImportAddressTableRVA which is what the CRT does and also fixes the issue on 20H1.
