### ISSUE TITLE
ProcessHacker is missing UDP traffic

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#427]
I noticed today that process hacker is not showing UDP traffic of my file-sharing client in the network tab.

Upon some investigation I have found two issues why that happens:

**First**: in etwmon.c EtpEtwEventCallback
on my windows 10 1903 for incoming UDP packets the endpoints are swapped, i.e. the destination endpoint corresponds to the local socket not the source endpoint.

For TCP connections (ingoing and outgoing) and for outgoing UDP packets its fine, the issue appears only for incoming UDP packets.

there the fix is easy:
add:
`
            if ((networkEvent.ProtocolType & PH_UDP_PROTOCOL_TYPE) != 0 && networkEvent.Type == EtEtwNetworkReceiveType)
            {
                PH_IP_ENDPOINT temp = source;
                source = destination;
                destination = temp;
            }

`
before `networkEvent.LocalEndpoint = source;`

**Second**:
The source Address is always the IP address on which the packet has been received, 
while in out socket list as IP address we have "0.0.0.0" and "::" 

I haven't looked into the hash table that holds this list but since fix one did not do the trick, I assume that ProcessHacker is not smart enough when invoking PhReferenceNetworkItem to have a wildcard match for "0.0.0.0" and "::" address entries.

In my own GUI front end for the Process Hacker Library, fixing these two issues solved the problem.

So the proper fix for issue 2 will be some more code rework, hence I thought I'll leave that to someone more familiar with Process Hacker source code.

In my project the Hash for the socket map is generated only from ports and process ID:
`
quint64 CSocketInfo::MkHash(quint64 ProcessId, ulong ProtocolType, quint16 LocalPort, quint16 RemotePort)
{
	if ((ProtocolType & PH_UDP_PROTOCOL_TYPE) != 0)
		RemotePort = 0;
	quint64 HashID = ((quint64)LocalPort << 0) | ((quint64)RemotePort << 16) | (quint64)(((quint32*)&ProcessId)[0] ^ ((quint32*)&ProcessId)[1]) << 32;
	return HashID;
}

`

and when looking up a socket, for all the matching result a separate Match function is executed which can be provided with a bStrict parameter

`
bool CSocketInfo::Match(quint64 ProcessId, ulong ProtocolType, const QHostAddress& LocalAddress, quint16 LocalPort, const QHostAddress& RemoteAddress, quint16 RemotePort, bool bStrict)
{
	if (m_ProcessId != ProcessId || m_ProtocolType != ProtocolType || m_LocalPort != LocalPort)
		return false;
	// a socket may be bount to all adapters than it has a local null address
	if (bStrict || m_LocalAddress != QHostAddress::Any)
	{
		if(m_LocalAddress != LocalAddress)
			return false;
	}
	// don't test the remote endpoint if this is a udp socket
	if (bStrict || (m_ProtocolType & PH_TCP_PROTOCOL_TYPE) != 0)
	{
		if (m_RemotePort != RemotePort)
			return false;
		if (m_RemoteAddress != RemoteAddress)
			return false;
	}
	return true;
}

`

When looking up connections provided by PhGetNetworkConnections `bStrict == true` when looking up sockets in a network event it is `bStrict == false` this way sockets that are bound to all network adapters are properly associated with the encountered traffic.

I hope a fix of this type can be added with in a reasonable amount of afford to ProcessHacker, since nowadays almost all FileSharing clients are using UDP based NAT-Traversal a lot of traffic goes over UDP and it would be a shame to miss it.

Cheers
David X.

**Comment by dmex** [comment]
> incoming UDP packets the endpoints are swapped

Thanks! Good catch 👍 

> The source Address is always the IP address on which the packet has been received

It was assumed these packets were from different connections but you're correct ETW uses the local adapter address instead of the inaddr_any address.

> socket list as IP address we have "0.0.0.0" and "::"

RtlIpv4AddressToString/RtlIpv6AddressToString will return those addresses for sockets using in4addr_any/in6addr_any (values of zero).

> I assume that ProcessHacker is not smart enough when invoking PhReferenceNetworkItem to have a wildcard match for "0.0.0.0" and "::" address entries. In my project the Hash for the socket map is generated only from ports and process ID:

You will have hash collisions by using just the Port and ProcessID because applications can create multiple sockets for the same port in the same process.

**Comment by DavidXanatos** [comment]
> You will have hash collisions by using just the Port and ProcessID because applications can create multiple sockets for the same port in the same process.

Yes that's why I'm using QMultiMap which can hold multiple entries for the same key after retrieving entries for a given hash I use the mentioned Match to find out which entry if any is the right one.
