### ISSUE TITLE
[Enhancements]Add total of memory of a process and all of its child process

### ISSUE THREAD

**Issue by arlllk** [processhacker/processhacker#428]
Add a way to see all of the memory consumption of a process and its child process to measure the real quantity of memory that a program uses (Google Chrome / IDEs )

**Comment by dmex** [comment]
You can enable the 'Include usage of collapsed processes' option in Settings and collapse the tree to see the total usage of the process and its children 👍

**Comment by arlllk** [comment]
Thanks, I was incapable of figuring out
