### ISSUE TITLE
It seems to not follow the rule like Visual Studio and other Microsoft debuggers to find symbols for my dll or exe

### ISSUE THREAD

**Issue by ssfang** [processhacker/processhacker#432]
I placed pdb in the same folder to my dll on my test computer, but I found, it couldn't display correct function names in the stack list window of threads for my process.

I means the rule comes from [Debugging with Symbols - Getting the Symbols You Need](https://docs.microsoft.com/en-us/windows/desktop/dxtecharts/debugging-with-symbols#getting-the-symbols-you-need)

-------over

> ## Getting the Symbols You Need
> Visual Studio and other Microsoft debuggers, such as WinDbg, are typically set up to just work if you are building an application and debugging it on your own computer. If you need to give your executable to someone else, if you have multiple versions of a DLL or an .exe file on your computer, or if you want to accurately debug an application that uses Windows or other libraries, such as DirectX, you need to understand how debuggers find and load symbols. The debugger uses either the symbol search path that is specified by the user—which is found in Options\Debugging\Symbols in Visual Studio—or the _NT_SYMBOL_PATH environment variable. Typically, the debugger searches for matching PDBs in the following locations:
> 
> 1. The location that is specified inside the DLL or the executable file.  
>  If you have built a DLL or an executable file on your computer, by default the linker places the full path and file name of the associated PDB file inside the DLL or the executable file. When you debug, the debugger first checks to see if the symbol file exists in the location that is specified inside the DLL or the executable file. This is helpful, because you always have symbols available for code that you have compiled on your computer.
> 
> 2. PDBs that may be present in the same folder as the DLL or executable file.
> 
> 3. Any local symbol cache folders.
> 
> 4. Any local network file share symbol servers.
> 
> 5. Any Internet symbol servers, such as the Microsoft symbol server.
> 
> To make sure that you have all the PDBs that you need for accurate debugging, install the debugging tools for Windows. The 32 and 64 bit versions can be found at https://www.microsoft.com/whdc/devtools/debugging/default.mspx.
> 
> A useful tool that is installed with this package is symchk.exe. It can help to identify missing or incorrect symbols. This tool has a large number of potential command line options. Here are two of the more useful and commonly used ones.
>
> ### Check if a given DLL or .exe file and PDB in the same folder match
> ```bat
> "c:\Program Files\Debugging Tools for Windows\symchk" testing.dll /s
> 
> SYMCHK: FAILED files = 0
> SYMCHK: PASSED + IGNORED files = 1
> ```
> The **/s** option tells **symchk** to look for symbols only in the current folder, and not to look in any symbol servers.
>
> ### Check if all the DLLs and executable files in a set of folders have matching PDBs
> ```bat
> "c:\Program Files\Debugging Tools for Windows\symchk" *.* /r
> ```
> The **/r** option sets **symchk** to recursively traverse through folders, to check that all the executable files have matching PDBs. Without the **/s** option, **symchk** uses the current _NT_SYMBOL_PATH to search for symbols on any private or local server, or on the Microsoft symbol servers. The **symchk** tool searches only for symbols for executable files (.exe, .dll, and similar). You cannot use wild cards search for symbols for non-executable files.
>
> ## How symchk Works
> When the linker generates .dll, executable, and PDB files, it stores identical GUIDs in each file. The GUID is used by tools to determine if a given PDB file matches a DLL or an executable file. If you alter a DLL or an executable file—by using a resource editor or copy protection encoding, or by altering its version information—the GUID is updated and the debugger cannot load the PDB file. For this reason, it's very important to avoid manipulating the DLL or executable file after it is created by the linker.
> 
> You can also use the DUMPBIN utility that comes with VS.NET to show the symbol paths that are searched, and to see if symbol files are found that match a given DLL or executable file. For example:
> ```bat
> DUMPBIN /PDBPATH:VERBOSE filename.exe
> ```

```cmd
D:\> where dumpbin
INFO: Could not find files for the given pattern(s).

D:\> "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe" /PDBPATH:VERBOSE D:\Dev\MyToy\x64\Release\toy.dll

Microsoft (R) COFF/PE Dumper Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file D:\Dev\MyToy\x64\Release\toy.dll

File Type: DLL
  PDB file 'D:\Dev\MyToy\x64\Release\toy.pdb' checked.  (File not found)
  PDB file 'D:\Dev\MyToy\x64\Release\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\symbols\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\dll\symbols\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\dll\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\symbols\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\dll\toy.pdb' checked.  (File not found)
  PDB file 'C:\Windows\toy.pdb' checked.  (File not found)

  Summary

        B000 .data
        1000 .gfids
        A000 .pdata
       54000 .rdata
        2000 .reloc
        1000 .rsrc
       B3000 .text
        1000 .tls


D:\> mklink /H "C:\bin\symchk.exe" "C:\WinDDK\7600.16385.1\Debuggers\symchk.exe"
Hardlink created for C:\bin\symchk.exe <<===>> C:\WinDDK\7600.16385.1\Debuggers\symchk.exe
D:\> mklink /H "C:\bin\SymbolCheck.dll" "C:\WinDDK\7600.16385.1\Debuggers\symbolcheck.dll"
Hardlink created for C:\bin\SymbolCheck.dll <<===>> C:\WinDDK\7600.16385.1\Debuggers\symbolcheck.dll

D:\> mklink /H C:\bin\dumpbin.exe "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\dumpbin.exe"
Access is denied.

D:\> %comspec% /k ""C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat""
```

**Comment by dmex** [comment]
> I placed pdb in the same folder to my dll on my test computer, but I found, it couldn't display correct function names in the stack list window of threads for my process.

You need to configure the symbol path on the options window or have the PDB in the same location as the machine that compiled the binary.
