### ISSUE TITLE
Firewall ExtraPlugin leaks memory!

### ISSUE THREAD

**Issue by AltF5** [processhacker/processhacker#434]
The Firewall Monitor causes PH to leak memory, increasing at about 100MB per hour. Tested as the only plugin. Occurs only when PH is running Elevated.

I suggest either fixing or removing this faulty component. It’s unclear if it’s the sheer column of traffic populating in its list view, but it does it in the background without ever switching to the Firewall tab, when run as an admin. Took many days to figure this out, but glad to report DONT USE IT unless you plan on restarting PH daily, if running it elevated.

**Comment by dmex** [comment]
> I suggest either fixing or removing this faulty component. 

It's not included with the official builds or main repository and also why the description of the plugins-extra repository states "highly unstable, buggy, incomplete" 😉

**Comment by AltF5** [comment]
Fair, but definitely need a nice warning on any discovered that leak memory. Pulled my hair out thinking it was my modifications when it was this silly plugin the whole time.

**Comment by skipik** [comment]
![111](https://user-images.githubusercontent.com/24621645/60771921-4b2b3580-a0f7-11e9-9537-0f88c1a9c1de.png)

**Comment by VictorVG** [comment]
[**Git-40d8a6ca9f29**](https://github.com/processhacker/plugins-extra/commit/40d8a6ca9f296e078cd13eca982a8cd001351dff)

[ERROR] .\plugins-extra\firewallmonitorplugin\monitor.c(548): error C2065: FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP: undefined identifier [.\plugins-extra\FirewallMonitorPlugin\FirewallMonitorPlugin.vcxproj]
.\plugins-extra\firewallmonitorplugin\monitor.c(548): error C2065: FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP: undefined identifier [.\plugins-extra\FirewallMonitorPlugin\FirewallMonitorPlugin.vcxproj]

The FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP identifier is not currently used (at least grep says so:

```
[1] .\plugins-extra\FirewallMonitorPlugin\monitor.c

545-            FWPM_NET_EVENT_KEYWORD_CLASSIFY_ALLOW |
546-            FWPM_NET_EVENT_KEYWORD_INBOUND_MCAST |
547-            FWPM_NET_EVENT_KEYWORD_INBOUND_BCAST |
548:            FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP;
549-
550-        if (FwpmEngineSetOption(
551-            FwEngineHandle,
552-            FWPM_ENGINE_NET_EVENT_MATCH_ANY_KEYWORDS,
553-            &value
554-            ) != ERROR_SUCCESS)
555-        {
556-            return FALSE;
557-        }
558-
```
). Can it comment out temporarily?

**Comment by dmex** [comment]
>  identifier is not currently used

Your SDK/WDK is outdated. You can comment it out but you should update.

**Comment by VictorVG** [comment]
And what version of the SDK / WDK should I put? I now have MS VC ++ 15.9.11 with its set SDK/WDK.

**Comment by skipik** [comment]
I have MS VS 2019 16.1.5 / SDK 18362 and still can't build the plugin.

**Comment by VictorVG** [comment]
I commented string ./plugins-extra/FirewallMonitorPlugin/monitor.c :: 548 and build success using VC++ 15.9.11. My temporary path is:

starting string 547:
```
            FWPM_NET_EVENT_KEYWORD_INBOUND_BCAST;
//            FWPM_NET_EVENT_KEYWORD_INBOUND_BCAST |
//            FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP;
```
Test possible Ok!, but I wait download and install VC++ 15.9.13 ...

**Comment by dmex** [comment]
> I have MS VS 2019 16.1.5 / SDK 18362 and still can't build the plugin.

Project menu > retarget solution > 10.0 > click ok

**Comment by skipik** [comment]
Thanks! Works now.

**Comment by VictorVG** [comment]
And for VC++ 15.9.13 (SDK 10.0.17763) what to do?

**Comment by dmex** [comment]
@VictorVG 

Update to the latest sdk?

**Comment by VictorVG** [comment]
Yes, now, at the prompt, **skipik** downloaded the SDK v10.0.18362.0 and corrected the draft version of it in the file. With the new SDK gathered. Thank! If I understood correctly, did FWPM_NET_EVENT_KEYWORD_PORT_SCANNING_DROP be added to RS6?
