### ISSUE TITLE
3.0.2471 Crash & dump

### ISSUE THREAD

**Issue by Tharn** [processhacker/processhacker#435]
Got a crash for you here. As it happened, I was clicking 'X' to exit out of the program.

[ProcessHacker_BAFGCUJQIOHOIQC_DumpFile.zip](https://github.com/processhacker/processhacker/files/3365173/ProcessHacker_BAFGCUJQIOHOIQC_DumpFile.zip)

**Comment by dmex** [comment]
Try with the latest nightly r2495

**Comment by Tharn** [comment]
Crash right after update & 
[ProcessHacker_FXUPHSFNWKZWWTZ_DumpFile.zip](https://github.com/processhacker/processhacker/files/3366111/ProcessHacker_FXUPHSFNWKZWWTZ_DumpFile.zip)
restart.

**Comment by dmex** [comment]
> Crash right after update to v. 3.0.2496 & restart.

The minidump doesn't make any sense as to why it crashed and was probably caused by 3rd party software trying to modify something. 

You could try resetting the Process Hacker settings to default?

**Comment by Tharn** [comment]
I could try that.
I run a very minimal set-up, no AV or anything. So I can't see what third party software should modify anything here. It was definitely related to just having been updated before, as I couldn't make it crash again afterwards. But it was Process Hacker.

**Comment by dmex** [comment]
> It was definitely related to just having been updated before, as I couldn't make it crash again afterwards. 

It crashed enumerating the toolbar items in a way that's not logical. I can't reproduce the crash and the way it crashed doesn't match what the code does. I've seen similar cases and it generally happens when something was modified/patched by some other program or some type of memory corruption such as overclocking/faulty hardware.

I can only guess as what caused it 🤷‍♂

**Comment by Tharn** [comment]
Interesting.. considering I have the toolbar disabled.

The hardware should be fine.

**Comment by dmex** [comment]
> I have the toolbar disabled. (But toolbar plugin was loaded)

Thanks! This is what caused the crashes. GDI doesn't validate window handles are actually valid and when the toolbar was disabled the graphs were still drawing without valid handles which (silently) causes corruption.

I've updated the nightly build with changes to validate the handles before drawing 👍
