### ISSUE TITLE
Run as limited user regression

### ISSUE THREAD

**Issue by diversenok** [processhacker/processhacker#436]
The new implementation for starting limited processes has several issues:

 - [x] It does not work if explorer isn't running at the moment. Maybe PH should fall back to using `WdcRunTaskAsInteractiveUser` in this case.
 - [x] The new process inherits environmental variables from the caller, not from the parent. Since I use to run PH as SYSTEM, the new process can't access its Temp and AppData folders.
 - [ ] The same applies to security descriptors on the new process and its initial thread. The system constructs them using the caller's default DACL, which might lead to inconsistently assigned permissions.

**Comment by diversenok** [comment]
@dmex 
The third item is still here, and, as turned out, also includes the token of the new process. Although too restrictive access on the process object and its initial thread affects only purely written programs that do not utilize pseudo-handles, way more applications depend on opening the current token.

The call to `NtOpenProcessToken(NtCurrentProcess(), MAXIMUM_ALLOWED, &hToken)` behaves differently depending on the context:
 - If the user starts the process from explorer it returns full access;
 - If the user starts the process from an elevated Process Hacker the call returns read & execute access;
 - If the user starts the process from PH running as SYSTEM, the call fails.

**Comment by dmex** [comment]
> too restrictive access on the process object and its initial thread

This shouldn't be an issue because both of those objects (for the current process only) are a type of 'pseudo' object that are hard-coded to allow any access.

> The call to NtOpenProcessToken(NtCurrentProcess(), MAXIMUM_ALLOWED, &hToken) behaves differently 

MAXIMUM_ALLOWED should never be used with NtCurrentProcess because you already have full access to the object?

**Comment by diversenok** [comment]
@dmex 
> MAXIMUM_ALLOWED should never be used in conjunction with NtCurrentProcess because you already have full access to the object when using NtCurrentProcess?

Full access to the process object, not to the token object which you open with the preceding code. And you can't open a token without performing access checks on it. Since the token gets the wrong DACL, the limited process can't open it for full/any access depending on the way it was started.

**Comment by dmex** [comment]
> Full access to the process object, not to the token object

The kernel bypasses access checking when a process is opening its own token - there is a hard-coded check in the kernel for the requestor == owner.

> Since the token gets the wrong DACL, the limited process can't open it for full/any access depending on the way it was started.

Can you give me an example of a program that has this issue?

**Comment by diversenok** [comment]
@dmex
> The kernel bypasses access checking when a process is opening its own token

At least on Windows 7, it's not the case — opening current token even for TOKEN_QUERY can result in access denied.

Here are several ways to reproduce this problem on Windows 7:
1) From an elevated instance of Process Hacker (**A**) start a limited instance of Process Hacker (**B**). Using the limited instance (**B**)  try to view the process properties of itself (**B**). Most of the pages: Memory, Environment, Modules, and Handles won't work. The Token page works fine for viewing but does not allow you to adjust privileges. Without the driver's support, it can't open its token for write access.
2) Start Process Hacker as NT AUTHORITY\SYSTEM, and then run cmd from it (as a limited user). Auto-completion of paths (the one that happens when you press tabulation) won't work.
3) From Process Hacker that runs as NT AUTHORITY\SYSTEM start a limited instance of Process Hacker.  It will crash immediately.

**Comment by dmex** [comment]
> opening current token even for TOKEN_QUERY can result in access denied.

CreateProcess is creating the child with Medium IL token but with DAC security descriptor set to High IL... It's what causes the access_denied issue and a severe bug with the API.

> Here are several ways to reproduce this problem on Windows 7

I've been able to reproduce the issue on Windows 10 too.

**Comment by dmex** [comment]
I've added some workarounds in the latest nightly and reported the bug to Microsoft 👍
