### ISSUE TITLE
Get thread info via command line

### ISSUE THREAD

**Issue by spinn** [processhacker/processhacker#44]
Would it be possible to add a new command line option that would print out info about a specific thread? Something like:

`processhacker -c -ctype thread -cobject 180 -caction info`

Or alternatively, a command line option that would allow searching for specific threads (something like the search option in the GUI already does, but instead of displaying the results in the GUI, it should print out results back into the command line).

**Comment by dmex** [comment]
Can you be more specific about what type of information should be printed?
