### ISSUE TITLE
Suggestion: Add sorting indicator to column headings

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#441]
Today I can't find any way of seeing how/if a table in PH is sorted.

I suggest introducing  a visual indicator, like for example in Window Explorer (see image), in the column header for the column which sorting is done on.

![image](https://user-images.githubusercontent.com/7513795/61187280-f8f69100-a66f-11e9-8085-513d6ebcbf2c.png)

**Comment by dmex** [comment]
This is a bug with the experimental theme support. I'll add it to the existing issue:
https://github.com/processhacker/processhacker/issues/368

**Comment by Bartolomeus-649** [comment]
ok, thanks.
Disabling the themes support made the sorting indicator visible.

@dmex , When turning of the theme support I noticed that it might be so that **it's not possible to change a setting via the "advanced tab" in the option dialog if the same option is exposed with its own setting on another tab**. It's like the save-settings process start reading settings from the advanced tab, and then after that, it reads the settings from the other tabs, so if there's specific GUI for a setting on any of the other tabs, it "over writes" the setting done in the advanced tab.
Perhaps make the settings "observables" connected to a "settings view model", and connect each visualization of a setting to the same property in this "view model", so no matter where the setting is changed, it is immediately reflected by any and all controls connected to the same setting, no matter where in the GUI they might appear.

**Comment by dmex** [comment]
> it might be so that it's not possible to change a setting via the "advanced tab" in the option dialog if the same option is exposed with its own setting on another tab.

The advanced tab settings are saved at runtime while all other settings are saved when you close the Options dialog.

It has to be done this way otherwise the advanced tab would always overwrite the other settings back to defaults. It's the same issue when you manually edit the settings file; closing the program overwrites the changes.

**Comment by Bartolomeus-649** [comment]
> It has to be done this way otherwise the advanced tab would always overwrite the other settings back to defaults. It's the same issue when you manually edit the settings file; closing the program overwrites the changes.

Unless everything updates a settings object in memory, and, in realt-time (observable), reflect that settings object in the GUI, where ever it might be.
So changing a setting in the advanced GUI would update the settings object, which in turn would notify all subscribers of this update. And the same thing if a setting is changed in any other way.

And by monitoring the file where settings are saved, either in real-time, or by checking if has changed since it was read last time, you cold ask the user what they want, use the settings file, or over write it.

Or just include those settings that don't exist on another tab among those settings shown in the advanced tab. 
As it's now, it's very confusing, and I spent a lot of time trying to turn of the themes support before realizing it couldn't be done in the advanced tab.
