### ISSUE TITLE
possible issue in PhInvokeCallback

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#444]
I think there may be an issue in PhInvokeCallback

    while (listEntry != &Callback->ListHead)
    {
[...]
        if (registration->Unregistering)
            continue;
[...]
        listEntry = listEntry->Flink;
    }

when registration->Unregistering is true, the code will hand in the loop forever as it will never go to the next list item

my fix would be to remove the listEntry = .. from the end fo the while loop and use a for loop instead loke this:
for (listEntry = Callback->ListHead.Flink; listEntry != &Callback->ListHead; listEntry = listEntry->Flink)

**Comment by dmex** [comment]
> the code will hand in the loop forever as it will never go to the next list item

PhInvokeCallback invokes the callback synchronously and PhUnregisterCallback removes the item immediately after the callback has executed?

**Comment by DavidXanatos** [comment]
I might be wrong but the way I see it the following can happen:

PhUnregisterCallback sets Registration->Unregistering = TRUE;
and then waits for: PhAcquireQueuedLockExclusive(&Callback->ListLock);

if PhUnregisterCallback is called in the moment when PhInvokeCallback is being executed PhInvokeCallback will already have a lock on PhAcquireQueuedLockShared(&Callback->ListLock); hence PhUnregisterCallback will have to wait.

And if the particular registration wasn't yet processes it will encounter         if (registration->Unregistering)    continue;

And as it than never moves to the next listEntry as listEntry = listEntry->Flink is never called it will loop forever waiting for registration->Unregistering to become false again which it never will.

BAM Deadlock.

**Comment by dmex** [comment]
> PhUnregisterCallback sets Registration->Unregistering = TRUE;
and then waits for: PhAcquireQueuedLockExclusive(&Callback->ListLock);

This could be fixed by moving Unregistering = TRUE inside the ListLock?

> it than never moves to the next listEntry as listEntry = listEntry->Flink is never called it will loop forever waiting for registration->Unregistering

Its unlikely that this would happen because no deadlocks have ever been reported and unregistering callbacks are very limited 🤔
