### ISSUE TITLE
Possible issue with FindNetworkAdapters

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#445]
In netoptions.c FindNetworkAdapters, when using Context->UseAlternateMethod == true
the returned list of adapters contains a huge amount of virtual filter adapters, when removing the flag GAA_FLAG_INCLUDE_ALL_INTERFACES from ULONG flags, it creates a much more reasonable list.

Is this behavior of listing all virtual filter adapters intended? Or is that a bug?

Imho the user does not benefit from seeing the traffic of his actual adapter ~5 times under slightly different names.
Also its a hindrance if one would want to sum up the traffic of all adapters and provide a global graph for network using this source of data instead, as its currently done, using the ETW monitoring.

**Comment by dmex** [comment]
> Is this behavior of listing all virtual filter adapters intended?

Yes. The original version of the plugin was named NetAdapters and used that method to enumerate the adapters on the machine. The plugin was later merged into the HardwareDevices plugin which uses the newer PnP configuration manager interfaces to enumerate adapters.

> the user does not benefit from seeing the traffic of his actual adapter ~5 times under slightly different names.

These other adapters are not visible by default so any usability issues are not an issue. 

There are feature cases where some users needed to monitor a specific virtual adapter vs the physical adapter and users did complain when it was removed from the newer plugin. It was decided that this feature would remain in the newer version to preserve compatibility with the original plugin and the users preferences. 

> Also its a hindrance if one would want to sum up the traffic of all adapters and provide a global graph for network using this source of data

This plugin was designed for monitoring specific adapters considering the alternative of motioning of all network adapters is already implemented using the ExtendedTools plugin.

**Comment by DavidXanatos** [comment]
I see, thanks
