### ISSUE TITLE
Suggestion: Display Explanation text in tool-tip

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#446]
Where possible/relevant, it would be great to get a tool tip to display info on a column or value being displayed.
When possible, perhaps the explanation text from performance monitor counters could be used?

Also, if each column and value got it's own unique ID , there could be an XML file with meta data on that property.
Step one could be to just assign unique IDs and create an empty XML  file template entries for each unique ID.

Then the community could help out providing explanations and other metadata.

Possible Metadata _(in no specific order, and without any serious thought or consideration...just food for thought)_:
1. DisplayName
2. ShortDescription
3. LongExplanation
4. Category (column, 
5. ValueUnit (second, "counter", MemorySize, ...)
6. ValueType (TotalCount, DeltaCount, TotalTime, DeltaTime, ...)
7. RelatedSeeAlsoList (list of other IDs that might be interesting together with this)
8. ValueExpectedNormal (What is the numeric value typically expected. tricky, could be different depending on hardware, OS version and so on....perhaps a "lambda")
9. ValueAbnormalLow (see 8)
10. ValueAbnormalHigh (see 8)
11. PerformanceCounterName (if applicable)

**Comment by Bartolomeus-649** [comment]
Another thought popped-up...

The xml-file could also contain definitions of "Dynamic Views", which would appear in the application under the new "dynamic view" menu, where you could open them up as modeless windows (with an option to make them top-level-windows, so thy don't minimize together with the main window)

**Comment by dmex** [comment]
> display info on a column or value being displayed

Can you give some examples of what values would need a description?

**Comment by Bartolomeus-649** [comment]
Pretty much all of them. For example, the explanation text for perf-counters contain info like it is a momentary value or average.
Also, in the case of counters that are combination of other counters, you sometimes are told which they are.
On page faults and such you get to know if they are hard or not.

**Comment by dmex** [comment]
> Pretty much all of them

There isn't much amiability about what they show. All columns are either raw values or deltas?

**Comment by Bartolomeus-649** [comment]
Not sure I agree with you on that, just take CPU, it seems like a straight forward value, right?
Still, there's a rather long description for the `Processsor\Processor Time` performance counter:
> % Processor Time is the percentage of elapsed time that the processor spends to execute a non-Idle thread. It is calculated by measuring the percentage of time that the processor spends executing the idle thread and then subtracting that value from 100%. (Each processor has an idle thread that consumes cycles when no other threads are ready to run). This counter is the primary indicator of processor activity, and displays the average percentage of busy time observed during the sample interval. It should be noted that the accounting calculation of whether the processor is idle is performed at an internal sampling interval of the system clock (10ms). On todays fast processors, % Processor Time can therefore underestimate the processor utilization as the processor may be spending a lot of time servicing threads between the system clock sampling interval. Workload based timer applications are one example  of applications  which are more likely to be measured inaccurately as timers are signaled just after the sample is taken.

Another example, CPU Cycles, I can't find any perf-counter for it, perhaps it's a calculated value based on time and cpu-frequency?  Or perhaps you use `rdpmcin` a clever way?

If you just look/use the data to monitor private personal non-technical use of your computer, then I agree, you probably don't need more details then what you can intuitively infer from the column names, but when you are troubleshooting or trying to understand why something really behave the way it does, you need to know what the values actually measure.
And since PH has so many more features than for example the Prformance Monitor, you often end up using it.

**Comment by dmex** [comment]
Related topic: https://github.com/processhacker/processhacker/discussions/1078#discussioncomment-2254342
