### ISSUE TITLE
Process Hacker shows a different value for Cache WS as Windows Task Manager

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#450]
Process Hacker does not show properly the amount of memory used for caching by the OS.
For example, it says Cache WS: 588MB, while Windows Task Manager says In Cache: 42GB
It would be great to have a fix for that.

**Comment by dmex** [comment]
The 'cached' memory value shown by Task Manager is not the same as the 'Cache WS' value shown by Process Hacker. 

Windows Internals, 6th edition, page 346
![image](https://user-images.githubusercontent.com/1306177/62403179-eb795a80-b5ce-11e9-8d33-79f075c75b7a.png)

Process Hacker shows the exact same values as Process Explorer 😉

**Comment by DavidXanatos** [comment]
ah I see, thanks :-)

**Comment by Biswa96** [comment]
> Windows Internals, 6th edition, page 346

Did you read all of them, word-by-word? 🤯
