### ISSUE TITLE
Can't replace Task Manager with Process Hacker annymore

### ISSUE THREAD

**Issue by RedstoneMedia** [processhacker/processhacker#452]
I can't replace Process Hacker with the Task manager annymore, even after starting Process Hacker with admin rights.

This is the error im getting :
![well_this_happend](https://user-images.githubusercontent.com/34373974/62415748-24491c00-b62f-11e9-9fb7-25023ad19428.PNG)

The "Zugriff Verweigert" is just german and means acces forbidden .

Today 03.08.2019 it just changed back to the Task Manager and I can't change it back annymore .

Is this a bug in Process Hacker or some wierd Windows behavior ?

**Comment by dmex** [comment]
Update to latest nightly build 👍
