### ISSUE TITLE
Why is PhGetTokenElevationType re-checked? can it change?

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#455]
I wonder why is PhGetTokenElevationType called when updating process items, can the elevationType os a process change at run time?

Same question for PhGetTokenUser a few 10 lines further up in procprv.c the user a process is assigned to shouldn't change at run time, so why re query this values, it would be enough to do that once when a new processItem is added, or am I missing something?

Since we are at it... 
if we have processExtension we have the field JobObjectId which when the process is assigned to a job is != 0 hence we only need to query the processes Job Data if that value is not 0. 

just a few thoughts to improve on CPU usage....

**Comment by dmex** [comment]
> shouldn't change at run time, so why re query this values, it would be enough to do that once when a new processItem is added, or am I missing something?

https://stackoverflow.com/questions/5141997/is-there-a-way-to-set-a-token-for-another-process/13066468#13066468

**Comment by DavidXanatos** [comment]
From the stackoverflow question

> Yes, you can, using the undocumented NtSetInformationProcess function, however once the process has started running the process token is locked and can no longer be modified. You must therefore start the process with the CREATE_SUSPENDED creation flag, set the process token, then resume the process using ResumeThread(). 

So its almost as I thought just with a catch 22... the trick with CREATE_SUSPENDED 
Hence the best course of action would be to have a flag process started which gets set to true once the process has been seen in any other sate than suspended.

Or has > 1 thread, or can I CREATE_SUSPENDED and than inject a thread into it resulting in a still suspended process with a changeable token and two threads inside?

Anyhow...
Once we see the flag has been triggered, we can stop re querying these token Information.


Also whats with using JobObjectId top or flop?

**Comment by diversenok** [comment]
@DavidXanatos 
As dmex said, it is possible to alter a primary token on early stages of process' life. Sandboxie, for example, does it with all processes running under its supervision. By re-querying tokens, we make sure that program can't trick PH show outdated low-privileged tokens while they use highly-privileged ones.

> Or has > 1 thread, or can I CREATE_SUSPENDED and than inject a thread into it resulting in a still suspended process with a changeable token and two threads inside?

Creating the second thread also locks the primary token. Though, Windows Internals states that it happens unless the process is a POSIX subsystem process.

> Can the ElevationType of a process change at run time?

In fact, yes. Elevation type is not a property of a token itself — it's more a property of a token's logon session. When we say that a token has a linked token we mean that its logon session has a linked logon session, so querying linked token duplicates a token of a linked logon session.

If you have SeCreateTokenPrivilege, you can manually link logon sessions using `NtSetInformationToken` with `TokenLinkedToken` information class. It changes elevation type of both logon sessions and so of all tokens that reference them. That's how UAC sets elevation type internally and why we should not cache it.

**Comment by DavidXanatos** [comment]
I see...

So there is nothing about a token that can be safely cached even after the process started
PhGetTokenUser, PhGetTokenOwner, PhGetTokenPrimaryGroup, PhGetTokenSessionId, PTOKEN_APPCONTAINER_INFORMATION
???

**Comment by diversenok** [comment]
Not really. You can cache almost everything, but after doing so, you need to query 
TOKEN_STATISTICS to monitor Modified ID, and be ready to invalidate the cache if it changes. If you also want to cover the case when the whole token gets replaced, use a pair of Token ID + Modified ID to identify it.

On Windows 7 it will cover everything except session ID, elevation type, and token flags (from TOKEN_ACCESS_INFORMATION). On later versions, it may also include some newer information classes.
