### ISSUE TITLE
Some processes have invalid image timestamps

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#456]
Some processes have invalid image timestamps, see the screanshot:
![badtimestamp](https://user-images.githubusercontent.com/3890945/63186891-d33d1d00-c05d-11e9-8502-953d83ae7e7d.png)

I know the files in question probably just provide an invalid value, but it would be nice to detect that and in such case show an empty string instead.

**Comment by dmex** [comment]
> show an empty string instead

You can't really determine whats an 'invalid' value:
https://devblogs.microsoft.com/oldnewthing/20180103-00/?p=97705

**Comment by DavidXanatos** [comment]
oh I see thanks
