### ISSUE TITLE
Error while compiling 

### ISSUE THREAD

**Issue by Zenek-Hastro** [processhacker/processhacker#459]
Hi, when i try to compile, vs report me this:

https://prnt.sc/owh7yv

**Comment by dmex** [comment]
You're probably missing the Windows SDK
________________________________

**Comment by Zenek-Hastro** [comment]
i already have install it, right now !

**Comment by Zenek-Hastro** [comment]
https://prnt.sc/owhdpz

**Comment by Zenek-Hastro** [comment]
Probably i have found a soluction!

I have installed the SDK Package directly from MSsite... but if you start the "Visual Studio Installer" you can see other version of the program SDK. Which version is the correct ? 

https://prnt.sc/owhl6v

**Comment by dmex** [comment]
Does the \build\build_debug.cmd script successfully complete the build?
________________________________

**Comment by Zenek-Hastro** [comment]
No, there is the console warning:

> 


[Warning] Git not installed.
Version: 3.0.0

[00:00] Building ProcessHacker (x32)...
[ERROR] D:\Visual Studio\IDE\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(67,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found. To build using the v142 build tools, please install v142 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\PH-Source\phlib\phlib.vcxproj]
Press any key to continue . . .

**Comment by Zenek-Hastro** [comment]
I already have tryed to retarget the application and change it into the 17763 versione of SDK, but seems not wrok

**Comment by Zenek-Hastro** [comment]
I have fix it: just need to install the vs2019 version with last SDK version 1.7.... last question is, how can i change the name of the process in taskmanager ?

**Comment by dmex** [comment]
> how can i change the name of the process in taskmanager ?

Rename the file?

**Comment by Zenek-Hastro** [comment]
yea, i mean ... i have successfully renamed the exe file, but it still appear as "process hacker", it is a bad stuff cause some protection detect it!

https://prnt.sc/ox7yr1
