### ISSUE TITLE
NtQueryInformationFile hangs for "File" "\\Device\\VolMgrControl" on windows 7

### ISSUE THREAD

**Issue by DavidXanatos** [processhacker/processhacker#460]
When searching handles and finding "\\Device\\VolMgrControl" i cant open its proeprties, it seams it hangs at NtQueryInformationFile , below this commend:
// NOTE: NtQueryInformationFile for '\Device\ConDrv\CurrentIn' causes a deadlock but

same issue with querying fileStandardInfo and filePositionInfo

the problematic device type is FILE_DEVICE_NETWORK

also when FileStandardInformation and or FilePositionInformation on windows 10 (1903) while it does not hang, it returns success while not writign anythign to the buffer i.e. we end up with garbage.

I think we should change the check 
if (isPipeHandle || isConsoleHandle)
to 
if(!isFileOrDirectory)

and when querying file position and size add the same check

**Comment by dmex** [comment]
Fixed 1cf148f94131e72c49fe84fb31507a76409ccda0
