### ISSUE TITLE
Notification icon pop-up prevents access to notification icon

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#461]
When you move the mouse cursor over the PH Notification Icon in the Notification Area, it pops-up a window which covers the notification icon hence preventing access like dubble clicking it to open PH.
I see to solutions that would work independently, but should probably both be implemented.
1. Introduce a delay before the notification icon initiates the pop-up.
2. Position the pop-up in such a  way that it don't block the notification icon.

Care must be taken to not remove the pop-up to fast so you can move the mouse cursor from the notification icon to the popup without it disappearing, but at the same time not keep it open so long or in a way which prevent access to other notification icons.

![image](https://user-images.githubusercontent.com/7513795/63690495-168d4d80-c80d-11e9-851a-df16b9b36d5c.png)

**Comment by dmex** [comment]
IMO the changes required to work-around systray differences and popups and various user taskbar locations and preferences between Win7 and Win10 is just way too messy.

The easiest fix is simply un-hiding the tray icon so it remains visible on the taskbar.
