### ISSUE TITLE
Issues when searching for windows...

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#462]
When you search for a window the list is actually _filtered_, and any window not matching the search text is removed. 

1. When searching, any parent window of those matched should be shown in the list (recursive).

2. When you have searched and have a window selected and active in the search list, and you cancel the search, then when the complete list of ll windows is shown again the selection should be preserved and scrolled into the visible part of the list.

3. There should be a way to do what's traditionally called a search, that is, you should highlight the matches and be able to move back and forth between the found matches. Perhaps a radio-button next to the "search field": Filter | Search ?

**Comment by dmex** [comment]
1) Ends up showing too many unrelated entries to the search.
2) The selection is already preserved but the view doesnt get scrolled because searching often changes the position of entries.
3) The support for this there but its already being used for showing details about the entries.
