### ISSUE TITLE
Suggestion: All lists to Excel

### ISSUE THREAD

**Issue by Bartolomeus-649** [processhacker/processhacker#463]
It would be really great if any list, no matter what it show/contain, could always be exported(copied) to Excel. 
A quick and easy way to do it that would be enough is to just copy the list to the clipboard as normal text, with `<tab>` separating columns, and `<newLine>` separating rows, then Excel will handle it, and will paste it into rows and columns correctly. Enclose every value in double quotes (i.e. "value") and it will handle both newlines and tabs in values. The escape character for double quote is a double quote, i.e. `data"moreData` becomes `"data""moreData"`
Perhaps the shortcut could be: : ctrl + L + C  ( **L**ist **C**opy)

**Comment by DavidXanatos** [comment]
Have you already seen my alternative UI for the process hacker library and driver: https://github.com/DavidXanatos/TaskExplorer/releases/tag/v0.8.0
it allows you amongst other things to copy every list panel to clipboard as coma separated lists.
And it has a really nice search feature that allows you to choose between filtering and highlighting.
Any many other useful improvements.

**Comment by Bartolomeus-649** [comment]
The problem with a comma separated list is that Excel can't handle it automatically. You need to use the text import wizard to get that into Excel. 
There is a common misconception that a "comma separated file" consists of columns separated by comma. When it  comes to Excel, a "comma separated file" is separated with whatever is specified as the "List Separator" in the Windows Regional Configuration in Control Panel.
So, double-clicking a "comma separated file" in windows, will get you the entire content for each row in the A-column in Excel. Ant it pork the same with data being pasted into Excel. The only Way to really get to work, no matter the Regional settings or anything other is to use tab to separate data.

A lot of countries round the world, including Sweden where I'm from, do not have the comma as the list separator as in USA. Here in Sweden comm is used as the decimal character in numbers.
This also leads to things like we have to write/call functions in Excel by using semi-colon to separate the function arguments (`=Max(12;42;17)`).

**Comment by dmex** [comment]
> The problem with a comma separated list is that Excel can't handle it automatically.

It does but the CSV data needs to be in the correct format before Excel can display the data properly.

**Comment by DavidXanatos** [comment]
hmm... good point I will change it to tabs for the next build or so.
