### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [processhacker/processhacker#464]
I would like to point out that identifiers like “[`_PH_MODULE_NODE`](https://github.com/processhacker/processhacker/blob/a8ecb36740f4e43b0d9d01fa5e98578e01482435/ProcessHacker/include/modlist.h#L35 "Update candidate")” and “[`_SERVICE_INFO`](https://github.com/processhacker/processhacker/blob/d798340d9de204a751d856803017a861ecaff90e/plugins/OnlineChecks/onlnchk.h#L54 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by Biswa96** [comment]
99% of Windows structures and enumerations declaration follows that style. After all you are not using that name in code because its just typedef to another _name_.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
