### ISSUE TITLE
Notifications not shown

### ISSUE THREAD

**Issue by ferenczy** [processhacker/processhacker#465]
ProcessHacker is not showing system tray notifications about starting and exiting processes and/or services. It used to work (potentially long) before.

I have a very simple configuration for both processes and services:

![process notifications configuration](https://user-images.githubusercontent.com/1712992/64175996-cccfe300-ce5c-11e9-929e-4ac802f3cce8.png)

The _Notifictions - Logging_ is working fine, all events are being successfully logged.

Also, I have _Send notifications to Growl_ enabled on the _Notifications - Growl_ tab, but it's not working either. I have Snarl (compatible with Growl) configured so it's capturing both Windows' system tray and Growl's notifications, but ProcessHacker is not sending notifications in any way.

Windows 7 Ultimate 64-bit
ProcessHacker 3.0.2582

**Comment by dmex** [comment]
I can't reproduce
