### ISSUE TITLE
Make the portable version a single file

### ISSUE THREAD

**Issue by amithegde** [processhacker/processhacker#467]
Including all files in one binary makes it easier to copy around.

**Comment by dmex** [comment]
A single file significantly increases the number of false positives by 'anti-virus' while also making the binary easier to detect and block by 'legitimate' and illegitimate software.

As it stands there are 14 major security and gaming companies right now either blocking various binaries from the project, injecting code to conceal information about your machine or data mining usage of Process Hacker and a single binary would make it too easy.
