### ISSUE TITLE
Slow UI (requires multi-threading)

### ISSUE THREAD

**Issue by dennisbabkin** [processhacker/processhacker#471]
Some new features in the Properties -> Inspect tabs need to be moved to a worker thread. Otherwise the preview window may hang for an abnormally long amount of time, especially on a slower computer.

Examples are: CFG tab, Exports or Imports tabs that require longer resolution.

I recorded a [demo video](https://youtu.be/Ws1ZNHyeESs).

[![Demo video](https://img.youtube.com/vi/Ws1ZNHyeESs/0.jpg)](https://youtu.be/Ws1ZNHyeESs)

(Due to my previous testing before recording some tabs opened quite quickly -- possibly since they were already cached in RAM. But the issue is clearly shown somewhere in the middle of that video.)

Running tests on Windows 10 x64 (latest updates installed as of today).
Process Hacker v.3.0.2584

**Comment by dmex** [comment]
Fixed in latest nightly 👍
