### ISSUE TITLE
Hanging CFG tab in Inspector window for a process built with /guard:cf

### ISSUE THREAD

**Issue by dennisbabkin** [processhacker/processhacker#472]
Building an image file with Control Flow Guard enabled and then opening its process in Inspect -> CFG tab hands up the preview process (indefinitely.)

The following [demo video](https://youtu.be/rNvDAtLAWjM) shows the steps:

[![Demo video](https://img.youtube.com/vi/rNvDAtLAWjM/0.jpg)](https://youtu.be/rNvDAtLAWjM)

Was running the test on:
Windows 10 x64 (w/latest updates)
Process Hacker v.3.0.2584

**Comment by dmex** [comment]
The peview thread stacks should show what function blocked the peview UI?

**Comment by dmex** [comment]
This is related to #471
