### ISSUE TITLE
Is the Donate link still current?

### ISSUE THREAD

**Issue by beevvy** [processhacker/processhacker#475]
Clicking Help->Donate, even in the current nightly builds, takes me to wj32's PayPal page. Given that all new development for a couple years now has been done by dmex, I wonder if donating there actually supports continued development of Process Hacker?

**Comment by dmex** [comment]
> Clicking Help->Donate, even in the current nightly builds, takes me to wj32's PayPal page

Is it a problem?

> Given that all new development for a couple years now has been done by dmex, I wonder if donating there actually supports continued development of Process Hacker?

Yes, It does. I don't need donations to continue development (which should be obvious by now) 😄 

@wj32 asked about sharing donations but I refused and asked that they go towards server hosting costs @ https://wj32.org/processhacker and the update servers.

**Comment by beevvy** [comment]
> Is it a problem?
Not at all.

Thanks!
