### ISSUE TITLE
Request: decrease minimum size of "System Information" window

### ISSUE THREAD

**Issue by token0** [processhacker/processhacker#477]
Because it's default minimum size is huge. I would consider to make it as low as 200 px on X-axis.
Thanks!

**Comment by dmex** [comment]
What size screen are you using?

**Comment by token0** [comment]
24" WUXGA

**Comment by token0** [comment]
Well, built it with this changes, now I'm happy.
sysinfo.c @425-426
```
- MinimumSize.right = 430;
- MinimumSize.bottom = 290;
+ MinimumSize.right = 43; //430
+ MinimumSize.bottom = 29; //290
```

**Comment by dmex** [comment]
Duplicate of #659
