### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by iMpervert** [processhacker/processhacker#479]
Can & how i move "`Reduce working set`" in miscellaneous to Main menu. i use alot. it very useful for someone have computer small ram. or keyboard shortcut key..

**Comment by VictorVG** [comment]
Yes, this command is needed, but why not drag everything into the main menu. Enough of a hotkey.

**P.S.**

And so, I didn’t see much benefit from it when I tried to reduce the memory size of the SeaMonkey x86 process from 1.8 - 2 GB when the browser almost stopped responding to commands ("thanks" Adobe for Flash v10 + - went to the site de it is used and get a local DoS attack), and for other processes as well. :)

It is more suitable for complacency of the user, and to reduce the size of the program memory they say it’s worth setting them up, and if they are compressed by some kind of packer like PECompack, UPX then unpack them if possible.

The same UPX uses from 6 to 16 MB of RAM for each binary compressed by it to unpack it. Therefore, I almost abandoned the use of packers of executable modules in my projects. It is better to optimize the binary at the compiler level than to solve problems arising from their packaging afterwards.

**Comment by Syst3mSh0ck** [comment]
> Yes, this command is needed, but why not drag everything into the main menu. Enough of a hotkey.
> 
> **P.S.**
> 
> And so, I didn’t see much benefit from it when I tried to reduce the memory size of the SeaMonkey x86 process from 1.8 - 2 GB when the browser almost stopped responding to commands ("thanks" Adobe for Flash v10 + - went to the site de it is used and get a local DoS attack), and for other processes as well. :)
> 
> It is more suitable for complacency of the user, and to reduce the size of the program memory they say it’s worth setting them up, and if they are compressed by some kind of packer like PECompack, UPX then unpack them if possible.
> 
> The same UPX uses from 6 to 16 MB of RAM for each binary compressed by it to unpack it. Therefore, I almost abandoned the use of packers of executable modules in my projects. It is better to optimize the binary at the compiler level than to solve problems arising from their packaging afterwards.

Are you on drugs or is this just some kind of copy pasta? lol

**Comment by dmex** [comment]
> some kind of copy pasta

Google translate 😲

**Comment by Syst3mSh0ck** [comment]
Apologies.

**Comment by dmex** [comment]
> Apologies.

It's just spam. No use, no value and makes no sense to anyone.

**Comment by dmex** [comment]
> Can & how i move "Reduce working set" in miscellaneous to Main menu

You would need to change this line:
https://github.com/processhacker/processhacker/blob/de5b6d97f227bdcf61dd49b41f3cf809a9c60b2f/ProcessHacker/mwpgproc.c#L737

Moving it here would make it the main menu:
https://github.com/processhacker/processhacker/blob/de5b6d97f227bdcf61dd49b41f3cf809a9c60b2f/ProcessHacker/mwpgproc.c#L700-L707

> keyboard shortcut key

It doesn't currently have a hotkey. What button would you use?
