### ISSUE TITLE
Mitigation Policies window is missing ProcessChildProcessPolicy

### ISSUE THREAD

**Issue by dennisbabkin** [processhacker/processhacker#480]
Using v.3.0.2610.

The process Mitigation Policies window seems to be missing the [`ProcessChildProcessPolicy`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntddk/ns-ntddk-_process_mitigation_child_process_policy):

![Capture1](https://user-images.githubusercontent.com/25473659/65813212-e11aad80-e186-11e9-8d36-c68cc1ec4250.PNG)

**Comment by dmex** [comment]
The code is there for showing the values but Windows might not expose the policy to user-mode:
https://github.com/processhacker/processhacker/blob/master/ProcessHacker/procmtgn.c#L466-L481

**Comment by dennisbabkin** [comment]
OK. My apologized. It was actually in this version:

![Capture1](https://user-images.githubusercontent.com/25473659/65828958-71bfbf00-e255-11e9-8c17-802155da92ce.PNG)
