### ISSUE TITLE
v.3.0.2610 (nightly build) does not save previous location & size of the main window

### ISSUE THREAD

**Issue by dennisbabkin** [processhacker/processhacker#481]
This nightly build doesn't seem to remember/save the previous main Process Hacker window location & size on the screen and resets it upon every launch:

![Capture1](https://user-images.githubusercontent.com/25473659/65829002-cb27ee00-e255-11e9-9b04-9470f1f6a902.PNG)

**Comment by VictorVG** [comment]
Not confirmed. Try checkif IsConfigReadOnly. Example cuse CMD console and type this OS command

cd /d <Proceess Hacker config dir > 
attrib *.settngs,xml

and read attrib output. Files this your see "_R_" symbol is read only. Then use command  _attrib -r filename_. Also your can don't have write rings to PH config - then edit ACL use any OC tools.

But, possible your have locally source for this problem...

**Comment by dennisbabkin** [comment]
@VictorVG Oh, I see what’s going on. If it’s saving its configuration in a file in its installation folder, and if such folder is %ProgramFiles%, the config file will not be accessible for writing if PH was not started as administrator.

 I’m not sure if this was intentional, but it might be better to save configuration file in the %appdata% folder instead.

**Comment by VictorVG** [comment]
By default config save to %appdata%. And% ProgramFiles% is not writable by users - see its ACL. Otherwise, someone will make mistakes. "Foolproof", albeit effective.

**Comment by dennisbabkin** [comment]
@VictorVG that's what makes it **not save** previous window location if PH **is not** started under administrative account. I wouldn't call it "_albeit effective_" though.

**Comment by VictorVG** [comment]
Process Hacker source, ./ProcessHacker/main.c::1038:
```
    if (!PhStartupParameters.NoSettings)
    {
        static PH_STRINGREF settingsPath = PH_STRINGREF_INIT(L"%APPDATA%\\Process Hacker\\settings.xml");
        static PH_STRINGREF settingsSuffix = PH_STRINGREF_INIT(L".settings.xml");
        PPH_STRING settingsFileName;

        // There are three possible locations for the settings file:
        // 1. The file name given in the command line.
        // 2. A file named ProcessHacker.exe.settings.xml in the program directory. (This changes
        //    based on the executable file name.)
        // 3. The default location.
```
