### ISSUE TITLE
PH cann't download GeoLite-Country2 DB after update MaxMind required to TLS/1.2+ or letter. 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#484]
All version PH cann't download MaxMind GeoLite-Country2.tar.gz then [**MaxMind**](https://blog.maxmind.com/2019/04/12/important-updates-about-tls-v1-0-v1-1-unencrypted-http-requests-and-the-legacy-minfraud-soap-api/) wrote:

> **October 16, 2019:**
> We retired support for TLS v1.0/v1.1 and unencrypted HTTP requests to minFraud services on October 16, 2019, as part of our commitment to securing and protecting your data. Please ensure you are using TLS v1.2+ to connect to MaxMind services.

If use any WWW browser and support TLS/1.3 (example if in to user OS installed OpenSSL v1.1.1.4 Toolkit (Open SSL 1.1.1d)), then user can manually download DB and unpack tarball in to PH dir, other user can't download it. 

MaxMind company work in progress - https://status.maxmind.com/ and using sniffer I see that TLS 1.3 orther OpenSSL 1.1.1.4 is supported by remote  host, but PH use system transport have only TLS/1.1+ support and cann't connect to MaxMind server - the company cares about the safety of users, and at the same time about its own income as even from the office of a contract with them it was not possible to download the database through the "system Tarnsport + TLS 1.2" connection, but they sent us a letter about the suspension of the "dummy client" service.

The server terminated the connection either at the establishment stage or during data transfer. A minimum of TLS 1.3 is required to connect with them, and if the protocol version is lower, they consider the connection “not secure” and disconnect at any time.

P.S.

At least today, their representative took a moment to confirm this, but first he demanded from us papers confirming that we were us, so much that several railway trains would be required for their transportation, and that each one had a seal of the Heavenly Chancellery certified with a signature and by a personal stamp of St. Peter, they say otherwise they can not verify the authenticity of the client. :)

**Comment by dmex** [comment]
You'll probably have to install KB3140245 on Windows 7:
http://catalog.update.microsoft.com/v7/site/search.aspx?q=kb3140245

**Comment by VictorVG** [comment]
I solved the problem with MaxMind, although the hint did not work - updating kb3140245 does not include TLS 1.2, although it was installed.

The solution turned out to be simpler, but I had to tinker:

1. put OpenSSL 1.1.1d (OpenSSL v1.1.1.4) - it is his libraries that provide support for TLS 1.3 which is not in the OS itself.

2. We import into the Registry (the values are taken from an article on the Microsoft website  [***Update to enable TLS 1.1 and TLS 1.2 as default secure protocols in WinHTTP in Windows**](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2 -as-default-secure-protocols-in-wi) script:

```
REGEDIT4

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
"DefaultSecureProtocols"=dword:00000a80

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
"DefaultSecureProtocols"=dword:00000a00

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Internet Settings]
"SecureProtocols"=dword:00000a80
```
we put the PH v3.0.7163.2636 Git-ffea1dc8 and everything works. Just checked on two machines. The second recommended update kb3140245 is not at all, only entries in the Registry and OpenSSL 1.1.1.4 were enough.

Big thanks! Thank you so much for the tip - she helped me find the right solution.

**Comment by dmex** [comment]
> put OpenSSL 1.1.1d (OpenSSL v1.1.1.4)
> We import into the Registry script

No

> put the PH v3.0.7169.2642 Git-082bb8f9 and everything works

If it was the correct way of fixing the problem then I would have already done this 😉

**Comment by VictorVG** [comment]
This is understandable, but now my friend answered the ru-board, who first drew attention to the problem:

> **ozr1**
> 
> to **Victor_VG**
> 
> "[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp]
> "DefaultSecureProtocols" = dword: 00000a00
> 
> Is there definitely no typo here? By analogy with the other keys listed, IMHO, 0x0a80 is suggested instead of 0x0a00 ... "
>  
> By the way, I did not install OpenSSL 1.1.1.x - and without it everything worked: apparently, support for TLS 1.2 was enough.
> 
> And the last of the listed keys in the registry was already present - apparently, it was registered at the next update of Windows ... Update kb3140245 I have - from the build package UpdatePack7R2. 

I can’t say for sure that KB3140245 is not required so it could be installed as part of other OS patches, but it seems that besides it, it is also necessary to adjust the Registry either manually or by downloading and running the MicrosoftEasyFix51044.msi utility, although I personally did everything manually - my own hand lord. :)

**Comment by dmex** [comment]
> I can’t say for sure that KB3140245 is not required

You don't need the patch since I fixed the version checks.

**Comment by VictorVG** [comment]
Big thanks!
