### ISSUE TITLE
Empty space right to processor name where clock rate should be

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#486]
I think clock rate should be here: 
![YLInKUM 1](https://user-images.githubusercontent.com/3091645/67166413-c7d8db80-f397-11e9-8308-91d1394349ac.png)

**Comment by dmex** [comment]
What does Task Manager show?

**Comment by TETYYS** [comment]
@dmex shows the speed normally, it changes each refresh.

**Comment by TETYYS** [comment]
Still empty space on 7ec0b104

**Comment by dmex** [comment]
Can you post some screenshots?

**Comment by TETYYS** [comment]
![ProcessHacker_lfgpnLyZeU](https://user-images.githubusercontent.com/3091645/67945145-e2f0ea00-fbe6-11e9-88eb-dd26716e048a.png)
![Taskmgr_mq2AigJ8os](https://user-images.githubusercontent.com/3091645/67945174-f00dd900-fbe6-11e9-9415-61e363d7a42d.png)
Other processor:
![aHX8Xo5 1](https://user-images.githubusercontent.com/3091645/67945345-5692f700-fbe7-11e9-9c1a-fc42e407bc14.png)
![NO8zhs4 1](https://user-images.githubusercontent.com/3091645/67945359-5f83c880-fbe7-11e9-89eb-885677ba02db.png)
