### ISSUE TITLE
Is there an automatic method i.e. Command Line option for Process Hacker?

### ISSUE THREAD

**Issue by gaveitatry02** [processhacker/processhacker#490]
I'm new to injecting dlls, so I have never used command line injections before.  But I think that is what I need/want.

Currently, it is necessary for me to have Process Hacker pinned to the taskbar for easy access, but I would prefer to not have it on the taskbar.  Then I have to click the icon to launch the program.  Then I have to type in the Search Processes search box for the program that I want to inject.  Then I have to wait a while for the search results to appear.  Then I have to right-click a search result and select Miscellaneous.  Then I have to select Inject DLL.  Then I have to select the dll that I want to inject and confirm.  That's a lot of steps.

I would just like to use a macro.  Like press the F1 key and have it automatically inject the dll into the program without me having to do anything.  Using a bat file or something similar.  Can that be done with Process Hacker?  I found an old thread back in 2012 where some guy claimed to have made a patch "Command line DLL injection support (patch inside)" [https://wj32.org/processhacker/forums/viewtopic.php?t=829](url) that does something like that, and the owner wj32 claims to have added the features to the latest version of Process Hacker.  That was 7 years ago.  If it is a feature, how do I access and use it?

**Comment by dmex** [comment]
> wj32 claims to have added the features to the latest version of Process Hacker. That was 7 years ago. 


[Remove dll injection feature](https://github.com/processhacker/processhacker/commit/02b2c0afcb1117f6cbab0ba4280c074c65286fd5)
