### ISSUE TITLE
Qestion - What causes the grouping under one icon of several running at AllowOnlyOneInstance = 0 from one image of copies of Process Hacker?

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#491]
Exist up to v3.0.7207.2680 Git-178a04a0 in to Win7 x64 and Win 8.1. In to Win10 has not yet sent observations, so I don’t know what to say.

_If AllowOnlyOneInstance = 0 and several copies of Process Hacker are launched from the same image, then when minimized to tray they are grouped under the same icon, and in the process list we see all running copies with different PIDs._

Previously, I did not pay attention to this, but forum.ru-board.com was asked what it is, but I don’t know what to answer.

**Comment by dmex** [comment]
The system tray remembers the position and location of tray icons but wasn't designed for multiple instances of the same program.

**Comment by VictorVG** [comment]
Ok!

**Comment by maxvlas** [comment]
> Системный трей запоминает положение и расположение значков в трее, но не предназначен для нескольких экземпляров одной и той же программы.

[b]Process_Hacker_v3.0.0.118_RUS[/b] 4 запустил, закрыл и в трее 4 иконки
[url=https://funkyimg.com/i/2Y4rx.png][img]https://funkyimg.com/p/2Y4rx.png[/img][/url]
https://www33.zippyshare.com/v/HPGzEHBd/file.html
[b]ProcessHacker-v3.0.5462.935_RUS_старое_окно_настроек[/b] 4 запустил, закрыл и в трее 4 иконки
[url=https://funkyimg.com/i/2Y4rx.png][img]https://funkyimg.com/p/2Y4rx.png[/img][/url]
https://www76.zippyshare.com/v/AY1vEYeM/file.html
