### ISSUE TITLE
Could not find all GDIs

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#492]
In main window in Processes tab right click to some process, select Miscellaneous sub menu, select GDI Handles menu, GDI Handles window appears. Notice, that it doesn't show all GDI objects the target application allocated.

This is because Process Hacker scans only GDI_MAX_HANDLE_COUNT handles which is 0x4000 or 16384 or 16k. This is the default limit for maximum GDI handles. But according to [1] this limit can be increased up to 0xFFFF or 65535 or 64k. I created small test program [2] that exercises this limit. It allocates 1000 GDI objects, waits for the user to press any key, then allocates another 50000 GDI objects and waits for the user to press any key. If it fails to create any GDI object, it disappears and doesn't wait for the key press. I tested this program on my Windows 7 x86 virtual machine with increased GDI objects limit. It succeeded to allocate all objects, but Process Hacker (latest version 3) failed to recognize all of them. I changed the GDI_MAX_HANDLE_COUNT value in file \processhacker\phnt\include\ntgdi.h, line 24 to 0xFFFF, recompiled Process Hacker and it succeeded to recognize all 51000 handles my test program allocated.

I have only small problem: I don't know how to determine size of GdiSharedHandleTable referenced by Process Environment Block. I'm afraid that I could read past array bounds some unrelated memory or even invalid memory and crash Process Hacker. On my test machine I could read all 0xFFFF entries even with default limit without any problem. So increasing the limit inside Process Hacker miiight beee fiiine ... I don't know.

Anyway, I prepared a change to increase this limit inside Process Hacker.

Best Regards,
Marek

[1]
https://docs.microsoft.com/en-us/windows/win32/sysinfo/gdi-objects
[2]
````C++
#include <cstdlib>
#include <windows.h>

int main()
{
	for(int i = 0; i != 1000; ++i)
	{
		HBRUSH gdi_obj = CreateSolidBrush(i);
		if(gdi_obj == NULL)
		{
			return 0;
		}
	}
	std::system("pause");
	for(int i = 0; i != 50000; ++i)
	{
		HBRUSH gdi_obj = CreateSolidBrush(i);
		if(gdi_obj == NULL)
		{
			return 0;
		}
	}
	std::system("pause");
}
````

**Comment by dmex** [comment]
> this limit can be increased up to 0xFFFF or 65535 or 64k.

It can be increased but its very rare that something would be using that many GDI handles these days because GDI is deprecated?

> I don't know how to determine size of GdiSharedHandleTable

You should be able to loop until Object && NextFree == 0x00000000ffffffff which gives you a count. 

The table is shared by all processes so even if you do have a count there will be race conditions enumerating the table.

**Comment by MarekKnapek** [comment]
The loop condition you mentioned didn't work for me, at least not on x86, didn't tried on x64. But I added check for allocated block size, it works fine on both x86 and x64. I updated and re-based my branch.

**Comment by dmex** [comment]
I've added these changes to the latest nightly build 👍
