### ISSUE TITLE
The "Cycles Delta" column actually show "Context Switches Delta"

### ISSUE THREAD

**Issue by yossizahn** [processhacker/processhacker#495]
As the title says.
Here is a demonstration (2 screenshots, second one was taken at the next refresh after the first - I set the refresh rate to 10s to make sure I don't miss a refresh):
1. (snapshot 1)
![image](https://user-images.githubusercontent.com/19174667/67852286-d2703f00-fb14-11e9-8f78-c62055d83384.png)

2. (next refresh 10s later...)
![image](https://user-images.githubusercontent.com/19174667/67852329-e451e200-fb14-11e9-9e17-8b10183ee78f.png)

**Comment by dmex** [comment]
Process Hacker was blocked from querying the thread cycle count and instead you'll see the ContextSwitches delta:

https://github.com/processhacker/processhacker/blob/32cb77f9cd845bc3500ac4488eed89f28447c588/ProcessHacker/prpgthrd.c#L595-L597

https://github.com/processhacker/processhacker/blob/32cb77f9cd845bc3500ac4488eed89f28447c588/ProcessHacker/thrdlist.c#L695-L710

**Comment by yossizahn** [comment]
> antivirus/other issue

1. I have no antivirus installed other than windows defender.
What may "other issue" be?
To be clear I am seeing this on every process on my system.

2. Reverting to context switches is very confusing behavior. Wouldn't it be better to just show nothing? or a indication that the data is inaccessible? How is the user to know what the values represent (without reading the source code)?

3. Why is there no separate column for context switches delta?

**Comment by yossizahn** [comment]
Actually, thinking about it, something doesn't add up here, because as you can see in the picture, the cycle count _is being updated_, so obviously PH has no issue querying the cycle count...

**Comment by yossizahn** [comment]
OK, so I did some debugging...
Here is the bug:
https://github.com/processhacker/processhacker/blob/7ec0b1049d6d876f908b0bbe54f6df2ae6546d73/ProcessHacker/thrdlist.c#L175
This nullifies the `UseCycleTime` flag.
