### ISSUE TITLE
We were told the reason for the transition of KPH3 v3.1 to the SERVICES_STOP_PENDING state when the driver stopped, leading to a blocking of its removal during installation.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#496]
Help answer on [**forum.ru-board.com - Software - Inno Setup**](http://forum.ru-board.com/topic.cgi?forum=5&topic=46338&start=2520#15)

We were told the reason for the transition of KPH3 v3.1 to the SERVICES_STOP_PENDING state when the driver stopped, leading to a blocking of its removal during installation. This is an old problem that I crutched with `If IsDriverRunning (KPH3) Then skip Else Install End;` in the installer PH.

> 
> 
> "So KPH3 is not a curve"
> 
> to **Victor_VG**,
> 
> in DriverEntry, when IoCreateDevice is called, the device pointer is written to the local variable deviceObject, after which this pointer is assigned to the global variable KphDeviceObject. When exiting DriverEntry deviceObject (and therefore KphDeviceObject) will be referenced into space and already in DriverUnload the call IoDeleteDevice(KphDeviceObject) will not lead to anything good.

P.S.

**El sanchez** wrote:

> I fix typo - mast be `IoCreateDevice` in `DriverEntry`, not `IoDeleteDevice`

**Comment by dmex** [comment]
Bad translation
