### ISSUE TITLE
The Handles tab is empty if PH is running in elevated mode

### ISSUE THREAD

**Issue by umokk** [processhacker/processhacker#498]
In normal mode: https://s8.hostingkartinok.com/uploads/images/2019/11/7902e2ee032cce0fc713684cc52b3533.png
In elevated mode: https://s8.hostingkartinok.com/uploads/images/2019/11/ad59afacfb9f4ca29bbd7b8d1ee08104.png

**Comment by dmex** [comment]
Options > deselect kernel driver
