### ISSUE TITLE
Logarithmic scale on tray icon CPU graph

### ISSUE THREAD

**Issue by ygoe** [processhacker/processhacker#500]
I'd find it very helpful to have a logarithmic scale on the tiny tray icon graph for CPU usage. We have CPUs with 8 threads today and will have ones with 32 threads soon. That icon is still 16 pixels tall (maybe a bit more on high-res monitors). It's barely visible or even completely invisible to see one active thread there. But it already makes a big difference whether the CPU is completely idle or working in a single thread. That already increases the power consumption and heat a lot. The other cores/threads don't add as much anymore, so they shouldn't have the same weight in the graph.

The same applies to the equally-tall graphs in the process tree. The bigger separate graph views in the system information window wouldn't need this change.

This might be an option if some users prefer to see the linear usage of their CPU. And the new option may not be available for 1- or 2-thread CPUs since it's not really necessary there.

**Comment by dmex** [comment]
>  It's barely visible or even completely invisible to see one active thread there.

This is by design because the tray icon graph shows the total cpu usage and and a single core/thread running at maximum is not utilizing the total number of processors.

> makes a big difference whether the CPU is completely idle or working in a single thread.

You'll see the graph when it utilizes more than one core?

**Comment by ygoe** [comment]
> This is by design

I'm asking to change exactly that.

> You'll see the graph when it utilizes more than one core?

If this is a question, I don't understand it.

**Comment by ygoe** [comment]
Great user experience, by the way. Thanks for slamming the door right in front of me. :-( @dmex Nothing has improved over the years. At least there was no new release for a while. Seems I can fork this project and add the missing usability feature myself without too much work.

**Comment by dmex** [comment]
@ygoe 

Ok

![image](https://user-images.githubusercontent.com/1306177/69464779-67dcb700-0dd3-11ea-9108-1d6c82142967.png)
