### ISSUE TITLE
Build Tool problem

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#503]
Hello, I've just re-installed OS and noticed some problem. I insalled both visual studio versions - 2017 and 2019. When I run build tool looks like it goes to C:\Program Files (x86)\Microsoft Visual Studio and find the 1st available version there - it's 2017, then it tries to build it using that 2017 version and fails (as v142 doesn't support there).
I had to rename 2017 to _2017 in this folder C:\Program Files (x86)\Microsoft Visual Studio and it fixed the problem.
I only have this problem on a clean OS installation, is it something on my side? Or if you can please fix it please.

**Comment by dmex** [comment]
> it tries to build it using that 2017 version

I recently migrated the BuildTools to .NET core and changed how Visual Studio gets detected.

> 2017 and 2019

This should be fixed in the latest commit 👍

**Comment by skipik** [comment]
I'm sorry, but it didn't help.
That's how it looks like:
![111](https://user-images.githubusercontent.com/24621645/69014975-82143080-09a0-11ea-8cf1-ff01a8ca9078.png)

vswhere.exe shows 2019 as the latest installed VS

**Comment by dmex** [comment]
@fengjixuchui 

You need to stop spamming the issue tracker with commit messages.

**Comment by ge0rdi** [comment]
@dmex 
You need to update `ProcessHacker.sln` so that it is opened by VS2019 by default.
Right now it has `Visual Studio 15` which means VS2017.

Unfortunately VS doesn't automatically update SLN when opened with new version.
You need to open it in VS2019, click on solution in Solution Explorer and save manually (Ctrl+S).

**Comment by dmex** [comment]
> Right now it has Visual Studio 15 which means VS2017.

You can build the project using 2017 by changing the SDK version and platform toolset in the project properties:

![image](https://user-images.githubusercontent.com/1306177/69205457-1eefed00-0b9e-11ea-9869-022cdd29027e.png)

**Comment by dmex** [comment]
>  build the project using 2017

I've added a workaround in the latest commit 👍
