### ISSUE TITLE
Feature Request: Bottom view like Process Explorer

### ISSUE THREAD

**Issue by NN---** [processhacker/processhacker#504]
The only missing feature in PH for me is configurable bottom view which shows either dlls list or handles list (or any process tab if possible).
That way I don't need to open a full process details of each process, but rather simply navigate between process and see the relevant information instantly.

**Comment by dmex** [comment]
> configurable bottom view

The process and properties windows are separate so you can rearrange them using either preference or by dragging the Window to the corners/edges of the current monitor.

>  shows either dlls list or handles list (or any process tab if possible).

A Handles window showing every handle like the View > Windows menu showing every Window?

**Comment by NN---** [comment]
No, make a docking window with handlers or dlls or any other tab.

![](https://docs.microsoft.com/en-us/media/landing/sysinternals/processexplorer.jpg)

**Comment by dmex** [comment]
The window separation is required for showing processes with 20,000 or more handle objects. The memory and resource usage is dependent on the window lifetime making it easier to cleanup and reuse for other processes.
