### ISSUE TITLE
KPH driver disappearing

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#507]
1. Install the latest nightly processhacker-build-setup.exe on a clean OS
2. Check [x] "Install KProcessHacker as a service and uncheck [ ] "Start Process Hacker after setup exists"
3. After the setup finishes click Close
4. Go to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ and look for KProcessHacker3 - it exists, all ok now
5. Run Process Hacker from the desktop icon with double mouse click (NOT with the right click and Run As Admin). Double click is important
6. PH started, go again to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\ - the KProcessHacker3 doesn't exist and has been deleted.
It's prob due to https://github.com/processhacker/processhacker/commit/86ac0db562c9641f75596c8aa7fa913a2592cdcc
But I'm not sure, just can say that the effect appeared 3-4 days ago.

**Comment by VictorVG** [comment]
Yes, after Git 86ac0db5 "2019-11-15 04:55:18 +1100 dmex : Reset KPH after Windows build updates" if settings EnableKPH switched 1 to 0 then PH try stop and delete driver and if I try send any command to driver then OS say's "This services not respond and mark for deletion" and `sc query KProcessHacker3` show status _SERVICES_STOP_PENDING_ and driver also mark for deletion.

If I try install driver after reboot, then install is success, but PH again try remove driver of not have end cycle ...
