### ISSUE TITLE
Process search doesn't work well with "Collapse services on start" enabled

### ISSUE THREAD

**Issue by ge0rdi** [processhacker/processhacker#508]
Process search (Ctrl+K) doesn't find any service process when `Collapse services on start` option is enabled.

It was broken by this [commit](https://github.com/processhacker/processhacker/commit/c1d28ee68a154a278d3c36348a1ca1bb164dd601).

Previously services were collapsed just once (first time when `services.exe` process was encountered).

Now it seems services are collapsed during more events (for example when process search edit box is changed).

**Comment by dmex** [comment]
https://github.com/processhacker/processhacker/issues/519
