### ISSUE TITLE
Find in started on v3.0.7364.2837 Git-0e1e2ce4 then MaxMind GeoIP.db update user see wrong switch text "MaxMind GeoIP download progress..." to "MaxMind GeoIP upload progress..." after ~ 50% download.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#510]
Find in started v3.0.7364.2837 Git-0e1e2ce4, humor only, but cosmetics bug is exist:

Then MaxMind GeoIP.db update user see wrong switch text "_MaxMind GeoIP download progress_" to "_MaxMind GeoIP upload progress_" after ~ 50% download. :) I can't find source for it, but users write for this phenomena on forum.ru-board.com...

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Thanks! Merry Christmas and Happy New Year at the same time!
