### ISSUE TITLE
Do not put user processes under services

### ISSUE THREAD

**Issue by dzenanz** [processhacker/processhacker#511]
Sometimes, `explorer.exe` is displayed under `services.exe`. Since I usually have `services.exe` process collapsed, some processes are hidden. Is there a way to move a process to be "top level", as if I killed its parent? Can it be ensured that `explorer.exe` never ends up under `services.exe`?

This affects latest stable release (2.39), things might have changed since. I only discovered GitHub for Process Hacker today.

**Comment by VictorVG** [comment]
Process services.exe is special host process for _"services"_ - loadable kernel mode OS modules required for extended system task. but not for user mode shell. Explorer.exe is user-mode shell process and not require kernel-mode privileges and always run as children process  stated WinLogon.exe - User Session Manager running ntoskernel.exe. 

See PID for any process (add PID column use MsRClick for column toolbar, and press Choice column..) or just click for Name column for change sorting mode... ????

**Comment by dzenanz** [comment]
Perhaps screenshot can say it better. Why are this instance of `explorer` and `notepad++` under services?
<img width="588" alt="Screenshot 2019-11-25 11 40 09" src="https://user-images.githubusercontent.com/1792121/69559827-abbcf100-0f78-11ea-941f-7a73eda4fd7e.png">

**Comment by dmex** [comment]
These processes are created by DCOM/COM+ service running as svchost.exe and it's the correct parenting order - adding code to change the parenting behavior is already problematic due to changes between different versions of Windows.

I would recommend using the View > Hide processes from other users menu
