### ISSUE TITLE
Windows Defender Alert

### ISSUE THREAD

**Issue by BeldenGit** [processhacker/processhacker#513]
Don't know where to post this but wanted to let you know, maybe you can fix this so people don't get their programs removed?

Thanks

> HackTool:Win64/ProcHack
> 
> Varningsnivå: Hög
> Status:
> Datum: 2019-12-02
> 
> Rekommenderad åtgärd: Ta bort hotet nu.
> 
> Kategori: Verktyg
> Information: Det här programmet har ett oönskat beteende.
> 
> Läs mer (https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=HackTool:Win64/ProcHack) (https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win64/ProcHack&threatId=-2147221926)
> 
> Objekt som påverkas:
> 	file: C:\Program Files\Process Hacker 2\ProcessHacker.exe
> 	
> 	file: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Process Hacker 2\Process Hacker 2.lnk
> 	file: C:\Users\\*username*\Desktop\Process Hacker 2.lnk
> 	
> 	process: pid:5080,ProcessStart:132197777571184659
> 	
> 	regkey: HKCU@S-1-5-21-3899246799-2416352189-668163949-1001\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\\Process Hacker 2
> 	regkey: HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\Process_Hacker2_is1
> 	runkey: 
> 	HKCU@S-1-5-21-3899246799-2416352189-668163949-1001\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\RUN\\Process Hacker 2
> 	startup: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Process Hacker 2\Process Hacker 2.lnk
> 	uninstall: HKLM\SOFTWARE\MICROSOFT\WINDOWS\CURRENTVERSION\UNINSTALL\Process_Hacker2_is1

**Comment by dmex** [comment]
Duplicate https://github.com/processhacker/processhacker/issues/454
