### ISSUE TITLE
GPU not working in windows 10

### ISSUE THREAD

**Issue by kotenok2000** [processhacker/processhacker#514]
Gpu load is not shown in the gpu column, gpu memory is missing too.
The issue is present since 3.0.2627
The issue is not present on build 3.0.2621

![Снимок экрана (75)](https://user-images.githubusercontent.com/8822292/70058676-68a1f400-15f0-11ea-987f-a6753d135aa2.png)

**Comment by dmex** [comment]
Try changing this setting to zero:

1) Exit Process Hacker
2) Open settings.xml
3) Change ProcessHacker.ExtendedTools.EnableD3DKMT from 1 to 0
4) Start Process Hacker

**Comment by kotenok2000** [comment]
It worked.  Thank you.

**Comment by cxbignekoc** [comment]
Dont have that in my settings, can i just add?
"ProcessHacker.ExtendedTools.EnableD3DKMT"

**Comment by dmex** [comment]
@cxbignekoc 

No. That setting is for nightly builds:
https://wj32.org/processhacker/nightly.php

**Comment by mitchellmaler** [comment]
Running Windows 10 build 19042 using a AMD RX 5700 XT and running Process Hacker as Admin shows GPU utilization at 0%. I am guessing it is not able to pull stats. I tried adding the above config to the settings.xml but did not yield any results. @dmex What can I do to help troubleshoot this issue, is there any logs or config I could provide that would help?

**Comment by dmex** [comment]
@mitchellmaler 

1) Does Process Explorer and Task Manager have the same issue?

2) Are you also using one of these options?

![image](https://user-images.githubusercontent.com/1306177/103079862-d02a4780-4628-11eb-8934-2c5f8c4c8ae4.png)

**Comment by mitchellmaler** [comment]
The performance graph in Task Manager shows the utilization where Process Hacker only shows 0%. This screenshot shows when I started up a game which increased usage.
![image](https://user-images.githubusercontent.com/4107699/103103063-bf57e280-45e4-11eb-992f-90281909b1a8.png)


I do not have those options in my Graphics settings.

**Comment by dmex** [comment]
> The performance graph in Task Manager shows the utilization where Process Hacker only shows 0%

Microsoft changed/broke the D3DKMTQueryStatistics function starting with 20H1 | May 2020 Update | 10.0.19041

So much for Windows backwards compatibility... It'll only return partial statistics and only for some processes. For example it'll report the correct usage until you start playing any graphics intensive games then both Process Explorer and Process Hacker report 1% utilization while Task Manager will report the correct utilization > 90%

For example:
![image](https://user-images.githubusercontent.com/1306177/109501447-b0f9db80-7aeb-11eb-9894-818d104dde68.png)

**Comment by dmex** [comment]
Closing since a new implementation was added and compatibility with D3DKMTQueryStatistics was fixed 👍

**Comment by Somnambulating** [comment]
Excuse me, process hacker cannot get utilization when open Hardware Accelerated GPU Scheduling.  Is the bug fixed?

The windows version of my computer is 21H2.

Thank you very much..

![screenshot-20220525-103620](https://user-images.githubusercontent.com/42727858/170168306-21433461-b7a3-4873-91a6-bc9c598d8478.png)

**Comment by Somnambulating** [comment]
> Closing since a new implementation was added and compatibility with D3DKMTQueryStatistics was fixed 👍



> Closing since a new implementation was added and compatibility with D3DKMTQueryStatistics was fixed 👍

Excuse me, process hacker cannot get utilization when open Hardware Accelerated GPU Scheduling.  Is the bug fixed?

The windows version of my computer is 21H2.

Thank you very much..
![screenshot-20220525-103620](https://user-images.githubusercontent.com/42727858/170168862-940dc3ad-7f7b-44e4-bec2-d48502c1ebb5.png)

**Comment by dmex** [comment]
> process hacker cannot get utilization when open Hardware Accelerated GPU Scheduling. Is the bug fixed?

Yes, fixed long ago. You need to install the nightly build.

**Comment by blakegordon** [comment]
Are there plans to reveal CUDA activity via System Informer even when Hardware-Accelerated GPU Scheduling is enabled?  Certainly would be nice.

Believe it or not, this is what my secondary card looks like under full load.  Yes, it really is being used:

![image](https://github.com/winsiderss/systeminformer/assets/53873866/f5ffa22d-d200-4be8-af62-ff5978962e49)

FWIW, Task manager has the same problem.  Dearth of activity shown even as the fan reels from all the CUDA activity....  Unless the user disables HAGS in Windows settings.         -BGU

**Comment by scotrod** [comment]
Few years later, this tool still isn't showing (Windows 10 Pro, running as an admin) GPU usage, at all. Any logs I can provide to track this issue further?

**Comment by AcccGO** [comment]
![image](https://github.com/winsiderss/systeminformer/assets/23721753/4ddb21d6-16f7-4c6e-90df-a34ca028e603)
Still there is no gpu memory info

**Comment by dmex** [comment]
> Still there is no gpu memory info

You're running Process Hacker 2.39 from 2016... You should install a newer version: https://systeminformer.sourceforge.io/nightly.php
