### ISSUE TITLE
If kernel-mode driver enabled, significant mouse lag when running VirtualBox VMs

### ISSUE THREAD

**Issue by kocmo** [processhacker/processhacker#516]
After upgrading VirtualBox from 6.0.10 to 6.0.14, I got significant mouse lag on host when VMs were running, and I wasn't even able to boot any Windows-based VMs to completion anymore, they would freeze on boot or very slowly display Windows boot animation and never go past that. I also upgraded Process Hacker to the current version v3.0.2866 shortly after upgrading VirtualBox, but I was seeing the same problems about a month ago; back then I had VirtualBox 6.0.14 and then-current version of Process Hacker.

Those problems went away after I disabled kernel-mode driver in Process Hacker options.

I have Windows 7 x64 on host and guest, have VBoxSVGA controller and 3D acceleration enabled for guest, and run current Avira antivirus on host.

Also [posted this on VirtualBox forums](https://forums.virtualbox.org/viewtopic.php?f=6&t=95890&p=464755#p464755).

To reproduce on Win7/8/10 x64, have Process Hacker kernel-mode driver enabled, install VirtualBox 6.0.14, and try booting any Windows x64 VM (i.e., Windows 7 or Windows 10 installer ISO).

**Comment by dmex** [comment]
> upgraded Process Hacker to the current version v3.0.2866 shortly after upgrading VirtualBox, but I was seeing the same problems about a month ago;

The kernel driver is the same binary for all versions (stable/nightly) since 2016 so I would assume VirtualBox.

> Windows 7 x64 on host and guest, have VBoxSVGA controller and 3D acceleration enabled

Do you have the same issue after changing VBoxSVGA to VBoxVGA?

**Comment by kocmo** [comment]
Correction: after I've re-tested with Extension Pack and Guest Additions versions matching the VirtualBox version being tested, I no longer see a correlation between kprocesshacker.sys and VirtualBox troubles.

Posting VBox testing results just in case.

| VirtualBox, ExtPack, and Guest Additions | GPU | 3D acceleration | kprocesshacker.sys | Results |
| -------------------- | --- | --------------- | ------------------ | ------- |
| v6.0.14 | VBoxSVGA | enabled | disabled on host & guest | win7 guest boots and runs slowly |
| v6.0.14 | VBoxSVGA | enabled | enabled on host & guest | win7 guest boots and runs slowly |
| v6.0.12 | VBoxSVGA | enabled | disabled on host & guest | no problems |
| v6.0.12 | VBoxSVGA | enabled | enabled on host & guest | no problems |
| v6.0.10 | VBoxSVGA | enabled | enabled on host & guest | no problems |

Logs: [VBox 6.0.14 performance regression - logs.zip](https://github.com/processhacker/processhacker/files/3966427/VBox.6.0.14.performance.regression.-.logs.zip)

**Comment by dmex** [comment]
@kocmo 

Tried changing VBoxSVGA to VBoxVGA?
