### ISSUE TITLE
Restore CollapseServicesOnStart checkbox in Settings

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#519]
_From https://github.com/processhacker/processhacker/commit/a37876f614cb7ecc4d19d11802aac2f305fca7f8_:

At least

> If you don't want to loose the checkbox, add a popup explaining where to find the configuration option

or, "fix properly" by:

> I'll add the option back (implemented as a wrapper around the Misc menu) if someone creates a bug ticket.

**Comment by dmex** [comment]
I've added this to the Settings > Usernotes options
