### ISSUE TITLE
System Information Idea (enhancement)

### ISSUE THREAD

**Issue by Cryptic2** [processhacker/processhacker#522]
Currently, In the CPU graph if you hover over the graph it shows what program was taking up the majority of the processor at that time; I think this is quite useful but In the system information CPU, GPU, or RAM graphs, It could be nice to split the graph into multiple colors representing different processes on those systems. (example of that type of graph below)

![stacked_area_graph](https://user-images.githubusercontent.com/56946513/70818468-a9380500-1d88-11ea-8c72-36ad2cb2576b.png)

**Comment by dmex** [comment]
> It could be nice to split the graph into multiple colors representing different processes

Its a good idea but there are generally more than 300 processes running on Windows (especially with browsers). How would you see the more than maybe 5 colors?

**Comment by Cryptic2** [comment]
That could work just seeing 3 - 5 most demanding processes and show the rest as a miscellaneous color. most of the processes do not take up more than a percent of your CPU so it wouldn't be necessary seeing it anyway.

**Comment by dmex** [comment]
This won't work in the current GDI framework. It would be possible to do this via HTML5 graphs but would only be available for some 'remote management' feature. 

I would recommend creating a ticket for remote administration via web interface which can be used locally.
