### ISSUE TITLE
Tray icon not clickable on non-main monitors

### ISSUE THREAD

**Issue by spixy** [processhacker/processhacker#523]
Hi.
- Process Hacker v **2.39.124**
hover and click on tray icon on all monitors works

- Process Hacker v **3.0.2873**
hover and click on tray icons on non-main monitor does not work

I am using DisplayFusion 9.5

(I downgraded to v2 for now, I am OK with that)

**Comment by dmex** [comment]
This is an issue with DisplayFusion and the Shell_NotifyIcon API with the NIF_GUID flag. v3.0 uses the NIF_GUID flag to enable Windows tray icon customization. If we remove the flag then you won't be able to re-order or customize tray icons and have those customizations persisted across reboots.

You need to report the issue with NIF_GUID to the DisplayFusion developers.

**Comment by RobotGizmo** [comment]
I'm a DisplayFusion developer and I've been trying to sort out this compatibility issue. I was wondering if you could help me understand how your tray icon receives it's window messages. When I use Spy++ to monitor the messages being sent to your window from the Windows system tray icon I can't seem to find any messages being sent to any windows in the Process Hacker process. This is unusual as all other applications I've tested have a recipient window. Is Process Hacker blocking the Spy++ message hook maybe? Or is there something else I'm missing here with the new version of Process Hacker? Thanks!

**Comment by dmex** [comment]
> Is Process Hacker blocking the Spy++ message hook

Yes. Process Hacker is blocking dynamic executable code generation and the modification of existing executable code which blocks the DLL injection needed by Spy++ to intercept window messages.

1) You will need to delete this key from the registry:
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ProcessHacker.exe`
2) Then execute Process Hacker using the command "`processhacker.exe -nomp`"

If these two conditions are true then you'll be able to use spyxx_amd64.exe or spyxx.exe 👍 

> I've been trying to sort out this compatibility issue.

The only major changes between 2.39 and the 3.x branch ([nightly builds](https://wj32.org/processhacker/nightly.php)) was mainly the addition of the NIF_GUID flag but there were also some changes to the icon index (NOTIFYICONDATA->uID)

The Windows shell also had some issues with that flag:
* If two executables with different file paths use the same guid then the tray icons are invisible for one executable but visible for the other - you'll see this after using a debug build and running the nightly builds - the only way to fix this is clearing the tray icon cache or generating a new guid (clearing PH settings).
* The NOTIFYICONDATA field uID is an unsigned int but the PH IconId is an unsigned long which shouldn't be an issue unless you're using a high value but there were still a bunch of weird issues depending on the value.

The other thing would be if DisplayFusion is injecting code. If its being injected into Explorer then you should be able to just send the same messages as Explorer for showing the context menu but if its injecting code into PH then it'll get blocked by the mitigation polices - we can LoadLibrary your DLL during startup if thats the case.

**Comment by RobotGizmo** [comment]
This information helped a lot, thank you! I think we've got it working here now, we'll be releasing a beta version today or tomorrow that should fix this up for your users. Thanks!

**Comment by dmex** [comment]
You're welcome 👍

**Comment by ImSpecial** [comment]
Just a lurker that uses and loves both DisplayFusion & Process Hacker, and feel compelled to tell you  two how awesome of devs you guys are. Especially you dmex! Always helpful, answering all questions, etc.

**Comment by RobotGizmo** [comment]
Sorry to re-open this case again, but I have another question about Process Hacker 3. We're sending NIN_POPUPOPEN on mouse hover but for some reason the popup window never appears on our secondary DisplayFusion taskbars. If I single-click the icon it does appear, so I know it's possible. I've looked at the messages being sent using Spy++ and they're identical to the messages Windows is sending, same messages and all that but no luck. Is there something I'm missing to trigger the popup on hover? Thanks!

**Comment by dmex** [comment]
> something I'm missing to trigger the popup on hover?

It sounds like the lparam/wparam might be incorrect or some window doesn't get activation/focus first but can't be sure.

>  the popup window never appears on our secondary DisplayFusion taskbars.

Are you able to add some breakpoints into the PhNfForwardMessage function and let me know where Process Hacker is failing? If the lparam/wparam for the messages you're sending are correct there should be calls to GetCursorPos here:
https://github.com/processhacker/processhacker/blob/5c5995cb0a695413c95a10e44fff292e7f8adab4/ProcessHacker/notifico.c#L407-L419

The other issue could be a window not getting activated/foreground properly and just disappearing before its visible. You would need to add some breakpoints into PhMipContainerOnShowWindow and see if its receiving two WM_SHOWWINDOW messages one after another causing the window to be hidden: https://github.com/processhacker/processhacker/blob/5c5995cb0a695413c95a10e44fff292e7f8adab4/ProcessHacker/miniinfo.c#L329-L337

**Comment by RobotGizmo** [comment]
I found something interesting. If I move the DisplayFusion taskbar to the same screen as the Windows taskbar the hover works perfectly. If the hover takes place on a different monitor from the Windows taskbar the hover doesn't work at all. DisplayFusion is sending the same messages in both cases, the only difference is the x/y position of the mouse cursor. After looking through the Process Hacker code the issue appears to be in the PhMipCalculateWindowRectangle function. This function uses the appbar position to position the window, and if it's not on the same monitor it gets cropped down to 0px. Would it be possible to rework this function to use the workarea of the monitor where the mouse is located to position the hover, or something like this? Thanks!

**Comment by dmex** [comment]
> This function uses the appbar position to position the window

We're using the same method used by wpf-notifyicon:
https://github.com/hardcodet/wpf-notifyicon
https://www.codeproject.com/Articles/36468/WPF-NotifyIcon-2

> Would it be possible to rework this function to use the workarea of the monitor where the mouse is located to position the hover

I can give it a try.

**Comment by dmex** [comment]
@RobotGizmo 

Was this issue fixed with DisplayFusion 9.7?

**Comment by ImSpecial** [comment]
Yup. 👍
