### ISSUE TITLE
Network don't show the Latency

### ISSUE THREAD

**Issue by QQ2017** [processhacker/processhacker#525]
Network don't show the Latency and Packet Loss，now is show “Extended TCP statisitics are disable”，what is mean？
version:3.0.2873
system:win10x64 1903 ltsc

**Comment by dmex** [comment]
Hello,

You need to enable this checkbox:

![image](https://user-images.githubusercontent.com/1306177/71057584-480d9880-21b1-11ea-941a-21dcd2fd4669.png)

**Comment by QQ2017** [comment]
thank you
