### ISSUE TITLE
Pagefiles menu item is gone

### ISSUE THREAD

**Issue by andrew-boyarshin** [processhacker/processhacker#526]
#502 removed (disabled) pagefiles menu without providing an alternative. Now to view the pagefile size I have to either launch _Windows Task Manager_ or WSL1 `htop` (oh, the irony of that).

It would be nice to see this back, preferably as an additional panel in _System Information > Memory_, instead of an extra dialog as it was before.

**Comment by dmex** [comment]
> removed (disabled) pagefiles menu without providing an alternative. 

I've re-added the menu in the latest nightly build. I wasn't sure anyone used the page-file window but now I know to update the window and make it more usable 👍

> It would be nice to see this back, preferably as an additional panel

The number of pagefiles is only limited by the number of drives, so you need a separate window to show them. You could show the totals on the memory window but you would lose the individual totals?

**Comment by andrew-boyarshin** [comment]
Thanks, I did the 2fa61bc7 in my local working tree too.

> You could show the totals on the memory window but you would lose the individual totals?

Yeah, good question. Maybe the _Pagefiles_ should follow the same principle as _Memory lists_: summary usage in a panel (maybe with full info on top 3 pagefiles), detailed view in a separate window shown on button click.

**Comment by dmex** [comment]
I've updated the dialog with new stats and other fixes in the latest nightly build 👍 

> detailed view in a separate window shown on button click.

I was thinking we could show an extra row with just the totals (the green boxes)?

![image](https://user-images.githubusercontent.com/1306177/71307133-dbf39480-243d-11ea-90d1-980597dba1ef.png)

**Comment by andrew-boyarshin** [comment]
Showing the totals makes sense when there are multiple of them. When there are, minimum and maximum grow columns total values aren't really helpful. I believe the bottom row is better (since it's 3 values only).

This dialog can also use autorefresh (like process tree and System Information).

**Comment by dmex** [comment]
> when there are multiple of them.

Windows has always included an extra hidden pagefile. Windows 8 and above create two additional hidden pagefiles. 

For example compare this screenshot to my last screenshot:
![image](https://user-images.githubusercontent.com/1306177/71307870-aa33fb00-2448-11ea-893f-bba7d1136304.png)

You can see 3 pagefiles total but 2 pagefiles were hidden from the NativeAPI. Windbg enumerates them using the PageFileHead from the MiState variable but I don't know the structure type to enumerate them:

`?? ((nt!_MI_SYSTEM_INFORMATION*)@@masm(nt!MiState))->PagingIo`
or
`dt nt!_MI_SYSTEM_INFORMATION @@masm(nt!MiState) -r`

> This dialog can also use autorefresh

Yep. I'll be adding that shortly after performance testing 😉

**Comment by andrew-boyarshin** [comment]
Yeah, RTL_AVL_TREE wouldn't be easy to traverse from user-space. Maybe KPH should do that?

**Comment by dmex** [comment]
> Maybe KPH should do that?

The MiState variable changes almost every 3 months with each build of Win10 and not something you want included with a driver for that reason.

Process Explorer and Process Hacker also don't show the paged and non-paged pool limits on the system information window (from user-mode) on Win10 because those fields were moved into MiState variable and changes way too often even with symbols.

> This dialog can also use autorefresh

The refreshing resets the selections and needs more work. I'm going to close the ticket since the other stuff was done and the selection issue is unrelated 👍
