### ISSUE TITLE
Pause on start

### ISSUE THREAD

**Issue by tophf** [processhacker/processhacker#528]
Repro: start Process Hacker
Expected: GUI shows up instantly
Observed: GUI shows up in one second

Bisected to 3.0.2621 (ok) - 3.0.2627 (bad): https://github.com/processhacker/processhacker/compare/fa6620014ca2a721ddda74dce21fec9ddf15b026...e0f0a2c6b05cdf9e16c1f5e2804cc1486b9199fe

Windows 10.0.18363.476 19H2 [1909]
Built-in Windows Defender.
CPU i7-3770K
RAM 32 GB
SSD for OS
Dynamic ImDisk RAM drive for the TEMP/TMP dir

When WindowBlinds OS theming engine is active the startup takes up to one minute with 100% CPU and physical memory exhaustion, along with EventLog service 100% CPU consumption.

All of this didn't happen in 3.0.2621 and older.

**Comment by tophf** [comment]
Oh it's actually worse(?): any recent PH3 starts successfully - that is instantly - only if I have PH2 installed (KProcessHacker3 service is enabled). Can't test nightlies earlier than six month ago, though.

**Comment by dmex** [comment]
It's caused by reinitializing the kernel driver configuration after windows updates / build changes.

It should only ever happen once after the Windows build changes or the settings file is deleted. I can include a setting to disable the initialization as was the legacy behaviour?

**Comment by dmex** [comment]
KPH is disabled by default for now and the reconfiguration is also now disabled by default 👍
