### ISSUE TITLE
Pseudo parent for filtered processes

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#530]
Something like this:
![image](https://user-images.githubusercontent.com/8224786/71376029-3bce7480-25d1-11ea-95df-f51decbd73ab.png)

When we have such pseudoparent and option Include usage of collapsed processes - we can see in columns total of all filtered processes when pseudoparent collapsed.

**Comment by dmex** [comment]
The items can only be reparented with multiple arrays which has issues with searching/showing stale objects.
