### ISSUE TITLE
PH executable missing version information

### ISSUE THREAD

**Issue by negrutiu** [processhacker/processhacker#531]
ProcessHacker.exe is missing version information.
It's impossible to determine PH's version other than manually opening the About box.
Tools specialized in software inventory are unable to list PH correctly.
Suggestions:
* Add version information block to ProcessHacker.exe
* Add version registry values in Uninstall section
<br>
Thank you guys, PH rocks!

**Comment by dmex** [comment]
> ProcessHacker.exe is missing version information.

Yes it does.

The version information was removed from the binary last year after evidence of malware (and even some 'legitimate' software) using the information to block our binaries on your machine.

To be clear that evidence was not software restriction policies on corporate networks but malware and marketplace corruption from third party software blocking binaries on users own machines. When Process Hacker is configured as the default windows task manager these actions also prevent users from also running the built-in Windows taskmgr.exe and caused many others issues.

> other than manually opening the About box.

I don't see any other way unfortunately and even that information might be removed in the future for the same reason.

:|

**Comment by negrutiu** [comment]
Ok, it's your decision and I respect it.
But, working in the anti-malware industry I can tell you that an executable without version information and/or digital signature looks extremely suspicious to an AV. It's likely that the missing version will do PH more harm than good in the long run...
Thanks for your answer!

**Comment by dmex** [comment]
> It's likely that the missing version will do PH more harm than good in the long run

It's a two way street. Products doing those sort of stupid things generally lose customers over time.
