### ISSUE TITLE
About windows defender and PH

### ISSUE THREAD

**Issue by Glubzor** [processhacker/processhacker#535]
Hi, 
I don't understand where to continue discussion about this subject so I open this thread.

Adding this entry to the registry avoid Windows Defender detection inside Process Hacker :

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths]
"C:\\Program Files\\Process Hacker 2"=dword:00000000

tested on Windows 7 and Windows 10

**Comment by dmex** [comment]
>  where to continue discussion 

#454
