### ISSUE TITLE
GeoIP database update errors

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#536]
**Happy New Year!**

New rules started in 30.12.2019 

In to blog - https://blog.maxmind.com/ :

> **Significant Changes to Accessing and Using GeoLite2 Databases**
> Reasons For Changes
> 
> MaxMind has always been committed to an individual’s right to privacy on the internet. We welcome the burgeoning privacy regulations, such as GDPR and CCPA, for the benefit they can provide to internet citizens. However, these new legislative measures place restrictions that impact our ability to continue distributing our GeoLite2 databases on a public page under the Creative Commons Attribution-ShareAlike 4.0 International License.

in to any download page redirected to page https://www.maxmind.com/en/geoip2-country-database and users see:

> **GeoLite2 Free Downloadable Databases**
> 
> Due to upcoming data privacy regulations, we are making significant changes to how you access free GeoLite2 databases starting December 30, 2019. Learn more on our blog.

> Obtain GeoIP.conf with Account Information For Paid GeoIP2 and GeoIP Legacy Databases

any (non commercial) user can't access for download DB.

also new API. used - https://github.com/maxmind/libmaxminddb/releases ...

**Comment by pasha-zzz** [comment]
This is fake. Blocked for non-registered users.
I wrote script, daily updated bases here - http://geolite2.6te.net/

**Comment by stonedreamforest** [comment]
![image](https://user-images.githubusercontent.com/16742566/73933742-10e97700-4918-11ea-87c7-225884690999.png)

**Comment by dmex** [comment]
This issue depends on bug #539 - the database is downloaded from wj32.org and I can't login to the server to update the php code @wj32

**Comment by niemant** [comment]
> 
> 
> This is fake. Blocked for non-registered users.
> I wrote script, daily updated bases here - http://geolite2.6te.net/

Where should I place the files from your site to have them working with PH?
Regards

**Comment by dmex** [comment]
The update URL has been fixed. You can continue update using the built-in Tools > Network tools > GeoIP update menu.

**Comment by VictorVG** [comment]
Big thanks! Update success.

**Comment by dmex** [comment]
The database will only be updated once a month so downloading it more than once isn't needed.

**Comment by VictorVG** [comment]
Naturally, what's the point of changing the IP distribution by country daily? Unless to create a type of stormy activity, well, there were always enough fans of show-off. :)
