### ISSUE TITLE
Is it actually neccessary to use FindWindowEx in WindowExplorer?

### ISSUE THREAD

**Issue by poizan42** [processhacker/processhacker#537]
The code here:

https://github.com/processhacker/processhacker/blob/b44a1573eb263e5b585abb377966d169df574de2/plugins/WindowExplorer/wnddlg.c#L257-L259

was added in 0d5a6488cef9cf56cac366067545e04b7f1ff649 in 2012. To enumerate "immersive" windows it is necessary to add the DisableWindowsFiltering element to the manifest, which was done some time later here: https://github.com/processhacker/processhacker/commit/199fa76149caeb0b1f6fff505ca8cab2e6310ad0#diff-b79242c33bab388819b4787050075056

So what I'm wondering is if the current usage of FindWindowEx over EnumChildWindows actually serves any purpose today? The current method is obviously more fragile since windows being created/destroyed during enumeration might mess things up.

**Comment by dmex** [comment]
> I'm wondering is if the current usage of FindWindowEx over EnumChildWindows actually serves any purpose today?

That's a good question. Have you already tried switching the code and checked for any differences? 

The internal implementation of FindWindowsEx is 1:1 user<->kernel syscalls for every invocation but EnumChildWindows only does one the syscall and enumerates from usermode and should be more reliable.

**Comment by dmex** [comment]
I've added a new setting called EnableAlternateEnumWindow that will enumerate windows using EnumChildWindows instead of FindWindowsEx.

It might be the default in a future version if it works better but for now you can enable it manually 👍
