### ISSUE TITLE
It would be useful to have optional line wrap for some columns

### ISSUE THREAD

**Issue by rwperrott** [processhacker/processhacker#538]
e.g the "Command line" column can get quite long, and I'd rather not have to stretch the window and resize the column across multiple screens, to see the full content for multiple concurrent processes.

Anyway, this is a very nice tool and better in some ways than the older "Iarsn TaskInfo".

**Comment by dmex** [comment]
The process properties window shows the individual parts and the complete string.

Some processes have command lines with 32,000 characters and it's not feasible to wrap the string across multiple treelist rows without some major issues hence the commandline column is just supposed to be a basic summary?
