### ISSUE TITLE
Forum issues

### ISSUE THREAD

**Issue by dmex** [processhacker/processhacker#539]
The latest phpbb automatic update borked the server and it needs a manual update @wj32

**Comment by dondolarson** [comment]
Is there a way to register on the forum? I can't see any register possibility? Is that true?

**Comment by dmex** [comment]
@dondolarson 

Registration is temporarily disabled after a MITM attack by OpenDNS:
https://wj32.org/processhacker/forums/viewtopic.php?t=4019

It'll be enabled again soon.

**Comment by dmex** [comment]
Forum is live and registration is enabled.
