### ISSUE TITLE
Image file name

### ISSUE THREAD

**Issue by Progress1** [processhacker/processhacker#540]
Some releases before **image file name** changed and doesn't display disk letters (C:\ , D:\) Is it bug or feature? :-) In browser i like it display with old way, in detail it can stay.

![image](https://user-images.githubusercontent.com/10151485/72325483-7ba6ea00-36ad-11ea-8503-088f040f7852.png)

**Comment by dmex** [comment]
It's a regression bug. It'll be fixed when I get back from holidays 👍
