### ISSUE TITLE
What does -nomp mean?

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#541]
What does that actually mean?
I want to run PH via taskschd.msc, should I add just "C:\Program Files\Process Hacker\ProcessHacker.exe" or it's important to add the "-nomp" parameter?

**Comment by dmex** [comment]
> What does that actually mean?

You're missing the windows mitigation options and need to manually add them into the registry.

Save this text with the .reg extension and import them:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\ProcessHacker.exe]
"MitigationOptions"=hex(b):00,10,11,00,11,01,10,01
```

**Comment by skipik** [comment]
Thank you very much!
