### ISSUE TITLE
New changelog - no "you are here" mark

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#542]
This issue was closed - https://github.com/processhacker/processhacker/issues/384

But now it shows where we will be AFTER update. But there is no mark where we are now.
![image](https://user-images.githubusercontent.com/8224786/72519184-e8fe7a80-3867-11ea-87ff-e2b4fb93c77e.png)

**Comment by dmex** [comment]
This was already fixed yesterday 👍 
https://github.com/processhacker/processhacker/commit/de62890da2eef7a9120519a3825f405de3ef7b14

**Comment by pasha-zzz** [comment]
I saw it. But "Update to" mark is important too. Both marks is excellent. Maybe one bold and other italic. When they are the same - bold italic.

**Comment by stdedos** [comment]
_Relates to and enhances #217_

**Comment by dmex** [comment]
I've added blue text for showing the latest nightly build and black text for showing the current build.

**Comment by stdedos** [comment]
Verified as fixed:
![image](https://user-images.githubusercontent.com/133706/99144754-280c8080-2671-11eb-9127-fbb0f946a6d2.png)

**Comment by dmex** [comment]
> Verified as fixed

👍🏿
