### ISSUE TITLE
Option to disable warning when "terminating" a program

### ISSUE THREAD

**Issue by 1024mb** [processhacker/processhacker#543]
Title is clear enough. Just an option to disable/enable the warning message that appears every time one tries to terminate a program.

Thanks.

**Comment by AltF5** [comment]
But to keep all other warnings? You can disable all in settings.

**Comment by 1024mb** [comment]
> 
> 
> But to keep all other warnings? You can disable all in settings.

Yes, I'm looking for an option to disable specific warnings, in this case the "Do you want to terminate xxxx.exe" warning.

**Comment by dmex** [comment]
I would have liked to implement a specific setting for the termination warning dialog but it would be abused by malicious projects such as this one: hxxps://github.com/Mrakovic-ORG/TaskManager-Button-Disabler/

It's better for you to disable all warnings which also prevents abuse of the UI dialogs.
