### ISSUE TITLE
peview is identified as Trojan:Win32/Detplock by Windows Security

### ISSUE THREAD

**Issue by letrec** [processhacker/processhacker#544]
![Threat](https://user-images.githubusercontent.com/996569/72985728-8c7bfc00-3e21-11ea-9b71-5790dfaaf482.png)
PH version 3.0.2895

**Comment by letrec** [comment]
False alarm submission tracking link https://www.microsoft.com/en-us/wdsi/submission/756488e5-c741-4467-bd78-31aeb0d23429

**Comment by letrec** [comment]
File details
Name: peview.exe
Size: 653824 bytes (638 KiB)
CRC32: F74B5843
CRC64: 0DC6B60B64B6EF39
SHA256: 11FF5127313D6778B50D9590DC191C783AD2AD413D97225BD0CAB2B1368E7AC2
SHA1: E0BE0787813D4C3DD099754852643F9E15D58489
BLAKE2sp: BF2D9F98B4F0FBD7244EDC72A777440FCF08943AC1DA1C9B18E74D5CD9AF826E

**Comment by letrec** [comment]
Microsoft has removed the detection.

**Comment by dmex** [comment]
@letrec 

Thanks for reporting this and getting Microsoft to remove the detection. I wasn't able to look into this due to fire evacuation in my area here in Australia and your help getting it resolved is much appreciated!
