### ISSUE TITLE
Feature Request: Find exe for window

### ISSUE THREAD

**Issue by skjerns** [processhacker/processhacker#545]
I really love PH, but there is one feature that Process Explorer has that I'm missing:

![Capture](https://user-images.githubusercontent.com/14980558/73127341-9d11ab00-3fb6-11ea-918a-34da519f5005.PNG)

When dragging and dropping this to a window it will select the corresponding executable.

Would be possible to add this feature?

**Comment by diversenok** [comment]
There is an icon on the toolbar that does exactly what you say:

![image](https://user-images.githubusercontent.com/30962924/73127396-df8bb580-3fbf-11ea-9d24-bc64285fb346.png)

If there is no, right click on the toolbar and select "Customize..."

**Comment by skjerns** [comment]
I'm blind apparently. was already wondering. muchos thanks!
