### ISSUE TITLE
[Feature request] Always start as administrator

### ISSUE THREAD

**Issue by KaKi87** [processhacker/processhacker#546]
It would be nice to have a checkbox in Process Hacker settings to always start the program as administrator.

Thanks

**Comment by Biswa96** [comment]
I just created a shortcut with 'Run as administrator' enabled in shortcut properties.

**Comment by KaKi87** [comment]
Well, it actually even works with the original EXE.
However, it would be still better for user experience design to put this feature in the app settings.

**Comment by pawelzwronek** [comment]
For now I use the trick with windows scheduler described here https://wj32.org/processhacker/forums/viewtopic.php?f=14&t=3670  It's working on my Win10.

**Comment by dmex** [comment]
This feature has been added to the latest nightly build. Select the "Enable start as admin" option on the settings window to automatically launch Process Hacker with elevated permissions.

It's currently experimental and might be removed if there are any security issues.

**Comment by pasha-zzz** [comment]
1stly it is security hole. 2ndly via Task Manager PH started in background. Old foreground window still has focus.
Last can be solved (partially) by:
start "" "C:\Program Files\Process Hacker\ProcessHacker.exe"

**Comment by dmex** [comment]
> 1stly it is security hole.

If there is a security hole then you could mention what it is?

I've been testing stuff and haven't seen anything obvious yet:
* It's disabled by default. 
* Command line parameters are not passed into the elevated process.
* Requires an interactive desktop session currently logged into the machine.
* Non-administrators cannot access or execute the task - administrative users are required to execute.

There might be something that I've missed but adding the feature lets everyone test it and provide feedback (the reason we have nightly builds) and the code can be changed or removed at any time.

If there is a security issue it'll be fixed or the feature removed and the nightly build updated. I don't see any issues yet so I'm making the feature available for everyone to test and provide feedback.

There were other considerations too:
* Microsoft are using the exact same method in their source code: 
https://github.com/microsoft/PowerToys/blob/master/installer/PowerToysSetupCustomActions/CustomAction.cpp#L28-L32 (also see the Microsoft Edge and Google Chrome sources)
* The exact same method is also being used in other popular projects: 
https://github.com/henrypp/routine/blob/master/rapp.cpp#L2776-L2782
* This feature has been requested for more than 8 years (check the forum) but we constantly turned it down believing it would cause a security issue.
* Users have been configuring these tasks manually themselves via Windows already for a very long time with varying methods and varying configurations that are insecure - using our own builtin method will ensure the configuration is secure and reliable.

If Microsoft and others can use the task scheduler for elevation then its not an issue for us to use the same functionality for the same reason. There are some things that I can definitely add for security hardening the task more than it is right now but I'm not sure that's actually necessary based on the code being used by Microsoft and other projects.

> PH started in background. Old foreground window still has focus.

This and multi-user support have not been added yet.

**Comment by KaKi87** [comment]
Thank you for implementing this, I tested it and seem to work. :)

**Comment by dmex** [comment]
It still needs some fixes for the foreground issue and multi-user desktop support. I'll fix those if its secure enough to continue using and close the ticket once those are finalized 👍

**Comment by pawelzwronek** [comment]
How about an option to grand elevated privileges only to chosen plugins? Is it possible anyway?

**Comment by dmex** [comment]
> How about an option to grand elevated privileges only to chosen plugins? Is it possible anyway?

You can't choose which plugins have elevated privileges but you can choose what features are used while elevated so you'll need to be more specific about the request.

**Comment by pawelzwronek** [comment]
Actually I don't understand why running PH as Admin creates a security hole. By requesting selectable elevated privileges to plugins I wanted to avoid giving Admin to untrusted 3rd-parties plugins.

**Comment by pasha-zzz** [comment]
> If there is a security hole then you could mention what it is?

If unelevated process have permissions to change/write to executable and/or to plugins - they may be infected or replaced. And infection will be elevated when PH started next time

**Comment by KaKi87** [comment]
Hello, has the feature been proved secure enough to be finalized ? :)

**Comment by AltF5** [comment]
Hi all. I have written a tool which is launched via the Debugger Replacement which will take the command line, pass it to another custom app run via task scheduler, whom reads the file written out by app 1. This effectively launches PH with elevated permissions via Ctrl+Shift+Esc. Lmk or message me if you need this functionality. I can put this on git

**Comment by dmex** [comment]
Closing since this feature has been implemented 👍
