### ISSUE TITLE
Report which module is causing a System handle

### ISSUE THREAD

**Issue by mirh** [processhacker/processhacker#549]
I mean, if it is possible at all. 
I'm here banging my head against the monitor, not understanding what driver or other amenity is causing a folder to be "locked".

**Comment by dmex** [comment]
Have you tried searching for the folder name using the Hacker menu > Find handles or DLLs option?

**Comment by mirh** [comment]
Mhh no, and to be fair after a reboot I can't get back to reproduce it..
Though at the same time, wouldn't that just tell me "System" is the culprit?

**Comment by dmex** [comment]
> wouldn't that just tell me "System" is the culprit?

Yes and no. System will show up in some cases but not others since kernel mode can use other methods to reference the file that won't be visible without object tracing.

Let me know if you can't find the handle using the Find handles or DLLs option and I'll post instructions for object tracing 👍

**Comment by mirh** [comment]
Ehrm.. I think there's some misunderstanding. 
It's not that I have handles that I know being opened by System, that PH is not actually showing. 
I have every one I could think of. 

It is that I don't know which specific driver/module *inside* System is being responsible for it. 
And I was hoping kprocesshacker.sys could pull off some magic.

**Comment by KaoDome** [comment]
> Let me know if you can't find the handle using the Find handles or DLLs option and I'll post instructions for object tracing 👍

Slightly off-topic, but maybe related...

Sometimes, Windows' safely remove function on external disks fails on me stating that the device is in use. Checking for open handles what I usually get are some system handles (e.g. _System (4), File, K:\$Extend\$RmMetadata\$Txf, 0x2ee0_).

At times, re-starting the Server (LanmanServer) service is enough to make safe removal work, but other times not even then it's possible. Do you think object tracing could help in this case? If so, please let me know how to do it (and thanks anyway!).

**Comment by dmex** [comment]
>  which specific driver/module inside System is being responsible for it

It's not really possible without enabling object reference tracing:
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/object-reference-tracing
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/configuring-object-reference-tracing

It requires a debugger and these traces slow down the machine so it's not something you would want enabled all the time. Process Monitor might show some of the entries but kernel drivers can reference existing objects that won't show up.

> Do you think object tracing could help in this case?

object tracing doesn't really help with tracing file activity. The most you get is a stack trace which doesn't catch applications using wrong flags and not flushing data.

Process Monitor would probably be more reliable in this case.

**Comment by mirh** [comment]
If this would be so heavy, then indeed it make no sense to enable by default... but at least having some hidden option somewhere would be much appreciated.
