### ISSUE TITLE
set affinity for multiple selected processes

### ISSUE THREAD

**Issue by larz93** [processhacker/processhacker#553]
For music application (like foobar2000), i can get more clean sound quality by setting one core to the process exclusively. Process hacker only supports setting affinity for one process a time. I hope adding the feature for setting affinity for multiple selected processes a time.
1.select all processes and set affinity to core 0, 1, 2.
2.select foobar2000 and set affinity to core 3, now foobar2000 runs on core 3 exclusively.
![sample2](https://user-images.githubusercontent.com/60838092/74098476-8f7e2880-4b53-11ea-9e74-41a63b703cba.jpg)

**Comment by dmex** [comment]
#583

**Comment by Henri-J-Norden** [comment]
I would find this feature useful as well; it does not seem to be possible in 3.0.4373. 

I do see that this issue has been closed, but #583 is about setting the affinity for multiple process threads, not multiple processes?

**Comment by dmex** [comment]
> #583 is about setting the affinity for multiple process threads, not multiple processes?

It's the same code for both which is why that issue is best for tracking the feature @Henri-J-Norden
