### ISSUE TITLE
[Feature request] - Add "Finder Tool" to Windows list

### ISSUE THREAD

**Issue by Progress1** [processhacker/processhacker#557]
Add some kind of "Finder tool" (select window with mouse) button. When user press it, it start look what window is under mouse pointer and when user click (or release button) it select exact window in our list. It's common functionality in all window spy tools. It helps fast identify exact window. It's very easy to code, there is API that return all you need (GetCursorPos, WindowFromPoint ...) Look for Spy++ or other tools

![image](https://user-images.githubusercontent.com/10151485/74128528-a79a8a00-4bdd-11ea-8c53-1e4410c11b75.png)

some old example: https://www.codeproject.com/Articles/1698/MS-Spy-style-Window-Finder

**Comment by dmex** [comment]
> Add some kind of "Finder tool" (select window with mouse) button.

The main window already included these 3 find window tools:
![image](https://user-images.githubusercontent.com/1306177/74331999-8fdf2380-4de0-11ea-8d5f-f735d085ca91.png)

> It's common functionality in all window spy tools.

I've added a new button to the Windows dialog. You'll need to minimize the main window for now until its fully implemented 👍 

![image](https://user-images.githubusercontent.com/1306177/74332182-ef3d3380-4de0-11ea-94d1-4de6b859faee.png)

**Comment by Progress1** [comment]
Looks good, it's working, minimize is not a problem :)
