### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by mrkaban** [processhacker/processhacker#558]
Hello, the installation file with sourceforge removes google chrome, it says that they say the virus, I'm trying to download "processhacker-2.39-setup.exe".

Of course, I understand what potentially dangerous software is, but when you cannot download the program, you just find another one.

also the main file and the portable archive show very high on Virustotal 17 out of 62.

**Comment by dmex** [comment]
> Hello, the installation file with sourceforge removes google chrome, it says that they say the virus, I'm trying to download "processhacker-2.39-setup.exe".

Your antivirus is blocking the download not Chrome.  Both downloads work fine:

![image](https://user-images.githubusercontent.com/1306177/74281173-abf3ae00-4d69-11ea-8c60-53ff53b77e00.png)


> I understand what potentially dangerous software is, but when you cannot download the program, you just find another one.

If you can't stop your antivirus from blocking downloads then you should find another antivirus product that won't ignore your preferences.

> the main file and the portable archive show very high on Virustotal 17 out of 62.

Have you looked at the names given in those results?

Not-a-virus
Riskware
Unwanted-Program
Hacktool

These classifications are deliberately ambiguous to dupe unsuspecting customers into thinking their security products are protecting them against threats that in reality don't exist.

You should find a better antivirus product that isn't trying to scam you.
