### ISSUE TITLE
Checking for new releases never finished

### ISSUE THREAD

**Issue by gemal** [processhacker/processhacker#560]
I'm using version 3.0.2902
and when I do a check for updates it just runs forever

It never finished and I cant see anything in the log

![image](https://user-images.githubusercontent.com/69105/74518552-59a2c080-4f14-11ea-8424-9e149ce8c7e6.png)

**Comment by dmex** [comment]
The update check can be delayed a long time depending on the number of workqueue tasks. These tasks can include signature checking all processes and services (an average of 100 processes and 600 services) and hashing all exectuables and services (same number as the signature checking) not including a bunch of other background tasks that would have delayed the update check.

I've removed the workqueue from the updater in the latest nightly which should improve performance... If the updater is not able to download the latest version then you might need to manually download the latest nightly: https://wj32.org/processhacker/nightly.php

Let me know if the latest nightly still doesn't check for updates 👍
