### ISSUE TITLE
The service mpksldrv has been created, then deleted: why?

### ISSUE THREAD

**Issue by WiliTest** [processhacker/processhacker#561]
Why process hacker created this service ?
![image](https://user-images.githubusercontent.com/24194840/74532842-806ef000-4f30-11ea-8085-8543028721ef.png)

**Comment by dmex** [comment]
Process Hacker shows alerts about services created and deleted by Windows and other programs. It doesn't create or delete anything unless you're actually doing it yourself.

You can disable these alerts using the View > Tray icons > Notifications menu 👍

**Comment by eried** [comment]
@WiliTest what was that service doing? I had the same notification in a vm

**Comment by dmex** [comment]
@eried 

mpksldrv is used by Windows Defender for definition updates.

**Comment by eried** [comment]
Oh! Thanks!

**Comment by Fisheiyy** [comment]
this pops up for me randomly but it doesnt just say MpKslDrv it has a bunch of numbers 
![Screenshot 2021-03-30 173143](https://user-images.githubusercontent.com/54205282/113065051-d1b26100-917d-11eb-8258-9583286e868e.png)

**Comment by dmex** [comment]
@Fisheiyy 

Windows Defender uses a random service name when updating the antimalware definitions. If it were using a fixed static name then it would be deleted/blocked by malware and would not be able to update.

**Comment by lexavey** [comment]
> @eried
> 
> mpksldrv is used by Windows Defender for definition updates.

thanks, no worry again

**Comment by mooleshacat** [comment]
> You can disable these alerts using the View > Tray icons > Notifications menu 👍

Option does not exist in PH 2.39.124

**Comment by Vasilich** [comment]
> Option does not exist in PH 2.39.124
1.  It as existed at least in tray icon right click - notifications.
2. We are in SystemInformer repo, so who cares about abandoned Processhacker?

**Comment by MakarovDs777** [comment]
The same nonsense, I don't know if it's still relevant or not?

![Image](https://github.com/user-attachments/assets/aa52890d-8960-4d85-9f48-626cb0490c8f)

![Image](https://github.com/user-attachments/assets/a693051e-f973-43bf-843f-a0253a5b4fe6)

**Comment by Vasilich** [comment]
Ever tried to read this issue from the beginning? Your question was already answered here.
