### ISSUE TITLE
What piece of code makes the main window caption black? (curiosity)

### ISSUE THREAD

**Issue by umokk** [processhacker/processhacker#566]
A question just out of curiosity:
What lines of code make the main window caption black?

**Comment by Biswa96** [comment]
What is the "main window caption"?

**Comment by dmex** [comment]
The dark theme window frame?

**Comment by umokk** [comment]
**Biswa96**, it's the area that contains the window title ("Process Hacker") and the minimize, maximize and close buttons.

**dmex**, no, the window title area is rendered black in normal mode when no dark theme is activated.

**Comment by RanHum** [comment]
Interestingly, i have the opposite: with dark theme enabled i get white titlebar of "system information" window, like this: 
![image](https://user-images.githubusercontent.com/11231107/75678166-d1ac0d00-5cae-11ea-9e68-a355218b8ff0.png)
 But it turns black after i alt-tab back and forth or minimize-maximize, any interaction. Oh, and it's happening only in maximized window, which i use for it daily, in floating window mode it's all good.

**Comment by umokk** [comment]
I meant these black window titles:
![ph](https://user-images.githubusercontent.com/7175477/75678963-cd2c2800-5c9f-11ea-9504-3a927a9f8c0b.png)

**Comment by dmex** [comment]
@umokk 

It depends which version of Windows 10 you're using?

**Comment by umokk** [comment]
I see.
Sorry for wasting your time with this stupid question. It was purely out of curiosity, nothing more. :)

**Comment by dmex** [comment]
@umokk 

The window shouldn't be black unless you've enabled dark theme support in the options window so I wanted to know the version of Windows to check why its automatically enabled when it shouldn't be?

The dark frame code is here: https://github.com/processhacker/processhacker/blob/64619f112efb578453558179e41d34f219f02d97/phlib/theme.c#L99-L133

**Comment by pasha-zzz** [comment]
@dmex

RMC on desktop - Personalisation - Colors
and select color and last check mark
