### ISSUE TITLE
[feature req] selected item highlight color setting

### ISSUE THREAD

**Issue by myshzzx** [processhacker/processhacker#567]
I can't set selected item color in "Highlighting Options", and the default color is so unconspicuous,
could you tell which one is selected? It's hard to find the process when "Find Window".

![image](https://user-images.githubusercontent.com/2025090/75851074-b6aed980-5e23-11ea-8951-16689c1dabec.png)

**Comment by dmex** [comment]
Have you tried changing the "`TreeListCustomColorsEnable`" setting from 0 to 1?

After you enable the setting you can change the colors using these three settings: 
`TreeListCustomColorText `= text color
`TreeListCustomColorFocus `= focus color
`TreeListCustomColorSelection `= selection color

The format is hexadecimal with the format RRGGBB... 
FF0000 = red
00FF00 = green 
0000FF = blue 

You can also use various online charts:
https://www.w3schools.com/colors/colors_picker.asp
https://www.rapidtables.com/web/color/html-color-codes.html
https://htmlcolorcodes.com/

**Comment by myshzzx** [comment]
that works, but when I set "0000FF", it should turn out BLUE but actually RED, so a bug ?

**Comment by myshzzx** [comment]
> Have you tried changing the "`TreeListCustomColorsEnable`" setting from 0 to 1?
> 
> After you enable the setting you can change the colors using these three settings:
> `TreeListCustomColorText `= text color
> `TreeListCustomColorFocus `= focus color
> `TreeListCustomColorSelection `= selection color
> 
> The format is hexadecimal with the format RRGGBB...
> FF0000 = red
> 00FF00 = green
> 0000FF = blue
> 
> You can also use various online charts:
> https://www.w3schools.com/colors/colors_picker.asp
> https://www.rapidtables.com/web/color/html-color-codes.html
> https://htmlcolorcodes.com/

that works, but when I set "0000FF", it should turn out BLUE but actually RED, so a bug ?

**Comment by dmex** [comment]
> it should turn out BLUE but actually RED

I might have got the layout incorrect. Try FF0000 instead and if its blue the format is BBGGRR instead of RRGGBB.
