### ISSUE TITLE
[Bug] Unreadable menu bar (hidpi ?)

### ISSUE THREAD

**Issue by KaKi87** [processhacker/processhacker#570]
Sometimes (cannot reproduce systematically), the menu is illegible, like this :

![2020-03-06 22_15_39-Process Hacker  DESKTOP-B4UDRIE_Tiana + (Administrator)](https://user-images.githubusercontent.com/21284089/76124839-ddc00380-5ffb-11ea-91de-7398d2fe3467.png)

I guess hidpi is responsible for this, because I have an Ultra HD resolution (3840 × 2160) on a 15" laptop, but I'm not sure.

Thanks

**Comment by dmex** [comment]
> hidpi is responsible for this

Yes the DPI would cause the text to offset incorrectly. The problem would be related to the dark theme menu introduced on Windows 10 - Process Hacker doesn't draw the menu, Windows does so I'll have to research the Windows implementation and see what might be missing to fix the issue - the main problem is that the implementation is undocumented so might take some time to figure out.

**Comment by dmex** [comment]
The dark theme menu should be fixed in the latest nightly v3.0.2977

**Comment by KaKi87** [comment]
Thanks !
