### ISSUE TITLE
Tray Icon not shown after update

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#572]
_Some vendor_, despite #388, allowed to auto-update PH recently :-D (it of course garbage-collected the sysdriver, but I can live with that ;-))

I don't have much to over except the two lines above. Host is a Win 10 1803 (17134.1304), and I have no idea from which version I updated.

I tried turning off and on again.

**Comment by dmex** [comment]
That vendor might have polluted the shell tray icon cache and you might need a new icon guid.

1. open settings.xml
2. change the IconGuids value back to default:
`  <setting name="IconGuids"></setting>`
3. start Process Hacker

**Comment by stdedos** [comment]
That works. So, just removing that line is okay? Do I need to do anything with that data I removed?

**Comment by dmex** [comment]
> So, just removing that line is okay?

Yep

> Do I need to do anything with that data I removed?

Nope, you can delete them. Process Hacker will generate new guids for the explorer shell and the tray icons will continue working without the old data :)
