### ISSUE TITLE
[bug] Auto-Focus to SearchBox > enabled > odd restricted behavior 

### ISSUE THREAD

**Issue by nonspin** [processhacker/processhacker#576]
#533 #521 @php940 
 
I'm not 100% percent sure, but i think the enhancement worked for a couple of days
as one would expect: (example: feature enabled)
PH > type 'adobe' to filter processes
> use CTRL-A or Up/Down to select/highlight > DEL (+Enter) to kill it 
and/or use (Shift)TAB/(CtrlShift)TAB to jump Tabs (Procs/Service/Net ...)
Right ?

The problem is that, now the SearchBox doesn't let go of the focus,
applying all keyboard-shortcuts to itself -> SearchBox > CTRL-A >
selecting the text "Adobe" > not the filtered processes.
even after SHIFT-TAB / CTRL-SHIFT -TAB it wouldn't let go.

example2 (feature disabled)
PH > CTRL-K > type 'Adobe' > CTRL-A (or use Up/Doen to select) > DEL(ENTER) > works
Toggling the TABs, Up/Down lets you select a process. 

If someone could look into it please, ..
Thanks in Advance

**Comment by nonspin** [comment]
Let me put this way .. right now it is "Always Auto-Focus to SearchBox".
Instead of (if set) setting the focus once (on start), it's re-setting (because it is set) >> re-focusing.
There shouldn't be recurring checks in the loop - only once on start, otherwise you are stuck in the SearchBox

**Comment by dmex** [comment]
Fixed in the latest nightly build 👍
