### ISSUE TITLE
Unable to start the kernel event tracing session

### ISSUE THREAD

**Issue by dondolarson** [processhacker/processhacker#577]
I couldn't register on the forum due to the DDOS attacks or something and I decided to "report" it as a bug here. I don't really believe that it's a bug, rather something that needs to be activated on my PC to get the disk tab to work, but I get the problem as title say, and can't figure it out what's going on. This text is everything I see when opened Process Hacker with admin privileges. Worth of saying that I'm using the portable version of Process Hacker. Anyone could help me to get this done? What need to be activated? What need to be checked? Thank you for help, and thank you for your awesome application. I don't know what could I do without it. Probably nothing 🙃

**Comment by dmex** [comment]
> Unable to start the kernel event tracing session

This indicates the event tracing subsystem returned an error during registration.

> What need to be activated? What need to be checked?

Nothing needs to be activated but there are a few things that can be checked when there is an error.

Have you tried rebooting? Rebooting does generally fix most issues with event tracing registration - Let me know if rebooting doesn't solve the issue and I'll post instructions on how to locate the event tracing console for checking errors.

**Comment by dondolarson** [comment]
Yes sir. I've rebooted like hundred of times, googled for over a week for "kernel event" for how to activate this but it doesn't look like it's anything I would mess with, checked "Event" services running and they all are on/manual, as well as checked Autoruns with the "kernel" phrase but everything there is activated as well.

![Process Hacker autoruns kernel](https://user-images.githubusercontent.com/49354563/77240024-916ee900-6be1-11ea-9941-9e4bedb4be24.jpg)
![Process Hacker options](https://user-images.githubusercontent.com/49354563/77240027-92a01600-6be1-11ea-9faa-d6d7add2cfbe.jpg)

**Comment by dmex** [comment]
You need to check the event trace sessions via mmc.

1) Run perfmon.msc 
2) Check for any sessions starting with "Ph"

![image](https://user-images.githubusercontent.com/1306177/77240713-ade84100-6c34-11ea-8d31-f57dbf9208fc.png)

**Comment by dondolarson** [comment]
I've checked mine and there aren't these 2 entries. I've compared other entries as well and everything looks like your, except Diagtrack-Listener. It's not there either.

Maybe it will help solve my problem, maybe not. I've searched Autoruns for "Diag" and this is what I've found. 

![Process Hacker Autoruns #2](https://user-images.githubusercontent.com/49354563/77711838-51897680-6fd2-11ea-936b-5160c4278eea.jpg)

**Comment by dmex** [comment]
Autoruns doesn't show Event tracing sessions.

Have you tried using the nightly builds and seeing if they work?
https://wj32.org/processhacker/nightly.php
________________________________

**Comment by dondolarson** [comment]
Ohhh thank you. Sooo easy. Didn't even knew about newer, nightly versions. However, I've tried to import **settings** and **userdbnotes** from 2.39 version and it stopped to work again. Now I see that the v3 need to be opened as an administrator and it's not working, though it's opened as an administrator.

**Comment by dmex** [comment]
@dondolarson 

Update to the latest version using the Help > Check for updates menu.

I've added error messages to the disk tab. Can you please post the error code shown in brackets on the right?

![image](https://user-images.githubusercontent.com/1306177/77840378-25d0e100-71ca-11ea-8990-2e6e133bde73.png)

**Comment by dondolarson** [comment]
I don't see any error message, just this.

![Process Hacker v3](https://user-images.githubusercontent.com/49354563/77846153-4ee67700-71b4-11ea-99f2-0d83a13d5267.jpg)

**Comment by dmex** [comment]
Looks like you've disabled event tracing via the settings file.

1) Exit Process Hacker
2) Open the settings file
3) Change `ProcessHacker.ExtendedTools.EnableEtwMonitor` from 0 to 1

**Comment by dondolarson** [comment]
You're a genius man! Now everything is working :)
 
I haven't disabled anything by manually changing the setting file in v2.39. I've set it up by the options tab (portable version).

**Comment by dmex** [comment]
> I haven't disabled anything by manually 

It may have been one of a few file encoding issues with the mxml library which was fixed in newer versions 👍
