### ISSUE TITLE
Malwarebytes detecting processhacker.exe has generic malware suspicious 

### ISSUE THREAD

**Issue by j0taDasFestas** [processhacker/processhacker#578]
Hi there today my malwarebytes triggered this "C:\Program Files\Process Hacker 2\x86\processhacker.exe" has generic malware suspicious but not the .exe in "C:\Program Files\Process Hacker 2\processhacker.exe"  

 what's going on ?

**Comment by dmex** [comment]
Have you reported the binary as a false positive to Malwarebytes here?
https://forums.malwarebytes.com/forum/42-file-detections/

**Comment by j0taDasFestas** [comment]
no, ill do it and share here
