### ISSUE TITLE
64 Bit version is quarantined by Windows Defender under Windows 10 since end of 2019

### ISSUE THREAD

**Issue by NoComment1965** [processhacker/processhacker#579]
64 bit Version is quarantined under Windows by Defender as soon as it is unpacked. It is simply not usable and hopefully a new version will change this. Until then : ProcessHacker  (64 Bit version only) is - as already said - simply unusable on current Windows systems

**Comment by dmex** [comment]
What name has defender given you for the detection and are you using the nightly builds or the stable build?


(internal github issue reference: #454 #564)

**Comment by dmex** [comment]
If you can post screenshots it'll help too

**Comment by dmex** [comment]
Please post screenshots in this issue #454
