### ISSUE TITLE
Wrong memory usage info for WSL2 Vmmem process

### ISSUE THREAD

**Issue by seven-mile** [processhacker/processhacker#580]
**Windows TaskMgr Display: (157.3MB is the mem usage)**

![Windows TaskMgr Display](https://i.loli.net/2020/03/27/IWuMAiXmUgVYFOD.png)

**PH Displaying: (1.2GB)**

![PH Displaying](https://i.loli.net/2020/03/27/1hjDokARWBe5n8r.png)

Evidently there are some differences on the way to calculate mem usage between the two. But I think PH just calls previous APIs to do that. So why MS didn't update the old API? Or PH has something wrong?

Anyway, I think it's better to be consistent with taskmgr.

**Comment by ge0rdi** [comment]
Windows `Task Manager` shows size of private working set as memory usage.

Not sure what column you have enabled in `Process Hacker` (can't see full name), but I assume it is `Private bytes`.
That's something different.

You can enable `Private WS` column and then it should show the same value as `Task Manager`.

**Comment by dmex** [comment]
You need to enable the Private WS column.
