### ISSUE TITLE
Cores when opening PH

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#582]
_In the same system as https://github.com/processhacker/processhacker/issues/572_

[PHCrashDumps.zip](https://github.com/processhacker/processhacker/files/4392070/PHCrashDumps.zip)

Can I somehow "clean" or "force open" Task Manager? I think that PH does such activation by command line flags, but `PH.exe [(-)-help,-h,/?,/h]` don't give anything as output.

_May be also related to https://github.com/processhacker/processhacker/issues/581_

**Comment by dmex** [comment]
Those crashes are caused by `C:\Program Files\Microsoft Office\Office16\GROOVEEX.DLL`

> Can I somehow "clean" or "force open" Task Manager?

Rename or delete that DLL or use autoruns and remove the entry.

> I think that PH does such activation by command line flags, but PH.exe [(-)-help,-h,/?,/h] don't give anything as output.

You need to execute the command from the command prompt.

**Comment by stdedos** [comment]
> > I think that PH does such activation by command line flags, but PH.exe [(-)-help,-h,/?,/h] don't give anything as output.
> 
> You need to execute the command from the command prompt.

I did that. No output

**Comment by dmex** [comment]
> I did that. No output

You need to uninstall/remove/delete the GROOVEEX.DLL module causing the crashes - It's trying to install shell hooks which are disabled by mitigation policy - I can't fix office since its third party.

**Comment by stdedos** [comment]
Didn't you want, at some point, to block all external hooks? 😕

**Comment by dmex** [comment]
Office is calling a memory address which doesn't exist causing a memory access violation crash. They will need to update their code to check the address isn't NULL but since that won't happen you'll need to remove/rename their DLL to fix the crash.

**Comment by stdedos** [comment]
> Office is calling a memory address which doesn't exist causing a memory access violation crash. They will need to update their code to check the address isn't NULL but since that won't happen you'll need to remove/rename their DLL to fix the crash.

Oh 😂🤣😂🤣 Isn't that priceless?

Unfortunately, it seems that I may need to restart the host computer (I don't know how to find which process loaded a dll into the memory, and I've already renamed it)

**Comment by stdedos** [comment]
I think it may be that this bug will annoy a lot of people, and with 0 user feedback. Isn't there _anything_ you could do about it on any level (eg warn)?

**Comment by dmex** [comment]
> I think it may be that this bug will annoy a lot of people, and with 0 user feedback.

Probably.

> Isn't there anything you could do about it on any level (eg warn)?

It crashes the process during startup before our code even executes. I could add a launcher for process hacker that checks for office and shows a warning then launches process hacker but that's a lot of work required just to avoid an office shell extension DLL that you could just rename instead?

**Comment by stdedos** [comment]
> > I think it may be that this bug will annoy a lot of people, and with 0 user feedback.
> 
> Probably.
> 
> > Isn't there anything you could do about it on any level (eg warn)?
> 
> It crashes the process during startup before our code even executes. I could add a launcher for process hacker that checks for office and shows a warning then launches process hacker but that's a lot of work required just to avoid an office shell extension DLL that can just be renamed?

I started this as a separate comment _for the simple user_ (that may not even bother checking in on the forum). I know that your target audience is _not exactly this user_.

I was just trying to bounce one concern - I agree that it sounds tedious and niche to do for one small bs _thing_; but in my head, it didn't sound more than 100 annoying lines.

Feel free to ignore me.

**Comment by dmex** [comment]
> I agree that it sounds tedious and niche to do for one small bs thing; but in my head, it didn't sound more than 100 annoying lines.

It's also plugins and command line parameters. Process Hacker already relaunches itself for the command line, wow64, stack tracing, updater, mitigation polices, update/install support etc... adding a launcher requires rewriting a large amount of code just to workaround a bug with Microsoft Groove injecting its buggy shell extension.

I don't see the need for having to rewrite so much code and for Process Hacker to use a launcher when Microsoft are going to fix that bug especially when its more reliable and easier to just disable the extension 😄

**Comment by stdedos** [comment]
> [...] when Microsoft are going to fix that bug [...]

I would report it on Microsoft if they had a _easy to reach_ place for bug reports.

Hopefully they'll do.

> Unfortunately, it seems that I may need to restart the host computer (I don't know how to find which process loaded a dll into the memory, and I've already renamed it)

Unfortunately, there is _something else_ that's preventing PH to launch (without any explanation), so I cannot verify that. I could only check if `cmd` gives output, but I don't think it does.

**Comment by stdedos** [comment]
It turns out, maybe the "PH is not opening" was not about these cores. 😕
