### ISSUE TITLE
Provide the filename with build number on download

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#587]
https://wj32.org/processhacker/nightly.php writes `build-3.0.2958-bin.zip` as filename, but gives `processhacker-build-bin.zip`

Could they somehow be merged, e.g. `processhacker-build-3.0.2958-bin.zip`?

I know it's no biggie when autoupdating, or in the long run, but it's annoying to have to store `processhacker-build-bin.zip` e.g. for giving out, or for archiving purposes (e.g. rollbacks)

**Comment by dmex** [comment]
Filename version for website downloads was fixed 👍
