### ISSUE TITLE
EnableStartAsAdmin does not allow PH to start

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#588]
It seems the cause for this https://github.com/processhacker/processhacker/issues/582#issuecomment-606490971 was the EnableStartAsAdmin.

This might be because the processes in the system don't escalate via UAC, but use CyberArk Endpoint Priviledge Manager (somehow it intercepts UAC calls)

After disabling `EnableStartAsAdmin` I was given this:

[ProcessHacker_KXOBONBAZQTHNFP_DumpFile.zip](https://github.com/processhacker/processhacker/files/4408408/ProcessHacker_KXOBONBAZQTHNFP_DumpFile.zip)

And then everything was normal.

_Still, there are no Executable Properties > Details, and no command line flag that lists the version or the other command line flags_

**Comment by dmex** [comment]
> processes in the system don't escalate via UAC

EnableStartAsAdmin uses the task scheduler registration for elevation requests identical to Chrome and Edge processes.

 > CyberArk Endpoint Priviledge Manager (somehow it intercepts UAC calls)

Are you using this on your home machine?

**Comment by stdedos** [comment]
> > processes in the system don't escalate via UAC
> 
> EnableStartAsAdmin uses the task scheduler registration for elevation requests identical to Chrome and Edge processes.

Oh 😕 Well, I don't know what happens with those in that system

> > CyberArk Endpoint Priviledge Manager (somehow it intercepts UAC calls)
> 
> Are you using this on your home machine?

"_Yes, of course I am using that in my home machine_ 😝" (no, I am not; it's the https://github.com/processhacker/processhacker/issues/572 system)

**Comment by stdedos** [comment]
Setting the executable compatibility settings to launch as admin "works correctly"; so I assume the TaskManager call / creation is intercepted somehow

**Comment by stdedos** [comment]
> Setting the executable compatibility settings to launch as admin "works correctly"

... but not for the shortcut-version 😞 

Well, all of this might be too complex and outside of your target audience to solve. Feel free to handle this as you wish

**Comment by dmex** [comment]
> I assume the TaskManager call / creation is intercepted somehow

They would be injecting code into system processes and hooking functions since there isn't any other way to implement their type of product on Windows.

>  all of this might be too complex and outside of your target audience to solve

It's not complex just a waste of time trying to workaround buggy third party products that probably won't exist with the amount of issues they're causing.
