### ISSUE TITLE
Anyway to make "peview.exe" portable like his big brother? 

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#589]
Hi, this will be quick, like a band-aid rip-off! Okay so, maybe this can already be done, and obvious and I'm just oblivious, but can "peview.exe" be made to save its settings to the same location as "ProcessHacker.exe" so that everything can be nice a portable?

I've tried the obvious like placing the "peview.xml" next to the "peview.exe" but that was a fail...

Ouch!

**Comment by dmex** [comment]
The filename was incorrect for peview. You'll need to update to the latest nightly build: https://processhacker.sourceforge.io/nightly.php

The correct filename is `peview.exe.settings.xml`
