### ISSUE TITLE
GPU data inconsistent

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#590]
Do you think either PH or Task manager is wrong? 😕 

![image](https://user-images.githubusercontent.com/133706/78301273-8309c100-7541-11ea-8ca4-6d61e04a349b.png)

**Comment by dmex** [comment]
It depends if you're using the Process Hacker kernel driver. 

Task Manager can query GPU usage for all processes (including protected processes) but Process Hacker can only query all processes (including protected processes) when the Process Hacker kernel driver has been loaded.

You can also try enabling the "ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters" setting from 0 to 1 which uses performance counters for GPU usage which should be identical to Task Manager?

**Comment by stdedos** [comment]
> It depends if you're using the Process Hacker kernel driver.

Oh yeah, no driver because Avast 😕 

> Task Manager can query GPU usage for all processes (including protected processes) but Process Hacker can only query all processes (including protected processes) when the Process Hacker kernel driver has been loaded.

![image](https://user-images.githubusercontent.com/133706/78358661-3fa06880-75bc-11ea-8aa0-e72702cc906a.png)

Are non-elevated processes protected? 😕

> You can also try enabling the "ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters" setting from 0 to 1 which uses performance counters for GPU usage which should be identical to Task Manager?

The screenshot from https://github.com/processhacker/processhacker/issues/591 is with the flag enabled.

Does PH need to restart, or do they apply automatically?

**Comment by stdedos** [comment]
Oh, also the more info windows from GPU; they don't inherit AlwaysOnTop

**Comment by dmex** [comment]
The EnableGpuPerformanceCounters flag wasn't working properly on Win10 2004 and was fixed in the latest nighties 👍

**Comment by stdedos** [comment]
I was in 1803 and now I am in 1909 😃
