### ISSUE TITLE
Separate GPU graphs by device

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#591]
![image](https://user-images.githubusercontent.com/133706/78358533-0667f880-75bc-11ea-8ec5-dc3b46146aee.png)

Add a header like the left one, on the right window

**Comment by MagicAndre1981** [comment]
Intel HD and AMD 7700 sounds like Laptop where the [AMD GPU is only used on demand](https://www.amd.com/en/support/kb/faq/dh-017)

**Comment by stdedos** [comment]
That's not the case - _all*_ CPUs nowadays offer integrated graphics, even if not used

**Comment by MagicAndre1981** [comment]
Post your device specs

**Comment by stdedos** [comment]
In which format do you prefer?

**Comment by MagicAndre1981** [comment]
doesn't matter. I just want to see which hardware you have

**Comment by pasha-zzz** [comment]
> _all*_ CPUs nowadays offer integrated graphics

No. F.e. Intel with F suffix.

**Comment by stdedos** [comment]
> Post your device specs

![image](https://user-images.githubusercontent.com/133706/78530217-ef0f5200-77eb-11ea-9fd8-5556b4704610.png)

There you go



> > _all*_ CPUs nowadays offer integrated graphics
> 
> No. F.e. Intel with F suffix.

*: all the CPUs I have happened to stumble randomly so far

**Comment by dmex** [comment]
> Add a header like the left one, on the right window

The distribution of nodes with hybrid graphics changes dramatically with multiple graphics cards between different builds of Windows with different versions of the same driver and changes too often making it confusing and would end up looking like spaghetti.

It's a similar thing with the CPU and showing cores/hyperthreads in groups which nobody does because its not accurate and confuses more people than it would help.

**Comment by stdedos** [comment]
Okay, if you say so 😕 

It's just hard to understand at a first glance, why do I have 2 `3D Graphs`, multiple `Video X` graphs etc etc.

If they were separated by physical device, I thought it would be a bit clearer (e.g. clearly group integrated vs external graphics cards).

Basically, I agree with #65; just add on the right window "similar looking" sections like the left window on top of it.

**Comment by dmex** [comment]
> If they were separated by physical device

Adapters will be split into separate graphs and nodes the same way disks/network adapters have separate graphs 👍

**Comment by stdedos** [comment]
> > If they were separated by physical device
> 
> Adapters will be split into separate graphs and nodes the same way disks/network adapters have separate graphs 👍

Well, I'm sorry, but I don't see what you are saying:
![Screenshot_2020-04-08_15-35-25](https://user-images.githubusercontent.com/133706/78784880-ca170c80-79ae-11ea-8fa7-eecd3b61b587.gif)
(_gif is a bit broken, idk what I configured wrong with ShareX_)

![image](https://user-images.githubusercontent.com/133706/78784877-c8e5df80-79ae-11ea-938e-d1b1fc16f436.png)

**Comment by dmex** [comment]
> Well, I'm sorry, but I don't see what you are saying:

It hasn't been added yet.
