### ISSUE TITLE
Viewing stack strings for a thread?

### ISSUE THREAD

**Issue by nyanpasu64** [processhacker/processhacker#592]
Sometimes I have a process where a thread is stuck in an endless loop. I want to use Process Hacker to look for strings in the stack.

NirSoft's WhatIsHang allows you to view strings in a frozen *process*, but not inspect individual threads.

Process Hacker doesn't seem capable of this now. I'll try debugging using Visual Studio or maybe windbg preview.

**Comment by dmex** [comment]
You can right-click the Thread and select Analyze to view the function causing a loop/deadlock but it only shows strings when the stack has a file handle or a known function parameter such as CreateFile/DeviceIoControl.

The Analyze window could easily show strings on the stack for that thread?
