### ISSUE TITLE
"Private WS" not displayed for some processes

### ISSUE THREAD

**Issue by Nojevah** [processhacker/processhacker#593]
In column "Private WS", for some processes (noticed only with Chrome for now), nothing is displayed whereas value is present in process properties. It is displayed correctly with task manager or Process Explorer.

![2020-04-08_11-50-15](https://user-images.githubusercontent.com/7541249/78770674-2ec26f00-798f-11ea-95e5-817d188e69cb.png)

Windows 10 1909
PH x64 Version 3.0.2963

**Comment by dmex** [comment]
Thanks for reporting this bug 👍 

It's a regression from a recent performance patch in the nightly branch and should be fixed in the latest nightly build v3.0.2976
