### ISSUE TITLE
Processes notifications doesn't work

### ISSUE THREAD

**Issue by dondolarson** [processhacker/processhacker#596]
It looks like adding a process*.exe has no impact on notifications, or I'm doing something wrong? I've just started using this functionality and can't tell if it worked before. Services notifications works brilliant though. I'm running the latest version of Process Hacker.

I restart each of them but don't get any notification, even when I paste the destination folder followed with the run ,exe fie at the end of the path.

![Processes](https://user-images.githubusercontent.com/49354563/78843331-cf9e4200-7a02-11ea-8eb8-895d3c061da7.png)

**Comment by dmex** [comment]
By default only the notifications for created/deleted services are enabled. You need to also enable the process notifications using the main menu > View > Tray icons > Notifications menu
