### ISSUE TITLE
[Enhancement] Column View / Items > positional

### ISSUE THREAD

**Issue by nonspin** [processhacker/processhacker#598]
Seems like the "Name" column cannot be moved - positional-wise.
I know it cannot be hidden .. but it would be nice to have a "PID"-column first .. like

PID - Name - CPU ... whatever

Thanks in advance

btw, if a (darker) "Theme" is applied, 
The "View -> Toolbar -> Customize"-Window ignores it - no effect

**Comment by dmex** [comment]
> Seems like the "Name" column cannot be moved

The flags are disabled for the processes tree. I could enable them so it can be moved with another column becoming the tree but it won't sort by that new column.

**Comment by dmex** [comment]
> he "Name" column cannot be moved

Changing the `ProcessTreeListNameDefault` setting to `0` enables moving the Name column

> Toolbar -> Customize"-Window ignores

Fixed a while ago but this issue wasn't updated 👍
