### ISSUE TITLE
ProcessHacker just crashed

### ISSUE THREAD

**Issue by MarkusGaugg** [processhacker/processhacker#600]
Minidump attached. 
[ProcessHacker_CWSGYTJBUSFPKPR_DumpFile.zip](https://github.com/processhacker/processhacker/files/4499074/ProcessHacker_CWSGYTJBUSFPKPR_DumpFile.zip)

**Comment by dmex** [comment]
The crashing issue was fixed in the latest nightly build. You can download the update using Help > Check for Updates 👍

**Comment by MarkusGaugg** [comment]
Thank you for your fast response and your good work. Keep it up :thumbsup:
