### ISSUE TITLE
ProcessHacker resumes suspended threads after viewing the callstack.

### ISSUE THREAD

**Issue by qsneeze** [processhacker/processhacker#601]
Say a process has a thread in a suspended state. When ProcessHacker goes to read the call stack of that suspended thread, ProcessHacker ends up resuming the thread instead of leaving it in its suspended state.

Version 3.0.3031 (61e12369)
KProcessHacker is enabled
All default plugins are enabled.

**Comment by qsneeze** [comment]
Updated version information

**Comment by dmex** [comment]
I've removed the code causing this issue that I added as a workaround for better responsiveness of the stack dialog when downloading symbols 👍
