### ISSUE TITLE
use it in cli for scripting

### ISSUE THREAD

**Issue by x0rld** [processhacker/processhacker#604]
Hi
Is it possible to use processhacker in cli and extract the memory strings like in the screenshot ? 
![image](https://user-images.githubusercontent.com/45242856/80892658-17477f00-8ccc-11ea-9f16-c26ee3a8b93e.png)
or even with the sdk ?

**Comment by dmex** [comment]
Have you tried strings from Microsoft?
https://docs.microsoft.com/en-us/sysinternals/downloads/strings
