### ISSUE TITLE
Help->log no PID

### ISSUE THREAD

**Issue by kilitary** [processhacker/processhacker#606]
no PID for logged services.
this is like showing that svchost.exe is using microphone in  windows 10, but not showing what PID.
Correct that.

**Comment by dmex** [comment]
The PID is included on the log inbetween brackets?

![image](https://user-images.githubusercontent.com/1306177/81026951-3fe39a80-8ebf-11ea-8ce8-f3f28f76c787.png)

**Comment by kilitary** [comment]
i am blind
