### ISSUE TITLE
WDDM version listed as 'ERROR' 

### ISSUE THREAD

**Issue by DmitryKo76** [processhacker/processhacker#608]
In  System Information, the Details window on the GPU tab of shows me "ERROR" instead of actual WDDM version.
 
Also, you have to pass the size of  **D3DKMT_DRIVERVERSION** to EtpGetGpuWddmVersion,  not D3DKMT_ADAPTERTYPE  (though by coincidence they are both _unsigned int_).

**Comment by dmex** [comment]
> you have to pass the size of D3DKMT_DRIVERVERSION to EtpGetGpuWddmVersion

It was copypasta. The function wasn't used so I removed it.

> the Details window on the GPU tab of shows me "ERROR" instead of actual WDDM version. 

Thanks, fixed in latest nightly build 👍

**Comment by DmitryKo76** [comment]
Thankls! FYI the [latest SDK ](https://docs.microsoft.com/en-us/windows-insider/flight-hub/)includes a definition of **KMT_DRIVERVERSION_WDDM_2_8 = 2800**.

Also you don't have to throw error for unknown values - enum is encoded wth a straightforward formula, so you can derive major and minor versions from it:
```
MajorVer = DriverVer / 1000;
MinorVer = ( DriverVer - MajorVer * 1000) / 100
```

**Comment by dmex** [comment]
> you don't have to throw error for unknown values

We're unfortunately using a lot of undocumented structures. I've been using the error value as a visual indication that we have to review the undocumented types for changes. It's also been handy for identifying which exact insider build introduced those changes which makes it easier :P

**Comment by DmitryKo76** [comment]
Kernel-mode display driver thunks are documented, they were part of Windows DDK since VIsta and [D3DKMthk.h](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/d3dkmthk/ne-d3dkmthk-_qai_driverversion) comes with Windows SDK 19041 (20H1).

**Comment by dmex** [comment]
@DmitryKo76 

Not all types are included. For example the NODEMETADATA structure has been included on Windows for about 3 years but was only added in the last two months and there are others.
