### ISSUE TITLE
Connections to nyc-lane.wj32.org

### ISSUE THREAD

**Issue by j123123** [processhacker/processhacker#609]
When I started processhacker first time, I saw some connection to nyc-lane.wj32.org - this is @wj32 domain name
I don't think this is some malicious activity, maybe I need to disable update checks, but ... how about to completely disable ANY processhacker network activity by default, and allow it only if user agrees? And where in the source code that "nyc-lane.wj32.org" domain? I don't see it there.

**Comment by dmex** [comment]
> completely disable ANY processhacker network activity by default

You would need to disable these two settings in the options window:

Options > General > Resolve network addresses
Options > Updater > Check for updates automatically

1) Resolving network addresses sends queries to the DNS server for IP address hostname.
2) Downloads a JSON file from the build server (sourceforge.net and wj32.org)

> where in the source code that "nyc-lane.wj32.org" domain? I don't see it there.

wj32.org is the domain for the A and AAAA records.
nyc-lane.wj32.org is the domain for the PTR record.
