### ISSUE TITLE
Show progress for a file handle

### ISSUE THREAD

**Issue by VasiliPupkin256** [processhacker/processhacker#612]
The unix utility called `progress` is able to show progress of a file processing task for a separate process. It reads the file pointer for an open file and divides it by the file size. It would be very nice to see the same in ProcessHacker. If only it would be possible to implement the feature in the driver and show progress bar for each file handle without a major performance drawback .

**Comment by dmex** [comment]
Process Hacker does show the offset position of File handles which is similar to 'Progress' but the position information is not available for all files such as when they're memory mapped:

![image](https://user-images.githubusercontent.com/1306177/81316183-9a9f1100-90ce-11ea-8679-f85b7982f15f.png)

The value also doesn't currently refresh unless you close/open the dialog which I guess wouldn't help see the realtime progress of the position?

**Comment by VasiliPupkin256** [comment]
In which version was it introduced? I don't see this field and in my processhacker the handle properties dialog is different

**Comment by VasiliPupkin256** [comment]
Ok. I've installed the version 3 from nightly builds and it indeed has this feature implemented. It seams that the major feature request should be the request to release.
