### ISSUE TITLE
phnt incompability

### ISSUE THREAD

**Issue by mq1n** [processhacker/processhacker#614]
When I try include "WbemCli.h" or "WbemIdl.h" file to my project it's cause some incompability issues with phnt.

If I put the "WbemXXX" includes to top of my project(before than phnt) the compiler spreads some random winsock errors, just like;
`
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(2547): message : see previous definition of 'STATUS_FLOAT_MULTIPLE_TRAPS'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ntstatus.h(7650,1): warning C4005: 'STATUS_REG_NAT_CONSUMPTION': macro redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(2548): message : see previous definition of 'STATUS_REG_NAT_CONSUMPTION'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared\ntstatus.h(8633,1): warning C4005: 'STATUS_HEAP_CORRUPTION': macro redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winnt.h(2549): message : see previous definition of 'STATUS_HEAP_CORRUPTION'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(171,1): warning C4005: 'FD_SET': macro redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(99): message : see previous definition of 'FD_SET'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(180,16): error C2011: 'timeval': 'struct' type redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(1035): message : see declaration of 'timeval'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(236,17): error C2011: 'hostent': 'struct' type redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(1023): message : see declaration of 'hostent'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(564,1): warning C4005: 'FD_CONNECT': macro redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(563): message : see previous definition of 'FD_CONNECT'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(567,1): warning C4005: 'FD_CLOSE': macro redefinition
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(564): message : see previous definition of 'FD_CLOSE'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(1625,1): error C2375: 'accept': redefinition; different linkage
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(739): message : see declaration of 'accept'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(1647,1): error C2375: 'bind': redefinition; different linkage
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\winsock.h(744): message : see declaration of 'bind'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(1668,1): error C2375: 'closesocket': redefinition; different linkage
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(4206,1): error C2059: syntax error: '}'
2>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\WinSock2.h(4206,1): error C2143: syntax error: missing ';' before '}'
`

Otherwise when the phnt headers on top of the my project, some Wbem functions are missing, just like;
`
Error	C2039	'GetNames': is not a member of 'IWbemClassObject'
Error	C3536	'hError': cannot be used before it is initialized	
Error	C2039	'Get': is not a member of 'IWbemClassObject'
Error	C2039	'ConnectServer': is not a member of 'IWbemLocator'	
Error	C2039	'ExecQueryAsync': is not a member of 'IWbemServices'	
`

IDE: Visual studio 2019 & Win10 SDK

**Comment by dmex** [comment]
How do you include the PHNT headers in the project?

This compiled fine for me:
```
#include <phnt_windows.h>
#include <phnt.h>

#include <WbemCli.h>
#include <WbemIdl.h>
```

**Comment by mq1n** [comment]
When I try include like your posted, some Wbem functions are seems missing.

`
Error C2039 'GetNames': is not a member of 'IWbemClassObject'
Error C3536 'hError': cannot be used before it is initialized
Error C2039 'Get': is not a member of 'IWbemClassObject'
Error C2039 'ConnectServer': is not a member of 'IWbemLocator'
Error C2039 'ExecQueryAsync': is not a member of 'IWbemServices'
`

**Comment by dmex** [comment]
Is this in a CPP file or C file?

**Comment by mq1n** [comment]
It's a .cpp file

https://i.imgur.com/sVY4I8r.png

**Comment by dmex** [comment]
Open phnt_windows.h and remove these lines:

```
#ifndef CINTERFACE
#define CINTERFACE
#endif

#ifndef COBJMACROS
#define COBJMACROS
#endif
```

**Comment by mq1n** [comment]
Now works fine 👍
