### ISSUE TITLE
Avast: Error updating to the latest version

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#615]
@dmex: Avast's new scourge:

![image](https://user-images.githubusercontent.com/133706/81487672-24361680-9268-11ea-9105-3d51374afd1f.png)

_As always, FYI - you don't need to care_

Solution for others: Disable Avast! before starting to download. Can enable after (with known limitations)

**Comment by dmex** [comment]
"The file or directory has been corrupted and is not possible
to read."

> Disable Avast! before starting

Disabling Avast won't stop it form corrupting other files. I'd recommend uninstalling Avast before your machine is trashed especially considering they were caught stealing personal documents and data from users machines.
