### ISSUE TITLE
ClamWin Memory Scan detected a virus on Process Hacker

### ISSUE THREAD

**Issue by g-2-s** [processhacker/processhacker#617]
Hello, I just made a memory scan with ClamWin 0.99.4 and it has detected a virus on ProcessHacker.exe: the virus in question is called Win.Virus.Expiro-7614864-0. I have no idea if this is legit or not, I downloaded the installer from https://processhacker.sourceforge.io/downloads.php

Here's the ClamWin report:

Scan Started Fri May 15 12:11:45 2020

-------------------------------------------------------------------------------

 *** Scanning Programs in Computer Memory ***

 *** Memory Scan: using ToolHelp ***

Unloading program C:\Program Files\Process Hacker 2\ProcessHacker.exe from memory

 *** Scanned 34 processes - 531 modules ***

 *** Computer Memory Scan Completed ***

C:\Program Files\Process Hacker 2\ProcessHacker.exe: Win.Virus.Expiro-7614864-0 FOUND

----------- SCAN SUMMARY -----------

Known viruses: 6945073

Engine version: 0.99.4

Scanned directories: 0

Scanned files: 565

Infected files: 1

Data scanned: 321.90 MB

Data read: 0.00 MB (ratio 0.00:1)

Time: 4067.520 sec (67 m 47 s)

--------------------------------------

Completed

--------------------------------------

**Comment by dmex** [comment]
> Expiro.A creates a duplicate file alongside of infected files named with an .IVR extension.

Do you have a file named ProcessHacker.IVR in the C:\Program Files\Process Hacker 2\ directory?

**Comment by g-2-s** [comment]
I'm a newbie at tech stuff so I panicked and uninstalled Process Hacker after the scan finished. I was about to reinstall it again but I just read your comment. The file in question is not present, could you help me in figuring out what should I do now as my next steps? Reinstall it and run another scan? Thanks.

**Comment by dmex** [comment]
> the virus in question is called Win.Virus.Expiro

The Win.Virus.Expiro virus creates files with the extension IVR when you're infected. 

> The file in question is not present

This would mean no virus infection and it's a false positive.

> could you help me in figuring out what should I do now as my next steps? 

Reinstall and submit a false positive to the antivirus vendor I guess.
