### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by JW-Schuetz** [processhacker/processhacker#618]
For me the build is broken because PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY is undefined.

**Comment by Biswa96** [comment]
Try to use latest Windows SDK or DDK. `PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY` should be in winnt.h (um) or ntddk.h (km).

**Comment by JW-Schuetz** [comment]
It worked, thanks
