### ISSUE TITLE
Is there a way to disable the tooltips?

### ISSUE THREAD

**Issue by sorin-costea** [processhacker/processhacker#619]
For me they are quite distracting and I don't understand (nor care about) most of the information presented in them anyway. I mostly use PE to kill hanging processes (often, due to debugging my work) and having everything popping around while I hover in search of a process is confusing... thank you!

**Comment by dmex** [comment]
You can disable tooltips by changing the `EnableTooltipSupport` setting to zero

**Comment by sorin-costea** [comment]
Uh there's no such setting I can see, in any of the 5 Options tabs.

dmex <notifications@github.com> schrieb am Di., 19. Mai 2020, 15:45:

**Comment by dmex** [comment]
Options > General > check the "Show advanced options" setting
Options > Advanced > EnableTooltipSupport > double click > 0

You might have to relaunch Process Hacker after changing the option

**Comment by sorin-costea** [comment]
I'm in 2.39.124 and I don't have a "show advanced" on my General tab. I do
have an Advanced tab showing, with a setting called "Show tooltips
instantly" which only changes the speed of the tooltips popups. Could be
that you have an older version and the setting was removed in the meantime?

dmex <notifications@github.com> schrieb am Di., 19. Mai 2020, 15:55:

**Comment by dmex** [comment]
The show advanced option is only available in the nightly builds. You'll have to edit the settings file manually to disable the tooltips.

1) Exit PH
2) Open %appdata%\Process Hacker 2\settings.xml
3) Change EnableTooltipSupport to 0
4) Start PH

**Comment by sorin-costea** [comment]
Thank you, but I don't have any settings.xml there.
I googled about that and could only find mentions of creating by hand a
ProcessHacker.exe.settings.xml which I created. Indeed PH saves some stuff
there but now every time I start it, it will complain the settings are
corrupt and resets them to defaults. So I removed that file. Any other
ideas how I could get a working settings.xml?

dmex <notifications@github.com> schrieb am Di., 19. Mai 2020, 18:23:

**Comment by dmex** [comment]
> only find mentions of creating by hand a ProcessHacker.exe.settings.xml

That configuration file is for portable builds which shouldn't be used for non-portable installations.

> I don't have any settings.xml there

The path is always this location:
C:\Users\USERNAME\AppData\Roaming\Process Hacker 2\

Nightly builds have a slightly different location:
C:\Users\USERNAME\AppData\Roaming\Process Hacker\

If the folders are not in those locations then you might have to open command and execute `echo %appdata%` to find the appdata folder.

Otherwise update to the nightly build and use the newer advanced configuration options:
https://processhacker.sourceforge.io/nightly.php

**Comment by sorin-costea** [comment]
`  <setting name="EnableTooltipSupport">0</setting>` and same tooltips...

**Comment by dmex** [comment]
Did you exit PH before changing the setting?

**Comment by sorin-costea** [comment]
Yes I did. The problem is, after restarting PH, it OVERWRITES the settings.xml and removes my changes.

**Comment by sorin-costea** [comment]
Sorry, to be more precise:
- I stop PH
- edit settings.xml
- start PH
- the tooltips are still there (setting ignored)
- close PH
- settings.xml gets overwriten when exiting (I see the timestamp) and my setting goes away

**Comment by dmex** [comment]
> settings.xml gets overwriten when exiting (I see the timestamp) and my setting goes away

The settings are cached when starting PH. If the settings are reset then it's the value that was cached at startup.

> I stop PH

Maybe it didn't fully exit before you changed the setting or some other program (e.g. antivirus) is blocking changes to the settings file.

You could try rebooting then changing the settings and starting PH or try using the nightly build (which has a different settings path and not be blocked by antivirus)?

> the tooltips are still there (setting ignored)

The tooltips are disabled for the processes tab and system information window but some others like toolbar graphs and properties window will remain enabled. I just checked and the setting works in those cases so it should work on your machine unless something else is doing something to the settings file.

**Comment by sorin-costea** [comment]
Rebooted, same behavior. I have no idea if the AV does something (although I don't see why it should) so I think I'll have to live with it... Thank you for your support!
