### ISSUE TITLE
unable to load the kernel driver signature

### ISSUE THREAD

**Issue by trippleflux** [processhacker/processhacker#623]
![ProcessHacker](https://user-images.githubusercontent.com/1216215/82875192-49fa3580-9f61-11ea-87a0-43ada1dae0e7.png)

I am building the latest vanilla git using Visual Studio 2019 16.6.0 because needing plugins-extra, when  i am enabling "Enable start as admin" in the option, and re-run process hacker, i am getting error above, the kernel driver (kprocesshacker.sys) is not re-compiled or self compiled, it the default signed one copied from either nightly build or when self-building the process hacker.

How to proceed with these?

It's running on Windows 10 x64 Enterprise 2004, no 3rd-party antivirus/anti-malware being installed, only default windows defender.

**Comment by dmex** [comment]
If you don't care about using the driver disable the error dialog by changing the `EnableKphWarnings` setting to zero.

The official driver can't be used with unofficial builds compiled from github souce without changing the hard-coded public keys and resigning the driver.  You need to generate a new keypair using the \tools\CustomSignTool\ project, update the public key hard-coded in the driver source (verify.c) and sign the processhacker.exe binary using the private key (CustomSignTool) saving the signing signature into processhacker.sig.

**Comment by trippleflux** [comment]
I see, thanks, to make it easier for all us, would you also includes nightly build for plugins-extra available?

**Comment by dmex** [comment]
> would you also includes nightly build for plugins-extra

These plugins are generally incomplete or cause issues?

**Comment by Biswa96** [comment]
How about adding a `#define MAINTAINER_MODE 0` (or something like it) by default which will make all the verification functions to dummy functions like `return 0;` ?

**Comment by Avtroman** [comment]
Search "unable to load" and comment this block

**Comment by dmex** [comment]
> make all the verification functions to dummy functions

I've silenced the error prompts for debug builds. I'll look at doing that with the driver later.
