### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#624]
Can't compile, many errors. Compilation was be ok about 3 weeks ago, and earlier.

Errors - https://cloud.mail.ru/public/4Wek/CC1z9Cbdc

Main: process_magration_user_shadow_stack_policy symbol not defined. And many symbols not defined

**Comment by Biswa96** [comment]
Duplicate of https://github.com/processhacker/processhacker/issues/618 issue. Try to use latest Windows SDK or DDK. `PROCESS_MITIGATION_USER_SHADOW_STACK_POLICY` should be in winnt.h (um) or ntddk.h (km).

**Comment by Avtroman** [comment]
I have latest SDK and Visual Studio 2019 16.6. 0

Earlier, always compile was be OK, without any errors

**Comment by dmex** [comment]
You need to select the 10.0.19041.0 SDK in the visual studio installer:

![image](https://user-images.githubusercontent.com/1306177/83224326-76f85380-a1c0-11ea-8969-95ff819eb2b8.png)
