### ISSUE TITLE
[Bug] Can't run task with argument

### ISSUE THREAD

**Issue by a1lic** [processhacker/processhacker#625]
Attempt to create task as administrator, executable file with some arguments (e.g. "regedit /m", "cleanmgr /d c"), PH says "File not found". Same behavior on fullpath and PATHed.
It happens when create task with Administrator. (Administrator+TrustedInstaller or None are OK.)
![ph_run1](https://user-images.githubusercontent.com/4565500/83315544-94c6c680-a25b-11ea-8901-2e21f01c21ff.png)

PH said:
Unable to execute the command.
The system cannot find the file specified.
![ph_run2](https://user-images.githubusercontent.com/4565500/83315547-985a4d80-a25b-11ea-907f-f6598b96d129.png)
This text is "指定されたファイルが見つかりません" because I use Japanese as OS language.

**Comment by dmex** [comment]
Thanks, fixed in latest nightly build 👍
