### ISSUE TITLE
Stopping Driver does not refresh the view

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#627]
_Details, origin etc in https://github.com/antonpup/Aurora/issues/2062_

For

![image](https://user-images.githubusercontent.com/133706/83552862-18f6a380-a513-11ea-86af-f8e1eec3952b.png)

when I stopped the Driver, the view did not refresh. Asking PH to Stop the driver again (because it was appearing Started, and I was able to), I got the "cannot stop non-started driver" message, and still it wasn't updated.

![image](https://user-images.githubusercontent.com/133706/83560798-755fc000-a51f-11ea-851f-38fe03516eb7.png)

_Service not started_

**Comment by dmex** [comment]
What's the value of the EnableServiceNonPoll setting?

Try changing the setting value and relaunching PH?

**Comment by stdedos** [comment]
> What's the value of the EnableServiceNonPoll setting?

Value 1, Default 0

> Can you try changing the setting value and relaunching PH.

What is "the value you are expecting the flag to have"?
I see a lot of advanced settings having non-default actions, without me touching them 😕

**Comment by dmex** [comment]
> What is "the value you are expecting the flag to have"?

The value that fixes the refreshing of the services window after stopping a driver (the same issue you reported).

Try changing the value. It enables/disables the polling mode/notifications for driver/service events. I made various changes to service/driver event callbacks and knowing which value fixes the issuewill determine the default value.

> The value that fixes the refreshing of the services window after stopping a driver (the issue you reported).

Some settings are changed via UI while others were changed in updates (which don't change existing preferences).

**Comment by stdedos** [comment]
> Some settings are changed via UI while others were changed in updates (which don't change existing preferences).

If a value is not explicitly changed, is its default written to the config file, or not?

I would expect that I can keep up with your defaults, given that I have not changed them.

(For the "really" advanced options, I would also expect that if we e.g. discuss and we change a value during a troubleshooting session, "after a while" I would be informed that it's high time I reset it / the bug that this value worked around is fixed, and _whether I would consider now following the defaults or not_. But I guess that would be a very, very big feature 😄)

**Comment by stdedos** [comment]
Neither seems to work
![image](https://user-images.githubusercontent.com/133706/83560798-755fc000-a51f-11ea-851f-38fe03516eb7.png)

_Service not started_

**Comment by dmex** [comment]
> If a value is not explicitly changed, is its default written to the config file, or not?

The default is from the very first installation. If the default gets changed in a later update then it'll still be the original value in order to preserve your preferences.

> would be informed that it's high time I reset it

When a reset is required its already done automatically by the newer version 👍 

> 0 seems to work

The previous default was 1 but I changed this to 0 a few weeks ago in the nightly builds after adding/updating newer windows service/driver notification callbacks.

0 should be the default going forward but there still might be increased CPU usage in the services.exe process. Let me know if you notice any issues with services.exe

**Comment by stdedos** [comment]
FYI, now I am on i5-4430, but (hopefully) will soon move to an i7-9700K.

If you would be looking a more "legacy-friendly" view, soon that might not be me.

**Comment by dmex** [comment]
> don't raise this to Microsoft standards

Nah. I just stop using that setting entirely and remove the older code unlike the BS with win10 updates 😄 

> If you would be looking a more "legacy-friendly" view, soon that might not be me.

I still have machines with XP running v2.38 and earlier versions for testing 👍
