### ISSUE TITLE
Feature: Support for RTSS/MSI Afterburner OSD overlay

### ISSUE THREAD

**Issue by altimumdelta** [processhacker/processhacker#629]
Hello

I was wondering one day would it be cool to support Rivatuner Statistics Server and also MSI Afterburned I believe because I'm not sure if RTSS can be used by it self or I never figured out how to do so.

Particularly interested in showing Thread activity for a specific process for OSD, so that it's visible in a fullscreen application.

However in MSI Afterburner when trying to add Data Providers it seems like there's no way to add a custom one, only the ones MSI has to support, so this may need some back-and-forth with them perhaps?

Much appreciated, but I understand this may not be small amount of work.

**Comment by altimumdelta** [comment]
https://forums.guru3d.com/threads/msi-afterburner-net-class-library.339656/

**Comment by dmex** [comment]
Support for the xbox game bar would be better since it's included with Win10 by default:
https://docs.microsoft.com/en-us/gaming/game-bar/overview
