### ISSUE TITLE
Request:      view   total  column values when collapse  [ example  picture]:

### ISSUE THREAD

**Issue by BunyaminBozdagli** [processhacker/processhacker#630]
![image](https://user-images.githubusercontent.com/63051484/84104159-9e032080-aa1d-11ea-92eb-920e29b2b786.png)

**Comment by Biswa96** [comment]
IT looks like you are using old ProcessHacker version. Try to use the nightly one from here https://processhacker.sourceforge.io/nightly.php.

**Comment by BunyaminBozdagli** [comment]
> IT looks like you are using old ProcessHacker version. Try to use the nightly one from here https://processhacker.sourceforge.io/nightly.php.

![image](https://user-images.githubusercontent.com/63051484/84105188-3e5a4480-aa20-11ea-97f4-e2dc8b945b5b.png)
win 7 64-bit

**Comment by dmex** [comment]
> win 7 64-bit

2.39 is the current stable TLS while the latest nightly is 3.00

> Request: view total column values when collapse

This was fixed in the nightly builds:
https://processhacker.sourceforge.io/nightly.php

**Comment by BunyaminBozdagli** [comment]
> > win 7 64-bit
> 
> 2.39 is the current stable TLS while the latest nightly is 3.00
> 
> > Request: view total column values when collapse
> 
> This was fixed in the nightly builds:
> https://processhacker.sourceforge.io/nightly.php

Thanks.
