### ISSUE TITLE
Request:   some same notifications bothers me constantly.  I would like   the user-prefered blacklist feature   to be added to this program

### ISSUE THREAD

**Issue by BunyaminBozdagli** [processhacker/processhacker#631]
![image](https://user-images.githubusercontent.com/63051484/84105055-d7d52680-aa1f-11ea-9f13-f836dd72c349.png)

**Comment by dmex** [comment]
You can blacklist proceses from notifications using the Hacker menu > Plugins > ExtendedNotifications > Options

Enter the process name, select Exclude and add the entry:

![image](https://user-images.githubusercontent.com/1306177/84107773-e5ab9b80-aa61-11ea-8fcd-d6082b8ae25a.png)

**Comment by BunyaminBozdagli** [comment]
> You can blacklist proceses from notifications using the Hacker menu > Plugins > ExtendedNotifications > Options
> 
> Enter the process name, select Exclude and add the entry:
> 
> ![image](https://user-images.githubusercontent.com/1306177/84107773-e5ab9b80-aa61-11ea-8fcd-d6082b8ae25a.png)

Thanks
