### ISSUE TITLE
Viewing Heaps for suspended UWP apps causes PH to crash (0xc0000005)

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#634]
When I use the new Heap View, PH first hangs and later crashes if I try to view heaps for a suspended UWP app.

Win10 2004 (19041.331), 32Bit, [PH3.0.3146](https://github.com/processhacker/processhacker/commit/c46fddb859fc7ca8a8ef8be22484d7720f52fa4f)

**Comment by MagicAndre1981** [comment]
On 64 Bit 18362 I have no issues.

Here is windbg output:

```
FAULTING_SOURCE_FILE:  D:\processhacker\phlib\native.c

FAULTING_SOURCE_LINE_NUMBER:  8964

FAULTING_SOURCE_CODE:  
  8960:         RtlDestroyQueryDebugBuffer(debugBuffer);
  8961:         return status;
  8962:     }
  8963: 
> 8964:     heapDebugInfo = PhAllocateZero(sizeof(PH_PROCESS_DEBUG_HEAP_INFORMATION) + debugBuffer->Heaps->NumberOfHeaps * sizeof(PH_PROCESS_DEBUG_HEAP_ENTRY));
  8965:     heapDebugInfo->NumberOfHeaps = debugBuffer->Heaps->NumberOfHeaps;
  8966:     heapDebugInfo->DefaultHeap = debugBuffer->ProcessHeap;
  8967: 
  8968:     for (ULONG i = 0; i < heapDebugInfo->NumberOfHeaps; i++)
  8969:     {


SYMBOL_NAME:  ProcessHacker!PhQueryProcessHeapInformation+8d

MODULE_NAME: ProcessHacker

IMAGE_NAME:  ProcessHacker.exe

STACK_COMMAND:  ~0s ; .ecxr ; kb

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_ProcessHacker.exe!PhQueryProcessHeapInformation

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x86

OSNAME:  Windows 10
```

![image](https://user-images.githubusercontent.com/8274816/85694002-049f6400-b6d7-11ea-912e-5fdc556cfe69.png)

**Comment by dmex** [comment]
Fixed in latest nightly build 👍

**Comment by MagicAndre1981** [comment]
> Fixed in latest nightly build 👍

ok, I get the messagebox now, but as said it works in 190x, so maybe check debugBuffer for NULL so that we can still query it on 190x

**Comment by dmex** [comment]
>  so maybe check debugBuffer for NULL

This is how I fixed the crash.

> we can still query it on 190x

It still needs some work. I'll enable querying UWP in a day or two.

**Comment by MagicAndre1981** [comment]
> It still needs some work. I'll enable querying UWP in a day or two.

ok

**Comment by MagicAndre1981** [comment]
> > so maybe check debugBuffer for NULL
> 
> This is how I fixed the crash.

you skip the call by checking is process is immersive and return . So the code is not executed. I just tested 1709 and 1809 with old version and here I can view the data for suspended apps (shell is suspended as I use StartIsBack++)

![image](https://user-images.githubusercontent.com/8274816/85957669-7f92a400-b98f-11ea-9333-2e09fe329e9f.png)

The new code also blocks viewing heap for store apps on my mainly used Windows 8.1.

So maybe MS broke the API in 2004 or changed it a bit which caused the error.

**Comment by dmex** [comment]
> you skip the call by checking is process is immersive and return

I fixed the crash by checking if the buffer is null:
https://github.com/processhacker/processhacker/blob/d69943514418ad41f0e62899e7c9b2edf24a5cc8/phlib/native.c#L8968-L8977

> The new code also blocks viewing heap for store apps

This is temporary. Querying store apps can still deadlock the entire process when it gets automatically suspended while we're querying heaps. I've been testing various methods to enable the process and disabled the query while working on that issue.
