### ISSUE TITLE
ProccessHacker always opens in the background (beind other windows, ie. not foreground).

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#639]
Hi! I don't know if this is common, but for me it is and I'm constantly having to fight with it, hope something positive can come from this report.

Anyways, so what I mean by this is, if I run ProcessHacker, it always opens behind other windows, for example, I have an windows explorer.exe window and foobar2000.exe and notepad++.exe open on my second monitor, if I run PH it opens on my second monitor too, but always behind other things like these example, then I need to click PH to bring it to the foreground to see things.

PH should always launch in the foreground no? Can it be made this way somehow? Windows 10 Task Manager for example ways launches in the foreground, that's how a "Task Manager" type program should act IMO.

Few notes I guess, on the latest Windows 10 update, using latest dev build of PH currently at (3.0.3160), PH runs as admin, PH runs in a window size (not fullscreen), view setting > "Always on top" is unchecked. (but checking this still has PH start behind things regardless, it just stays in focus once it has it by clicking it).

Hopefully I made this issue clear, and it's not just me, and someone can help, and lastly thanks for reading.

**Comment by Biswa96** [comment]
Not an issue in my case. Did you enable "Start Hidden" option?

**Comment by ImSpecial** [comment]
Nope, my settings. https://i.imgur.com/eNUTyy6.png

**Comment by ImSpecial** [comment]
Did some light testing, it doesn't happen "normally", but when fullscreened "things" are running on my primary monitor this happens, so like a video game that is running either fullscreened or windowed fullscreen, wish there was a way to get around this...

Just want to add that doing the Ctrl+Shift+Esc to bring up Window's Task Managers is always foreground, so there's got to be a way to make ProccessHacker do the same.

**Comment by dmex** [comment]
> start behind things regardless

The 'Enable start as Admin' setting is not able to show the window in the foreground due to how Task Scheduler executes the binary. I'm still looking into methods to resolve the issue.

> doing the Ctrl+Shift+Esc to bring up Window's Task Managers is always foreground

Task Manager is using a function named CreateWindowInBand for showing top-most but this function includes a signature check for "Microsoft Windows" preventing third party products from calling that API - It's one of the most anti-competitive functions on Windows designed to give Microsoft an unfair competitive advantage over third party products.

**Comment by ImSpecial** [comment]
Well I'm glad you understand the situation at least, and good luck on your journey to finding a solution too, I'll just sit patiently for that day then, honestly it's my only grip with PH... otherwise such a great TM. Thanks.

**Comment by ImSpecial** [comment]
You know, another thing I just noticed was on my second monitor, I use DisplayFusion along with [Open-Shell](https://github.com/Open-Shell/Open-Shell-Menu), and when I launch PH from that, it's foreground, it's opening above my foobar2000 music player for example, but when I launch PH using Windows own gross start menu/billboard it's opening behind foobar2000 and other things like notepad. Just a thing I wanted to add...

**Comment by ImSpecial** [comment]
Just want to update and correct the above info I said earlier about DisplayFusion and Open-Shell, basically disregard it, it's not 100% the case it seems and I can't reproduce it always, so it's kinda false info and don't want anyone to waste their time having them look into that.

**Comment by pasha-zzz** [comment]
> due to how Task Scheduler executes the binary

When using "start" command we can open PH in foreground from Task Scheduler

**Comment by dmex** [comment]
> When using "start" command we can open PH in foreground from Task Scheduler

In this case the console process creates a window when running the start command which is why that methods works. The problem would then be the console window appearing and disappearing within a few seconds. 

The other way would be to manifest the application with requireAdministrator and UIAccess=true for automatic elevation with foreground focus but this requires signing the nightly builds.

**Comment by pasha-zzz** [comment]
> The problem would then be the console window appearing and disappearing within a few seconds confusing people.

Start GUI process w/o windows, it starts "start" in hidden mode, "start" launches PH ;-)

**Comment by pasha-zzz** [comment]
What about command line parameter? For bring main window to front. SetForegroundWindow must working.

**Comment by ImSpecial** [comment]
Maybe look into how CCleaner does it? I've never seen that get hidden behind other windows, it's always foreground, and it launches as admin through Task Scheduler much like Process Hacker.

**Comment by pasha-zzz** [comment]
> Maybe look into how CCleaner does it?

CCleaner signed with Digital Signature - https://github.com/processhacker/processhacker/issues/639#issuecomment-654132244

**Comment by dmex** [comment]
Recently nightly builds included extra foreground checks 👍

**Comment by ImSpecial** [comment]
Does 3.0.4444 have this? Or later as in 3.0.4453?

**Comment by dmex** [comment]
It was done back in June or July but I didn't update the thread... any nightly build in the last 6 months includes the extra foreground states. If there's still issues then always-on-top is the only other option available until Microsoft allow other task mangers access to the CreateWindowInBand function.

**Comment by ImSpecial** [comment]
Oh I see, I updated recently to 4444, on all my PC's so I was only wondering, I can't say I've done much thinking about it issue though, but I'll keep an eye on things now that I know.

**Comment by dmex** [comment]
> can't say I've done much thinking about it

Probably been fixed if you're not seeing the issue and forgotten 😄

**Comment by ImSpecial** [comment]
You know, I wanted to prove your wrong, but I cannot get it to start behind anything that was already opened, so I really think you cracked this nut.

Almost want to ask you how you figured it out/did it, but then again letting the "secret sauce" out will just teach Miscrosoft how to block it. :)

**Comment by dmex** [comment]
>  I cannot get it to start behind anything that was already opened

There are a few cases where this can still happen but most were fixed with some changes to where things were called. The last few will get fixed when CreateWindowInBand can be used (but current restricted to task manager).
