### ISSUE TITLE
Missing GPU text in mini popup window

### ISSUE THREAD

**Issue by AzAgarampur** [processhacker/processhacker#640]
![image](https://user-images.githubusercontent.com/42058942/86076315-b247a580-ba3e-11ea-98aa-03ef4785486a.png)

When the GPU mode is selected, the text GPU does not show. It only shows the percent value instead of `GPU 32.44%` If we could add this that'd be helpful so I don't have to check what mode the mini toolwindow is currently using.

Process Hacker Version 3.0.3146 (c46fddb8)

**Comment by dmex** [comment]
This was fixed in the nightly build from a few days ago 👍 
https://github.com/processhacker/processhacker/commit/bbc4f39d3bc48787a6352c99b1e3f7d7f10377d9
