### ISSUE TITLE
CustomBuildTool.exe Git ef824e8b unable to find installed Visual Studio 2019 VC++ 2019 v16.6.4 

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#645]
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Total 31 (delta 19), reused 19 (delta 19), pack-reused 12
Unpacking objects: 100% (31/31), 3.96 MiB | 485.00 KiB/s, done.
From https://github.com/processhacker/processhacker
   39d6efa3..ef824e8b  master     -> origin/master
Updating 39d6efa3..ef824e8b
Fast-forward
 tools/CustomBuildTool/Build.cs                     |  49 ++++------
 tools/CustomBuildTool/CustomBuildTool.csproj       |   1 +
 tools/CustomBuildTool/Program.cs                   |   7 +-
 tools/CustomBuildTool/Utils.cs                     | 100 +++++++--------------
 tools/CustomBuildTool/app.manifest                 |  40 +++++++++
 .../bin/Release/CustomBuildTool.exe                | Bin 40924450 -> 40924226 b
ytes
 .../bin/Release/CustomBuildTool.pdb                | Bin 16020 -> 16028 bytes
 7 files changed, 95 insertions(+), 102 deletions(-)
 create mode 100644 tools/CustomBuildTool/app.manifest
Already up to date.

$ build_release.cmd
Unable to find Visual Studio.
Для продолжения нажмите любую клавишу . . .

my OS - Win7 SP1 x64, **skipik** use Win10

**Comment by skipik** [comment]
Same problem here.

**Comment by VictorVG** [comment]
I try test use previous build CustomBuildTool.exe  - build PH v3.0.7727.3200 Git-afab9067 Ok!

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Big thanks!

**Comment by VictorVG** [comment]
I test it - problem is exist:

> $ build_release.cmd
> Unable to find Visual Studio.

but, I see git diff:

```
diff --git a/tools/CustomBuildTool/Utils.cs b/tools/CustomBuildTool/Utils.cs
index 2490a468..51093acf 100644
--- a/tools/CustomBuildTool/Utils.cs
+++ b/tools/CustomBuildTool/Utils.cs
@@ -574,9 +574,9 @@ public string MissingDependencyList
                     list += "VC.14.Redist" + Environment.NewLine;
                 }
 
-                if (!this.Packages.Exists(p => p.Id.StartsWith("Microsoft.VisualStudio.Component.Windows10SDK.19041", StringComparison.OrdinalIgnoreCase)))
+                if (!this.Packages.Exists(p => p.Id.StartsWith("Microsoft.VisualStudio.Component.Windows10SDK", StringComparison.OrdinalIgnoreCase)))
                 {
-                    list += "Windows SDK [19041]" + Environment.NewLine;
+                    list += "Windows SDK" + Environment.NewLine;
                 }
 
                 return list;
diff --git a/tools/CustomBuildTool/bin/Release/CustomBuildTool.exe b/tools/CustomBuildTool/bin/Release/CustomBuildTool.exe
index 61c4850d..65660543 100644
Binary files a/tools/CustomBuildTool/bin/Release/CustomBuildTool.exe and b/tools/CustomBuildTool/bin/Release/CustomBuildTool.exe differ
diff --git a/tools/CustomBuildTool/bin/Release/CustomBuildTool.pdb b/tools/CustomBuildTool/bin/Release/CustomBuildTool.pdb
index 484b95ee..e5071c59 100644
Binary files a/tools/CustomBuildTool/bin/Release/CustomBuildTool.pdb and b/tools/CustomBuildTool/bin/Release/CustomBuildTool.pdb differ

```

**Comment by VictorVG** [comment]
Thanks again! Checked out Git [af740c1ee] - BuildTools: Fix dependency string - now everything works. And I was looking for the reasons for the error - I thought that the HDD had a failure.

**Comment by skipik** [comment]
![Снимок экрана (1)](https://user-images.githubusercontent.com/24621645/87873044-becc7780-c9c6-11ea-9343-3acd897db8b1.png)

@dmex it's even worse now. It looks for vs2017. But I have installed vs2019 and SDK 19041. Why it can't find them?

**Comment by VictorVG** [comment]
This is local configuration error (?). I try control build check:

![1](https://user-images.githubusercontent.com/906886/87873876-c2afc800-c9cd-11ea-951c-6996a8b92236.png)

**Comment by skipik** [comment]
> This is local configuration error (?)

No, it's a fresh installed Windows 10 + VS2017 + VS2019 + all the SDKs. No local errors.

**Comment by skipik** [comment]
You can easily repro this on a virtual machine:
Install Windows 10 20H1
Install all SDKs
Install VS 2017
Install VS 2019
That error on my screen

**Comment by skipik** [comment]
So it's a problem with the latest CBT, waiting for a fix.

**Comment by skipik** [comment]
It only reproduces on a fresh installation of windows / vs, that's why you prob don't have it.
But everything works fine with the previous version of CBT, even on a fresh installation.

**Comment by skipik** [comment]
![Снимок экрана (2)](https://user-images.githubusercontent.com/24621645/87876065-0d394080-c9de-11ea-9f41-39f01994319f.png)

No problems on a previous version of CBT, as I've mentioned earlier.

**Comment by dmex** [comment]
@skipik 

fixed 👍

**Comment by VictorVG** [comment]
I also try fix problem in FirewallMonitorPlugin.dll for Windows 10 v1607 - v1803 - I had to tweak the scripts in the toolkit a bit, let's see what users say. "Terrible" warning in the readme.txt of my assembly, I have already entered - let them read it, otherwise the fashion was led by others "I do not want to study, I want to get married!" (A.S. Griboyedov, "Woe from Wit") and instead of reading the documentation, they claim that it does not work like that ... :)

**Comment by skipik** [comment]
Thanks a lot! Now it works correctly!
