### ISSUE TITLE
Updated to 3.0.3231 today, now the Network tab causes my firewall to go off?

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#651]
Basically what the title says, selecting the Network tab now causes my firewall to go off, asking me to grant ProcessHacker internet access, my settings have not changed since previous builds (I think I was on 3.0.3200 prior). Any idea how to can make this stop?

**Comment by dmex** [comment]
Fixed in latest nightly 👍🏿

**Comment by ImSpecial** [comment]
Does what it says on the box, would recommend to friends and family. Thanks!
