### ISSUE TITLE
DbgHelp.dll not always found. Symbols not working

### ISSUE THREAD

**Issue by negrutiu** [processhacker/processhacker#652]
Environment:
* `Process Hacker` 3.0.3205 (latest)
* `Windows 20h1` x64
* `X64 Debuggers And Tools` 10.1.19041.1 (latest)

`Process Hacker` is unable to find DbgHelp.dll at runtime.
In my case debuggers get installed in `C:\Program Files\Windows Kits\10\Debuggers\x64`

Apparently `(symprv.c) PhpSymbolProviderCompleteInitialization` always looks for DbgHelp's location under the WOW64 registry node which in my case doesn't exist.
As soon as I manually create the Software\WOW6432Node\...\KitsRoot10 registry value symbols start to download immediately.

**Suggestion:** both `Software\Windows Kits\...` and `Software\WOW6432Node\Windows Kits\...` should be inspected for DbgHelp.dll location.

**Comment by VictorVG** [comment]
PH don't needed dbghelp.dll, needed latest dbgcore.dll is included as part of Windows 10 Platform SDK, included in to X64 Debuggers And Tools-x64_en-us.msi and X86 Debuggers And Tools-x86_en-us.msi ("\SourceDir\ProgramFiles64Folder\Windows Kits\10\Debuggers\x64\dbgcore.dll" and "\SourceDir\ProgramFiles64Folder\Windows Kits\10\Debuggers\x86\dbgcore.dll"). As example Your can unpack it use [**FarUE x86-64**](https://github.com/VictorVG/FarUE3_x64/releases/) (native portable, ready to use) - select any .msi, Ctrl-PgDn, F5. Current latest version this SDK is 10.0.19041.0 included as part MS VisualStudio 2019 v16.6.x.

**Comment by dmex** [comment]
> X64 Debuggers And Tools 10.1.19041.1 (latest)

The Windows SDK installs both the 32bit and 64bit Debuggers And Tools MSI installer packages which configure both KitsRoot10 values while manually installing the MSI only configures the 64bit value.

> always looks for DbgHelp's location under the WOW64 registry node which in my case doesn't exist.

I've added a second check for the 64bit value 👍🏿
