### ISSUE TITLE
How to make Debug and Release consistent.

### ISSUE THREAD

**Issue by IOL0ol1** [processhacker/processhacker#654]
I get fewer results than Release when I debug with Find Handles or DLLs. 
Do I need special debugging settings?

**Comment by dmex** [comment]
Debuggers have SeDebugPrivilege which you only get with PH by running as administrator?

**Comment by IOL0ol1** [comment]
> Debuggers have SeDebugPrivilege which you only get with PH by running as administrator?

yes,i debug PH with visual studio(as administrator).
Search for “explorer.exe” in **Find Handles or DLLs** window results less than the Release version.
There are no process and thread type search results in debug mode, but there are in the release.

**Comment by dmex** [comment]
I can't reproduce this.

The debug builds don't have mitigation policies so I'd assume something on your machine probably injected code and hooked native functions causing them to return an error.
