### ISSUE TITLE
Feature: New Column: Counter for tracking Thread Bounces in Process Properties -> Threads Tab

### ISSUE THREAD

**Issue by altimumdelta** [processhacker/processhacker#656]
If it's possible to do via some custom calculations? I haven't seen this anywhere else so I'm assuming it's not something provided out of the box from the Windows API and low level providers or any other utilities, but I don't think it should be that hard

I've had this in my mind previously, just never directly tried to get this number specifically with other tools when I working with them. I fired up WPA for now, and am trying to see if it's possible to configure a filter in such a way to show such a count I'm looking for. 

While I can't immediately explain the usefulness of this right now, I do have some ideas, for one it works as an indicator whether or not a Thread is really glued to a particular CPU core or not (whether respecting the affinity settings 100% of the time)

This data it self may not be that useful, but I have some other ideas pairing it in context with other data, at least to prove a point that I would be doing in a performance analysis, perhaps to negate something, so it may be used to disprove if a particular behavior has any effect/difference compared to another, so that's why I think it could be useful even if it's not directly useful.

Additionally, perhaps a "delta" version of this counter could also be added, just like "Context Switches Delta"

I also propose some possible names for this new column label: 

> CPU-Relocative Context Switches
> CPU-Migrative Context Switches
> CPU-Transferring Context Switches
> 
> Relocating Context Switches
> Context Switches Between CPUs
> 
> Thread Bouncing Count
> Thread Bounces 
> Thread Migrations
> Thread Relocations
> Thread Reassignments
> 
> Thread CPU Transference Count

However, after all this moniker thinkering, depending on what behavior is actually behind "Context Switches",  the whole Thread Bounce count may not be comparable and would be a different thing, there's nothing different that happens under the hood, we just use the same data and order it differently to get some new statistic out, right, perhaps it should not have any relation to "Context Switching" terminology in that case.

Logically I presume this is how this would be detected, but in practice ofcourse this would need to be modified for performance, however I don't think it could work with "Any Last-Thread that switched out" ... it should be monitoring each Thread ID separately because other threads could switch in on another CPU before it, so the code would need to be more advanced and making sure edge cases are covered and other safety.
```
if (Thread-9542 Switches-Out on Last-CPU) && (Thread-9542 Switches-In on !Last-CPU))
{
Thread_Bounce++;
}
```

While I meant this only for Threads, this could be done for Processes too if it's not too difficult (probably just a sum of all thread to core bounces right?), except it's harder to justify the usefulness for Processes.

**Comment by dmex** [comment]
Last I checked Windows doesn't expose information about which core the thread was/is currently executing so you can't calculate "thread bounces".

The spectre fixes for CPU errata also changed the scheduling on Windows such that threads always execute on the same core instead of switching to the first available core (mitigating the majority of speculative execution issues) so if it does expose the information it wouldn't be of any use?

**Comment by altimumdelta** [comment]
I was about to reply, this shouldn't be completely over yet, but we can discuss while it's closed and reopen it later if okay.

**Comment by altimumdelta** [comment]
Yes it's definitely unusual. I've opened this ticket up a bit too early while the investigation continues, we'll have to dig deeper on what can be done, if not real-time, perhaps some in-between compromise solution in the end, or none at all in relation to Process Hacker.

_I happened to had a web browser crash right as I was writing a paragraph here, I think I forgot some of the points, I'll try to remember as I go or will do next time._

I'll write this piece in general for others to understand easily so some of it may be redundant to developers and experts.

https://i.imgur.com/eWhmOdZ.png

For example, you can take a look at this image I did using WPA, with the filters configured in a way I'm trying to get at, but that's just the raw data, you have the thread's _switch-in time_ (when it starts executing) and _next switch-out time_ (when it stops) and then on the CPU column you can see how the CPU's it has switched-in varies, but sometimes is the same, the number we want is how many times did it change the CPU (totals, per sec/minute, etc), I do not know yet if this is possible within WPA or any other existing MS performance or similar 3rd-party program, but we would need, if we can access the raw data preferrably in real-time, or perhaps offline by analyzing WPR recording (.ETL file), write some custom piece of code that would calculate this out for us. 
And since I've discovered Process Hacker, long story short, I had the idea perhaps it may be beneficial to add such functionality to Process Hacker, with my help wherever I can, rather than me developing a totally separate application, I think the ability to parse .ETL could unlock many possibilities beyond just "thread bouncing" and we may be able to report a lot of other calculated statistics that WPA isn't able to display, or where raw-source-data view types and graphs just aren't that useful.

I've breiefly had an exchange with the head person behind UIforETW saying that he thinks it's tricky and difficult to attempt parsing ETW data myself ... but it's not like we would need to identify all the parameters, just the ones necessary ones for the "thread bouncing" initially, and I would assume most of the WPA's code is about manipulating the data around rather than purely just parsing it, no? (I'm asking in general, I see you're not familiar with WPA)

https://github.com/google/UIforETW/issues/142

I'm more of an optimistic person in general, I don't want to just give up. I talked to other people, they were less pessimistic. Certainly I respect his warnings and ofcourse I agree it takes skill into the inner workings of an OS to understand many of these numbers, but I don't know what could go wrong if we keep working until we do it right, with a good .ETL file and get the "thread bounce time" or "thread bounces per second" out that could be interpreted in a wrong way, well, surely it takes a skilled observer, but I don't think the actual software would be buggy or to blame, right? Or does he mean that we wouldn't understand how to properly parse it an forget something? It can be tested for sure by using a short .ETL (file generated by Windows Performance Recorder (WPR)) in the custom utility and comparing it manually to the WPA's graphs and counting all the switch-in and out entries of a particular thread-s, if they match, it should **just work**, right? 

I'm also writing a larger background around this, which I decided to split a bit, and still not sure if I should post it here or somewhere else.
