### ISSUE TITLE
Tools can't resize Window

### ISSUE THREAD

**Issue by rzfzr** [processhacker/processhacker#660]
I'm trying to use winLayout, WindowGrid, WindowManager, all of them can resize all my other programs' windows, BUT processhacker and its system information, why would that be?

**Comment by dmex** [comment]
Best guess is those tools injecting code and getting blocked.

**Comment by rzfzr** [comment]
> Best guess is those tools injecting code and getting blocked.

aright, in that case can I enable this code ejection in process hacker?
Thanks
