### ISSUE TITLE
Can't execute ProcessHacker.exe after 3.0.7761.3234

### ISSUE THREAD

**Issue by twu2** [processhacker/processhacker#661]
I can't execute ProcessHacker.exe after build 3.0.7761.3234 in my laptop (AMD 4800H).
Got application error like this:
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-08-20T01:29:57.5926474Z" /> 
  <EventRecordID>23969</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="0" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>TOMMY-FA706IU</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>ProcessHacker.exe</Data> 
  <Data>3.0.7761.3234</Data> 
  <Data>5f20e1b8</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.19041.423</Data> 
  <Data>06701e03</Data> 
  <Data>c0000409</Data> 
  <Data>00000000000a3648</Data> 
  <Data>5d00</Data> 
  <Data>01d676916a081e88</Data> 
  <Data>C:\Portable\Utilities\SystemTools\Process Hacker\ProcessHacker.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>4385020f-3dba-4e46-8be7-2cf33105653d</Data> 
  <Data /> 
  <Data /> 
  </EventData>
</Event>`

But I still can execute the new version in my desktop pc (Intel CPU).
All running Windows 10 2004 x64 Enterprise version.

**Comment by dmex** [comment]
> my laptop (AMD 4800H)

Do you have any extra-plugins installed on the laptop that are not installed on your desktop?

**Comment by twu2** [comment]
I found the old NetAdapters plugin still exist in my laptop, after remove this plugins, it work fine now.
Thanks.
