### ISSUE TITLE
Highlight of Current Item

### ISSUE THREAD

**Issue by dbareis** [processhacker/processhacker#672]
Particularly when I use the "**Find Window**" option it normally takes me ages to find the item that it highlighted due to all the different colors on the screen.  While all other colors are configurable, I don't believe this is.  It would be nice if font and bold etc could also be selected.

Possibly could the selected item be bolded or flashed to show it's location?  Maybe selected items could be highlighted with a bar in the thing area just before the first column.

**Comment by dmex** [comment]
> Maybe selected items could be highlighted

You can change the focus and selection colors by enabling the TreeListCustomColorsEnable setting. The default will give a very dark selection color but you can customise those by changing the TreeListCustomColorText, TreeListCustomColorFocus and TreeListCustomColorSelection settings.

The format is RRGGBB and if you're unsure about color codes you can copy them from "html color tables" online such as: https://www.rapidtables.com/web/color/html-color-codes.html

**Comment by dbareis** [comment]
I have a portable install, if I add the lines to "ProcessHacker.exe.settings.xml":
```
  <setting name="TreeListCustomColorsEnable">1</setting>
  <setting name="TreeListCustomColorSelection">ff00ff</setting>
  <setting name="TreeListCustomColorText">0000ff</setting>
```

Nothing changes.  The post at "https://wj32.org/processhacker/forums/viewtopic.php?p=9582#p9582" shows an "Options" dialog that I don't have (obsolete?).

**Comment by dmex** [comment]
> shows an "Options" dialog that I don't have (obsolete?)

Both the settings and options window are only available in the Nightly builds:
https://processhacker.sourceforge.io/nightly.php

**Comment by dbareis** [comment]
Ok, got to wonder why but have I set the options correctly and if so why don't they work?

I started with "<setting name="TreeListCustomColorsEnable">1</setting>" and then added the others when I didn't notice any change.  If I need nightly builds to overcome my issue then this issue shouldn't have been closed?

**Comment by dmex** [comment]
> Ok, got to wonder why but have I set the options correctly and if so why don't they work?

Do you mean they're not working in the nightly build or at all?

> If I need nightly builds to overcome my issue then this issue shouldn't have been closed?

If the feature works in the nightly builds then the issue is closed as completed. If the issue is why haven't the nightly builds been made available then that's a different issue.

**Comment by dbareis** [comment]
I am on the latest build of process hacker 2.39.124 (when I click "check for updates" its says it's the latest, when I go to the website that is the latest available).

The post mentioning the settings that I referred to was dated 01 Mar **2018**, so the version I have must be OK.  I notice nothing if I add the settings.  I don't understand why you would add code to nightly builds only to remove it when released.  I don't want to use alpha or beta software just to have visible selections.

**Comment by dmex** [comment]
> when I click "check for updates" its says it's the latest, when I go to the website that is the latest available

The nightly builds are a separate branch that is not available via the Check for updates unless you're using a nightly build.

> I am on the latest build of process hacker 2.39.124

2.39 is LTS (Long-term-servicing) which does not get updates. Nightly builds are version 3.0 and above which get updated every other day.

> I don't want to use alpha or beta software just to have visible selections.

If there is an issue with the nightly build then it's corrected within a day. The question you have to ask is if that feature doesn't work they way you expected because nobody used the nightly build and it's released into LTS then it won't be changed and you still won't be able to use it.

So you have to use the nightly builds to test your feature request and if there is an issue and you report it then it'll be fixed otherwise you'll be stuck with that issue.

**Comment by dbareis** [comment]
Ok thanks, I see now that the "current release" is over 4 years and can't understand why your LTS isn't a good 3.0+ build but whatever...  I will use a nightly build.  Thanks for that info.

**Comment by dbareis** [comment]
In the latest nightly, if indeed the colors are meant to be **RGB**, then at least "TreeListCustomColorText" doesn't work properly:

- FFFFFF = white as expected
- 0000FF = FF = RED (incorrect, should be Blue)

Some other tests seem to confirm that the colors are not "RGB" but "BGR".

These don't seem to change anything no matter what values I choose:
  <setting name="TreeListCustomColorSelection">ff00ff</setting>

This value turns the blue background into black (and seems to have nothing to do with focus):
  <setting name="TreeListCustomColorFocus">1</setting>
