### ISSUE TITLE
BUGS in 3.0.3295 (c933473b) (1) Tray Icon (2) Popups displayed as PopUnders

### ISSUE THREAD

**Issue by dbareis** [processhacker/processhacker#674]
(1) I've only tried the CPU tray icon but unlike the latest official version which displays the CPU history, the nightly displays a straight line and is basically useless

(2) I have the option "display on top" for the app, if I open the about box or plugins... then they display under the app.

Process Hacker
Version: 3.0.3295 (c933473b)
Compiled: 7:43:14 PM 28/08/2020

OBJECT INFORMATION
PhObjectTypeObject: 14 objects
PhStringType: 6558 objects
PhBytesType: 0 objects
PhListType: 421 objects
PhPointerListType: 134 objects
PhHashtableType: 15 objects
PhFileStreamType: 0 objects
PhSymbolProviderType: 0 objects
PhProcessItemType: 357 objects
PhServiceItemType: 747 objects
PhNetworkItemType: 0 objects
PhModuleProviderType: 0 objects
PhModuleItemType: 0 objects
PhThreadProviderType: 0 objects
PhThreadItemType: 0 objects
PhHandleProviderType: 0 objects
PhHandleItemType: 0 objects
PhMemoryItemType: 0 objects

**Comment by dmex** [comment]
You can enable the CPU history tray icon from the View menu

**Comment by dbareis** [comment]
- Thanks but there is a bug in the settings also: ticking "CPU Usage" (and why is this the default) doesn't untick "CPU History" and visa versa. This is what happened to me.

- What about: (2) Popups displayed as PopUnders
