### ISSUE TITLE
Process Hacker crashed when switch to "Modules" tab in property of a UWP process

### ISSUE THREAD

**Issue by Null-SID** [processhacker/processhacker#675]
Double click any UWP process to open the property window, and switch to _Modules_ tab, Process Hacker will pop up a dialog say it has crashed with error code 0xC0000005(memory location access invalid). Then Process Hacker is unable to view any process' modules. 

Don't view UWP's module but only view traditional Win32 process' modules have no problem.

Any process doesn't in AppContainer but inside a package (e.g. Windows Terminal) will also affected by this problem. The only exception I found is _OpenConhost.exe_ in Windows Terminal.

Environment info:
Process Hacker: 3.0.3295
Windows 10 x64 10.0.18363.1016

![wd](https://user-images.githubusercontent.com/37217261/91910391-86b49600-ece1-11ea-84d7-62116ed2439f.png)
![setting](https://user-images.githubusercontent.com/37217261/91910405-8ddba400-ece1-11ea-85f8-846dad6e7651.png)
![wt](https://user-images.githubusercontent.com/37217261/91910413-916f2b00-ece1-11ea-9cb2-45d62fc86a90.png)
![conhost](https://user-images.githubusercontent.com/37217261/91910419-93d18500-ece1-11ea-92f2-266988200de8.png)
![processhacker](https://user-images.githubusercontent.com/37217261/91910742-283be780-ece2-11ea-821b-81b118c1c1be.png)

**Comment by Null-SID** [comment]
After a system reboot, I found this problem is not always occurred. I've created some minidump according to Process Hacker.
[Process Hacker Minidump.zip](https://github.com/processhacker/processhacker/files/5159121/Process.Hacker.Minidump.zip)

**Comment by dmex** [comment]
Fixed with commit https://github.com/processhacker/processhacker/commit/dd9d5ced038a865c3237a9567ce519fdafad0d07
