### ISSUE TITLE
Csrss process - Access denied in memory

### ISSUE THREAD

**Issue by Blovien** [processhacker/processhacker#677]
ProcessHacker version: 3.0.3296

After enabling "Hacker > Show details for all processes", The tab memory of the csrss processes says "Access denied".
P.S. I already tried to launch the application as administrator.

![Immagine 2020-09-07 125034](https://user-images.githubusercontent.com/20379165/92380080-d099e380-f108-11ea-807b-c312868baea4.png)

**Comment by Biswa96** [comment]
No issue in my case. Also "Show details for all processes" relaunches ProcessHacker as administrator.

**Comment by Blovien** [comment]
That works but it doesn't show Csrss strings after doing it. I tested it with other people too and they had the same problem.

**Comment by Blovien** [comment]
The problem applies to MsMpEng process too

**Comment by mrsshr** [comment]
it seems ppl(protected process light). its not a bug. its a feature.

**Comment by Blovien** [comment]
But with the stable version there's not such problem

**Comment by mrsshr** [comment]
use KProcessHacker.

you can use KProcessHacker by enabling below:

![image](https://user-images.githubusercontent.com/4264612/92391840-4d07e300-f158-11ea-8567-599da63b4f04.png)

**Comment by mrsshr** [comment]
anti-cheat software may ban you.
if not in use, unload it.

**Comment by Blovien** [comment]
Problem solved thanks for the advices. 👍
