### ISSUE TITLE
GPU graph shown usage for wrong node (3D/Copy) compared to Taskmanager (Win10 - 2004)

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#678]
I noticed that the GPU usage shown in Process Hacker doesn't match with Task manager. In Process Hacker it is shown as Copy, while task manager shows 3D, which is correct as I started a 3D game.

![image](https://user-images.githubusercontent.com/8274816/92404618-45cede00-f134-11ea-9dc9-89b8db7a590d.png)

The AMD driver for HD7730M is latest version `Win10-Radeon-Software-Adrenalin-2020-Edition-20.8.3-Aug27.exe`.

Process Hacker
Version: 3.0.3295 (c933473b)
Compiled: 11:43:14 28.08.2020
[Win10 - 2004](https://support.microsoft.com/en-us/help/4566782)

**Comment by dmex** [comment]
Try changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` setting to 1

**Comment by MagicAndre1981** [comment]
makes no difference

**Comment by dmex** [comment]
Related to #514

**Comment by MagicAndre1981** [comment]
@dmex 

ok, I added the GPU counter value and now the setting is corrupted:

![image](https://user-images.githubusercontent.com/8274816/93017883-57990100-f5cc-11ea-908c-d08dc8e02e21.png)

Compared to others it misses space. When I close PH, add the space, restart PH, the space is gone again.

**Comment by dmex** [comment]
You might be saving the file with the wrong encoding which should be UTF8

**Comment by MagicAndre1981** [comment]
@dmex nope, it is UTF8. Opening the file in notepad3 shows inconsistent line break. I selected Windows, next UNIX and on next opening the same setting (only this setting, no other setting) changes back to this wired thing

**Comment by MagicAndre1981** [comment]
I checked this on different systems:

Other AMD GPU:

![image](https://user-images.githubusercontent.com/8274816/100379851-eb983780-3015-11eb-9824-b2ba672db209.png)

Here the 3D usage is shows altered for 3D and Copy in PH and as pure 3D in TaskManager.

On a different system with NVIDIA 1050ti, the 3D usage shows as Node 5 and 3D is empty in PH but 3D in Taskmanager:

![image](https://user-images.githubusercontent.com/8274816/100379989-374ae100-3016-11eb-9877-0eb5cbaec145.png)

This is really confusing.

**Comment by dmex** [comment]
Try changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` setting to 1

Duplicate of #514

**Comment by MagicAndre1981** [comment]
@dmex it is set to 1. 

```
<setting name="ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters">1</setting>
<setting name="ProcessHacker.ExtendedTools.EnableEtwMonitor">1</setting>
<setting name="ProcessHacker.ExtendedTools.EnableGpuMonitor">1</setting>
```

and this portable folder was copied to the 2 other systems with the same `ProcessHacker.exe.settings.xml`

**Comment by dmex** [comment]
@MagicAndre1981 

Can you reinitialize the graphics driver while Process Hacker is running and check if the values are still incorrect?

Execute:
pnputil /enum-devices /class Display

Look for your graphics adapter and copy the Instance ID:
pnputil /restart-device "Instance ID"

The screen will blank while the graphics driver restarts and reinitializes.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981
> 
> Can you reinitialize the graphics driver while Process Hacker is running and check if the values are still incorrect?
> 
> Execute:
> pnputil /enum-devices /class Display
> 
> Look for your graphics adapter and copy the Instance ID:
> pnputil /restart-device "Instance ID"
> 

the first command works, but not the second command as I'm on 1909, I'll try to check the 1050ti device tomorrow .

**Comment by MagicAndre1981** [comment]
what is the correct syntax for devcon? The value from pnputil doesn't work with devcon restart.

But I noticed now that the game runs in background and I have PH/Taskmgr open in foreground, both show 3D, but when I switch back to game, play a few seconds and use ALT+Tab go back taskmgr shows 3D all time and PH the altered data in 3D and Copy .

I tried wpr -start GPU and dumped it into an ETL, but WPA and gpuview don't show the used nodes. I have no idea if we can capture this information.

**Comment by dmex** [comment]
> what is the correct syntax for devcon?

pnputil /enum-devices /class Display

![image](https://user-images.githubusercontent.com/1306177/100783129-80a98f00-3461-11eb-9274-5e560aff3d0c.png)


Copy the instance string and include quotes: 
`pnputil /restart-device "Instance ID"`

**Comment by MagicAndre1981** [comment]
> Copy the instance string and include quotes:
> `pnputil /restart-device "Instance ID"`

as I said, this restart parameter was added in 2004 and I'm on 1909

**Comment by MagicAndre1981** [comment]
> pnputil /enum-devices /class Display
> 
> ![image](https://user-images.githubusercontent.com/1306177/100783129-80a98f00-3461-11eb-9274-5e560aff3d0c.png)
> 
> Copy the instance string and include quotes:
> `pnputil /restart-device "Instance ID"`

ok, I booted WinToGo SSD with 20H2 and here the command works and it this causes that the game crashes. 

Maybe TM uses a sampling and doesn't capture all data compared to PH? Maybe PH is correct.
