### ISSUE TITLE
Crash when trying to load dll-plugins

### ISSUE THREAD

**Issue by GflowerG** [processhacker/processhacker#679]
When I turn off ASLR:
```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management]
"MoveImages"=dword:00000000
```
I am getting the following:
![Screenshot_1](https://user-images.githubusercontent.com/69000814/92499959-f4971b00-f215-11ea-8020-b1d05623e880.jpg)
This happens when I open the application...

**Comment by dmex** [comment]
@GflowerG 

👍🏿
