### ISSUE TITLE
Unknown service type

### ISSUE THREAD

**Issue by TETYYS** [processhacker/processhacker#681]
Some kind of xbox crap creates a service that has an unknown type and trying to modify its Start type throws access denied. You can stop it though. What kind of crap is this?

![ProcessHacker_MM9U429ajq](https://user-images.githubusercontent.com/3091645/92793019-b8e78700-f3b6-11ea-915b-47e0321134bc.png)
![ProcessHacker_O9nka5XS7u](https://user-images.githubusercontent.com/3091645/92793081-c69d0c80-f3b6-11ea-8ad1-ea3d98c42656.png)
![regedit_wXFbkWCwYH](https://user-images.githubusercontent.com/3091645/92793123-d0267480-f3b6-11ea-8af8-307749a10259.png)
![mmc_GRf03T2oWH](https://user-images.githubusercontent.com/3091645/92793188-dd436380-f3b6-11ea-87d9-c272fe73b319.png)

**Comment by Biswa96** [comment]
From the registry value Type == 0x210, it is the OR-ed value of `SERVICE_WIN32_OWN_PROCESS` and `SERVICE_PKG_SERVICE`. Where,

```c
#define SERVICE_WIN32_OWN_PROCESS      0x00000010
#define SERVICE_PKG_SERVICE            0x00000200
```

So, the startup type maybe it's own process but with packaged mode i.e. UWP. phlib/svcsup.c need some changes.

**Comment by dmex** [comment]
Fixed in latest nightly 👍🏿
