### ISSUE TITLE
How to use phlib as dynamic library in custom program?

### ISSUE THREAD

**Issue by IOL0ol1** [processhacker/processhacker#683]
I hope to get the process information by calling DLL in other languages (like c#). 
How can I get the DLL file of phlib and the corresponding header file?
Or is there a better way for me to use it in other languages?

I try to compile phlib into DLL, but there are many errors. 
After adding lib reference, I compile, but the DLL file is not correct.    

**Compile configuration**
Visual Studio 2019 Version 16.7.3 
Configuration - Release
Platform - x64
Configuration Type - Dynamic Library (.dll)
Windows SDK Version - 10.0.19041.0
Platform Toolset  - Visual Studio 2019 (v142)
Runtime Library - Multi-threaded DLL (/MD)
Spectre Mitigation - Disabled

**Comment by dmex** [comment]
> How can I get the DLL file of phlib and the corresponding header file?

phlib is a statically linked library.

> I try to compile phlib into DLL, but there are many errors.

You would need to create a separate DLL project and import the static library using: 
`#pragma comment(lib, "phlib")`

> After adding lib reference, I compile, but the DLL file is not correct.

No idea. I'd guess you're missing some headers.
