### ISSUE TITLE
How do you get an account on the forum to post a question?

### ISSUE THREAD

**Issue by netnut404** [processhacker/processhacker#685]
I saw the thread at  https://wj32.org/processhacker/forums/viewtopic.php?t=2512   and was looking how to achieve dark mode in the process explorer app,  but I could not tell where the login is created for the forum so I may ask for details about the dark mode.

Thanks in advance for your response,

Net Nut

**Comment by dmex** [comment]
> How do you get an account on the forum to post a question?

The forum was getting too many spammers and fake accounts in one day recently. I disabled registration for a bit so they would move on somewhere else 😕

I've enabled it again so you should be able to register now 👍

>  how to achieve dark mode in the process explorer app

You can enable dark theme by selecting the Enable theme support checkbox in the Options window:

![image](https://user-images.githubusercontent.com/1306177/93665361-326b2d80-fab9-11ea-86b0-b8d829a656ae.png)
