### ISSUE TITLE
PH ignores "only one instance" while "System information" tab is opened

### ISSUE THREAD

**Issue by falcon4fun** [processhacker/processhacker#688]
Q,

Have to report very old annoying bug. It was for about 5-7+ years while I'm using PH.

1. Select one instance only.
2. Select minimize on close
https://i.imgur.com/wdMlDNP.png
3. CTRL+I (or open system information)
4. Close main window (no needs)
5. Press ctrl+shift+esc
...
Profit
You will get another copy of PH. And they can be billions.

Proof video: https://gfycat.com/PiercingSimilarGlassfrog
While normal behavior should be to focus main window like here (without system info tab): https://gfycat.com/LoneUniformIberianbarbel 

Please, add another check while opening second process to bring the main window of first one on process exit. Or smth to fix it :)

Version: 3.0.3371 (1c33a25c) but u don't really need this info

**Comment by falcon4fun** [comment]
Notice me, sempai.

**Comment by dmex** [comment]
> It was for about 5-7+ years

😦

> add another check while opening second process to bring the main window of first one

The same issue also prevents the Window Title and Window Status columns on the processes tab from showing the correct window.

**Comment by dmex** [comment]
Fixed in the nightly builds. Thanks for reporting it 👍

**Comment by falcon4fun** [comment]
Dat rocks :3 Thx u for your project :3
