### ISSUE TITLE
Small cosmetic incostistence - Updater dialog: fields "Compiled" have value as "Git hash" and "Compile time" is expected

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#689]
Small cosmetic incostistence - Updater dialog: fields "Compiled" have value as "Git hash" and "Compile time" is expected. Please, see screenshot:

![cosmetic](https://user-images.githubusercontent.com/906886/93719760-4aac7c80-fb8d-11ea-84af-7e5b2bd6be65.jpg)

**Comment by MagicAndre1981** [comment]
just noticed the same and was confused

**Comment by dmex** [comment]
Fixed 👍

**Comment by VictorVG** [comment]
Big thanks!

**Comment by VictorVG** [comment]
Big thanks!
