### ISSUE TITLE
Also cosmetic - menu About, dialod Diagnostcs - in to filed Compled: date/time is random garbage as date/time

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#690]
Example - go to menu entry About, dialog Diagnostcs and see wrong time/data like:

_Process Hacker
Version: 3.0.3373 (25673a6c)
Compiled: 19:19:58 05.08.2097_

_Process Hacker
Version: 3.0.3374 (c881b914)
Compiled: 4:39:32 18.12.1976_

_Process Hacker
Version: 3.0.3376 (ecb71236)
Compiled: 14:06:15 23.05.2025_

_Process Hacker
Version: 3.0.3378 (b6efab01)
Compiled: 12:18:35 20.05.2094_

_Process Hacker
Version: 3.0.3382 (41c9c5b8)
Compiled: 8:14:31 23.04.1999_

is cosmetics and wait for fix  - his priority is very low...

**Comment by dmex** [comment]
The nonsense dates help indicate deterministic timestamps for the image which is intentional for diagnostics 👍

**Comment by VictorVG** [comment]
Got it. I somehow did not think about it. Nice idea!:up:
