### ISSUE TITLE
Restore plugin options dialogs

### ISSUE THREAD

**Issue by Eagle3386** [processhacker/processhacker#691]
Currently, PH 3.x instances don't offer to open a plugin's options dialog, e. g. `Hacker -> Plugins... -> .NET Tools -> double click -> Options...` is disabled.

In the latest PH 2.x, it's possible to click that button.

**Comment by dmex** [comment]
The plugin options where moved to the main options window as separate tabs.

**Comment by Eagle3386** [comment]
I think, I'll have another look then. Couldn't find them prior to this issue. Anyway, thanks for the quick reply! 👍🏻
