### ISSUE TITLE
"Search processes" is not respecting theme

### ISSUE THREAD

**Issue by TheEragon** [processhacker/processhacker#693]
If you use black Windows theme and enable experimental theme support in PH, "Search processes" is not themed, also icons are missing from the toolbar.

![image](https://user-images.githubusercontent.com/5801389/93870781-0379d500-fcce-11ea-9533-ceb3bb3a8619.png)

In modules the searchbox is respecting the theme for some reason 🙅

**Comment by dmex** [comment]
> experimental theme support

Try changing the `Enable modern icons` checkbox on the toolbar settings window
