### ISSUE TITLE
Don't work, master at September, 27

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#695]
Don't work. Message 'restert, dump,

**Comment by Biswa96** [comment]
A detailed issue would be helpful to debug the issue. Please explain your issue, add your system, which version worked flawlessly, which version creates this issue etc.

**Comment by Avtroman** [comment]
[ProcessHacker_CGEGRFNXIZLAVEY_DumpFile.zip](https://github.com/processhacker/processhacker/files/5290873/ProcessHacker_CGEGRFNXIZLAVEY_DumpFile.zip)
[ComputerInfo.zip](https://github.com/processhacker/processhacker/files/5290878/ComputerInfo.zip)

**Comment by dmex** [comment]
The crash was caused by: `FirewallMonitorPlugin.dll`

You need to remove the DLL or recompile it with the latest changes.

You should also remove or update these plugins:
![image](https://user-images.githubusercontent.com/1306177/94420134-0fcaca00-01c7-11eb-8d11-b99a1d56e7bf.png)

**Comment by Avtroman** [comment]
Yes, error cause FirewallMonitorPlugin.dll

But it's from latest build, recompiled

**Comment by Avtroman** [comment]
> The crash was caused by: `FirewallMonitorPlugin.dll`
> 
> You need to remove the DLL or recompile it with the latest changes.
> 
> You should also remove or update these plugins:
> ![image](https://user-images.githubusercontent.com/1306177/94420134-0fcaca00-01c7-11eb-8d11-b99a1d56e7bf.png)
Ok, thanx, I download new plug-ins extra, recompile, and all ok

**Comment by dmex** [comment]
> recompile, and all ok

👍
