### ISSUE TITLE
ProcessHacker Crash

### ISSUE THREAD

**Issue by JW-Schuetz** [processhacker/processhacker#697]
Using built exe of  commit b291bde2 see a warning: "The kernel driver was not found" and after closing this I see an invalid memory access crash: "Process Hacker has crashed :(". The invalid memory location is 0xC0000005.
My last working build of Process Hacker was maybe a week ago.

What can I do?

**Comment by JW-Schuetz** [comment]
I mean "using build exe of commit b291bde" and not "building".

**Comment by dmex** [comment]
Try updating to the latest nightly build or removing any non-default plugins

**Comment by JW-Schuetz** [comment]
I build the last running version (commit edf229a3) and disabled all plugins.
Now the actual version (commit 7527d4d3) worked.
After re-enabling all plugins but "UserNotes.d" Process Hacker still worked.
Maybe this plugin is somehow corrupt? 
It has the nonstandard extension "*.d" and not "*.dll".

**Comment by dmex** [comment]
> It has the nonstandard extension ".d" and not ".dll".

You'll need to add the .dll extension. I'm not sure but something probably truncated the string before it was written.

> Process Hacker still worked.

It was probably the same bug causing both issues. Glad its working 👍
