### ISSUE TITLE
Idea - add check to /ProcessHacker/plugin.c::260 for prevent crash in to legacy OS then "FirewallMonitorPlugin.dll" is exists.

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#699]
Idea - add check `If OsVersion() <= 6.3 Then PH_STRINGREF_INIT(L"FirewallMonitorPlugin.dll") End` to /ProcessHacker/plugin.c::260 for prevent crash in to legacy OS then "FirewallMonitorPlugin.dll" is exists.
 Example:    
```
    static PH_STRINGREF PhpPluginBlocklist[] =
    {
        PH_STRINGREF_INIT(L"CommonUtil.dll"),
        PH_STRINGREF_INIT(L"ExtraPlugins.dll"),
        PH_STRINGREF_INIT(L"NetAdapters.dll"),
        PH_STRINGREF_INIT(L"SbieSupport.dll"),
        PH_STRINGREF_INIT(L"HexPidPlugin.dll"),
       If OsVersion() <= 6.3 Then PH_STRINGREF_INIT(L"FirewallMonitorPlugin.dll") End
    };
```
Source - forum.ru-board.com users bug-report's in summary:

_If some legacy system PH is carashed at startup if "FirewallMonitorPlugin.dll" is exists._

**Comment by dmex** [comment]
>  prevent crash in to legacy OS

The plugin supports Windows 7... The problem is you're using an older version of the plugin API and need to recompile the plugin for the latest nightly build.

You could always use the plugins with the stable build instead which would also solve the issue.

**Comment by VictorVG** [comment]
I try fix in to my [**toolkit**](https://github.com/VictorVG/Source/releases/tag/PHTk1170) and commited [**modifed FirewallMonitorPlugin source**](https://github.com/VictorVG/Source/releases/tag/FWMSrc1001). And wait users callback (in to latest revision I added only VERSION_INFO in to .rc).
