### ISSUE TITLE
Process Hacker has crashed: 0xC0000005 (Invalid access to memory location.)

### ISSUE THREAD

**Issue by svArtist** [processhacker/processhacker#700]
After a recent update to PH 3/nightly (I can't be sure which version it was, but I restarted my computer yesterday and updated PH nightly then), PH failed to start showing the message: 

> **Process Hacker has crashed :(**
> 0xC0000005 (Invalid access to memory location.)

I forgot about it until later today; I then manually installed the latest version (3.0.3443) because I was sure that that would take care of it.
But this issue persists.

I tried renaming the folder in _%APPDATA%/Process Hacker_ and running it with or without elevation, but both to no avail.
[ProcessHacker_QYHOCWQDUKLPPKA_DumpFile.zip](https://github.com/processhacker/processhacker/files/5319398/ProcessHacker_QYHOCWQDUKLPPKA_DumpFile.zip)
Crash dump attached (I only clicked that option after the latest update, sorry).

This is on Win 10 Pro x64 v1903

**Comment by n0101** [comment]
If you have FirewallMonitorPlugin.dll installed, that's causing the crash.  Remove it from the plugin folder.

**Comment by svArtist** [comment]
> If you have FirewallMonitorPlugin.dll installed, that's causing the crash. Remove it from the plugin folder.

Indeed it was!
I hope this is still being worked on?

**Comment by dmex** [comment]
> I hope this is still being worked on?

It's only an issue for old plugins using legacy imports. You need to update the plugin to the latest version.
