### ISSUE TITLE
Nightly Build (3.0.3456) Crash on start

### ISSUE THREAD

**Issue by kleuter** [processhacker/processhacker#702]
[ProcessHacker_MTYBZMLCYLWZBLD_DumpFile.zip](https://github.com/processhacker/processhacker/files/5329931/ProcessHacker_MTYBZMLCYLWZBLD_DumpFile.zip)

**Comment by dmex** [comment]
You need to delete this outdated plugin:

![image](https://user-images.githubusercontent.com/1306177/95135901-e3a7de00-07b0-11eb-8920-de47a3ede63b.png)

That file was long ago merged into HardwareDevices.dll plugin.

**Comment by kleuter** [comment]
Thanks, **dmex**!

**Comment by kleuter** [comment]
I suspect it would better detect such issues and don't crash.
