### ISSUE TITLE
Feature: Change injection method in settings

### ISSUE THREAD

**Issue by Frouk3** [processhacker/processhacker#703]
As title says

**Comment by dmex** [comment]
What method would be better than the current one?

**Comment by Frouk3** [comment]
Between **Standard** and **Manual** **Map**

**Comment by dmex** [comment]
> Standard 

We already use the standard LoadLibrary function.

> Manual Map

You could make a plugin to include this but it's not something that I'd support with the constant updates to the PE format for binaries on Windows 10.
