### ISSUE TITLE
Git b826eabf or newer. build error "LIB: fatal error C1900: IL mismatch between "P1", version "20200803" and "P2", version "20190715""

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#704]
Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.7.30310.162)
VisualStudio: VisualStudio/16.7.5+30523.141

Building... 3.0.7996.3469 (b826eabf) [master]

[00:00] Building ProcessHacker (x32)...
[ERROR] (1) LIB: fatal error C1900: IL mismatch between "P1", version "20200803" and "P2", version "20190715" [.\Phlib\phlib.vcxproj] LINK: fatal error LNK1257: failed to create code [.\phlib\phlib.vcxproj]

Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.7.30310.162)
VisualStudio: VisualStudio/16.7.5+30523.141

Building... 3.0.7998.3471 (8321694a) [master]

[00:00] Building ProcessHacker (x32)...
[ERROR] (1) LIB: fatal error C1900: IL mismatch between "P1", version "20200803" and "P2", version "20190715" [.\Phlib\phlib.vcxproj] LINK: fatal error LNK1257: failed to create code [.\phlib\phlib.vcxproj]

**Comment by VictorVG** [comment]
Big thanks! Fixed.

Also - black humor: "Fantomas raged or the fly swatter overdid it" - it looks funny - I put on a freshly picked Process Hacker and about the middle of the process a fly swatter wakes up - I decided to be vigilant:

```
10.10.2020 13:14:06 Statistics:
10.10.2020 13:14:06 Files checked: 1445
10/10/2020 01:14:06 PM Files found: 1
10/10/2020 13:14:06 Files cleaned: 0
10/10/2020 1:14:06 PM Deleted files: 1

10.10.2020 13:15:56 Module version = 6100.8979
10/10/2020 13:15:56 Antivirus, DAT file version = 9768.0
10/10/2020 13:15:56 Number of signatures to detect in EXTRA.DAT = No
10/10/2020 13:15:56 Names of signatures to detect in EXTRA.DAT = No
10/10/2020 13:18:33 Deleted xxxxxx\xxxxxx C:\Users\xxxxxx\AppData\Local\Temp\is-BPJ6D.tmp\processhacker-3.0-setup.tmp C:\Program Files\Process Hacker\x86\plugins\DotNetTools.dll GenericRXME-HU! CE1F2D329FDF (Trojan horse) ce1f2d329fdf3ec126dec4377f7c4a40 (MD5)
```
I had to give her a hand - your business is to catch viruses, do not go anywhere did not invite! - but simply reconfigure because the inclusion of the PH catalog in the exceptions does not affect the "useful zeal" of the fly swatter, because the computer is a big iron fool, just fry eggs. :)

**Comment by l0pu** [comment]
> Big thanks! Fixed.

How did you fix it? I get similar error 
`Error	C1900	Il mismatch between 'P1' version '20210202' and 'P2' version '20200803'	phlib	`

**Comment by dmex** [comment]
@l0pu 

Run `\build\build_thirdparty.cmd`

**Comment by Bopobey** [comment]
> @l0pu
> 
> Run `\build\build_thirdparty.cmd`

what? Help me please
