### ISSUE TITLE
Request: Double click to open commit in github in changelog of updater

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#705]
It would be nice to only make a double click to open commit in github in changelog, instead of doing a right click and select  "View on github"

![image](https://user-images.githubusercontent.com/8274816/95727459-71d10800-0c7a-11eb-9e7e-e6d81130edb4.png)

**Comment by dmex** [comment]
>  open commit in github

Haven't you been traumatised enough without having to also look at the code? 😅

**Comment by MagicAndre1981** [comment]
> Added to latest nightly build 👍🏿

works fine 👍
