### ISSUE TITLE
Error some times 

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#708]
[ProcessHacker_RQAYAWVZMMVJHTB_DumpFile.zip](https://github.com/processhacker/processhacker/files/5401464/ProcessHacker_RQAYAWVZMMVJHTB_DumpFile.zip)

**Comment by dmex** [comment]
You've compiled the unstable plugin-extras repository which mentions they shouldn't ever be used:

C:\Program Files\WJL\Процессы\plugins\WaitChainPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\ObjectManagerPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\TerminatorPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\TaskbarExtPlugin.dll
C:\Program Files\WJL\Процессы\plugins\SecurityExplorer.dll   
C:\Program Files\WJL\Процессы\plugins\PoolMonPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\ProductPolicyPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\FirmwarePlugin.dll   
C:\Program Files\WJL\Процессы\plugins\PerfMonPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\NvGpuPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\MemoryExtPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\FirewallMonitorPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\DpiAwarenessExtPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\DnsCachePlugin.dll   
C:\Program Files\WJL\Процессы\plugins\DbgViewPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\AtomTablePlugin.dll   
C:\Program Files\WJL\Процессы\plugins\TrustedInstallerPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\SetCriticalPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\ServiceBackupRestorePlugin.dll   
C:\Program Files\WJL\Процессы\plugins\ROTViewerPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\ForceShutdownPlugin.dll   
C:\Program Files\WJL\Процессы\plugins\AvgCpuPlugin.dll   


These plugins should have been deleted.
