### ISSUE TITLE
Undefined ProcessUserShadowStackPolicy

### ISSUE THREAD

**Issue by ronsav80** [processhacker/processhacker#709]
Trying to build and missing definition for ProcessUserShadowStackPolicy.  Per MSFT KB search, this should be in winnt.h but this is missing in _PROCESS_MITIGATION_POLICY definition for this build.  Are we missing something??

**Comment by Biswa96** [comment]
Try with latest stable Windows SDK. Official download link: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/

**Comment by dmex** [comment]
You need the 19041 SDK:

![image](https://user-images.githubusercontent.com/1306177/96740288-6add8e80-140c-11eb-9783-f0f2eb20957b.png)
