### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by a-ahmed** [processhacker/processhacker#711]
i got the following error when using bat file or visual studio!  can you help?
processhacker-master\phlib\include\phnativeinl.h(1770): error C2065: 'ProcessUserShadowStackPolicy': undeclared identifier (compiling source file colorbox.c)

**Comment by Biswa96** [comment]
Duplicate of this issue https://github.com/processhacker/processhacker/issues/709. Try to update the Windows SDK in your system.
