### ISSUE TITLE
0xC0000006 Crash Immediately Following Application Startup (v3.0.3477)

### ISSUE THREAD

**Issue by tylerjkline** [processhacker/processhacker#712]
![3f606b6b-750b-486f-9cb3-5c3a2eae6fc1](https://user-images.githubusercontent.com/52719358/97114087-c5a10f80-16c4-11eb-9de3-16494b3df546.png)

### Summary of issue
Basically, Any/every attempted start of process hacker (latest nightly build v3.0.3477 / 96f20096), the program crashes within one minute of launch and displays the error above. I can confirm this crash **DOES NOT** occur on the latest release version (v2.39 / 4310de8).

### All other potentially useful error/system info
- **Windows Version:** 2004 [Build [20241.1005](https://docs.microsoft.com/en-us/windows-insider/Active-Dev-Branch#build-20241)].  I am using the latest the dev channel Insider preview but that's not a factor of the crash as the error was occuring before I upgraded Windows to insider previews.
- **Crash Minidump:** [Direct Download](https://docs.google.com/uc?export=download&id=1QMar_4ARnhrxPfH-2cOD8CrP7vvS3Ol1)  |  [Virus Total](https://www.virustotal.com/gui/file/69ae088bac3ac60a5d09992b0ee035f0e9c80aacd4a2c3f343509396ae6532a5/detection)

- **WinDbg Dump Analysis:** WinDbg analysis found extended crash info -- [Pastebin of dump analysis](https://pastebin.com/agLpksNe)
- **I ran some tests + diagnostics to rule out a faulty hard disk and/or faulty RAM as the cause of the crash**. 
    - I considered this as a possible cause [a Microsoft](https://answers.microsoft.com/en-us/windows/forum/all/referenced-memory-error/9ba71233-6a1a-4db2-9bca-58d5a6d74dd9) & [Reddit](https://www.reddit.com/r/24hoursupport/comments/8lxmeu/the_required_data_was_not_placed_into_memory/) said that similar errors were/could be caused by hardware/RAM faults.
    - Even further damning to the idea hardware/RAM is to blame is the improbability of a hardware/RAM fault causing an error that is present on one version (crashes on v3.0.3447) but isn't present on another version (doesn't crash on v2.39). Still, to further rule it out, I ran extensive diagnostics on my hardware and ran SFC/ChkDsk repairs which found no problems.
- **Possibly Related Kernel Error:**
    - > `Session "PhEtKernelLogger" failed to start with the following error: 0xC0000035`
    - This error appears in my event logs immediately following the process hacker crash so I'm assuming it's related, but it doesn't make much sense as my Kernel Driver in Process Hacker's options is turned off? 
    - I was able to find this [old thread](https://wj32.org/processhacker/forums/viewtopic.php?t=2719) of someone who had a similar process hacker error which was being caused by their AV, but suggested solutions didn't solve the problem.

**Comment by dmex** [comment]
>  rule out a faulty hard disk and/or faulty RAM as the cause of the crash.

The code crashes when reading the dos header after it's tested the memory by reading it. It's crashing for the exact thing the probe checks for already so it would have to be some driver or hardware causing the issue:
![image](https://user-images.githubusercontent.com/1306177/97124994-6c99b000-1786-11eb-8a39-d9493a72a15d.png)

![image](https://user-images.githubusercontent.com/1306177/97124921-28a6ab00-1786-11eb-9ad9-8158a7f7f11b.png)

> failed to start with the following error: 0xC0000035

The object name already exists. The PhEtKernelLogger already existed when Process Hacker started up and created an ETW session with the same name.

>  program crashes within one minute of launch and displays the error above

Try changing these settings to zero:

EnableServiceStage2  = 0
EnableStage2 = 0

**Comment by dmex** [comment]
Are you still getting crashes in the latest build?
