### ISSUE TITLE
Suspending WmiPrvSE.exe leads to an un-interactable (but working) ProcessHacker

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#713]
Replicate with:

* Suspending WmiPrvSE.exe 
* Wait for it (5-10 minutes, maybe more ...)

```
Process Hacker
Version: 3.0.3477 (96f20096)
Compiled: 8:41:15 μμ 28/2/2039

OBJECT INFORMATION
PhObjectTypeObject: 15 objects
PhStringType: 7314 objects
PhBytesType: 2183 objects
PhListType: 285 objects
PhPointerListType: 97 objects
PhHashtableType: 19 objects
PhFileStreamType: 0 objects
PhSymbolProviderType: 0 objects
PhProcessItemType: 247 objects
PhServiceItemType: 708 objects
PhNetworkItemType: 0 objects
PhModuleProviderType: 0 objects
PhModuleItemType: 0 objects
PhThreadProviderType: 0 objects
PhThreadItemType: 0 objects
PhHandleProviderType: 0 objects
PhHandleItemType: 0 objects
PhMemoryItemType: 0 objects]
```

**Comment by dmex** [comment]
> Suspending WmiPrvSE.exe

Does Process Explorer have the same issue?

**Comment by stdedos** [comment]
No, just PH.
I started PE first, suspended both WinPrvSE processes, PH froze, PE not.

![image](https://user-images.githubusercontent.com/133706/97564843-e1225800-19ed-11eb-8492-e4c3e627025f.png)

Resuming one of the two (the first one), allows PH to continue working.
I'll keep PE overnight in case it takes longer for it to happen.

**Comment by dmex** [comment]
If the mouse is over the Name column when suspending the process. The name column tooltip attempts to query WMI for the instance names, since you've just suspended the WMI process this causes the process to deadlock.

You can see the WMI instances from the process properties so we can remove the tooltip information 👍

**Comment by stdedos** [comment]
Some timeout (or other deadlock-protection e.g. `if ping "helo" ; then query ; else echo 'Timeout'; fi`) could be used too.

However, if you think it's better this way; then it is! Cheers!

**Comment by dmex** [comment]
>  it's better this way; then it is

The tooltips are instant (no background query) and WMI queries are internally RPC calls into the WmiPrvSE.exe process. The RPC calls are going to deadlock when you've suspended the WmiPrvSE process and without a background thread you can't show the information without also deadlocking the UI and main process.

It's easier to remove the tooltip text which nobody would care to look at for WMI info then add the machinery needed to support querying the WMI text on threads when someone wants to view the tooltip.

**Comment by dmex** [comment]
I've re-enabled the tooltips after adding some workarounds for the WMI deadlock 👍
