### ISSUE TITLE
3.0.3515 - Crash on start

### ISSUE THREAD

**Issue by Progress1** [processhacker/processhacker#714]
It start crashing between 3.0.3494 (works) and 3.0.3501 (crash). Win 10 x64

![image](https://user-images.githubusercontent.com/10151485/97275329-1be19000-1836-11eb-9881-9af665098c2c.png)

**Update**: it looks that PH start using all plugins and they are mandatory. In past i use only few selected plugins. After copying all plugins (.dll) PH starts.

**Comment by dmex** [comment]
Does the latest nightly crash?

**Comment by Progress1** [comment]
yes, starting from 3.0.3501to current 3.0.3515, but i already figure it out where is problem, read Update up.

**Comment by dmex** [comment]
> In past i use only few selected plugins.

Disable the `EnableSafeDefaultPlugins` setting from 1 to 0 when using non-default plugins

> After copying all plugins (.dll) PH starts.

Windows Defender deleted the plugins and later never restored the files: #454 

Error messages for missing plugins are now enabled by default. You need to restore the missing files or disable the error message using the above setting.

**Comment by Progress1** [comment]
1) i use only default plugs so EnableSafeDefaultPlugins can stay at 1 
2) i always choose plugs that i use and manually delete rest :) 

Try remove some plugs, and start PH to simulate it. It's no problem for me keep all plugs together ;-)
