### ISSUE TITLE
PH crashes at every PC reboot

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#715]
This is my minidump: https://www.dropbox.com/s/hglztz5tl6emerk/ProcessHacker_SMCLKMFLFAMMNPR_DumpFile.dmp?dl=0

**Comment by skipik** [comment]
https://github.com/processhacker/processhacker/issues/712 prob same problem here...

**Comment by dmex** [comment]
Try the latest build 3521 and upload a new dump

**Comment by skipik** [comment]
Sill crashes at every reboot.
The new dump: https://www.dropbox.com/s/r61h0dztf1b3ojl/ProcessHacker_PWKTHMGTSZRRRRW_DumpFile.dmp?dl=0

**Comment by skipik** [comment]
I think it's related to Firewall plugin as I disabled firewall event monitoring and it doesnt crash.
It also only hapens on system startup and I have Kaspersky AV, may be this info will help you to investigate the problem.

**Comment by dmex** [comment]
Thanks, fixed in the latest nightly build 👍
