### ISSUE TITLE
Bad window title in GPU details

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#716]
Steps to reproduce:
 - Open Process Hacker version 3.0.3521 (Win10.0.18363.1139, x64, as administrator).
 - Click System Information button from toolbar.
 - Click GPU button / graph.
 - Click Detail button.
 - New window appears, look at its title, it says "Firewall Rules".
 - This is wrong, it should say GPU details or something similar.

**Comment by dmex** [comment]
>  it says "Firewall Rules"

Thanks. I edited the wrong template in an earlier commit 👍
