### ISSUE TITLE
v3.0.8054.3527 Git-029c0777: ExtendedTools not showing firewall events on Windows 7

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#721]
In Git log I see

> [8da01eff] 2020-10-28 03:43:09 +1100 dmex : ExtendedTools: Fix firewall events not showing on Windows7

but ExtendedTools in to Process Hacker 3.0.8054.3527 Git-029c0777 not showing firewall events at Win7 SP1, but v2.39.0.124 is show it. I try fix this isues in to ./pliguns/ExtendedTools/fwmon.c , bun failure and rollback changes. To be honest, I'm already confused - I tried to add code blocks for Win7 similar to the old FirewallMonitorPlugin source codes according to the list of events, but taking into account the code that is in ExtendedTools. It assembled, but did not work :( - the tab is empty as if disabled ...

![2](https://user-images.githubusercontent.com/906886/97421293-6427ad80-191d-11eb-8330-4ae0b954db91.png)

**Comment by VictorVG** [comment]
In to v3.0.8055.3528 Git-d168ccea on Firewall tab display error messages:

`Unable to start the firewall tracing session: the flags field contains an invalid value (2150760478)`

**Comment by dmex** [comment]
Fixed

**Comment by VictorVG** [comment]
Thank you so much! It worked instantly as soon as it was assembled and launched.

**P.S.**

Bloody infection - quarantine and several acquaintances picked it up. And when will doctors be able to fight it? Flu - accustomed, but it is not a gift, but this dirty trick ... It would be better if it did not exist in our lifetime ...
