### ISSUE TITLE
Kernel-EventTracing errors while using Process Hacker

### ISSUE THREAD

**Issue by dmex** [processhacker/processhacker#726]
"Kernel-EventTracing" errors while using Process Hacker.

![image](https://user-images.githubusercontent.com/1306177/97708339-c09cef80-1b0c-11eb-8e30-d995c100ed5a.png)

_Originally posted by @ImSpecial in https://github.com/processhacker/processhacker/issues/641#issuecomment-717525773_

**Comment by dmex** [comment]
@ImSpecial 

Fixed in latest nightly build 👍

**Comment by ImSpecial** [comment]
Thanks for looking into this!

But I'm not so sure everything's all cleared up yet, I grabbed the latest PH (3.0.3564) from the other day after I saw your notification and noticed there are still "Kernel-EventTracing" errors being generated around the exact same time I load up PH for usage, I don't recall first hand what they were about, might be different ones from that of your picture, but the time stamps on them were pretty exact.

**Comment by dmex** [comment]
> there are still "Kernel-EventTracing" errors being generated

![image](https://user-images.githubusercontent.com/1306177/97975359-1f1fe180-1e1d-11eb-98ae-b7d818260fc1.png)

The kernel rundown provider (3b9c9951-3480-4220-9377-9c8e5184f5cd) won't generate rundown for file events until after closing the trace handle even though we're using a real-time trace... So you're forced to destroy and recreate the rundown provider (like you were saving to disk) which then ETW generates that warning because the real-time events were not processed before destroying the previous trace 🤔

The other problem is that this provider also doesn't include a final DCEnd event like other built-in providers so you cannot check when an existing real-time trace session has ended or reuse an existing session. This provider was ported to ETW from WMI starting with Vista and probably forgot the call for DCEnd.

I've worked around the real-time trace issue with the rundown provider by recreating the provider. The provider doesn't lose any events and doesn't otherwise cause a single other issue than that warning. 

So the warning is otherwise nonsense that can be safety ignored.
