### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Skibicki** [processhacker/processhacker#729]
Windows 8.1 64-bit
Broken at: Process Hacker 3.0.3557 Commit: 8818aa1c4bda3abdc6bff1ffae9e5e379c9d7e38
Process Hacker crashed when starting. It does not crash when started as Admin.
0xC0000005 (Invalid access to memory location.)

**Comment by Skibicki** [comment]
It starts normally with plugins disabled.
Dump: 
[ProcessHacker_KEEJBCYXGZNPHJJ_DumpFile.zip](https://github.com/processhacker/processhacker/files/5471956/ProcessHacker_KEEJBCYXGZNPHJJ_DumpFile.zip)

**Comment by dmex** [comment]
Thanks I've fixed the crash in the latest nightly build 👍

You can delete \plugins\ExtendedTools.dll temporarily and preform the update via the Help menu.
