### ISSUE TITLE
Feature Request: Bring Windows to screen X

### ISSUE THREAD

**Issue by Geolim4** [processhacker/processhacker#73]
Hello,

As a long-time user of process hacker, I would like you to add this feature.
For multi-screen users it can be sometimes annoying to retrieve a Window.

An option such as "Bring Window to screen > *screen list* 1 , 2"  would be welcomed !!

Thanks,
Georges

**Comment by TETYYS** [comment]
+1, some applications which save their window position can be hard to move to primary monitor if secondary is disconnected. But you could always move them from taskbar context menu ([image](http://i.imgur.com/GRKPsw3.png))

**Comment by Geolim4** [comment]
Hello @wj32 @dmex any ETA on this, i would love have it in a close future, or maybe do you have a nightly builds/beta system ?

**Comment by Geolim4** [comment]
@wj32 @dmex Bump :)

**Comment by Geolim4** [comment]
@wj32 @dmex Bump :)

**Comment by Geolim4** [comment]
@wj32 @dmex Bump :)

**Comment by dmex** [comment]
I've looked into adding this feature a few times but it becomes too complex trying to handle multiple displays with varying sizes and varying types of windows. There's dedicated software for handling this which would do a much better job.

**Comment by Geolim4** [comment]
> I've looked into adding this feature a few times but it becomes too complex trying to handle multiple displays with varying sizes and varying types of windows. There's dedicated software for handling this which would do a much better job.

Okay, got it, thanks for trying anyway !
