### ISSUE TITLE
Total% CPU and % Total Memory Percentage

### ISSUE THREAD

**Issue by ferhugox** [processhacker/processhacker#730]
Hello everyone! I am using version 2.39.124. I would like to know if there is any possibility to add the feature
in the process window: in which the percentage (%) TOTAL (not partial) of cpu and the percentage (%) TOTAL of memory are shown for each process,
similar to the one shown in windows 10 process manager.

I am attaching sample screenshots.

Thank you very much in advance and I await any comments.

Cheers
![process hacker 2 ](https://user-images.githubusercontent.com/71852136/97819114-68d5c400-1c85-11eb-9578-0cc9846a2ac3.JPG)
![task manager windows](https://user-images.githubusercontent.com/71852136/97819123-70956880-1c85-11eb-9fce-fc4874ce4f74.JPG)

**Comment by dmex** [comment]
> similar to the one shown in windows 10 process manager

Enable the `Include usage of collapsed processes` setting in the options window

**Comment by ferhugox** [comment]
Thanks!!

**Comment by dmex** [comment]
😛
