### ISSUE TITLE
Malwarebytes detects as malware

### ISSUE THREAD

**Issue by Team-Sys** [processhacker/processhacker#732]
![image](https://user-images.githubusercontent.com/63068185/98228952-e831f480-1f1e-11eb-8485-be0d01698c07.jpg)

https://forums.malwarebytes.com/topic/265982-process-hacker-task-manager-false-positive/?tab=comments#comment-1418617

**Comment by kristibektashi** [comment]
Malwarebytes said they will fix it. Why did you open an issue?

**Comment by dmex** [comment]
@Team-Sys 

Thank you for reporting the issue!

Malwarebytes is a very welcome change compared to some other vendors (#454) and it's really good seeing how quickly they resolved the issue in under 3 hours ❤


@kristibektashi 

You should always create a ticket for issues that affect the project even when they're already fixed. They're shown on the project homepage to help raise awareness of problems that others may encounter and they are a big help when doing yearly reviews of top issues, metadata and for historical references in newer/related issues.
