### ISSUE TITLE
[Question]: Is Process Hacker a focus-stealing detection program?

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#733]
It says here https://en.wikipedia.org/wiki/Focus_stealing#Focus-stealing%20detection%20programs:

> # Focus-stealing detection programs
> Programs have been written to identify what is stealing focus.
> * Process Explorer

I cannot find that feature in Process Explorer.
Do you remember/know where is it?
Does PH have that too?
If so, where?

**Comment by dmex** [comment]
> Does PH have that too? If so, where?

The processes tab and/or windows tab?

> I cannot find that feature in Process Explorer.

The person who wrote it probably used Process Explorer to find a program stealing focus therefore Process Explorer is a tool for focus-stealing detection.
