### ISSUE TITLE
I can't restart process hacker from process hacker 

### ISSUE THREAD

**Issue by kotenok2000** [processhacker/processhacker#734]
when i right click processhacker.exe process and press restart process hacker closes, but does not start again.

**Comment by dmex** [comment]
This was posted last year?
https://wj32.org/processhacker/forums/viewtopic.php?f=24&t=3735

**Comment by VictorVG** [comment]
Build filed:

Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.7.30310.162)
VisualStudio: VisualStudio / 16.7.7 + 30621.155

Building ... 3.0.8107.3580 (c0a72c34) [master]

[00:00] Building ProcessHacker (x32) ...
[ERROR] (1). \ProcessHacker\mainwnd.c (964,32): error C2220: The following warning is treated as an error [.\ProcessHacker\ProcessHacker.
.\ProcessHacker\mainwnd.c (964,32): warning C4087: PhShowDebugConsole: declaration with "void" parameter list [.\ProcessHacker\ProcessHacker.vcxproj]

**Comment by VictorVG** [comment]
v3.0.8108.3581 build success
