### ISSUE TITLE
Feature: Provide summarized parent process statistics by counting in all of it's subprocess statistics

### ISSUE THREAD

**Issue by ghost** [processhacker/processhacker#735]
The web browsers of the world have all been using this modern multi-process approach for quite some time now, sometimes I want to see the usages of the whole application, but with 50 subprocesses it's hard to quickly sum up the application's memory usages, for example. 

I don't know of an utility (tho I didn't search much) that nicely summarizes all of the summarizable parameters of a process and all it's subprocesses, to get the sum of CPU usage, RAM usage, disk usage, network usage, network connections, etc.

This is ofcourse not limited to web browsers, so it may be useful across the board, heck half of our stuff runs under `services.exe` and `explorer.exe`. While the usefulness of grouping those statistics is perhaps lesser, it might still be for some kind of troubleshooting/testing scenario.

One way to do it is to provide "sum" versions of all of the applicable statistics columns, but that may be a lot of programming work and may not provide best UX/clarity? Perhaps implementing this as a completely different view into another version of the Processes tab would be another way.

Third, trying to stay in the same _Processes_ tab, perhaps we could add a button-s beside the existing shrink/expand button, for toggling this feature on/off. When activated the subprocesses would remain visible (if not shrinked) but the values in their statistics columns that are summarized to the parent's row would perhaps be colored differently (border or a shade change inner box) and perhaps not show any subprocess specific statistics (for clairty) and rather display a text note that would go something like "summarized to parent" or "sum mode active" or "see parent" (really rough suggestions). The feature could work irrespective of the shrink/expand functionality, so you could have many combinations.

Fourth, augumenting this feature together with the expand/shrink functionality/button, ... the biggest problem I see here is that some columns aren't statistics, they can't be summarized, those columns would become exceptions, still showing only the data for the paren't process, this leads to inconsistency that would need to be indicated in the GUI, and this could only be a special mode of the shrink/expand functionality that user could set in options, it shouldn't be hardcoded default behavior of the shrink/expand functionality/button. One way is to perhaps color the excluded columns/data of that parent process to indicate it's still showing only the parent specific data.

Bonus feature: There could be an option to summarize only the parent and it's subprocesses with exactly the same image name as the parent process, so for example `firefox.exe` parent would show memory usage for all of it's `firefox.exe` child processes, but not `maintenanceservice.exe`, `crashreporter.exe`, or `updater.exe` (incase those are subprocesses, I can't confirm right now, I have a more surer example with Opera browser, where I can see right now a subprocess `opera_crashreporter.exe` is used, so the code has to do exact match aswell, not partial)

**Comment by dmex** [comment]
>  summarizable parameters of a process and all it's subprocesses, to get the sum of CPU usage, RAM usage, disk usage, network usage, network connections, etc.

The 'Include usage of collapsed processes' option shows the total sum for all processes:

![image](https://user-images.githubusercontent.com/1306177/98443342-c3c45b00-215e-11eb-8e1b-d75e295889e0.png)

> There could be an option to summarize only the parent and it's subprocesses with exactly the same image name as the parent process, so for example firefox.exe parent would show memory usage for all of it's firefox.exe child processes,

This is what the option does but only when the parent is collapsed.

**Comment by altimumdelta** [comment]
Ohhh no, sorry about that, and I re-checked again to try to find if there's an option, just couldn't see it.

> This is what the option does but only when the parent is collapsed.

"collapsible" means all, including those who's names differ from the parent, right?

**Comment by dmex** [comment]
> "collapsible" means all, including those who's names differ from the parent, right?

Yep, the child process inherits the parents handles, device map, processor affinity, process/thread priority, quotas, process token, job object and other objects so the enumeration is based entirely on the processes children.

It wouldn't be accurate to exclude collapsed children with different names when you consider those same kernel objects are shared across all children and the result would be incorrect statistics for some columns/objects?

**Comment by altimumdelta** [comment]
Perhaps so yes. Tho when I said "applicable columns" I meant the ones that first can be counted at all, and  then secondly, as you pointed out only the ones that aren't shared in order to show correct totals.

Kernel objects and other stuff yes, but I don't think private memory is shared, CPU usage and other key resource stats, so those should be summable and be correct, AFAIK.

That would work, but perhaps it's something that could be added to a totally different area, to not mess and bloat the existing expand/collapse behavior. For example into the System Information page, one could have a filter for process names and/or PIDs there and it would display totals for all processes one puts into the filter box, so if one picks Firefox.exe, it adds the parent and all it's children, with that name, to the calculation, with an switch option (radio buttons) to either "Don't Include Children, Don't Include Parents" and "All that match filter".
