### ISSUE TITLE
Inject DLL [Process Hacker 3]

### ISSUE THREAD

**Issue by Sithic** [processhacker/processhacker#736]
I updated to the Nightly Build, and now I can't find the Inject DLL option. Where did it go?

**Comment by dmex** [comment]
> Where did it go?

It's gone?

**Comment by Sithic** [comment]
wtf help? why be a dick?

**Comment by dmex** [comment]
> Where did it go?

It moved to the process properties -> module tab -> options.

> wtf help? why be a dick?

An encouragement to checkout the changes in the latest build.
