### ISSUE TITLE
Icons missing in Processes tab

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [processhacker/processhacker#741]
Since version 3.0.3615 icons are missing in Processes tab.

**Comment by dmex** [comment]
Deleted the nondefault plugins?

**Comment by Bec-de-Xorbin** [comment]
I didn't delete anything. I also did a clean install in Windows Sandbox and processes' icons are missing there also. 3.0.3613 works ok.

**Comment by dmex** [comment]
Can you try version 3.0.3620?

**Comment by Bec-de-Xorbin** [comment]
I tried 3.0.3620 and 3.0.3625, icons missing on both.

**Comment by dmex** [comment]
Which version of windows?

**Comment by Bec-de-Xorbin** [comment]
Version 20H2 (OS Build 19042.662).

**Comment by lespea** [comment]
Same for 3625.  I tried disabled theme support, then cleaning settings, then reset all settings, and all icons are missing.

**Comment by dmex** [comment]
I've tested Windows 7, 8 and 10 but can't reproduce the issue.

**Comment by lespea** [comment]
The monitor is 4k using a dpi of 150% if that is relevant?  I can try to test more things when I'm done working later today

**Comment by dmex** [comment]
> 4k using a dpi of 150%

Try changing the DPI and any other settings.

**Comment by ts03GCZqIsTZtu4** [comment]
mine did this as soon as i updated it. every icon went away, a reinstall changed nothing.

**Comment by dmex** [comment]
Fixed in 3.0.3627 and above 👍

**Comment by Bec-de-Xorbin** [comment]
Missing again in 3.0.4016. Worked ok in 3.0.4000. Seems like DPI issue again, 100% scaling ok, 125% not ok.

**Comment by dmex** [comment]
@Bec-de-Xorbin 

Fixed in r4017
