### ISSUE TITLE
add nightly on scoop

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [processhacker/processhacker#743]
can u add processhacker nightly to scoop [extra](https://github.com/lukesampson/scoop-extras/tree/master/bucket)

**Comment by dmex** [comment]
They already have it I think?
https://github.com/lukesampson/scoop-extras/blob/master/bucket/processhacker.json

**Comment by 0ANIMEFREAK0** [comment]
> They already have it I think?
> https://github.com/lukesampson/scoop-extras/blob/master/bucket/processhacker.json

not the nightly one i was looking for nightly one and couldn't find it

**Comment by dmex** [comment]
Related to #415 and #454

**Comment by dmex** [comment]
I wouldn't add the nightly builds because they're unstable. The next stable release will include scoop support: #415
