### ISSUE TITLE
Priority -4 for some threads of Microsoft Edge (Chrome based)

### ISSUE THREAD

**Issue by MagicAndre1981** [processhacker/processhacker#745]
Viewing the threads of msedge.exe shows some threads have priority of -4:

![image](https://user-images.githubusercontent.com/8274816/100378915-50eb2900-3014-11eb-8c67-9cc5e7209a3d.png)

![image](https://user-images.githubusercontent.com/8274816/100379107-a7586780-3014-11eb-97e4-e4736a13714c.png)

What is this?

Windows 8.1 x64, Edge stable 87.0.664.47

**Comment by dmex** [comment]
These are nonstandard priorities with no name.

**Comment by MagicAndre1981** [comment]
ok, first time I saw this
