### ISSUE TITLE
Suspend

### ISSUE THREAD

**Issue by RGM12** [processhacker/processhacker#747]
When you put something on suspend you cannot see it anywhere, you have to remember it.
perhaps a sign may appear somewhere indicating that something is suspended.

**Comment by dmex** [comment]
> When you put something on suspend you cannot see it anywhere, you have to remember it.

Suspended processes are shown in Grey colours identical to Task Manager and Process Explorer:

![image](https://user-images.githubusercontent.com/1306177/101301818-155f2300-388e-11eb-81cb-47400f1c8c0b.png)

> somewhere indicating that something is suspended

The suspended state is shown on the threads tab and you can also enable the highlighting for individual threads:

![image](https://user-images.githubusercontent.com/1306177/101305270-683cd880-3896-11eb-8ae6-acf8681dad25.png)
