### ISSUE TITLE
processhack etw plugin can not show process read  write file event 

### ISSUE THREAD

**Issue by yangjian123** [processhacker/processhacker#749]
**Describe the bug**
   on windows7, i write a test app, which create,write,read,rename files, i switch to the disk tab in the processhacker and can not see anything event fired by my test app.

**To Reproduce**
1. start my  test app
2. open processhacker and switch to disk tab

**Expected behavior**
  processhacker can show file event fired by my test app

**Desktop (please complete the following information):**
 - OS: windows7 x64 serive pack 1

**Additional context**
   on windows7 , i write my own etw app to monitor test app, and my etw session name is nt kernel logger, it is also can not monitor my test app file event, the main cause is etw give process and thread id -1 which can not correlate filepath

**Comment by yangjian123** [comment]
my test code show in the below picture
[](url)
![image](https://user-images.githubusercontent.com/9816011/101606650-8e9d7800-3a3e-11eb-9de6-e4c6efa435d1.png)

**Comment by yangjian123** [comment]
processhacker test result picture show below
![image](https://user-images.githubusercontent.com/9816011/101606825-c60c2480-3a3e-11eb-8db3-90e645b67afe.png)

**Comment by dmex** [comment]
>  switch to the disk tab in the processhacker and can not see anything event fired by my test app

Does Resource Monitor show the disk activity?

Start > Run > "`perfmon /res`"

Expand the Disk Activity section and check for the files here:

![image](https://user-images.githubusercontent.com/1306177/101613695-2b244200-3a60-11eb-8981-5c35326b48e9.png)

**Comment by yangjian123** [comment]
it seems perfmon also can not monitor file read write, i test all of this in vmware.  but windows performance record and procmon can detect this behaviour, i hava no idea about this
![image](https://user-images.githubusercontent.com/9816011/101615023-9eba5500-3a48-11eb-96bf-76bd2e6b728b.png)

**Comment by dmex** [comment]
> perfmon also can not monitor file read write

Perfmon and Process Hacker are showing physical disk events which are separate to File events. Raymond Chen posted notes about this here: https://devblogs.microsoft.com/oldnewthing/20201125-00/?p=104480

![image](https://user-images.githubusercontent.com/1306177/101616494-899eef80-3a63-11eb-97ea-70d7dbff3412.png)


> windows performance record and procmon can detect this behaviour

The Disk tab only shows events from DISK IO for the actual physical disk activity. Those tools are showing FILE IO for every operation preformed on the file.

> i write a test app, which create,write,read,rename files

The operation must touch the physical disk to become visible on the Process Hacker disk tab. When the disk cache or a minifilter or another kernel driver processes/blocks/caches the operation and doesn't touch the physical disk then it won't be available.

I can post a new plugin that shows the individual file operations like procmon does if you create a new issue in the plugins-extra repository asking for a new plugin for the FileIO?
https://github.com/processhacker/plugins-extra/issues/new

The events are too verbose to include in the main application: 
![image](https://user-images.githubusercontent.com/1306177/101619582-94f41a00-3a67-11eb-8314-05fe22d2e227.png)

**Comment by yangjian123** [comment]
thanks dmex‘s Explanation,  I am a heavy user of processhack，I really hope to have such a plugin and i will create a new issue in plugins-extra repository

**Comment by dmex** [comment]
> really hope to have such a plugin and i will create a new issue

Thanks, I'll post something in a week or two over Christmas 👍
