### ISSUE TITLE
HardwaredDevices stroage build failed

### ISSUE THREAD

**Issue by kSpacer201** [processhacker/processhacker#753]
**HardwaredDevices stroage build failed**

when build on win10 machine with vs2019 , it will report :
 ```
    ...
    error C2220: the following warning is treated as an error 
    ...     stroage.c(1,1): warining C4819: The file contains a character that cannot be represented in the current code page (936).
   
    but the file is utf-8 , when i resave it with gbk.   THE ERROR IS MISSING.
 ```
.

**To Reproduce**
1. Just build on win10 with code page 936

**Expected behavior**
Not change the code page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version:  Microsoft Windows [Version 10.0.16299.847]
 - Visual Studio: 16.8.3+30804.86

**Comment by dmex** [comment]
Thanks for reporting the issue.

It's been fixed in the latest commit 👍
