### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DeluxNERD** [processhacker/processhacker#754]
When Ever I Try To Inject Dll's It's Not Opening The Dll. Is There A Way I Can Fix It Thanks.

**Comment by dmex** [comment]
The process can easily block injection by hooking LoadLibary. The other problem could be that you compiled a DLL with an executable manifest. Try disabling the manifest and recompiling the DLL:

![image](https://user-images.githubusercontent.com/1306177/102692532-11f17180-4268-11eb-8391-5a6e3d9b16bf.png)
