### ISSUE TITLE
 I got an error.

### ISSUE THREAD

**Issue by HoTab3322** [processhacker/processhacker#755]
![Screenshot_2](https://user-images.githubusercontent.com/76151554/102459646-ed727b00-4056-11eb-91b6-e8c0b7f64592.png)
1) Я скачал последнюю версию Process hacker.
2) Я запускаю приложение от имени администратора.
3) Я переустанавливал Process hacker 5 раз.
4) Я перезагружал компьютер.
How can I fix this error?

**Comment by dmex** [comment]
> How can I fix this error?

Do you have the same issue with the nightly builds?
https://processhacker.sourceforge.io/nightly.php

**Comment by dmex** [comment]
* The window title with "HID" indicates third party software causing the crash.
* That error is also not one of our dialogs and looks very similar to the csrss.exe dialog.

Closing as third party.
