### ISSUE TITLE
It crash me so much

### ISSUE THREAD

**Issue by shironaomi** [processhacker/processhacker#761]
_[The program stops working all the time in the latest update and I have to reopen it](https://i.paste.pics/0beef8dcfd711e540e44753f1fd79657.png) 
I don't know what causes it_

_I liked the new things of the update
And I say I liked it because the program that is always injected by the [virus now turns purple](https://i.paste.pics/de931b4a1dc0c391cc2e249b8b32cf88.png)_
_[This is the note](https://i.paste.pics/428ffce4718ba85f42253d2fb9dc0162.png)
[Before of be injected](https://i.paste.pics/726af3b0461162b4f04e69cb1b09bd03.png)
No antivirus can destroy this virus, nor can it detect it
They only detect the .exe it generates, but what actually originates it is undetectable
I would like you to add functions like see if the program was modified or injected by another program and those stuff_

**Comment by dmex** [comment]
> I don't know what causes it

I fixed a few crashes in the latest nightly build. Try updating the the latest version 3.0.3694

> No antivirus can destroy this virus, nor can it detect it

It's 2020 and vendors don't care about viruses anymore... They're doing more important things like creating +40 signatures (and counting) for Process Hacker instead: #454 

> add functions like see if the program was modified

You can use other tools like Windows-Kernel-Explorer for checking those things:
https://github.com/AxtMueller/Windows-Kernel-Explorer

**Comment by shironaomi** [comment]
Oh, thanks.

**Comment by shironaomi** [comment]
_Plz, fix this_

![ScreenShot_20210201072229](https://user-images.githubusercontent.com/76606218/106424883-4493aa00-6463-11eb-99d2-df18f4fff327.png)

![ScreenShot_20210201073848](https://user-images.githubusercontent.com/76606218/106424884-465d6d80-6463-11eb-8051-1995063b8457.png)

![ScreenShot_20210201073914](https://user-images.githubusercontent.com/76606218/106424888-478e9a80-6463-11eb-89c4-765fd84aae2f.png)
