### ISSUE TITLE
Relative start time column

### ISSUE THREAD

**Issue by pasha-zzz** [processhacker/processhacker#762]
Maybe optional shorter format of this column (now it too wide): "yy minutes zz seconds ago".... Too wide with hours/days too. Maybe like "10m 22s" and skip "ago"?

**Comment by dmex** [comment]
> Maybe optional shorter format of this column (now it too wide)

Have you tried the "Start time" column instead of the "relative start time" column?

**Comment by pasha-zzz** [comment]
And math runtime in my head?

**Comment by jxy-s** [comment]
The topic of formatting a time-span has little native support, or at least none I'm aware of. There is facility for formatting a date/time, but that isn't what we're after here. C# and ATL has some TimeSpan APIs. ATL maybe - might be able to query for the COM interface without all the overhead of ATL, and likely inappropriate for phlib.

Ideally, we would like to provide an "advanced option" so the user may specify the format. But that gets tricky, barring us finding something to pull in, it would require us to define a spec for a format string our self (probably mimicking one that is out there).

We can certainly go the easy route and provide an "advanced option" toggle which just turns on a non-configurable compressed format similar to what you're suggesting. But I'd like to let the brew a little and see if we come up with a nicer solution.

**Comment by dmex** [comment]
I've added a new setting for showing a shorter relative time format without any prefixes:

![image](https://user-images.githubusercontent.com/1306177/113291443-c2c6dc80-933e-11eb-8927-0d707885685f.png)

You can change the `EnableShortRelativeStartTime` setting to 1 in the latest nightly. This only applies to the relative start column but could be added elsewhere on request 👍

**Comment by pasha-zzz** [comment]
Maybe hide leading zero values at all? F.e. 0:18:41:48 -> 18:41:48. Or 0:00:10:32 -> 10:32.

**Comment by dmex** [comment]
@pasha-zzz 

> Maybe hide leading zero value

The zero padding is currently needed to prevent confusing the days with hours because of the text alignment... I could change the column alignment to resolve that issue but it might be a problem... Try it for a few weeks and if it's still an issue then create a feature request for removing the padding.
