### ISSUE TITLE
Collapse services.exe on start on v3

### ISSUE THREAD

**Issue by Nihilopia** [processhacker/processhacker#763]
In PH2 you had the setting to collapse services.exe on startup of PH; it seems like the option is no longer available on v3.
Are there any plans on re-adding that, because that was a really neat option that cleaned the clutter on startup?

**Comment by dmex** [comment]
> the option is no longer available on v3

It's still there but moved to the Options > Usernotes window

![image](https://user-images.githubusercontent.com/1306177/103306522-e0478a00-4a61-11eb-9d04-537e19a3634b.png)

> Are there any plans on re-adding that

It'll be moved back to to Options > General with the other checkboxes after I've added support for callouts. It's only on the Usernotes options as a temporary workaround while other stuff was updated.

**Comment by psouza4** [comment]
> > the option is no longer available on v3
> 
> It's still there but moved to the Options > Usernotes window
> 
> ![image](https://user-images.githubusercontent.com/1306177/103306522-e0478a00-4a61-11eb-9d04-537e19a3634b.png)
> 
> > Are there any plans on re-adding that
> 
> It'll be moved back to to Options > General with the other checkboxes after I've added support for callouts. It's only on the Usernotes options as a temporary workaround while other stuff was updated.

Google helped me find it... it doesn't come up in the Advanced search and wasn't on the General tab.  I wouldn't have even guessed to look through a UserNotes tab based on the tab name.

Any chance we can get this moved back in line with Process Hacker?  Thanks :)
