### ISSUE TITLE
SVCHost Handling

### ISSUE THREAD

**Issue by Chaython** [processhacker/processhacker#766]
**Is your feature request related to a problem? Please describe.**
SVC Host should show the related service... Maybe I'm just stupid, and there's already a way to do it, but it's not obvious to me. Process Explorer is incapable of showing SVCHost correctly as well so maybe it's an impossible issue. 

![image](https://user-images.githubusercontent.com/6486343/103450603-2b39eb00-4c76-11eb-81d5-d6bafbd3ddf2.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Biswa96** [comment]
I think you're looking for something like this: open Services tab -> right click on any **running** service -> go to process. Also if you hover over any svchost process you can see the associated services.

**Comment by dmex** [comment]
> SVC Host should show the related service

You can hover the mouse over the name and the tooltip will show the services:

![image](https://user-images.githubusercontent.com/1306177/103452171-8b856700-4d20-11eb-97d2-12e6eb39b1c6.png)


You can also right-click the svchost > Properties > Services tab and see which services are running there:

![image](https://user-images.githubusercontent.com/1306177/103452183-a48e1800-4d20-11eb-9251-238dec0e64e3.png)

You can also add the Services column to the Threads tab and see which threads belong to what service:

![image](https://user-images.githubusercontent.com/1306177/103452196-cab3b800-4d20-11eb-9a0e-b384ff229b63.png)


There are a dozen other menus/tabs where service information can also be viewed 👍

**Comment by Chaython** [comment]
How about showing the svchost service in brackets on the thread?
Sorry.

**Comment by dmex** [comment]
> How about showing the svchost service in brackets on the thread?

Is there a use case for brackets?
