### ISSUE TITLE
Dismissing PH still keeps it in focus

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#770]
Hello there,

I am having a chat with M$ for a feature of theirs, specifically https://github.com/microsoft/PowerToys/issues/7814.

I was wondering; is it a bug, or a feature, that PH still "technically" has focus after dismissing it with ESC? (returns to tray).
I haven't tried other ways (minimizing it or closing it; both with their "hide" options activated) still exhibit the same behavior

**Comment by dmex** [comment]
> is it a bug, or a feature, that PH still "technically" has focus after dismissing it with ESC?

I tested this and the focus returns to explorer.exe when pressing ESC and the window minimizes:

![image](https://user-images.githubusercontent.com/1306177/103737107-9f450c00-5045-11eb-81ac-8f907a61efc0.png)


PH was elevated and the test tool wasn't elevated. So it's an issue with whatever PowerToys does. Here's the code I used:


```
#include <Windows.h>
#include <wchar.h>

void main()
{
	while (TRUE)
	{
		HWND foreground = GetForegroundWindow();

		if (foreground)
		{
			HANDLE processHandle;
			ULONG processId;
			ULONG threadId;
			ULONG imageNameLength = MAX_PATH;
			WCHAR imageName[MAX_PATH];

			threadId = GetWindowThreadProcessId(foreground, &processId);

			processHandle = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, processId);

			if (processHandle != INVALID_HANDLE_VALUE)
			{
				if (QueryFullProcessImageName(processHandle, 0, imageName, &imageNameLength))
				{
					wprintf(L"%s: ProcessId: %lu - ThreadId: %lu\n", imageName, processId, threadId);
				}
				else
				{
					wprintf(L"[NO IMAGE]: ProcessId: %lu - ThreadId: %lu\n", processId, threadId);
				}

				CloseHandle(processHandle);
			}
			else
			{
				wprintf(L"[NO PROCESS]: ProcessId: %lu - ThreadId: %lu\n", processId, threadId);
			}
		}
		else
		{
			wprintf(L"[NO FOREGROUND]\n");
		}

		Sleep(100);
	}
}
```

**Comment by dmex** [comment]
Powertoys is missing a few things which probably cause the issue:

1) Their manifests are missing "disableWindowFiltering" which is needed to "disables window filtering so you can enumerate immersive windows from the desktop". This is documented here:
https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests

2) They also don't check the window properties for the main uwp window and instead default to hwndActive which is incorrect:
https://github.com/microsoft/PowerToys/blob/212ea2de30d69dbbfebf86c9d3604008d2272346/src/modules/keyboardmanager/common/Helpers.cpp#L216-L236

They should be calling EnumChildWindows for the current focused window and check: 
`GetProp(WindowHandle, L"Windows.ImmersiveShell.IdentifyAsMainCoreWindow")`

**Comment by stdedos** [comment]
Thank you for your effort 😀

**Comment by dmex** [comment]
@stdedos 

I tried.

**Comment by stdedos** [comment]
You tried tons^2 than I anticipated or expected! 😍 

I was already very very happy when I saw actual code and proof that "that's not PH". 

I wanted to tell you somehow that "you don't have to keep pushing it; it won't lead anywhere", but I don't have your email or anything else to reach you.

**Comment by dmex** [comment]
> I don't have your email or anything else to reach you

My email has always been available on my github profile?

> "you don't have to keep pushing it; it won't lead anywhere"

It's always worth trying to improve things regardless of the conversation.

> "it won't lead anywhere"

It's not my first rodeo when it comes to Microsoft over the last 15 years... I'm used to it and in these cases someone else will suggest the exact same thing in a few years and only then will it get fixed.
