### ISSUE TITLE
Request: A non-animated tray icon for Process Hacker

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#771]
Could a non-animated tray icon be added for Process Hacker?

What I mean...

Currently we have something like this when it runs: https://i.imgur.com/3BD9gEh.png

Or many alternatives from: https://i.imgur.com/CGMSd3f.png

But those are all "animated" in some way or another, can I request something simple like Process Hackers' icon, but for the tray: https://i.imgur.com/w33zSB3.png

I know I can remove the tray icon, but I want there to be one to show that it's running and to click on, etc., but I don't like the "eye-catchy-ness" of the animations.

Thanks!

**Comment by jxy-s** [comment]
Sounds like a reasonable request, let me see what can be done.

**Comment by jxy-s** [comment]
Ask and you shall receive:
![image](https://user-images.githubusercontent.com/11687482/103984739-eb2aaa80-5144-11eb-8ff2-0283147a25e0.png)

I'll put up a PR shortly, the "mini info" associated with this will show the default (CPU usage):
![image](https://user-images.githubusercontent.com/11687482/103984817-0eedf080-5145-11eb-81c2-f76f6bdc7353.png)

**Comment by jxy-s** [comment]
Merged 😄 - thanks for the enhancement @ImSpecial

**Comment by ImSpecial** [comment]
That was lightning quick, hope it wasn't too much trouble, but know that your efforts do not go unappreciated.

Oh, and thanks!
