### ISSUE TITLE
Regression in the Firewall Tab? Icons/Names are very close.

### ISSUE THREAD

**Issue by ImSpecial** [processhacker/processhacker#775]
I jumped quite a few version, so I don't know if this is a recent regression or it has always been the case, but I'm just now noticing it and can't unsee it, ugh!

Under the Firewall tab the icons and names are basically touching, all other instances of this sort of thing look fine in Process Hacker, just the Firewall tab has this issues.

Here's an image of what I'm talking about: https://i.imgur.com/79xEw2N.png

This is from the latest dev build: https://i.imgur.com/ehERfNw.png

**Comment by dmex** [comment]
Thanks, fixed in latest nightly build 👍

**Comment by ImSpecial** [comment]
Indeed it has been, thanks!
