### ISSUE TITLE
Feature: Use two rows for showing column description 

### ISSUE THREAD

**Issue by ghost** [processhacker/processhacker#776]
**Is your feature request related to a problem? Please describe.**
With lots of columns, space is usually scarce for several reasons (practically, technicall not) which makes colum descriptions to be truncated most of the time

**Describe the solution you'd like**
One day it clicked to me, why not simply have an option to expand the height of the top column (description) row to double height, so it would use the height of 2 standard rows as one.

**Describe alternatives you've considered**
None yet.

**Additional context**
Nope

**Comment by dmex** [comment]
Rows have fixed sizes for performance reasons.
