### ISSUE TITLE
Feature: Remember Process properties window user layout customizations

### ISSUE THREAD

**Issue by altimumdelta** [processhacker/processhacker#777]
**Is your feature request related to a problem? Please describe.**
All the columns in Threads tab are reset to default, in the same session even. The Process Properties dialog is also reset to it's default size, this severely affects practical usage when performance analyzing, etc.

**Describe the solution you'd like**
PH to remember column choices and layout in Process/Threads dialog as well as the Process dialog window size, preferrably in real-time, not only on clean exit. Threads tab columns should also remember their custom **width** as well, important too because this is usually finely tuned to fit in limited space as it is overlaid over other programs and full-screen applications.

**Describe alternatives you've considered**
None.

**Additional context**
No.

**Comment by dmex** [comment]
Are you using the nightly builds or v2.39?

**Comment by altimumdelta** [comment]
Yes nightly, installed about 20 minutes ago.

**Comment by dmex** [comment]
The threads tab and properties window already save/restore their settings in the nightly?

**Comment by altimumdelta** [comment]
Main Window remembers columns, but not their width. Process properties dialgo (threads tab, etc) doesn't remember anything. For me at least.

**Comment by dmex** [comment]
There must be something in your settings file preventing the layouts from saving. Can you attach a copy here on Github so I can debug it or alternatively reset your settings to default?

**Comment by altimumdelta** [comment]
It happens to also be a fresh Windows 10 (2004) install, oh and it's a ZIP binary, not setup.
[ProcessHacker.exe.settings.xml._altimumdelta_columnwidth.txt](https://github.com/processhacker/processhacker/files/5802227/ProcessHacker.exe.settings.xml._altimumdelta_columnwidth.txt)

**Comment by dmex** [comment]
>  it's a ZIP binary, not setup.

Are you running the binary from the zip without extracting it or did you extract the files from the zip then run it?

I tested your settings file and the customizations are correctly saved/restored so there must be something else preventing those settings from being saved. Do you have any antivirus products or other security software installed or running PH from a removable drive or something?

The only issue with your settings were the "Shareable WS" and "Shared WS" columns which have terrible performance. I've made some small changes that improve the performance slightly but I recommend using the "Shareable WS" and "Shared WS" counters on the properties window.

**Comment by altimumdelta** [comment]
Oh I have definitely extracted it, I have things well organized and everything that I manually install I create my own "program files" folders and stuff so yeah, definitely. I'm aware of that.

Yeah, I realized performance monitoring can be quite taxing on DPC latency and it would affect things, indeed it has come to my attention the amount of columns matter, but I never followed deep enough to figure out which of them is costly, so thanks for sharing that. This as initial setup and I haven't really finely tuned it if I really need Shared and Shareable WS at all, most likely not, at least in the main window.

**Comment by MagicAndre1981** [comment]
> Yeah, I realized performance monitoring can be quite taxing on DPC latency and it would affect the analysis,

process hacker is not the right tool for this. Use [ETW (WPR/xperf/WPA)](http://wiki.webperfect.ch/index.php?title=Trace:_Interrupts_(DPC/ISR)) for it.

**Comment by dmex** [comment]
> I realized performance monitoring can be quite taxing on DPC latency

performance monitoring shouldn't be "taxing" considering the spikes on this graph for DPCs (blue) were from moving the mouse: https://i.imgur.com/Edmd50n.png

> process hacker is not the right tool for this

You should only need WPR/xperf/WPA when there's an actual problem with DPC latency that needs diagnosing. Most machines can handle > 5 million a second without any delays.

**Comment by altimumdelta** [comment]
Sorry, I've kinda thrown my words out there, it's something around stuttering/DPC becuase I can see the mouse and game/app stuttering when Process Explorer / Process Hacker / Process Monitor is active in some cases, I've figured it probably has to do with the number of columns you enable. Tho I don't know if it's a program front-end or back-end (API) issue, as in, whether it would cause the same slowdown if there were no GUI, etc.

I believe some newer versions of Process Explorer introduced lag, as it seemed to me, or I wasn't using it in that manner before, I got more into digging I started experimenting, spamming a lot of columns. I've seen it affect DPC and it would cause issues.  

But as I mentioned that I do turn these things off when I'm doing actual analysis with the mentioned tools, otherwise the results would just be worthless. Why I use PH/PE at all, becuase it helps out in things where WPR(ETW)/GPA/VTune can't and not meant for, there's no one tool to rule them all and that's probably good anyway for other reasons.

Process Explorer causing high DPC or otherwise latency could be a side effect of some other root cause, but I've never narrowed it down to a specific column or feature yet, I'm now on a fresh Win10 with a much higher version than last time and if there was some sort of compatability this may fix it. Why I mentioned PE, it's because I had a similar experience with PH just a few days ago, I didn't actually checked what DPC latency looked like, becuase I'm not actually testing DPC latency in general, I'm testing programs, graphics apps, games (full screen applications). The reason why I need to keep DPC in check is because for the tests to be of any use (valid) I can't have any other factors affecting the analysis and the results.

Moreover, even if it perhaps may not matter with handling (polling) a lot of diagnostic info that much, and with DPC, it would still be good if it were only possible to poll 1 process, not all the processes nobody cares about. Unfortunate that the fundamentals of Windows and Window's profiling has such an inefficient limitation, or whatever it is, at least to my knowledge reading the docs, but I've been out of the loop for a while.

**Comment by altimumdelta** [comment]
It does seem to be remembering things now, perhaps that was just a one off edge case, or perhaps one particular column is triggering a bug.

**Comment by dmex** [comment]
> perhaps one particular column is triggering a bug.

Do you have issues saving settings anywhere else? The same function for saving those window settings is used throughout the application.

> It does seem to be remembering things now in the Threads tab

I haven't changed anything... You probably have third party software interfering with our window or the settings file and they've  updated their code so that isn't as obvious.

**Comment by dmex** [comment]
It could be a locale encoding issue. Try opening cmd and running the "systeminfo" command and post your locale settings so I can preform some tests using that same locale:
![image](https://user-images.githubusercontent.com/1306177/105331546-b2500280-5c27-11eb-8563-f985e36db436.png)

> third party software interfering

If there isn't a locale encoding issue then something probably hooked WideCharToMultiByte/MultiByteToWideChar and messed with the null terminators causing the settings to get written as garbage.

**Comment by dmex** [comment]
> third party software interfering

I've disabled the native Windows string conversion support... Update to the latest nightly build and check if settings are being saved correctly.

**Comment by altimumdelta** [comment]
Oh, right, I was busy, I will check it soon.

**Comment by altimumdelta** [comment]
I tried the latest Nightly version now and everything seems to work fine, in the Process Properties and Threads tab overall. And this time around it did save the Process specific stuff in the same session without closing first on the first run. But I'll still keep an eye still if I see something off. 

But I left all the options default, previously I think I was disabling plugins and extended features and changing some settings but I forgot exactly how/what.

**Comment by dmex** [comment]
> this time around it did save the Process specific stuff in the same session without closing first on the first run

Good to hear, thanks. Feel free to report any other issues you might run into 👍
