### ISSUE TITLE
Bonjour,

### ISSUE THREAD

**Issue by Xmen830FR** [processhacker/processhacker#781]
EN : In this [video](https://www.youtube.com/watch?v=7eFkToypW6c&feature=emb_logo) at this 0:16 footage.
The person has a dll file. But how can we download it?

FR : Dans cette [vidéo](https://www.youtube.com/watch?v=7eFkToypW6c&feature=emb_logo) à cette séquence 0:16.
La personne à un un fichier dll. Mais comment peut-on le télécharger ?

Veuillez me répondre à cette adresse email : behary2017@gmail.com
Please reply to this email address: behary2017@gmail.com

**Comment by dmex** [comment]
> But how can we download it?

WARNING 

It's a malicious trojan disguised as a game cheat for stealing passwords and account hijacking...  

DO NOT DOWNLOAD 

> The person has a dll file. But how can we download it?

WARNING 

https://www.virustotal.com/gui/file/adddb2a0735b0d284d33df3eeb5b288843c466badbbe02287b0999107de24828/detection

DO NOT DOWNLOAD 

Video traced to this webpage:
https[:]//www [.] gamingforecast [.] com/2020/09/among-us-radar-hack.html

To this pastebin:
https[:]//pastebin [.] com/8wDTgR5a


DO NOT DOWNLOAD 

![image](https://user-images.githubusercontent.com/1306177/104750713-902e2e80-57a8-11eb-92f4-64617d898889.png)
