### ISSUE TITLE
Choose Columns view is not DPI aware

### ISSUE THREAD

**Issue by roblabla** [processhacker/processhacker#782]
**Describe the bug**

The choose columns view is not DPI aware.

**To Reproduce**

1. Connect to windows via RDP, from linux I use this: `xfreerdp /gdi:hw /rfx /rfx-mode:video /scale:180 /scale-desktop:200`
2. Start Process Hacker
2. Right click on the columns -> Choose columns...

**Expected behavior**

The choose columns view to be DPI aware.

**Screenshots**
![image](https://user-images.githubusercontent.com/1069318/104759264-f6429380-575f-11eb-9271-c1a4309e3fd1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 

**Additional context**

I am connected via RDP to a VM, and set the DPI settings there. Maybe this causes the issue?

**Comment by dmex** [comment]
> I am connected via RDP to a VM, and set the DPI settings there. Maybe this causes the issue?

The item height wasn't scaled when DPI was >= 150%... I've fixed the issue in the latest nighty build. You can trigger the update by using the Help > Check for updates menu.

Thanks for reporting it 🍺
