### ISSUE TITLE
Peak handles not really the peak

### ISSUE THREAD

**Issue by mdblack98** [processhacker/processhacker#784]
Been tracking a handle leak and noticed the Peak Handles statistic resets itself periodically.  So it's not really "Peak Handles".
Seems to me Peak should mean Peak and if you want another "Peak in last minute" or such then that should be a  separate item.

Mike

**Comment by dmex** [comment]
> the Peak Handles statistic resets itself periodically

Does Process Explorer have the same issue?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

The performance tab should show the same values:
![image](https://user-images.githubusercontent.com/1306177/105636483-b8aadc80-5ebc-11eb-9b0a-21b366a5d5c7.png)

> So it's not really "Peak Handles". Seems to me Peak should mean Peak and if you want another "Peak in last minute" or such then that should be a separate item.

These values come directly from the Windows kernel for that process and we don't track the peak value ourselves... 

After debugging this I think that value was broken in a Windows 10 update... Those values were moved into HANDLE_TABLE_FREE_LIST and now only represent the count and maximum of the freelist. So when the freelist deallocates so does the "peak handles" which is a breaking change from previous versions of Windows.

If you can confirm that Process Explorer also has the same issue then I'll update the code to workaround the kernel changes and provide our own statistics for the peak counter on Windows 10.

**Comment by mdblack98** [comment]
Yes...same behavior in processexp
Mike

 

    On Sunday, January 24, 2021, 10:28:58 AM CST, dmex <notifications@github.com> wrote:  
 
 



the Peak Handles statistic resets itself periodically


Does Process Explorer have the same issue?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

The performance tab should show the same values:



So it's not really "Peak Handles". Seems to me Peak should mean Peak and if you want another "Peak in last minute" or such then that should be a separate item.


These values come directly from the Windows kernel for that process and we don't track the peak value ourselves...

After debugging this I think that value was broken in a Windows 10 update... Those values were moved into HANDLE_TABLE_FREE_LIST and now only represent the count and maximum of the freelist. So when the freelist deallocates so does the "peak handles" which is a breaking change from previous versions of Windows.

If you can confirm that Process Explorer also has the same issue then I'll update the code to workaround the kernel changes and provide our own statistics for the peak counter on Windows 10.

**Comment by dmex** [comment]
Thanks, I'll try adding some variables to check/track the handle counts. 

I also edited your reply since it included a lot of github junk 😋

**Comment by dmex** [comment]
Fixed in latest nightly build. You can force the update using Help > Check for updates

> Peak Handles statistic resets itself periodically

It'll now only reset when you close the properties window.

It could be extended in future to constantly query every process and track the maximum values for all processes but it would impact performance so I opted to only track the value when the properties window is currently open.

 Let me know if it's sufficient or would need more changes 👍

**Comment by mdblack98** [comment]
Check for updates didn't show any update available.
I was on 2.9.124
I just downloaded the nightly.
Thanks!!!  Now all I have to do is chase down my handle leak in the app I have....apparently not an easy thing...got thread handles hanging around and GC.Collect()+GC.WaitForPendingFinalizers() doesn't seem to clean them up.    
Mike

 

    On Monday, January 25, 2021, 07:02:04 AM CST, dmex <notifications@github.com> wrote:  
 
 


Fixed in latest nightly build. You can force the update using Help > Check for updates


Peak Handles statistic resets itself periodically


It'll now only reset when you close the properties window.

It could be extended in future to constantly query every process and track the maximum values for all processes but it would impact performance so I opted to only track the value when the properties window is currently open.

Let me know if it's sufficient or would need more changes 👍
