### ISSUE TITLE
It crash so much v2

### ISSUE THREAD

**Issue by shironaomi** [processhacker/processhacker#787]
_Plz, fix this, it crash every hour_

![ScreenShot_20210201073914](https://user-images.githubusercontent.com/76606218/106425199-d4395880-6463-11eb-98ad-0b458f67776c.png)

![ScreenShot_20210201072229](https://user-images.githubusercontent.com/76606218/106425215-ddc2c080-6463-11eb-9eb6-570d13a76a5a.png)

![ScreenShot_20210201073848](https://user-images.githubusercontent.com/76606218/106425222-e1564780-6463-11eb-9936-e805eeeb6976.png)

_Previous topic: https://github.com/processhacker/processhacker/issues/761#issuecomment-770621882_

**Comment by dmex** [comment]
1) Update to the latest version v3.0.3779

2) After it crashes, create a memory dump for processhacker.exe and upload it:

![image](https://user-images.githubusercontent.com/1306177/106465576-422a6200-64ee-11eb-9384-1fa097f348d0.png)

**Comment by shironaomi** [comment]
_To start with, I always keep it up to date
Here it's the dump file:_ [ProcessHacker.rar](https://www35.zippyshare.com/v/1znzkOsY/file.html)

**Comment by dmex** [comment]
Did you create the dump before or after it crashed? There's no crash information in the dump and nothing invalid.

**Comment by dmex** [comment]
I've found the offending code that was causing that crash and was fixed in the latest nightly build r3859 

Thanks for reporting it 👍
