### ISSUE TITLE
"Lost" the usage graphs atop the main window

### ISSUE THREAD

**Issue by JoelAzaria** [processhacker/processhacker#789]
**Describe the bug**
Not sure if it's an actual bug or just a pebcak but I lost the usage graphs at the top of the main PH window and cannot find how to restore them.  Have been through the settings/options many times and cannot find.  Right clicked everywhere I could think of, cannot find.  At a loss here.
Screencap attached.

Thanks

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Win 10 1903

![image](https://user-images.githubusercontent.com/470908/106872367-359a3b00-66a1-11eb-8934-0c35b523b8ed.png)

**Comment by Biswa96** [comment]
Did you try to enable that from the View -> Toolbar -> CPU history option?

**Comment by dmex** [comment]
> I lost the usage graphs at the top of the main PH window

Did you disable the toolbar?

![image](https://user-images.githubusercontent.com/1306177/106884337-4bf1d680-6735-11eb-971a-cc1ea07e50e3.png)

**Comment by dmex** [comment]
Feel free to reopen if you're still having issues 👍

**Comment by JoelAzaria** [comment]
Hey now, sorry for delayed reaction.  Missed the email notify.

> Did you try to enable that from the View -> Toolbar -> CPU history option?
I don't have that option in my menus
![image](https://user-images.githubusercontent.com/470908/107335938-8a192e00-6a86-11eb-980f-08b24590aef4.png)



> > I lost the usage graphs at the top of the main PH window
> 
> Did you disable the toolbar?
> 
> ![image](https://user-images.githubusercontent.com/1306177/106884337-4bf1d680-6735-11eb-971a-cc1ea07e50e3.png)
> 
> Or disable the ToolStatus plugin?
> 
> ![image](https://user-images.githubusercontent.com/1306177/106884577-983d1680-6735-11eb-9341-953233b49022.png)

I'm not sure how far behind I am.  I'm on 2.39 (which I thought was the current stable ver) and my options gui doesn't look *ANYTHING* like that.  Also, I have zero installed plugins.

![image](https://user-images.githubusercontent.com/470908/107336431-14fa2880-6a87-11eb-8e8c-064ef64dde65.png)

![image](https://user-images.githubusercontent.com/470908/107336520-322ef700-6a87-11eb-92dd-68ae9745c718.png)


Thanks.  Help much appreciated.
J.

**Comment by dmex** [comment]
All your plugins are missing... You will either need to reinstall the latest stable or install the latest nightly.

**Comment by dmex** [comment]
Also make sure you haven't accidently disabled plugins from the options window:

![image](https://user-images.githubusercontent.com/1306177/107643667-91307e00-6cca-11eb-86dc-8dc3a955aa58.png)

**Comment by JoelAzaria** [comment]
Ok.  Idk how that could've happened.  I know for sure I didn't disable or delete these myself.
I wonder if my AV could have smth to do with this..

**Comment by JoelAzaria** [comment]
Just want to update.  Reinstalling (well, unzipping the portable) package restored everything and works now.  Definitely my AV clobbered.
For reference that's BitDefender's GravityZone endpoint.  
Not sure why it keeps flagging you.  Maybe you can submit to them so they recognize you as legit?

Anyway, I'm sorted for now.  Thanks for all the help.

**Comment by dmex** [comment]
> BitDefender's GravityZone endpoint

Why just the plugins and not the whole project? 

> Not sure why it keeps flagging you. Maybe you can submit to them so they recognize you as legit?

Some grifter at Microsoft decided to blame the project for every last ransomware attack last year in their Defence Report: 

> Microsoft’s Detection and Response Team (DART) has observed that ransomware continues to be the most common reason behind our incident response engagements from October 2019 through July 2020. More threat actors are using open-source tools like ProcessHacker to initiate the attack that ultimately delivers ransomware payload.

Vendors are using that statement as a pretext to target and block the project. #454

**Comment by JoelAzaria** [comment]
> > BitDefender's GravityZone endpoint
> 
> Why just the plugins and not the whole project?
> 

Assumedly I had the main process excepted in the AV (I don't actually remember it would have been done a good while ago) and not the plugins.  And then further assumption, a recent-ish update in the AV made it yet more aggressive so it ate the plugins (perhaps based on some new EDR features added to our account - not sure on the timing, kinda guessing)

> > Not sure why it keeps flagging you. Maybe you can submit to them so they recognize you as legit?
> 
> Some grifter at Microsoft decided to blame the project for every last ransomware attack last year in their Defence Report:
> 
> > Microsoft’s Detection and Response Team (DART) has observed that ransomware continues to be the most common reason behind our incident response engagements from October 2019 through July 2020. More threat actors are using open-source tools like ProcessHacker to initiate the attack that ultimately delivers ransomware payload.
> 
> Vendors are using that statement as a pretext to target and block the project. #454

That kinda sucks.  They should be more diligent.  Perhaps work with you to check via hash or smth that the main .exe and/or other parts aren't compromised but I'm sure that's easier said than thought up.

Either way I've added more explicit, detailed exceptions.  For the main folder, the plugins folder, kprocess.sys, peview.exe and ofc the ph exe.   Hopefully that's sufficient to keep it from attacking ph and at least if it happens again I'll know wtf to look for.

And hopefully this now shows up in searches in case anyone else gets painted into the same corner.

thx.
