### ISSUE TITLE
add the same context menu to systray icon pop-up window like i have in main window

### ISSUE THREAD

**Issue by mailinglists35** [processhacker/processhacker#79]
i need this context menu ...
![image](https://cloud.githubusercontent.com/assets/2054302/20718940/76d2bdee-b66b-11e6-9278-675c804c7d3f.png)

to be available on this popup window...
![image](https://cloud.githubusercontent.com/assets/2054302/20719100/fc64ee0a-b66b-11e6-9b1a-d1af8bc51d09.png)

**Comment by dmex** [comment]
This was added to the latest nightly 👍

**Comment by mailinglists35** [comment]
thank you!
