### ISSUE TITLE
Windows 10 UTF8 CodePages

### ISSUE THREAD

**Issue by dmex** [processhacker/processhacker#793]
Windows Version 1903 (May 2019 Update), you can use the ActiveCodePage property in the appxmanifest for packaged apps, or the fusion manifest for unpackaged apps, to force a process to use UTF-8 as the process code page.

Add support for showing the active process codepage.

**Comment by dmex** [comment]
@pbatard 

![image](https://user-images.githubusercontent.com/1306177/107322245-347d6980-6af8-11eb-8e5b-e0593e495623.png)

**Comment by dmex** [comment]
Added 'cocepage' rather than codepage to latest nightly

**Comment by pbatard** [comment]
Nice feature to have indeed. Thanks for adding it!

For the record, latest versions of Windows 10 have introduced UTF-8 support in their `A` APIs, per https://docs.microsoft.com/en-us/windows/uwp/design/globalizing/use-utf8-code-page.

And of course, provided you run a recent Windows 10 release, you can also force UTF-8 for all apps through the BETA option in the system locale settings:
![BETA: Use UTF-8](https://1.bp.blogspot.com/-ieh39y8zebM/XdHOFULvqCI/AAAAAAAACd0/B_5-bgEY4MwtxP-Mn6C6iHn6vnCHNht1QCLcBGAsYHQ/s1600/Image1.png)

Doing that will turn pretty much every executable into using UTF-8 as their default codepage:

![Image1](https://user-images.githubusercontent.com/1206968/107393711-0184a700-6af3-11eb-8873-3646de62f349.png)

**Comment by dmex** [comment]
@pbatard 

I saw rufus was using the feature via manifest so I thought the extra column showing which processes were using the feature would be good 🙂

I added the same flags to Process Hacker as well since we support UTF8 and I also found "utf-8" isn't actually a valid setting but rather only uppercase UTF-8 so hopefully the column might help people diagnose those sort of issues.
