### ISSUE TITLE
GeoIP database update is broken since version 3.0.37xx

### ISSUE THREAD

**Issue by GitAndi8** [processhacker/processhacker#794]
**Describe the bug**
GeoIP database update is broken since version 3.0.37xx.

**To Reproduce**
1. Go to "Tools" -> "Network Tools"
2. Click on "GeoIP database update..."
3. See error

**Expected behavior**
In versions before nightly build 3.0.37xx the file was downloaded and extracted correctly.
Now when the download is finished an error message appears "Error downloading GeoIP database".

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 20H2

**Comment by dmex** [comment]
There was a regression deleting the existing file... I've updated the nightly build with the fix and you can force the update using the Help > Check for updates menu.

Thanks for reporting it 👍
