### ISSUE TITLE
Error message upon starting PH

### ISSUE THREAD

**Issue by Nihilopia** [processhacker/processhacker#795]
**Description**
Upon launching PH I get an error message box with following content:

```
---------------------------
Process Hacker [Z170A-M5\Emmi]+ (Administrator): ProcessHacker.exe - Bad Image
---------------------------
C:\Program Files (x86)\Overwolf\0.162.0.13\OWExplorer.dll

 is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc0000428. 
---------------------------
OK   
---------------------------
```

**To Reproduce**
1. Have Overwolf installed
2. Have Overwolf runnning, including the process `OverwolfHelper64.exe` with the arguments `path=C:\Program Files (x86)\Overwolf\0.162.0.13\OWExplorerLauncher.dll pid=7684` (where 7684 is the parent Overwolf.exe process)
3. Open PH

**Screenshots**
![image](https://user-images.githubusercontent.com/28660694/107513148-15d6ab80-6ba8-11eb-87f9-fd98734e264a.png)

**Additional info**
As soon as the error message pops up, the main window of Process Hacker stops responding. The error message window is not affected.

**App versions**
 - OS: Windows 10 20H2 (19042.746)
 - PH: 3.0.3813 (5ec361af)
 - Overwolf version: 0.162.0.13

**Comment by a1lic** [comment]
Disable "Enable mitigation policy" in options.
It causes confiricts with many shell extensions. (such as tortoisegit...)

**Comment by Nihilopia** [comment]
Seems to work. I get a normal start of PH now.

**Comment by dmex** [comment]
I've enabled extra error dialogs to help KaKi87 diagnose a crash reported here: https://github.com/processhacker/processhacker/issues/792

Overwolf is injecting a DLL into PH which fails the Microsoft signed mitigation causing that error dialog... It normally silent fails but since all errors are enabled you'll see that dialog until I disable them again in the next week, maybe two.

**Comment by dmex** [comment]
Error dialogs caused by third party software are disabled again 👍
