### ISSUE TITLE
Recent Restart of some processes results in "unable to restart - A required privilege is not held by the client"

### ISSUE THREAD

**Issue by Almighty188** [processhacker/processhacker#798]
Recent Restart of some processes results in "unable to restart - A required privilege is not held by the client" as seen in attached.

Not sure is this related to the latest Microsoft updates for Windows 10 20H2 or not.  

![2021-02-12_19-05-47](https://user-images.githubusercontent.com/78993393/107840431-82e46f80-6d67-11eb-88f8-60b9158784d2.jpg)

**Comment by dmex** [comment]
Yeah, something changed. Vanilla 20H2 doesn't have the error while patched 20H2 does.

I've changed the Restart option to instead use a different method which is more reliable for restarting processes in the latest nightly 👍
