### ISSUE TITLE
Add the option to view 16-bit processes on 32-bit systems since NTVDM still exists on the latest 32-bit version of Windows 10

### ISSUE THREAD

**Issue by kristibektashi** [processhacker/processhacker#800]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dmex** [comment]
What use would there be showing 16bit processes? vendors like nvidia are not even producing 32bit drivers anymore so even 32bit is basically dead now?

**Comment by kristibektashi** [comment]
> What use would there be showing 16bit processes? vendors like nvidia are not even producing 32bit drivers anymore so even 32bit is basically dead now?

It could be useful for 32-bit virtual machines that are used to run 16-bit software since it's not supported on 64-bit

**Comment by yfdyh000** [comment]
@kristibektashi So what do you want to see and what is missing for the present?

**Comment by dmex** [comment]
@kristibektashi 

When you open the properties for any `ntvdm.exe` process... You'll see the 16bit processes listed on the NTVDM tab with options to locate and terminate individual 16bit processes/tasks👍 

![image](https://user-images.githubusercontent.com/1306177/112073526-6b02d580-8bc8-11eb-8db2-2634363b2746.png)
