### ISSUE TITLE
Nvidia driver upgrade breaks GPU columns until PH restart

### ISSUE THREAD

**Issue by falcon4fun** [processhacker/processhacker#802]
**Describe the bug**
So. If you upgrade nvidia driver, then try to look into GPU colums, they will be empty. :)
Don't know if it is a bug or a feature. Don't know either if PH can handle it without restart but I report it as a bug :)

**To Reproduce**
1. Upgrade nvidia driver version
2. Look inside PH (add GPU, GPU dedicated memory, GPU shared memory columns before)
3. Profit. They are empty

**Expected behavior**
To handle it somehow without restart if it is possible ¯\_(ツ)_/¯

**Desktop (please complete the following information):**
 - OS: W10 x64 20h2
 - PH version: 3.0.3828 (ff0fbe1b)

**Comment by dmex** [comment]
Microsoft has broken the D3DKMTQueryStatistics API several times in the last three years... One of those changes randomly reassigns the LUID of the adapter everytime the driver updates.

The changes to the D3DKMTQueryStatistics API giving taskmgr.exe a competitive advantage over third party software such as Process Hacker is severe anticompetitive conduct - Microsoft did the same thing to netscape with similar API changes back in the 90s and it didn't work so well for them back then so hopefully the regulator will intervene soon. #454 

20H1 and above have the issue you reported and are no longer reporting the correct GPU usage... You can workaround that issue by enabling the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` option from 0 to 1 but it results in a severe performance degradation while using Process Hacker over long periods of time but it does report the correct gpu usage after the D3DKMTQueryStatistics API was changed.
