### ISSUE TITLE
How detect if process suspended programmatically via c++ ?

### ISSUE THREAD

**Issue by goodandrewsoft** [processhacker/processhacker#803]
How detect if process suspended programmatically via c++ ?

**Comment by dmex** [comment]
A process doesn't get suspended only its threads. So you need to enumerate all the threads and check if they're all suspended.

You can't really detect when they've been suspended and immediately resumed before/after the enumeration only if they're currently suspended at the time of enumeration so you would have to block all suspension using ObRegisterCallbacks if that's what you're looking for.

**Comment by goodandrewsoft** [comment]
Can you provide some code where thread enumerated and checking for suspending? 
Big thanks for your job.

**Comment by dmex** [comment]
https://github.com/processhacker/processhacker/blob/82236c5c04c3a7d7c193aa9e0e6092a5de9b7ce7/ProcessHacker/appsup.c#L54-L91
