### ISSUE TITLE
Memory Priority saver and Disallowed Process saver

### ISSUE THREAD

**Issue by Atlas1394** [processhacker/processhacker#805]
It would be nice if you could add the memory priority saving possibility, like the CPU and I/O Priority ones. Another nice feature would be the possibility to have a blacklist, in which Process Hacker could close the interested process if present in the list, when it find them active and running.

**Comment by dmex** [comment]
> add the memory priority saving possibility, like the CPU and I/O Priority ones

What benefit is there from saving the memory priority when its already determined based on the existing process priority? 

> the possibility to have a blacklist, in which Process Hacker could close the interested process if present in the list

I'd like this feature but Microsoft currently considers this malicious.

**Comment by Atlas1394** [comment]
When i start process hacker, the memory priorities of all processes are set to normal. Currently in process hacker there is the possibility to set it to low, for example, but not to save it permamently, like I/O priority or the process priority. So i have to manually adjust the priority everytime i log into the program. I noticed performance benefits in some games doing this. About your question, i could answer you with the same question: why you added the selection of memory priority, if it is automatically set by the process priority?
Anyway, thanks for answering, I really appreciate your work.
And sorry for my bad english.

**Comment by dmex** [comment]
> why you added the selection of memory priority, if it is automatically set by the process priority?

Yeah, I guess... I've added the options for saving the page priority to the latest nightly build 👍 

You can force the update using the Help > Check for updates menu
