### ISSUE TITLE
Question:  Composition of GPU shared memory limit: 49.52G on my PC

### ISSUE THREAD

**Issue by lovelifezhenzhen** [processhacker/processhacker#807]
This value in Process Explore is about 16G on my PC, approximate to physical ram size. But why this value is so big in Process Hacker? So can you share me the composition of GPU shared memory limit? There are two GPUs on my PC, for each GPU, shared memory size is about 8G.

**Comment by dmex** [comment]
Try changing the `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters`  setting from 0 to 1

**Comment by lovelifezhenzhen** [comment]
Thanks for your reply!
Do you mean change it in settings.xml, there is no settings about ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters;
If I add it and run process hacker, it is still 49.52G on my PC.
Settings in original xml file is as following:
  <setting name="ProcessHacker.ExtendedTools.DiskTreeListColumns"></setting>
  <setting name="ProcessHacker.ExtendedTools.DiskTreeListSort">4,2</setting>
  <setting name="ProcessHacker.ExtendedTools.EnableEtwMonitor">1</setting>
  <setting name="ProcessHacker.ExtendedTools.EnableGpuMonitor">1</setting>
  <setting name="ProcessHacker.ExtendedTools.GpuNodeBitmap">ffff0300</setting>
  <setting name="ProcessHacker.ExtendedTools.GpuLastNodeCount">12</setting>

**Comment by dmex** [comment]
> there is no settings

You need to have the nightly build for that setting to exist:
https://processhacker.sourceforge.io/nightly.php

**Comment by lovelifezhenzhen** [comment]
Thank you.
May I ask in which condition should we enable the GpuPerformanceCounters?
Two GPU exists and why only one GPU is displayed?

**Comment by dmex** [comment]
> it is still 49.52G on my PC.

How much RAM do you have on your machine?

**Comment by lovelifezhenzhen** [comment]
The latest version shows correct limit on my PC now.

**Comment by dmex** [comment]
The code hasn't changed so who knows what it was 🤷‍♂️
