### ISSUE TITLE
Windows does not go past asus spining circles after disabling some service using Process Hacker

### ISSUE THREAD

**Issue by aussiekendoll** [processhacker/processhacker#811]
I disabled some service using Process Hacker , after the next restart my PC does not go past asus spining circles where the spining stucks after few seconds.
Is there any way to re enable the disabled service?

**Comment by AzAgarampur** [comment]
Boot into WinRE and load the SYSTEM registry hive in regedit. Then enable the services manually via the registry.

**Comment by aussiekendoll** [comment]
> Boot into WinRE and load the SYSTEM registry hive in regedit. Then enable the services manually via the registry.

how could I enable it manually?  what should i type on the cmd?

**Comment by AzAgarampur** [comment]
Open the Windows recovery environment, then open the command prompt. Type `regedit` to open the registry editor. Then in regedit, click the `HKEY_LOCAL_MACHINE` hive, then goto File > Load Hive. Choose the `SYSTEM` hive from us OS's drive, like `C:\Windows\System32\config\SYSTEM`.

Then enter a name, like `RealOS`. Then use the registry editor to navigate the newly mounted hive `HKEY_LOCAL_MACHINE\RealOS\`, then click on either `CurrentControlSet` or `ControlSet001`. Then expand the `Services` key.

There you'll find all the registry keys for your services. Find the one you want then change the `Start` value for that key to the value you want.

**Comment by dmex** [comment]
There's also a guide here:
https://www.tenforums.com/tutorials/57567-restore-default-services-windows-10-a.html
