### ISSUE TITLE
VS2019 v16.9.0 - needed update tools\thirdparty\...\thirdparty.lib

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#820]
If not recompile have ERROR C1047 and link fatal error LNK1257 like:

Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.9.31004.209)
VisualStudio: VisualStudio / 16.9.0 + 31025.194

Building ... 3.0.8395.3868 (ae3164e) [master]

[00:00] Building ProcessHacker (x32) ...
[ERROR] (1) LINK: fatal error C1047: The object or library file ".\Phlib.lib" was created in a different version of the compiler than other objects, for example, ".\About.obj"; all objects and libraries will be rebuilt using the same compiler version [.\ProcessHacker.vcxproj] LINK: fatal error LNK1257: Failed to generate code [.\ProcessHacker.vcxproj]

I recomple all tools/thirdparty/.../thirdparty.lib and build success w/o Terminator plug-in - needed path  (diff)
```
---  ./TerminatorPlugin/kph2data.c	  Git 0ad3cac4b
+++  ./TerminatorPlugin/kph2data.c        working copy
@@ -233,10 +233,24 @@
 {
     ULONG majorVersion, minorVersion, servicePack, buildNumber;
 
-    majorVersion = PhOsVersion.dwMajorVersion;
-    minorVersion = PhOsVersion.dwMinorVersion;
-    servicePack = PhOsVersion.wServicePackMajor;
-    buildNumber = PhOsVersion.dwBuildNumber;
+    RTL_OSVERSIONINFOEXW versionInfo;
+    majorVersion;
+    minorVersion;
+    servicePack;
+    buildNumber;
+
+    memset(&versionInfo, 0, sizeof(RTL_OSVERSIONINFOEXW));
+    versionInfo.dwOSVersionInfoSize = sizeof(RTL_OSVERSIONINFOEXW);
+
+    if (!NT_SUCCESS(RtlGetVersion(&versionInfo)))
+    {
+        return STATUS_NOT_SUPPORTED;
+    }
+
+    majorVersion = versionInfo.dwMajorVersion;
+    minorVersion = versionInfo.dwMinorVersion;
+    servicePack = versionInfo.wServicePackMajor;
+    buildNumber = versionInfo.dwBuildNumber;
 
     memset(&Package->StructData, -1, sizeof(KPH_DYN_STRUCT_DATA));
```
or plugin is build failure....

**Comment by dmex** [comment]
The terminator plugin is archived and does not exist in this repository.

**Comment by VictorVG** [comment]
Ok! Then I'll kick him out, although the guys ask him. But for me personally, it came in handy three times over the years ...
