### ISSUE TITLE
processhacker sha1 request

### ISSUE THREAD

**Issue by BryceCanyon** [processhacker/processhacker#828]
I really need the ability to run ProcessHacker in some client environments, however, my enterprise class anti-malware package SentinelOne, strips the .exe upon install.  I can create an exclusion for the hash, but S1 does not support Sha2 as an Exclusion type, and there is no argument in Powershell to pull Sha2 as well.   Can you provide the sha1 for this file?

Thank you

BryceCanyon

**Comment by dmex** [comment]
> enterprise class anti-malware package SentinelOne... does not support Sha2

SHA1 has been deprecated for a decade. "Security" software should be using more secure hashing algorithms.

> there is no argument in Powershell to pull Sha2 as well. Can you provide the sha1 for this file?

You can get the SHA1 hash using powershell: 

`Get-FileHash -Algorithm SHA1 "C:\Program Files\Process Hacker\ProcessHacker.exe" | Format-List`
