### ISSUE TITLE
Affinity save

### ISSUE THREAD

**Issue by mdblack98** [processhacker/processhacker#833]
Can we get the ability to save the Affinity for a process?
Thanks

**Comment by dmex** [comment]
You can save affinity for processes in the nightly builds 👍
https://processhacker.sourceforge.io/nightly.php

**Comment by mdblack98** [comment]
Thanks Steven!!
Mike

 

    On Monday, March 15, 2021, 08:45:42 PM CDT, dmex ***@***.***> wrote:  
 
 


You can save affinity for processes in the nightly builds 👍
https://processhacker.sourceforge.io/nightly.php
