### ISSUE TITLE
Bad Image error message on start when DisplayFusion or MacType are installed

### ISSUE THREAD

**Issue by sokolovsa** [processhacker/processhacker#836]
**Describe the bug**
ProcessHacker shows error message on startup if DisplayFusion and MacType are installed.
DisplayFusion Pro 9.5
MacType 2019.1
ProcessHacker 3.0.3874

**To Reproduce**
1. Have the software listed above installed
2. Start ProcessHacker

**Expected behavior**
ProcessHacker starts without errors

**Screenshots**
When ProcessHacker starts, it shows 2 error messages:
![image](https://user-images.githubusercontent.com/13876721/111311304-19f65d00-866f-11eb-9125-91999db99ee9.png)
![image](https://user-images.githubusercontent.com/13876721/111311317-1fec3e00-866f-11eb-9ef1-19d084fd3e38.png)

**Desktop (please complete the following information):**
 - OS:  windows 10 x64
 - Version: Edition Windows 10 Pro, Version 20H2, OS build 19042.804, Experience Windows Feature Experience Pack 120.2212.551.0

**Comment by dmex** [comment]
Can you add the "Error mode" column to the processes list and copy the text for processhacker.exe?

You should have this:
![image](https://user-images.githubusercontent.com/1306177/111317376-37034e00-86b8-11eb-9ab9-f4c2e792b3ab.png)

**Comment by sokolovsa** [comment]
yes, that is excactly what I have:
Fail critical, GP faults, Openfile faults (0x8003)

**Comment by dmex** [comment]
Fixed in the latest nightly build 👍
