### ISSUE TITLE
Configurable row height

### ISSUE THREAD

**Issue by dhry** [processhacker/processhacker#837]
Super low priority request. I know there is an option to change the font. Could you also add an option to reduce the row height of each entry please? Which could also involve reducing the size of the app icons on the left of the process name as well. I have so many processes running that it's more than three screens' of scrolling, reducing the row height would alleviate this.

Cheers
Dhry

**Comment by dmex** [comment]
There's a setting named `ThinRows` for minimizing the row size. Enable the setting by changing from 0 to 1

For example from the advanced settings:
![image](https://user-images.githubusercontent.com/1306177/111340716-fd890d80-86cc-11eb-8a87-5182947151d8.png)
