### ISSUE TITLE
Administrator

### ISSUE THREAD

**Issue by mdblack98** [processhacker/processhacker#838]
How do we get ProcessHacker to run as Administrator from the task bar?
I've got the executable marked to run as Admin but it comes up without Admin.

Also the version on the nightly build shows 2.39.124 -- but the downlaod says 3.0.3880

Mike

**Comment by dmex** [comment]
2.x is the stable branch, 3.x is the nightly branch. Nightly is downloaded from the nightly page:
https://processhacker.sourceforge.io/nightly.php

The nightly builds have an experimental option for running as administrator by default but it might be removed in the future:
![image](https://user-images.githubusercontent.com/1306177/111381163-71d9a600-86f9-11eb-9ad5-94e1742d6ad9.png)

**Comment by mdblack98** [comment]
Had to uninstall the old 2.X version.
Without the "Run as Administrator" CPU Affinity was not restored to the executables on restart until ProcessHacker was run as Admin.
Mike

 

    On Tuesday, March 16, 2021, 04:19:37 PM CDT, dmex ***@***.***> wrote:  
 
 


2.x is the stable branch, 3.x is the nightly branch. Nightly is downloaded from the nightly page:
https://processhacker.sourceforge.io/nightly.php

The nightly builds have an experimental option for running as administrator by default but it might be removed in the future:
