### ISSUE TITLE
Run as TrustedInstaller

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#839]
I keep forgetting that RunAs TrustedInstaller is not here ...

![image](https://user-images.githubusercontent.com/133706/111518114-6ff5fe00-875e-11eb-81c6-f78635a64e9d.png)

(p.s. missing Always on Top)

... but here

![image](https://user-images.githubusercontent.com/133706/111517898-3d4c0580-875e-11eb-9524-32d659dd6e61.png)

Can the former dialog somehow contain the latter option?

**Comment by dmex** [comment]
> Can the former dialog somehow contain the latter option?

Th runas dialog is for running processes as users. TI isn't a user and so it doesn't have the same functionality?

**Comment by stdedos** [comment]
Oh, I see! 

Thank you for the disambiguation 😄
