### ISSUE TITLE
PEView's MaxSizeUnit option doesn't actually apply when changed (one-liner fix)

### ISSUE THREAD

**Issue by jgottula** [processhacker/processhacker#844]
Hi,

This is a small quick bug report / fix for something that's bothered me for a while.

In PEView, if you open the Options dialog and choose one of the unit sizes from the dropdown box and then hit OK, nothing happens: the sizes printed on the property sheets don't change; the `MaxSizeUnit` value in the peview.xml settings file doesn't change; and if you re-open the Options dialog, the dropdown simply reverts to whatever it was set to before.

Manually modifying `MaxSizeUnit` via the XML file **does** work as expected: the dropdown box in the Options dialog will show the correct thing based on what was manually set in the file, and the various sizes printed throughout the program are correctly rendered based on the setting. (But of course the dropdown box itself still doesn't actually function for changing the setting.)

---

I compared the PH and PEView settings/options code (and it's pretty clear that the latter is a... well... kinda incomplete adaptation of the former 😄), and discovered the difference between the two that explains the broken behavior in PEView.

PEView needs the following line (adapted from PH) added to its options.c so that the dropdown box selection will actually be applied to the `MaxSizeUnit` setting as well as the `PhMaxSizeUnit` variable:
```diff
diff --git a/tools/peview/options.c b/tools/peview/options.c
index ddcee26a..63aa6ead 100644
--- a/tools/peview/options.c
+++ b/tools/peview/options.c
@@ -155,13 +155,14 @@
 static VOID PhpGeneralPageSave(
     _In_ HWND WindowHandle
     )
 {
     HWND listViewHandle = GetDlgItem(WindowHandle, IDC_SETTINGS);

     //PhSetStringSetting2(L"SearchEngine", &PhaGetDlgItemText(WindowHandle, IDC_SEARCHENGINE)->sr);
+    PhSetIntegerSetting(L"MaxSizeUnit", PhMaxSizeUnit = ComboBox_GetCurSel(GetDlgItem(WindowHandle, IDC_MAXSIZEUNIT)));

     if (!PhEqualString(PhaGetDlgItemText(WindowHandle, IDC_DBGHELPSEARCHPATH), PhaGetStringSetting(L"DbgHelpSearchPath"), TRUE))
     {
         PhSetStringSetting2(L"DbgHelpSearchPath", &(PhaGetDlgItemText(WindowHandle, IDC_DBGHELPSEARCHPATH)->sr));
         //RestartRequired = TRUE;
     }
```
(I would have made a PR for this; but it seemed like a lot of hassle for a one-liner.)

With the addition of that line of code, the dropdown box now functions completely correctly!

---

Unfortunately, however, there doesn't seem to be any simple mechanism available in PEView to tell all the property sheets to redo their string formatting; and so any property sheets that have already been initialized will retain their units based on what the setting was at their initialization time. (It's actually kinda funny: you can set the setting to one value, load a tab, set it to another value, load another tab, set it to another value, load another tab, and then you get three property sheets that are all rendered based on different notions of what `PhMaxSizeUnit` is/was.)

So, short of a good idea on how to tell all the property sheets to reformat their stuff, it might be a good idea to make PEView's `MaxSizeUnit` setting be restart-required-on-change. (And so that'd mean not only setting `RestartRequired`, but **also** cutting out the inline assignment to `PhMaxSizeUnit`, so that consistency is maintained for string formatting during the remainder of the current run, to avoid property sheets that are initialized later being inconsistent.)

Okay, that's all. Thanks for the tremendously useful tools; Process Hacker is an indispensable part of my ability to do power-user stuff with ease. 😀

**Comment by dmex** [comment]
The setting was added to the latest nightly peview 👍 

> mechanism available in PEView to tell all the property sheets to redo their string formatting

I've been focusing more on the data/parsing/reversing the PE format and the options window only has the bare minimum few things requested via github issues. The options window will be completed some point after most of the other peview features are done 👍
