### ISSUE TITLE
Dragging the treelist column divider to left window edge breaks treelist drawing

### ISSUE THREAD

**Issue by townsman1** [processhacker/processhacker#849]
Tabs and scrollbar in Modules don't work.

**Comment by dmex** [comment]
Do you have a screenshot or reproduction steps?

**Comment by townsman1** [comment]
[Screenshot of tabs](https://s8.hostingkartinok.com/uploads/images/2021/03/9edc8c18069f40020d9ead7873e3cf76.png)

**Comment by townsman1** [comment]
[Screenshot of scrollbar](https://s8.hostingkartinok.com/uploads/images/2021/03/ecb5b320009576bec0ac9301a47f9187.png)

**Comment by townsman1** [comment]
In other windows of the program, the same glitch. Appears after dragging the left border of the second tab to the left to the end and back. Not playable on Windows 7, only on Windows 10.

**Comment by dmex** [comment]
> dragging the left border of the second tab to the left

The divider?

> only on Windows 10

This was fixed in the latest nightly build. You can update using the Help > Check for updates menu.

**Comment by townsman1** [comment]
Thank you!
