### ISSUE TITLE
Visual stability for process/IO/etc list views

### ISSUE THREAD

**Issue by the-vindicar** [processhacker/processhacker#850]
**Is your feature request related to a problem? Please describe.**
When dealing with quickly updating information, such as current I/O operations, it's sometimes hard to keep track of particular item because it's position in the window changes constantly due to items above it being added or removed. With particularly fast changes, the item might go off the visible part altogether, making it even harder to find it again.
While filtering could make it easier, it's not always feasible, as filtered list might still have the same problem if it's large enough.
Similarly, when you aren't sure which filter criteria to apply, you might seek for "something odd" visually anyway.

**Describe the solution you'd like**
Ideally, if user selected a row in a list view, that list view should scroll itself on every update so the position of selected item relative to the list window remains unchanged, if possible.

**Describe alternatives you've considered**
Alternative would be a separate window for "pinned objects" that would allow use to view specific items separately from their home lists.

**Comment by pjbuterbaugh** [comment]
Bump - It's possible to highlight objects in PH3, and *literally* everything else about this program is perfect, but the ability to be able to watch one or more processes without their row position changing would be invaluable.

**Comment by dmex** [comment]
Add the `Start time` column and use it for sorting, new processes will be added at the end.
