### ISSUE TITLE
Cannot choose columns in security tab in PEView.

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#853]
**Describe the bug**
Cannot choose columns in security tab in PEView.

**To Reproduce**
 - Open PEView.
 - Easiest way is to double-click on some process, go to modules tab, double-click on some module.
 - In PEView open some Microsoft module (such as ntdll.dll).
 - Go to Security tab.
 - Right-click on some column, you can hide it.
 - Right-click on header, Choose columns...
 - Nothing happens. I cannot display hidden columns, but I can hide them.
 - )-:

**Expected behavior**
Choose columns... menu item works.

**Screenshots**

**Desktop (please complete the following information):**
Windows 8.1 x86.
Windows 10 x64.
Process Hacker nightly.
PEView nightly.

**Additional context**
Doesn't work even if I build from sources.
Probably related to [line 610 in file misc.c](https://github.com/processhacker/processhacker/blob/master/tools/peview/misc.c#L610).

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
