### ISSUE TITLE
Total Working Set of Currently Selected Processes

### ISSUE THREAD

**Issue by Yaron10** [processhacker/processhacker#857]
**Is your feature request related to a problem? Please describe.**
I often want to know the **total** working set of a program using multiple processes (e.g. Firefox, Chrome).

**Describe the solution you'd like**
Add an option to display the total working set of all the currently selected processes in the status bar.

Thank you.

**Comment by dmex** [comment]
Added to latest nightly build

**Comment by Yaron10** [comment]
@dmex,

👍 
Very useful and works like a charm. Thank you so much.
***
The status-bar fields' values take ~4 seconds to display (compared to ~1 second in v2.39).
Is there anything I can do (disable ?) to speed it up?

**Comment by dmex** [comment]
> The status-bar fields' values take ~4 seconds to display (compared to ~1 second in v2.39).

After starting PH or at runtime?

**Comment by Yaron10** [comment]
After starting PH.
I've tested it on two machines and the difference is significant.

If this can not be changed, would it be possible to adapt the new `ToolStatus.dll` to v2.39?

Thanks again.

**Comment by Yaron10** [comment]
https://github.com/processhacker/processhacker/issues/929
