### ISSUE TITLE
Question: for system GPU decicated memory, Current > Limit, is it normal?

### ISSUE THREAD

**Issue by lovelifezhenzhen** [processhacker/processhacker#859]
For system GPU decicated memory, Current > Limit when EnableGpuPerformanceCounters = 1, is it normal? 
![2021-04-02_103951](https://user-images.githubusercontent.com/39288361/113374813-9ba0f700-93a0-11eb-9c19-1675df37fdac.png)

**Comment by dmex** [comment]
Is this an integrated graphics card and what does Task Manager show?

**Comment by lovelifezhenzhen** [comment]
It is a graphics card installed by ourselves, here is task manager result:
![2021-04-02_143212](https://user-images.githubusercontent.com/39288361/113388334-a075a300-93c0-11eb-826e-0f59bf09d5e4.png)

**Comment by dmex** [comment]
What's the model number?

**Comment by lovelifezhenzhen** [comment]
![Uploading 2021-04-02_153348.png…]()

**Comment by lovelifezhenzhen** [comment]
I find sometimes GPU dedicated bytes for devenv.exe is extremely large, when I close the exe, system GPU dedicated memory will be normal.
![2021-04-02_153348](https://user-images.githubusercontent.com/39288361/113403335-0c640580-93d9-11eb-925f-2b30424ebd9a.png)

**Comment by MagicAndre1981** [comment]
> I find sometimes GPU dedicated bytes for devenv.exe is extremely large, when I close the exe, system GPU dedicated memory will be normal.

inside VS options [disable HW acceleration and rich effects](https://docs.microsoft.com/en-us/troubleshoot/visualstudio/general/performance-crash-issue#workarounds) 

![image](https://user-images.githubusercontent.com/8274816/113503375-c53d5800-9531-11eb-82ac-a27a3c6149b0.png)

**Comment by dmex** [comment]
The GPU counter implementation was rewritten a few weeks ago and fixed the dedicated memory counter 👍
