### ISSUE TITLE
Memory->Strings->Filter not work with unicode (like cyrillic and emoji) string

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [processhacker/processhacker#865]
**Describe the bug**
In miranda32.exe process I'm type "123 еуые 👻 zxcvb 123" in textarea and if try Filter->Contains for еуые or 👻 i get 0 result.
If i try zxcvb then i get in Result window "123 5=zxcvb 123" where еуые and 👻 cutted/corrupted.
When i open result i get offset selection (selection does not start at 123) 
![изображение](https://user-images.githubusercontent.com/4449851/113708765-4d665d80-96ea-11eb-93e7-ebbdbe3c940f.png)
In row strings it displayed as: "1.2.3. .5.C.K.5. .=.{. .z.x.c.v.b. .1.2.3." (31 00 32 00 33 00 20 00 35 04 43 04 4b 04 35 04 20 00 3d d8 7b dc 20 00 7a 00 78 00 63 00 76 00 62 00 20 00 31 00 32 00 33 00). Raw unicode.

**Comment by dmex** [comment]
This is related to issue #851
