### ISSUE TITLE
is:issue is:open  after suspended the anti-malware service  my screen turns black and stuck 

### ISSUE THREAD

**Issue by sagor4u** [processhacker/processhacker#869]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Vista]

**Additional context**

**Comment by dmex** [comment]
> anti-malware service

What's the name of the service?

**Comment by dmex** [comment]
Closing until more information provided for reproduction.
