### ISSUE TITLE
Properties window of services doesn't work

### ISSUE THREAD

**Issue by Gladuin** [processhacker/processhacker#871]
**Describe the bug**
When trying to open the properties window of a service, it does not function properly. Some "ghost" window is opened, but that's it.

**To Reproduce**
1. Go to the services tab
2. Right click a service
3. Click "Properties"
4. Observe the windows opened by Process Hacker

**Expected behavior**
A properties window should have popped up.

**Screenshots**
Here is an image of the "ghost" windows opened by Process Hacker. Note that nothing happens when I click said windows.
![image](https://user-images.githubusercontent.com/34450360/115162986-e90eab00-a0a6-11eb-9e6d-6da1f81b2ad9.png)

**Version info**
 - OS: Windows 10, 1809 (17763.1879) (LTSC)
 - Process Hacker Version: 3.0.3993 (4cf0bfa)

**Additional Info**
Process Hacker is running as administrator, but this isn't achieved by using Process Hacker's own experimental "Enable start as admin" option.

**Comment by dmex** [comment]
What language are you using for Windows? I haven't been able to reproduce this using English versions.

**Comment by Gladuin** [comment]
> What language are you using for Windows? I haven't been able to reproduce this using English versions.

I am using the Dutch language on Windows.

**Comment by dmex** [comment]
I haven't been able to reproduce any crashes/blank windows with the services dialog

**Comment by masthoon** [comment]
I ran into a similar issue after moving these windows with multiple monitors and switching to a single monitor. To reproduce change the value of Advanced Settings HandlePropertiesWindowPosition for example to -2000,-2000, I fixed it by manually editing Advanced Settings *Position to positives values (like 200,200).

**Comment by Gladuin** [comment]
> I ran into a similar issue after moving these windows with multiple monitors and switching to a single monitor. To reproduce change the value of Advanced Settings HandlePropertiesWindowPosition for example to -2000,-2000, I fixed it by manually editing Advanced Settings *Position to positives values (like 200,200).

This was exactly what happened to me, I used to use two monitors but recently switched to using just a single one. This fixed it for me, thanks a lot!

**Comment by dmex** [comment]
@masthoon 

Thank you for that information! 

I've fixed that issue with some changes that will now check positions are still valid. You won't have that problem in the nightly builds or future versions 👍
