### ISSUE TITLE
CPU Scaling

### ISSUE THREAD

**Issue by mdblack98** [processhacker/processhacker#873]
Could we get auto scaling on the single CPU graph for both system and process performance graphs?
Also would like multi-CPU view on process performance graph if that info is available.
In multi-CPU could autoscale on the biggest graph.

Doing some analysis on software packages I've written and some more visibility on thread behavior and CPU usage (albeit small CPU usage) would be more than nice to have.

Mike

**Comment by dmex** [comment]
> get auto scaling on the single CPU graph

How would you determine the difference between 10% and 100% when one graph was scaled to the same height? I'd have thought the point of having fixed scale was to easily determine the utilization.

> some more visibility on thread behavior and CPU usage

The Threads tab columns would be a lot better for this than using the graphs? For example the nightly builds:

![image](https://user-images.githubusercontent.com/1306177/115432871-39723e00-a24a-11eb-8026-1995d0de834c.png)

**Comment by mdblack98** [comment]
The Threads tab shows cumulative -- I'm interested in real-time.
I would take the multi-CPU view and either put the scale in the graph or maybe just next the "CPU" to tell you the scale for all.Or perhaps let the user choose the scale.  Just need a few scales.
CPU Scale=100%CPU Scale=50%CPU Scale=20%CPU Scale=10%CPU Scale =5%CPU Scale = 2%CPU Scale = 1%




 

    On Tuesday, April 20, 2021, 11:37:17 AM CDT, dmex ***@***.***> wrote:  
 
 



get auto scaling on the single CPU graph


How would you determine the difference between 10% and 100% when one graph was scaled to the same height? I'd have thought the point of having fixed scale was to easily determine the utilization.


some more visibility on thread behavior and CPU usage


The Threads tab columns would be a lot better for this than using the graphs? For example the nightly builds:

**Comment by dmex** [comment]
The latest nightly includes a new `EnableScaleCpuGraph` setting for enabling scaling of the CPU graphs

**Comment by mdblack98** [comment]
Thanks for that....I see the peak is getting labeled to tell the scale....but it gets overwritten by the statistics...Maybe rather than scaling to the peak it could scale say to 50%/25%/10%/5% instead?Then the scale could just be in the upper right corner all the time.



Mike 

    On Sunday, July 25, 2021, 04:52:53 AM CDT, dmex ***@***.***> wrote:  
 
 


The latest nightly includes a new EnableScaleCpuGraph setting for enabling scaling of the CPU graphs

**Comment by dmex** [comment]
> it gets overwritten by the statistics

Options > Graphs > Show Text > untick
