### ISSUE TITLE
processes view has lost all columns after a crash

### ISSUE THREAD

**Issue by mailinglists35** [processhacker/processhacker#874]
**Describe the bug**
yesterday I was using version before 3.0.4000 (i don't know what it was) then app crashed and offered to save a minidump (attached).
[ProcessHacker_QMOFQHWDKDYRLOL_DumpFile.zip](https://github.com/processhacker/processhacker/files/6351023/ProcessHacker_QMOFQHWDKDYRLOL_DumpFile.zip)

After that, restarting the app lost all columns in processes tab. I tried updating which updated to 3.0.4000 but I still have the columns missing. how do I restore them?

**Screenshots**
https://i.imgur.com/fuMqisf.png

**Desktop (please complete the following information):**
 - OS: windows 
 - Version 20h2 19042.928

**Comment by mailinglists35** [comment]
WhoCrashed says this about the system, three hours earlier before PH crash (os is still up, there wasn't any reboot, just a logoff/logon)

On Wed 21.04.2021 00:00:37 your computer crashed or a problem was reported
crash dump file: C:\WINDOWS\LiveKernelReports\win32kbase.sys-20210421-0000.dmp
This was probably caused by the following module: win32kbase.sys (win32kbase!UpdateInputSettingWnfState+0x119) 
Bugcheck code: 0x190 (0x15, 0xFFFFFFFFC0000017, 0x0, 0xFFFFCE8555F340C0)
Error: WIN32K_CRITICAL_FAILURE_LIVEDUMP
file path: C:\WINDOWS\system32\win32kbase.sys
product: Microsoft® Windows® Operating System
company: Microsoft Corporation
description: Base Win32k Kernel Driver
Bug check description: This indicates that Win32k has encountered a critical failure. A live dump is captured to collect the debug information. 
The crash took place in a Microsoft module. Your system configuration may be incorrect. Possibly this problem is caused by another driver on your system that cannot be identified at this time.

**Comment by dmex** [comment]
> minidump (attached)

The build server doesn't save symbols for older versions so I wasn't able to debug this. If it happens again with 3.0.4000 then resubmit the minidump.

> I still have the columns missing. how do I restore them?

It's extremely unusual for the settings file to become corrupted after a crash considering it doesn't get saved after/during crashes... You'll need to re-add the columns manually.

**Comment by mailinglists35** [comment]
>You'll need to re-add the columns manually.

where are these saved? it's a pain to do this manually

**Comment by dmex** [comment]
> where are these saved? it's a pain to do this manually

The settings file is located in `%APPDATA%\Process Hacker\` but since the columns have already reset there isn't anything that can be done - you'll just have to re-add them.

**Comment by mailinglists35** [comment]
great, so deleting `%APPDATA%\Process Hacker\` brought back the default columns
