### ISSUE TITLE
Pcaclient not showing results 

### ISSUE THREAD

**Issue by 637bal** [processhacker/processhacker#876]
Hey, I recently installed process hacker for screensharing requirements in the minecraft server I play on, they check pcaclient and on my search results nothing pops up on the search results. Sometimes it says debug 5000.... something I don't exactly remember but I use my pc on a user side meaning I don't have 1 account on my windows computer I use the 2nd one sooo please give solutions
thanksss
[Search results.txt](https://github.com/processhacker/processhacker/files/6370462/Search.results.txt)

**Comment by dmex** [comment]
You probably need to run PH as administrator otherwise there isn't much else that can be done here.
