### ISSUE TITLE
ProcessHacker and PEView should respect _NT_SYMBOL_PATH environment variable.

### ISSUE THREAD

**Issue by MarekKnapek** [processhacker/processhacker#878]
I'm always frustrated when c:\symbols directory appears on my hard drive and I don't know what program created it.

If ProcessHacker's and/or PEView's symbol path was never configured by user (which is most of the time) and _NT_SYMBOL_PATH environment variable exists, both programs should respect value of this environment variable and do not download symbols into c:\symbols directory.

**Comment by VictorVG** [comment]
Can't build - error C2065: SYMOPT_UNDNAME: undeclared identifier in to .\tools\peview\peprp.c :: 1930 and  .\tools\peview\peprp.c :: 1931

I console write's:

Windows: Windows NT 6.1.7601.0
WindowsSDK: 19041 (16.9.31004.209)
VisualStudio: VisualStudio/16.9.4+31205.134

Building... 3.0.8530.4003 (da968c3) [master]

[00:00] Building ProcessHacker (x32)...
[ERROR]
.\tools\peview\peprp.c(1930,23): error C2065: SYMOPT_UNDNAME: undeclared identifier [.\tools\peview\peview.vcxproj]
.\tools\peview\peprp.c(1931,68): error C2065: SYMOPT_UNDNAME: undeclared identifier [.\tools\peview\peview.vcxproj]

In to newer commit this error is exist and see on Git-ff510355a

**Comment by VictorVG** [comment]
it seems that we are talking about dbghelp.dll parameters, but they are not described and the compiler correctly displays an error

**Comment by VictorVG** [comment]
Ok! Error C2065 is fixed in v3.0.8535.4008 (1048ad2). Big thanks!

**Comment by dmex** [comment]
@VictorVG 

You shouldn't hijack feature request threads for bug reports since you've just spammed this thread with garbage unrelated to the actual feature request... Create a new issue in future.

**Comment by VictorVG** [comment]
Sorry.:( Ok!

**Comment by dmex** [comment]
@MarekKnapek 

I've added support for this in the latest nightly build 👍
