### ISSUE TITLE
In Windows Server 2016, the version numbers of the files are not displayed. 

### ISSUE THREAD

**Issue by pushheap** [processhacker/processhacker#879]
Windows Server 2016, does not show the versions of the files, in the Version column.

When copying the **processhacker.exe.settings.xml** settings from windows 10 to Windows Server, the file versions are not displayed.

Deleting **processhacker.exe.settings.xml** on Windows Server and running Process Hacker again, file versions are not displayed.

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
