### ISSUE TITLE
Exception 0xC0000225 on v3.0.8535.4008 Git-1048ad22 after start on Win7 SP1 x64

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#881]
Exception 0xC0000225 on v3.0.8535.4008 Git-1048ad22 after start on Win7 SP1 x64ю Decode dump screensot:

![ph1](https://user-images.githubusercontent.com/906886/116208441-9d649d00-a749-11eb-8590-526562135801.png)

![ph1-1](https://user-images.githubusercontent.com/906886/116208443-9e95ca00-a749-11eb-8ad4-9ecfd41bf194.png)

![ph1-2](https://user-images.githubusercontent.com/906886/116208446-9e95ca00-a749-11eb-921a-50a5508ab263.png)

![ph1-3](https://user-images.githubusercontent.com/906886/116208447-9e95ca00-a749-11eb-8c1f-2658c37d0dbd.png)

![ph1-4](https://user-images.githubusercontent.com/906886/116208448-9f2e6080-a749-11eb-95ed-65aedb2989dd.png)

![ph1-5](https://user-images.githubusercontent.com/906886/116208450-9f2e6080-a749-11eb-93af-48cd136056f6.png)

![ph2-1](https://user-images.githubusercontent.com/906886/116208452-9fc6f700-a749-11eb-9e2f-f899f436cf3a.png)

![ph2-2](https://user-images.githubusercontent.com/906886/116208454-9fc6f700-a749-11eb-8ff8-665cf1b7f3e0.png)

![ph3-1](https://user-images.githubusercontent.com/906886/116208455-9fc6f700-a749-11eb-83a8-4ab3ad268603.png)

![ph3-2](https://user-images.githubusercontent.com/906886/116208458-a05f8d80-a749-11eb-9b6a-ee5245f29ce5.png)

![ph4-1](https://user-images.githubusercontent.com/906886/116208460-a05f8d80-a749-11eb-8f1d-a521e6d0e3c5.png)

![ph4-2](https://user-images.githubusercontent.com/906886/116208461-a0f82400-a749-11eb-8df6-27cfcb3a03e5.png)

![ph4-3](https://user-images.githubusercontent.com/906886/116208463-a0f82400-a749-11eb-9ecd-a94097fe86f7.png)

**Comment by dmex** [comment]
> Exception 0xC0000225 on v3.0.8535.4008

Crashes can be expected when you build the source. That version doesn't exist and hasn't been released 🤷‍♂️

**Comment by VictorVG** [comment]
Git 5112a29e work w/o problems. Big thanks!
