### ISSUE TITLE
explorer.exe frizzes and restarts after you try to open processhacker using double click on tray icon

### ISSUE THREAD

**Issue by peterek102** [processhacker/processhacker#883]
**Describe the bug**
explorer.exe frizzes and restarts after you try to open processhacker using double click on tray icon

**To Reproduce**
1. Use processhacker-3.0.4021-bin
2. Go to 'tray icon'
2. Double Click on it

**Expected behavior**
Well, I expected processhacker to open :)

**Screenshots**
![image](https://user-images.githubusercontent.com/13313433/116753473-6cb18b80-aa07-11eb-8615-9259efbadcf2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 
 - Version 20H2

**Comment by dmex** [comment]
> explorer.exe frizzes and restarts

Does any other program do this?

**Comment by peterek102** [comment]
I tried to reproduce it after restarting system but with no luck. I'm closing it. If it happens again I will try to gather more details and re-open.
