### ISSUE TITLE
Process disk items are empty when run processhacker with admin right

### ISSUE THREAD

**Issue by lovelifezhenzhen** [processhacker/processhacker#892]
When run processhacker without admin right, disk columns for processes is not empty, and there is no disk info in system information graph;
But when run processhacker with admin right, process disk columns are empty, disk info in system information graph are all zero, is this normal?

**Comment by dmex** [comment]
Is this the nightly or can you upload a screenshot?

**Comment by lovelifezhenzhen** [comment]
May I ask that is admin right needed for displaying both process disk columns and system disk information?

**Comment by dmex** [comment]
> is admin right needed for displaying both process disk columns and system disk information

Yes, administrator is required for disk statistics.

There is one exception in the nightly builds where disk statistics can be shown without administrator but these extensions are experimental and are currently only used without administrator.

**Comment by lovelifezhenzhen** [comment]
Thank you!
When I run latest ProcessHacker on an account without administrator, then process disk columns are still empty.

**Comment by dmex** [comment]
> I run nightly builds on an account without administrator, process disk columns are still empty, do you know the possible reason?

Maybe you're using an unsupported version of Windows 10 or you don't have enough privileges or something corrupted the feature or was disabled by Microsoft in a recent update or some malware/security software is blocking disk statistics?

I haven't seen this problem anywhere else so whatever the reason it's only something on your machine.
