### ISSUE TITLE
The About window is not on top

### ISSUE THREAD

**Issue by err0rsys** [processhacker/processhacker#896]
**Describe the bug**
The About window is not on top the main window, as usual in all applications.

**To Reproduce**
1. Go to Help menu,
2. Click on About item,
3. About window is "hidden" under the main window

**Expected behavior**
About window is on top of the main window.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10 Professional PL

**Additional context**
 - Process Hacker
 - Version: 3.0.4100 (ed9d1bf)

**Comment by dmex** [comment]
Did you by chance enable `View menu > Always on top` ?

**Comment by err0rsys** [comment]
Yes, but I had the same option turned on in version 2.39.124 and the About window was always on the top of the main "Always on Top" window.
You can check it. Enable "Always on top" with version 2.39.124, select About and then install 3.0.4100, and select About again.
Weird?

**Comment by dmex** [comment]
> version 2.39.124

The about window used to be owned/parented to the main window (you couldn't do anything else while it was open) and inherited 'always on top' when it was enabled.

That was changed on Dec 12, 2017 with commit b1e80bc0a4b34330b948e0ef78bb86478e3232c5 which itself was a feature request https://github.com/processhacker/processhacker/issues/201 and the parenting was removed.

The list of windows that need to be updated for 'always on top' are listed here: https://github.com/processhacker/processhacker/issues/200#issuecomment-766674169

**Comment by dmex** [comment]
About window fixed in latest nightly build 👍
