### ISSUE TITLE
RTL_USER_PROCESS_PARAMETERS.CurrentDirectoryPath and RTL_USER_PROCESS_PARAMETERS.CurrentDirectoryHandle Missing.

### ISSUE THREAD

**Issue by time-killer-games** [processhacker/processhacker#901]
You are missing two members of the RTL_USER_PROCESS_PARAMETERS struct.

CurrentDirectoryPath, which is a UNICODE_STRING struct:
https://github.com/time-killer-games/xproc/blob/b759c9d675357bd0ac3f5b0aed1d48f24ac6907b/crossprocess.cpp#L114

CurrentDirectoryHandle, which, (as the name suggests), is a HANDLE:
https://github.com/time-killer-games/xproc/blob/b759c9d675357bd0ac3f5b0aed1d48f24ac6907b/crossprocess.cpp#L115

Noticed you guys have CurrentDirectory, but this is a CURDIR struct, not a UNICODE_STRING struct or HANDLE:
https://github.com/processhacker/phnt/blob/e9c8121f41b00cd24e31eb466c9795785096b764/ntrtl.h#L2550

iirc a long time ago I attempted to include all 3 of these members of the struct in my code and it caused a crash. I'll let you guys figure that out on your own. Anyway that;s why I'm not using the CURDIR typed one in my code, there appears to be some sort of conflict between that and also having the HANDLE and UNICODE_STRING typed CurrentDirectory* members.

You'll notice from my AppVeyor CI output log the Current Working Directory of arbitrary Process ID's is being retrieved ok:
https://ci.appveyor.com/project/time-killer-games/xproc/builds/39324626

--------------------------

Also a bit unrelated but as a side note, do you guys support getting private api process info from a target 64-bit process to a calling 32-bit process and vise versa? I remember reading somewhere MS has no API for going both ways, but specifically only 64-bit -> 32-bit, not 32-bit -> 64-bit. I have a dirty hack as a work around to this issue, that may be able to help you if you are interested, let me know what the status of this is and I'd be tempted to make a pull request or at least file a new suggestion.

**Comment by Biswa96** [comment]
What you are referring as `UNICODE_STRING CurrentDirectoryPath` and `HANDLE CurrentDirectoryHandle` are member of `CURDIR CurrentDirectory`. So, your definition is somewhat different than the actual one.

**Comment by time-killer-games** [comment]
Interest, my mistake, feel free to fill me in on the the last paragraph on this ticket, or at least someone who'd like to, and I'll go ahead and close this.

**Comment by time-killer-games** [comment]
I guess I should've asked you guys for permission before using you code, but whether it's considered substantial in regards to whether i have the rights to change the license of the file it resides in, is up for debate.

My code is licensed under MIT, but this is GPL. GPL only applies to substantial portions of the code, whatever that implies..
https://github.com/time-killer-games/xProcess/commit/d58bd5743f8bbeb2ea32ffc14698386ff49710cb

The above commit is where I added a very small amount of process hacker's source to my project. Some of the struct members were renamed , but that doesn't change much as they do the same thing as before my commit where i got the bulk of this struct from a different code snippet I found that was had no license associated with it. If anyone reading this really wants me to revert that commit, I can -- although again I'm not sure what I did here is necessarily a GPL violation, so I'd like a second opinion before much longer if that's ok.

**Comment by time-killer-games** [comment]
> You should always reference your sources because it shows that you respect the work we put into reversing and maintaining those sources.

I assume this is what you meant for me to do:
- https://github.com/time-killer-games/xproc/blob/c009ca0efea5ca03433b87033fe232eb98066d61/crossprocess.cpp#L97
- https://github.com/time-killer-games/xproc/blob/c009ca0efea5ca03433b87033fe232eb98066d61/crossprocess.cpp#L108

Thank you for all the important info, I really do appreciate it! Of course, I respect the work you all put into this, it was just a bit of oversight and being a bit hasty that lead to my mistake of copy-pasting the code without asking before hand. Thank you!

**Comment by time-killer-games** [comment]
Nice! I appreciate the advice! :D

**Comment by time-killer-games** [comment]
> You can make some functions work this way but you'll never escape the limitations of 32bit so trying to support 64bit types on 32bit is a waste of time.

The nice thing about a 32-bit binary that can read such process information from a 64-bit is compatibility. For instance you may provide a 32-bit executable and regardless of whether it was downloaded onto a 32-bit or 64-bit OS the same binary will work with any process regardless of the target process architecture being 32-bit or 64-bit. Obviously on 32-bit os there is not 64-bit but idk I just support this personally because my project is on a much smaller scale and so it wasn't that difficult to add support for this.

Basically I created a command line executable which prints process information to stdout while preserving the null characters. This exe is embedded within the main one and extracted at runtime to a temp folder. There are two of these executables embedded one 32-bit and the other 64-bit. Depending on the target process architecture determines the exe that gets extracted and run, then the main app reads and parses the output from that.

It runs surprisingly fast. Although it is slower than doing this with with something else like dll injection, but I have no idea how to go about doing that so I stuck with this method. It would be a lot more ambitious to add something like this to your project so you're right it probably would be a waste of time at least in your projects case being a lot larger.
