### ISSUE TITLE
Nightly download 3.0.4110 reported as malware by Firefox and Windows defender

### ISSUE THREAD

**Issue by avih** [processhacker/processhacker#904]
With Firefox 88.01 (up to date release version): try to download the zip file: https://ci.appveyor.com/api/buildjobs/9v6c7idmp8ut88is/artifacts/processhacker-3.0.4110-bin.zip - linked from https://processhacker.sourceforge.io/nightly.php

Firefox doesn't download it, and instead displays a red message at the downloads list "This file contain malware or virus". Clicking "more info" doesn't reveal much (like a link to the source of this assessment), but does allow to download it anyway.

If we override the Firefox warning and download the file anyway, then Windows Defender with "Cloud-delivered Protection" enabled also declares it as "Trojan:Win32/Wacatac.B!ml" (This was tested by another user. I don't have Cloud-delivered Protection enabled, and for me Windows Defender finds it clean).

So the questions:
1. Is this a known issue?
2. Is it known why Firefox and/or Windows Defender declares it as malware?
3. Can this be addressed somehow by the project? (i.e. not by the user overriding the warnings).
4. The "SHA2" (probably should be renamed to "SHA256") at the download page does match - AD50...19E6, but if the sourceforge page can't be trusted, then it's not worth much... though it does look like the link is directly to an appveyor artifact.

**Comment by rstarkov** [comment]
It looks like ProcessHacker has been reported as risky by various vendors for _years_. Very sad.

Many VirusTotal engines started reporting issues between builds 4070 (normal) and 4097 (new positives): [compare](https://github.com/processhacker/processhacker/compare/1a37c73f74c284207270d5630f2c15a7f6b533fc...bd2901ef3f751436b29824e1657976210b9720d5). Too many to pin it on a specific change but if it helps I can try bisect it further, just ping me dmex if you think that's something that would help.

**Comment by Biswa96** [comment]
> It looks like ProcessHacker has been reported as risky by various vendors for years. Very sad.

Can you provide the answer "Why"? Waiting for it many years. There is a discussion about this false positive issue https://github.com/processhacker/processhacker/issues/454.

**Comment by Chaython** [comment]
I was perma banned without warning in Destiny 2[and support only gives automatic rejection] from having process hacker open in tray.
I guess it could be used for cheating, but I wasn't using it, I just have it set to launch at boot.
Other games that dislike it, warn you/stop you from logging in with the offending program open...
It will always get false positives, for the name "hacker", and it  will always trigger "riskware" because it can be used for dumping which could allow password grabbing[etc], stuff should be encrypted in memory but often isn't...

**Comment by rstarkov** [comment]
I was also permabanned from Destiny 2 yesterday, just a few hours after upgrading to build 3.0.4070...

**Comment by Chaython** [comment]
> I was also permabanned from Destiny 2 yesterday, just a few hours after upgrading to build 3.0.4070...

I don't recall which revision it was, it was 44 days ago.

**Comment by Biswa96** [comment]
You guys remind me this post a year ago https://www.zdnet.com/article/uk-police-distance-themselves-from-poster-warning-parents-to-report-kids-for-using-kali-linux/

**Comment by Chaython** [comment]
> Shouldn't this be reported to the game developer?
Ya, I kept trying to contact them, and you just get an automated rejection. I tried messaging staff in linkedin...

**Comment by Onepamopa** [comment]
Kaspersky directly removed ph ... "malware"

**Comment by Chaython** [comment]
> Kaspersky directly removed ph ... "malware"

What version of kaspersky and what process hacker? I've had no issue.

**Comment by Onepamopa** [comment]
> 
> 
> > Kaspersky directly removed ph ... "malware"
> 
> What version of kaspersky and what process hacker? I've had no issue.

Sorry for late reply, I completely uninstalled it yesterday.. I think it was 3.x.
Kaspersky Total Security - 21,3,19,391(b)

**Comment by Onepamopa** [comment]
Sorry for multiple edits, I was collecting info :)

**Comment by Chaython** [comment]
> > > Kaspersky directly removed ph ... "malware"
> Sourceforge has no problems hosting some nasty malicious code...
Source forge has an antivirus, and tells you if there's malware.
Github allows you to upload malware too, it's often used to inspect malware and I've never seen any malware warning, aside from the user's own readme.

**Comment by Chaython** [comment]
> Here's the event log from KTS (translated from Bulgarian, sorry for any inconsistencies with the "default" English translations)
> Event: Detected malicious object
> Component: Program control
> Result: Detected
> Type: Trojan
> Name: Trojan.Win32.Agent.xahvgm
> Threat level: High
> Object path: C:\Program Files\Process Hacker 2
> Object name: ProcessHacker.exe
> Reason: Definitions
> MD5: B365AF317AE730A67C936F21432B9C71


I'm not sure what you downloaded, but Kaspersky client doesn't detect malware, in virustotal however kaspersky does detect it as riskware, which it is.

**Comment by Onepamopa** [comment]
Well, this kaspersky (as in total security) detects it as malware.
What I've downloaded is the release currently listed as "latest" in github (which is quite old).

**Comment by helloitszay** [comment]
yes this has been going on for a long time because of processhackers ability to create new unverified processes it is sadly marked as malware it is a false postive it is safe to download tho :)

**Comment by helloitszay** [comment]
> It looks like ProcessHacker has been reported as risky by various vendors for _years_. Very sad.
> 
> Many VirusTotal engines started reporting issues between builds 4070 (normal) and 4097 (new positives): [compare](https://github.com/processhacker/processhacker/compare/1a37c73f74c284207270d5630f2c15a7f6b533fc...bd2901ef3f751436b29824e1657976210b9720d5). Too many changes to pin it on a specific commit but if it helps I can try bisect it further, just ping me dmex if you think that's something that would help.

yes :(

**Comment by helloitszay** [comment]
if you scan it with mccaffe or avast or something more advanced in terms of malware detection it will scan and mark it as safe

**Comment by Onepamopa** [comment]
Okay so... why is the application not signed? Can't afford a certificate?
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

App: 
processhacker-3.0.4164-setup.exe 
Publisher:  
Unknown publisher

**Comment by TPS** [comment]
Not to just pile on, but MS Edge reports _every single new version_ of PH as dangerous, so I have to `Keep` multiple times on each downloaded update.

Oddly, I think I've only done such w/ MS Defender/Security/whatever 1× & it seems to remember I want it.  Progress?

**Comment by dmex** [comment]
#454

**Comment by Yahyaajbali** [comment]
> if you scan it with mccaffe or avast or something more advanced in terms of malware detection it will scan and mark it as safe

i've had a quite opposite experience, checkpoint harmony detects it as well known malware and it stopped it even before the download is complete, i think it does so because the software is able to control processes and force close them, so for example if a machine has AV and is compromised, the offender can use process hacker to turn off the AV and they will have even more control

**Comment by Masamune3210** [comment]
It cannot do anything you cant do with the tools already built into Windows itself. Demonizing a fancier screwdriver because you can stab someone with it even though you have another screwdriver already sitting on your table is dumb
