### ISSUE TITLE
Get Dave Plummer, the original author of Task Manager, to help you write it.

### ISSUE THREAD

**Issue by gek169** [processhacker/processhacker#909]
Dave Plummer is the original author of Microsoft's Windows Task Manager. He is retired from Microsoft and might be willing to give you advice or tips on integration into Windows.

Contact him: davepl@davepl.com

Legal concerns:

He's retired, and if he had a non-competition clause in his contract, I seriously doubt it's still active. Regardless, you could get tips from him on making Process Hacker integrate better into Windows.

IP concerns:

Not sure. Is this a clean-room project?  

Very unlikely imho. I am not a lawyer, and this is not legal advice, though.

**Comment by jxy-s** [comment]
This is a better topic/discussion for the [forums](https://wj32.org/processhacker/forums/).
