### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by alabotski** [processhacker/processhacker#910]
Is it possible somehow to find out via RSS news that a new version has been released?

https://processhacker.sourceforge.io/nightly.php

**Comment by Biswa96** [comment]
This does the trick for me:

![Capture](https://user-images.githubusercontent.com/31443074/120882856-d705af00-c5f7-11eb-8996-4d291ffd9bc9.PNG)

**Comment by alabotski** [comment]
I want it through RSS

Something like this
https://sourceforge.net/projects/processhacker/rss?path=/

**Comment by dmex** [comment]
https://github.com/processhacker/processhacker/releases.atom

I'll look into updating the tooling for adding a nightly mirror.

**Comment by alabotski** [comment]
As an idea
I do not know if this is realizable

Can I add a snapshots folder here
https://sourceforge.net/projects/processhacker/files/

And I will already subscribe to it using standard sourceforge tools

**Comment by alabotski** [comment]
@dmex Hi any news?)
A couple of days ago a new beta came out

**Comment by alabotski** [comment]
> [processhacker/processhacker/releases.atom](https://github.com/processhacker/processhacker/releases.atom)
> 
> I'll look into updating the tooling for adding a nightly mirror.

Hi. Can you add?

**Comment by dmex** [comment]
> Hi. Can you add?

There's a blocking issue. I don't have an answer yet.

**Comment by dmex** [comment]
@alabotski 

https://github.com/ProcessHackerRepoTool/nightly-builds-mirror/releases.atom

**Comment by Biswa96** [comment]
Separate owner?

**Comment by dmex** [comment]
@Biswa96 

I'm the owner of that account?
