### ISSUE TITLE
When a process is killed, with its Process Properties window open, indicate somehow that the process has died

### ISSUE THREAD

**Issue by stdedos** [processhacker/processhacker#911]
- Stop the "Started" timer?
- Add 💀 somewhere? (https://twemoji.maxcdn.com/2/svg/1f480.svg, source https://emojidictionary.emojifoundation.com/skull)

**Comment by dmex** [comment]
The original 1.x versions would show the exit status in the window title but this was removed for 2.x... I can re-add that feature?

![image](https://user-images.githubusercontent.com/1306177/120934694-c150d080-c742-11eb-8079-b14374eef6f5.png)

**Comment by stdedos** [comment]
> The original 1.x versions would show the exit status in the window title but this was removed for 2.x... I can re-add that feature?
> 
> ![image](https://user-images.githubusercontent.com/1306177/120934694-c150d080-c742-11eb-8079-b14374eef6f5.png)

![image](https://user-images.githubusercontent.com/133706/120943120-a9bf1b00-c735-11eb-9be5-f7a71a0c28d2.png)
much nostalgia 😀

**Comment by dmex** [comment]
@stdedos 

This doesn't help answer the question about porting that feature 😂

**Comment by stdedos** [comment]
Yes, but but ... memes 😢 
And Win XP nostalgia 😕

**Comment by g-yui** [comment]
Good ol' XP, only thing missing from that screenshot is clippy 👀

**Comment by dmex** [comment]
Latest nightly includes the exit status in the window title:

![image](https://user-images.githubusercontent.com/1306177/123523395-971d7d80-d706-11eb-9396-6df1e07af968.png)

**Comment by stdedos** [comment]
"Technically", the 

> * Stop the "Started" timer?

from DoD is missing 😀

But it is good enough otherwise.

**Comment by dmex** [comment]
> Stop the "Started" timer

and show incorrect times?

**Comment by dmex** [comment]
Process started: 7:00 am
Process started time ago: 3 seconds
Process exits
Process started time ago: 3 seconds

leave window open... 

System time: 12:00pm
Process started time ago: 3 seconds

Why stop the timer and show incorrect values?

**Comment by stdedos** [comment]
I was thinking that "Started" timer counts only the time the process was active, not the time since the process started.
i.e. "Started for" not "Started at"

But anyway, that's a very niece situation: you have a Properties window open for X time after a process was killed. Maybe it's not important
