### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by manuclaudioty** [processhacker/processhacker#916]
HELLO !, Good morning, I hope you can attend me, I have a question, I would like to know if the processhacker processes can be remove.

//

¡HOLA!, Buen día, espero que puedan atenderse, Tengo una pregunta, desearía saber si se pueden eliminar los procesos de processhacker. 

(Hope the English translation is fine.)

**Comment by dmex** [comment]
Yes

**Comment by manuclaudioty** [comment]
Hello! Thanks for answering. How can this action be performed?... I have been looking for this information for a long time.

**Comment by dmex** [comment]
If you're trying to uninstall then it's the exact same way as every other application:
https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98

**Comment by manuclaudioty** [comment]
I think you can't understand me, I was referring to how to delete certain processes from the processhacker. It can?

**Comment by dmex** [comment]
> how to delete certain processes

Terminate or delete?

Deleting is outside the scope of what Task Manager software does. You can terminate processes by right-clicking the process:

![image](https://user-images.githubusercontent.com/1306177/122089935-9bb27e00-ce4a-11eb-9194-d1dc724a6236.png)

**Comment by manuclaudioty** [comment]
Hello! I meant if I could delete this (That part was sensed because it is private content)
![unknown](https://user-images.githubusercontent.com/82177951/122124183-8dd20e00-cdf4-11eb-9438-2ccf840fe6d5.jpg)

**Comment by garoto** [comment]
I smell malicious intent.

**Comment by manuclaudioty** [comment]
What do you mean malicious JAJAJAJAJAJA

**Comment by dmex** [comment]
> I meant if I could delete this

PH isn't a tool for deleting history so you should use privacy tools like ccleaner:

https://www.ccleaner.com/ccleaner

**Comment by manuclaudioty** [comment]
Ho! Ok thanks
