### ISSUE TITLE
[Feature request] Add a simple non-graph tray icon option

### ISSUE THREAD

**Issue by not-holar** [processhacker/processhacker#919]
Right now, all the options for a tray icon are graphs. It would be nice if you could have just a simple icon.

**Comment by dmex** [comment]
> It would be nice if you could have just a simple icon.

A simple tray icon already exists?

![image](https://user-images.githubusercontent.com/1306177/122649816-1e9d4680-d173-11eb-9d3b-227ae6d07803.png)

**Comment by not-holar** [comment]
![image](https://user-images.githubusercontent.com/58831297/122688425-ca529f00-d224-11eb-82f3-8722bda3e222.png)
Hmm, i seem to be missing something

**Comment by yfdyh000** [comment]
> ![image](https://user-images.githubusercontent.com/58831297/122688425-ca529f00-d224-11eb-82f3-8722bda3e222.png)
> Hmm, i seem to be missing something

Try the [Nightly Builds](https://processhacker.sourceforge.io/nightly.php).

**Comment by garoto** [comment]
Using `Version: 3.0.4144 (3da6990)` on Windows 8.1 (sort of outdated regarding MS updates), I get a blank icon on my systray when enabling the `static` icon in the view menu:

![screenshot-0708-21-06-2021](https://user-images.githubusercontent.com/11768175/122828329-e5bcb900-d2bb-11eb-895a-07fa4002a441.png)

**Comment by yfdyh000** [comment]
> Using `Version: 3.0.4144 (3da6990)` on Windows 8.1 (sort of outdated regarding MS updates), I get a blank icon on my systray when enabling the `static` icon in the view menu:
> 
> ![screenshot-0708-21-06-2021](https://user-images.githubusercontent.com/11768175/122828329-e5bcb900-d2bb-11eb-895a-07fa4002a441.png)
> 
> Edit: IconCache shenanigans perhaps, but don't think it's related.

I see the same situation, I think this is a bug in the code.

**Comment by garoto** [comment]
> I see the same situation, I think this is a bug in the code.

Windows 8.1 as well? In anycase, if it's indeed a "bug" and if not already fixed in more recent commits, hopefully dmex will have a fix a basic fix or/and a diagnostic.

**Comment by dmex** [comment]
> 3.0.4144

It works on my test machine running 8.1:

![image](https://user-images.githubusercontent.com/1306177/122851650-b016df00-d352-11eb-8478-c1e2dcf2d980.png)

> Windows 8.1 as well? In anycase, if it's indeed a "bug" and if not already fixed in more recent commits, hopefully dmex will have a basic fix or/and a diagnostic.

Did you disable the `View > Refresh automatically` option?

**Comment by yfdyh000** [comment]
3.0.4164 (https://github.com/processhacker/processhacker/commit/b0cd646) on Win10 19043.1052 x64. It offers a blank tray icon for me, and some options (like the CPU history) does not provide the tray icon.

**Comment by dmex** [comment]
@yfdyh000 

You need to delete the `IconGuids` setting so the shell refreshes the icon cache.

**Comment by yfdyh000** [comment]
> @yfdyh000
> 
> You need to delete the `IconGuids` setting so the shell refreshes the icon cache.

It works now. Removed the `IconGuids` line looks not enough, I also removed the `<setting name="ProcessHacker.ExtendedTools.TrayIconGuids">` line make it work, in `AppData\Roaming\Process Hacker\settings.xml` file.

However, I see this is unreliable. Once I enable the CPU usage and the tray static icon, the static icon will become blank, just remove the above lines and re-start the program will not effect unless the static icon is enabled only and then the above lines are removed.
In addition, the tray static icon is presented as a black blank at the beginning of a few seconds when I only the static icon enabled.

**Comment by dmex** [comment]
> Once I enable the CPU usage and the tray static icon, the static icon will become blank, just remove the above lines and re-start the program will not effect unless the static icon is enabled

I don't think it's an issue for the static icon to have a blank background for 1 second at startup. It has to use the existing implementation as the other icons to properly handle event notifications, drawing events, mouse callbacks and plugin event callbacks. 

The alternative is duplicating all that code just to update 1 static icon, 1 second earlier which isn't worth the performance costs.

> the tray static icon is presented as a black blank at the beginning of a few seconds when I only the static icon enabled

I've optimized this case so when the static icon is the one and only icon does it immediately update otherwise if there's multiple icons it'll be delayed until the first interval update to guarantee there isn't any performance costs from the icons during startup.
