### ISSUE TITLE
Give me that sweet Dark Mode!

### ISSUE THREAD

**Issue by 4g0tt3nSou1** [processhacker/processhacker#920]
Simply put, this is my favorite Task Manager tool ever. I install it on every Windows machine I touch.
But man, Every now and again I get blinded by my favorite tool because it is bright as the sun compared to all my other apps!
Please, Bless my eyes with an option to paint it black!

**Describe the solution you'd like**
Literally, just a checkbox to toggle, just color the UI to be darker.

**Describe alternatives you've considered**
None, not really much that can be done here except make this request.

**Additional context*
Doesn't have to be straight black, though AMOLED/OLED Would probably like that.

**Comment by dmex** [comment]
![image](https://user-images.githubusercontent.com/1306177/122656814-810d3b80-d1a1-11eb-9cc2-40680fbba9e2.png)

**Comment by 4g0tt3nSou1** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1306177/122656814-810d3b80-d1a1-11eb-9cc2-40680fbba9e2.png)

Is this on an experimental build? I am on stable latest, and this doesn't exist. Ideally, that's what would be nice to have.

**Comment by TETYYS** [comment]
If you are not on corporate network with enforced antivirus policy or similar, I would recommend nightlies and whitelisting it if AV complains.

**Comment by dmex** [comment]
https://processhacker.sourceforge.io/nightly.php

**Comment by pcroland** [comment]
A bit awkward but I can't find `Enable theme support` anywhere in the `Options`. Can someone tell where is it?

**Comment by dmex** [comment]
@pcroland 

Nightly build?

**Comment by pcroland** [comment]
Oh, I thought it should be in the stable now. Thanks.
