### ISSUE TITLE
Typing to go to the item does not support in column chooser

### ISSUE THREAD

**Issue by yfdyh000** [processhacker/processhacker#921]
**Describe the bug**
The listboxs are set to LBS_OWNERDRAWFIXED, so the WM_CHAR message is no longer working.

**To Reproduce**
1. Right click on the header of the any main lists, and then click the Choose columns menu...
2. Click to focus on the active columns / inactive columns listbox.
3. Try to type the first one letter (or more) of item you want.
4. It is always focused to the first item when you type.

**Expected behavior**
Typing to focus the first item or loop items, support typing one or more letters.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10. 
 - processhacker v3.0.

**Additional context**
- https://docs.microsoft.com/en-us/windows/win32/controls/about-list-boxes#default-window-message-processing
- https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-char
- https://docs.microsoft.com/en-us/windows/win32/api/windowsx/nf-windowsx-listbox_selectstring

**Comment by dmex** [comment]
> Typing to focus the first item or loop items, support typing one or more letters.

Why not use the searchbox above the column chooser?

**Comment by yfdyh000** [comment]
> > Typing to focus the first item or loop items, support typing one or more letters.
> 
> Why not use the searchbox above the column chooser?

Focusing to see is more intuitive from my view. I might be willing to check nearby items if assuming it's not disordered. I also sometimes mind too many results matching from the middle.

**Comment by dmex** [comment]
This was fixed in the latest nightly build 👍
