### ISSUE TITLE
Observation :: Strange crash v3.0.8720.4193 Git-226e3a95 when trying to view any process properties

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#923]
A copy of v3.0.8720.4193 Git-226e3a95 compiled in VC ++ 2019 v16.9.6, when trying to view the properties of any process, silently crashes without having time to display a message about the cause of the crash. After that, only the ghost of the icon of the running copy remains in the tray. Libs. \Tools\thirdparty\bin rebuilt in VC ++ v16.9.6, the compiler did not display assembly errors, the phenomenon got out during testing and is reproduced on two independent machines under Win7 SP1 x64 ...

I will try to update the compiler with what I was pulling because of numerous error messages in version v16.10 - and the code is not going to be assembled, and due to the change of the owner to Administrator in the ACL, the compiler is blocked from launching, and a number of errors of the new VS2019 in the Visual Studio theme at forum.ru-board.com.

**Comment by notes365** [comment]
+1

**Comment by dmex** [comment]
> when trying to view the properties of any process, silently crashes

Fixed in latest nightly

> \Tools\thirdparty\bin rebuilt in VC ++ v16.9.6, the compiler did not display assembly errors, the phenomenon got out during testing and is reproduced on two independent machines under Win7 SP1 x64

You need to update to the latest Visual Studio release or recompile thirdparty using the `\build\thirdparty.cmd` script.

> numerous error messages in version v16.10

What errors?

>  due to the change of the owner to Administrator in the ACL, the compiler is blocked from launching, and a number of errors of the new VS2019 in the Visual Studio theme at forum.ru-board.com.

I tested Windows 7 and works fine:

![image](https://user-images.githubusercontent.com/1306177/123559080-3d3bb700-d7dd-11eb-8060-05a9b683f58d.png)

**Comment by VictorVG** [comment]
v3.0.8722.4195 Git-bde01a2c is OK - does not fall! I didn’t even have to update the compiler, but I’ll use the advice to update - now I’ll look at version 16.10.2 on the test bench. a colleague said that he did not have an update for ChipCAD, but in it they completely rewrote the work of the analyzer of timing diagrams of logic and the block for calculating the impulse currents of circuits and in case of failure I would have to calculate everything manually, that in the current heat it is still a pleasure despite the wide open windows. ..

**Comment by VictorVG** [comment]
It is normally going to 16.9.6, but in 16.10.2 about errors .\Phlib\include\phnativeinl.h (1799.70): Error C2039: "EnableUserShadowStackStRictMode": Not a member "_Process_Mitigation_user_Shadow_Stack_Policy". (Compile source file data.c) despite the recompilation TiRDParty.sln and ChipCAD can't build ...

**Comment by dmex** [comment]
Install the latest SDK

![image](https://user-images.githubusercontent.com/1306177/123628716-c17e5080-d856-11eb-993d-e234fbc83f8c.png)

**Comment by VictorVG** [comment]
Big thanks!

Also in to my post box in to forum.ru-board.com user send new information:

```
For some time now, on VS 2019 PRO (somewhere starting from version 16.10.0), switching between form elements in VB.NET applications stopped working.

I tested it on clean Windows 10 with clean latest studio, even tested it on VS 2022 Pro Preview on Windows 11 - switching doesn't work anywhere.
```
as is ....

**Comment by Biswa96** [comment]
Can we consider 19041 as lates SDK now? Because there is already two new ones out there, 20348 and 22000.

**Comment by dmex** [comment]
> Can we consider 19041 as lates SDK now? 

Yes

> there is already two new ones out there, 20348 and 22000.

Until you can install them via the VS installer they're unreliable and unusable.
