### ISSUE TITLE
Renaming process hacker exe will make the plugins not load.

### ISSUE THREAD

**Issue by Beppe1509** [processhacker/processhacker#926]
**Describe the bug**
When renaming the process hacker exe to something else the plugins wont load.

**To Reproduce**
1. Rename process hacker
2. Run it in the same folder where the plugins are

**Expected behavior**
Process hacker will load the plugins while being renamed

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Comment by dmex** [comment]
Renaming binaries is only currently supported in the nightly builds:
https://processhacker.sourceforge.io/nightly.php
