### ISSUE TITLE
Kaspersky Antivirus detection

### ISSUE THREAD

**Issue by Diicorp95** [processhacker/processhacker#927]
**Describe the bug**
I assume that it's false-positive detection by Kaspersky Antivirus. Someone has added it to database of the antivirus last month.

Update: **I haven't updated it. The antivirus has updated local databases.**

**To Reproduce**
1. Install the program ([release 2.39](https://github.com/processhacker/processhacker/releases/tag/v2.39))
i. It could also be detected until it's installed: binaries or setup file.
2. Run it, if antivirus isn't detected Process Hacker yet.
3. It will be recognized as **Trojan.Win32.Generic**. You'll have a lot of notifications from Kaspersky about its malware activity. The antivirus will even roll back changes of Process Hacker, after question to cure it or not.

**Expected behavior**
Kaspersky Antivirus should not swear to it.

**Screenshots**
Nothing to add here, simply regular antivirus notifications.

**Desktop (please complete the following information):**
Don't think if it makes any sense but here's it:
 - OS: Windows
 - Version NT 6.1

**Comment by Biswa96** [comment]
Would you like to try the nightly version 3.x from here https://processhacker.sourceforge.io/nightly.php

**Comment by Diicorp95** [comment]
> 
> Would you like to try the nightly version 3.x from here https://processhacker.sourceforge.io/nightly.php

I'm not sure about nightly builds.

**Comment by dmex** [comment]
> It will be recognized as Trojan.Win32.Generic

You need to report the issue to kaspersky:
https://support.kaspersky.com/viruses/answers/1870


Alternatively switch to Malwarebytes:
https://www.malwarebytes.com/

**Comment by Diicorp95** [comment]
Thanks!
