### ISSUE TITLE
Focus back on process list from search box by pressing Escape

### ISSUE THREAD

**Issue by supra107** [processhacker/processhacker#928]
This is a very glaring issue I'm experiencing, where I cannot go back to the process list from the search box in any intuitive way. Pressing Ctrl+K to do it is not only unintuitive, but it also simply doesn't work, and while pressing Escape is the most natural thing to do, it closes the window instead of the search box. Simply being able to press Escape while focused on the search box to focus back on the process list would greatly improve keyboard usability of the program.

**Comment by dmex** [comment]
> Simply being able to press Escape while focused on the search box to focus back on the process list would greatly improve keyboard usability of the program

This would also make it easier for script kiddies to automate process termination via the searchbox using sendinput from scripts?

**Comment by supra107** [comment]
I don't think that would make a big difference considering that in such a scenario a script kiddie can already automate everything with a macro to the point where a proper mitigation would involve stripping the program from all keyboard shortcuts, so adding an ability to easily go back to the process list wouldn't impact security but it would improve usability for regular users.

**Comment by dmex** [comment]
> Pressing Ctrl+K

This will re-focus the main window in recent nightly builds. You'll be able to re-bind the hotkey in a future nightly.
