### ISSUE TITLE
Clarification Regarding VirusTotal Scanning

### ISSUE THREAD

**Issue by Still34** [processhacker/processhacker#931]
**Is your feature request related to a problem? Please describe.**
The "Enable VirusTotal scanning" option does not include a description or tooltip describing the feature.

**Describe the solution you'd like**
A tooltip that describes what ProcessHacker would do when the feature is enabled. For example, what data is sent back to VirusTotal. If the data simply includes the hash of the application and does not include the binary, then the tooltip should ideally describe it as such.

**Comment by dmex** [comment]
> A tooltip that describes what ProcessHacker would do when the feature is enabled.

This feature only sends a file hash. Binaries have to be manually uploaded via the Send To menu.

> the tooltip should ideally describe it as such.

VirusTotal support is likely going to get deleted because of their ongoing attacks towards this project.

**Comment by Still34** [comment]
> VirusTotal support is likely going to get deleted because of their ongoing attacks towards this project.
Huh, that's... interesting to know. Alright, I'll take your word for it and not ask too much about it. Thanks.
