### ISSUE TITLE
Help needed - Vc++2019 v16.10.3 or VС++2019 v16.10.4 - .\ProcessHacker\hidnproc.c (1162,37): Error C2065: TraceControlgetTraceGuidList: An undeclared identifier

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#932]
Something I can't work, although at all if it reacted and .\Tools\Thirdparty, and the compiler has updated, but:

run ./build/Build_release.cmd and see:

Windows: Windows NT 6.1.7601.0
WindowsSdk: 19041 (16.10.31205.252)
VisualStudio: VisualStudio / 16.10.3 + 31424.327

Building ... 3.0.8749.4222 (0CAB0DC) [Master]

[00:00] Building ProcessHacker (x32) ...
[Error] (1) .\ProcessHacker\hidnproc.c (1162,37): Error C2065: TraceControlgetTraceGuidList: An undeclared identifier [.\ProcessHacker\ProcessHacker.vcxproj]

Windows: Windows NT 6.1.7601.0
WindowsSdk: 19041 (16.10.31205.252)
VisualStudio: VisualStudio / 16.10.4 + 31515.178

Building ... 3.0.8750.4223 (B149DE7) [Master]

[00:00] Building ProcessHacker (x32) ...
[Error] (1).\ProcessHacker\hidnproc.c (1162,37): Error C2065: TraceControlgetTraceGuidList: An undeclared identifier [.\ProcessHacker\ProcessHacker.vcxproj]

Windows: Windows NT 6.1.7601.0
WindowsSdk: 19041 (16.10.31205.252)
VisualStudio: VisualStudio / 16.10.4 + 31515.178

Building ... 3.0.8752.4225 (EE19FB0) [Master]

[00:00] Building ProcessHacker (x32) ...
[Error] (1).\ProcessHacker\hidnproc.c (1162,37): Error C2065: TraceControlgetTraceGuidList: An undeclared identifier [.\ProcessHacker\ProcessHacker.vcxproj]

That's  see for fix or update in to my system?

**Comment by VictorVG** [comment]
I check compiller and add toolkit - SDK 10.19041 exist, but .... ????
```
Windows: Windows NT 6.1.7601.0
WindowsSdk: 19041 (16.10.31205.252)
VisualStudio: VisualStudio / 16.10.4 + 31515.178

Building ... 3.0.8752.4225 (EE19FB0) [Master]

[00:00] Building ProcessHacker (x32) ...
[Error] (1).\ProcessHacker\hidnproc.c (1162,37): Error C2065: TraceControlgetTraceGuidList: An undeclared identifier [.\ProcessHacker\ProcessHacker.vcxproj]
```
????

**Comment by Biswa96** [comment]
It was changed in this commit https://github.com/processhacker/processhacker/commit/2e45f7e888ce27eaf0b651a05c8cc1ca9128e097

**Comment by VictorVG** [comment]
@Biswa96

Yes, I find changes use diff Git 32e1614b - _master_ :) and try change hidnproc.c :: string 1162 : 

old:
```
    status = PhTraceControl(
        TraceControlGetTraceGuidList,
        NULL,
```
new:
```
    status = PhTraceControl(
        TraceControlEnumTraceGuidList,
        NULL,
```
then test build use ./buid/build_release.cmd:

![1](https://user-images.githubusercontent.com/906886/126736299-571d37c5-8663-478f-920a-8ce0807e7d3c.png)

but not check for work...

P.S.

https://github.com/processhacker/processhacker/blob/master/ProcessHacker/hidnproc.c string 1162 have old code ....

**Comment by VictorVG** [comment]
I test this fix - work success, also I fix build and for [**MemoryExtPlugin**](https://github.com/processhacker/plugins-extra/issues/90) (patch for pfn.c).
