### ISSUE TITLE
Error C2065: TraceControlgetTraceGuidList: An undeclared identifier

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#933]
Error C2065: TraceControlgetTraceGuidList: An undeclared identifier

**To Reproduce**

Just build project

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. Vista]

**Additional context**

**Comment by Biswa96** [comment]
Duplicate of previous issue https://github.com/processhacker/processhacker/issues/932

**Comment by VictorVG** [comment]
And fixed it :)
