### ISSUE TITLE
[Feature Request] Middle-clicking a process should select all its "peers"

### ISSUE THREAD

**Issue by Yaron10** [processhacker/processhacker#938]
**Is your feature request related to a problem? Please describe.**
I often use the great new feature [ToolStatus: Add working set for selected processes](https://github.com/processhacker/processhacker/commit/5a7672788811daebb35516ce81a021d6fdca6567) (thanks again! 👍) for summing up the total WS of a program running multiple processes.

I need to manually select all those processes.

**Describe the solution you'd like**
Middle-clicking a process should select all its "peers". 
That is: middle-clicking `firefox.exe` should select all processes with the same name.

Thank you.

**Comment by Yaron10** [comment]
@dmex,

May I ask what you think of this suggestion?
I just want to know if I should be looking forward to the implementation.

Thank you.

**Comment by Yaron10** [comment]
@TheEragon,

Could you please have a look at this request? - I'd appreciate it.

**Comment by TheEragon** [comment]
I can certainly look at this if I find some time, but @dmex should first approve such change. he is the owner of this project.

**Comment by Yaron10** [comment]
@TheEragon,
Thank you. Much appreciated.

@dmex,
I assumed you were busy and this feature should be very useful for me (and probably many other users).
Could you approve and assign it to @TheEragon?

Thank you for your great work.

**Comment by dmex** [comment]
> middle-clicking firefox.exe should select all processes with the same name.
>  @dmex should first approve such change

@TheEragon Why my approval? 😂I might be the current maintainer but never used to be. You or anyone else can become the maintainer just by showing initiative and being self assertive. You don't need permission, act like the boss, you want something then make the changes. If you're consistent enough then you'll be given an official role like any other project 👍

> I assumed you were busy and this feature should be very useful for me (and probably many other users).

I personally feel using the existing feature when holding shift/control to select multiple items is what you should be using? The majority of people on Windows are accustomed to holding down shift/control when selecting multiple items, using mouse3 wouldn't be getting used very often so the changes might not be useful? I'm not sure so just been waiting for more comments/feedback.

**Comment by TheEragon** [comment]
> @TheEragon Why my approval? 😂I might be the current maintainer but never used to be. You or anyone else can become the maintainer just by showing initiative and being self assertive. You don't need permission, act like the boss, you want something then make the changes. If you're consistent enough then you'll be given an official role like any other project 👍

Because I didn't feel like making a major GUI design change is my call :)

> I personally feel using the existing feature when holding shift/control to select multiple items is what you should be using? The majority of people on Windows are accustomed to holding down shift/control when selecting multiple items, using mouse3 wouldn't be getting used very often so the changes might not be useful? I'm not sure so just been waiting for more comments/feedback.

Agreed, I was thinking about introducing a key shortcut to select process sub tree rather, maybe CTRL+T? What do you guys thinking about that?

**Comment by Yaron10** [comment]
@dmex & @TheEragon,

Thank you both for the detailed replies. I appreciate it.

> The majority of people on Windows are accustomed to holding down shift/control when selecting multiple items...

> Agreed, I was thinking about introducing a key shortcut to select process sub tree rather, maybe CTRL+T? What do you guys thinking about that?

Yes, middle-clicking is a bit unconventional. I actually expected a "frowning" response. :)

But - I'm a "mouse-oriented" user and middle-clicking should be much more convenient for me.
Currently there's no action assigned to middle-clicking. Would it require a lot of code? Would you consider it a bloat?

***
@g-yui & @DerekZiemba,

Thanks for the thumbs-up. I'd appreciate your input.

**Comment by TheEragon** [comment]
I must be blind but I can't find a way to close this :)

**Comment by Yaron10** [comment]
@TheEragon,

Thank you very much for your work. Highly appreciated.

@dmex,

Thank you for approving and merging. Much appreciated.
