### ISSUE TITLE
"Start type" column on "Services" tab doesn't update on refresh after external changes

### ISSUE THREAD

**Issue by enervated** [processhacker/processhacker#939]
I'm running Process Hacker 3.0.4234 (f3f6ced) on Win10 Pro 21H1.

Example scenario: If a service is disabled and stopped and then is enabled and started _outside of PH_, the "Status" column for that service will update in PH, but the "Start type" column will not update unless the applicable service properties are opened and then closed.

**Comment by dmex** [comment]
You need to enable the `EnableServiceNonPoll` setting... Other people complained about 0.01-0.02 CPU usage when non-polling was enabled, so its disabled by default and unfortunately sometimes the service information doesn't get updated in some cases. 

Enabling `EnableServiceNonPoll` should resolve all issues with UI updating after changing configuration when using third party applications.
