### ISSUE TITLE
Chrome says that the downloaded file is a virus...?

### ISSUE THREAD

**Issue by mndudek** [processhacker/processhacker#940]
I tried to download the installer and Chrome deleted it saying it has a virus in it.

**Comment by Biswa96** [comment]
Then don't use Chrome 😁

**Comment by dmex** [comment]
This is part of Microsoft's ongoing campaign to destroy the project before anti-trust investigations by claiming the project is malicious #454 

Chrome forwards the results provided by Microsoft Defender so use a different product: https://www.malwarebytes.com/
