### ISSUE TITLE
What is virtualization?

### ISSUE THREAD

**Issue by Tima32** [processhacker/processhacker#942]
When right-clicking the mouse, a pop-up menu appears, in which there is a "Virtualization" drain. What is it, and where can you read about it?
![00000](https://user-images.githubusercontent.com/55636583/127744749-ccb80cec-21cf-423b-85f5-4788cda73670.jpg)

**Comment by diversenok** [comment]
It is a compatibility feature of User Account Control designed to help running legacy applications. You know how non-administrative programs cannot write to locations such as Program Files of HKLM, right? Some old programs were designed without these restrictions in mind, so they try doing that and fail. Virtualization transparently redirects such operations to writable per-user locations. For a process with enabled virtualization, it appears that it can write to such places, but in reality, the changes get saved under `C:\Users\%USER%\AppData\Local\VirtualStore` or `HKCU\Software\Classes\VirtualStore`.

You can find more details here: [How User Account Control works](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/how-user-account-control-works#virtualization).

**Comment by Tima32** [comment]
Thanks for the answer.
