### ISSUE TITLE
error C2011: _SYSTEM_SUPPORTED_PROCESSOR_ARCHITECTURES_INFORMATION: redefinition struct . Build errors 

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#946]
error C2011: _SYSTEM_SUPPORTED_PROCESSOR_ARCHITECTURES_INFORMATION:
Struct redefinition

**Comment by dmex** [comment]
https://github.com/processhacker/processhacker/commit/d91f208324b5bae75d0c9c598622317054c98b5a
