### ISSUE TITLE
no help menu

### ISSUE THREAD

**Issue by NeonSpaceTurtle** [processhacker/processhacker#947]
With a program so complicated that claims to make everything easier you'd think it comes a doc... The help dropdown menu has 5 options and none of them are actual help.

**Comment by dmex** [comment]
> With a program so complicated that claims to make everything easier you'd think it comes a doc

The intended users are developers and power users who already know what everything does.

> The help dropdown menu has 5 options and none of them are actual help.

What's wrong with asking here on github for help?

**Comment by fade2gray** [comment]
There is a [forum](http://forum.cheatengine.org/) link on the CE homepage - so, why is it people can't ask their general questions there and leave GitHub just for bug reports and the real issues?

Every day, I get a shed load of email notifications - "I can't download CE", "I can't install CE", etc., etc.

**Comment by dmex** [comment]
@fade2gray 

What is CE? That's not our forum link... This is the Process Hacker github.

Anyone can post questions as an issue here or the discussion section and we encourage it?
https://github.com/processhacker/processhacker/discussions

**Comment by fade2gray** [comment]
@dmex Ignore me -I'm a right plum posting in the wrong repo. 🙄

**Comment by NeonSpaceTurtle** [comment]
I really don't think explaining the meaning of colors in the application should require posting on github or even opening any external resources lol. Every program worth their two cents have a doc. Don't be that lazy dev that won't explain how any of it works because "it's targeted for 1334 haxors"

**Comment by dmex** [comment]
> explaining the meaning of colors in the application should require posting on github or even opening any external resources

You can hover the mouse over the color settings to see a description of what the colors mean:

![image](https://user-images.githubusercontent.com/1306177/130157903-9910efe4-87eb-4253-bbb9-f1e5468ee077.png)

**Comment by NeonSpaceTurtle** [comment]
I looked for such a menu and didn't find it. It would make sense to have it explained in the help section, I supposed you needed to dig in settings to find it.
