### ISSUE TITLE
Incorrect Image Base for 32-bit images on 64-bit version of Process Hacker

### ISSUE THREAD

**Issue by reubensammut** [processhacker/processhacker#950]
**Describe the bug**
When viewing an image properties for a 32-bit image (both EXEs and DLLs) on a 64-bit version of Process Hacker, the Image Base address is incorrect. The displayed value is the actual image base address (`ImageBase`) concatenated with the base of data element (`BaseOfData`) of `ntdll!_IMAGE_OPTIONAL_HEADER`. 

**To Reproduce**
1. Open 64-bit version of Process Hacker
2. Identify a 32-bit process running (or launch a new one) and double click it in Process Hacker 
3. Go to the Modules tab
4. Double click on any loaded module
5. The incorrect value is displayed in Image Base

**Expected behavior**
For 32-bit images, only 1 DWORD should be loaded for the Image Base (offset 0x1c from ntdll!_IMAGE_OPTIONAL_HEADER)

**Screenshots**
![image](https://user-images.githubusercontent.com/760324/129954941-b4b977c1-d3cc-43c2-839c-13697afc6277.png)
Selecting 32-bit process on a 64-bit version of Process Hacker

![image](https://user-images.githubusercontent.com/760324/129954615-208f5095-fb39-4fe3-998b-bd7bd826fe31.png)
Incorrect image base address 

![image](https://user-images.githubusercontent.com/760324/129956116-2bd5bcdc-79bd-4143-b548-61a84d9a277e.png)
Correct values as per Windbg

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Server 2019

**Comment by dmex** [comment]
Can you check if this is still an issue in the nightly builds? 

Peviewer was completely redesigned and rewritten some time ago:
https://processhacker.sourceforge.io/nightly.php

**Comment by reubensammut** [comment]
Hi @dmex,

Just checked the nightly build and it is correct in both the General and the Headers tabs. Really cool new Peviewer! Any ideas when this will be integrated into the stable release? 
![image](https://user-images.githubusercontent.com/760324/130040645-9607b1b2-d34b-4638-89d3-24fb61c94d17.png)
![image](https://user-images.githubusercontent.com/760324/130041017-bc6edea5-3997-44fc-b919-6ea0f151b1ec.png)

Also, as a small suggestion, I would add BaseOfData in the Headers tab for completeness sake. 

Thanks

**Comment by garoto** [comment]
> integrated into the stable release?

There won't be any "stable" v3.x release for quite sometime from what I gathered browsing this issue tracker:

https://github.com/processhacker/processhacker/issues/649
https://github.com/processhacker/processhacker/issues/415

**Comment by jxy-s** [comment]
`BaseOfData` does exist, but it is commented out for 64 bit images right now (https://github.com/processhacker/processhacker/blob/master/tools/peview/peheaderprp.c#L625). I'm not sure why, @dmex could probably answer that.

@reubensammut since this is resolved in the nightly we could probably close this out.

**Comment by dmex** [comment]
> I would add BaseOfData in the Headers tab for completeness sake.

It was added for 32bit images in the latest nightly build. jxy-s is correct that it doesn't exist for 64bit images.
