### ISSUE TITLE
FilaName is not a member of error C2039

### ISSUE THREAD

**Issue by Avtroman** [processhacker/processhacker#953]
2>D:\000\processhacker-master\ProcessHacker\thrdstk.c(1317,37): error C2039: "FileName": не является членом "<unnamed-tag>".
2>D:\000\processhacker-master\ProcessHacker\include\phplug.h(268): message : см. объявление "<unnamed-tag>"
2>D:\000\processhacker-master\ProcessHacker\thrdstk.c(1322,48): error C2039: "FileName": не является членом "<unnamed-tag>".
2>D:\000\processhacker-master\ProcessHacker\include\phplug.h(268): message : см. объявление "<unnamed-tag>"
2>D:\000\processhacker-master\ProcessHacker\thrdstk.c(1381,37): error C2039: "FileName": не является членом "<unnamed-tag>".
2>D:\000\processhacker-master\ProcessHacker\include\phplug.h(268): message : см. объявление "<unnamed-tag>"
2>D:\000\processhacker-master\ProcessHacker\thrdstk.c(1386,48): error C2039: "FileName": не является членом "<unnamed-tag>".
2>D:\000\processhacker-master\ProcessHacker\include\phplug.h(268): message : см. объявление "<unnamed-tag>"

**Comment by VictorVG** [comment]
1) https://github.com/processhacker/processhacker/issues/952
2) Fixed

А с DotNetTools - соберётся, проверю, но там вроде должно поправится...
