### ISSUE TITLE
Fix typo in source v3.0.8815.4288 Git-d4931074 - fix build filure of DotNetTools plug-in

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#954]
I try fix C2065 then build DotNetTools plug-in:
```
[ERROR] (1) .\plugins\DotNetTools\asmpage.c(1293,102): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]
.\plugins\DotNetTools\main.c(137,44): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]
.\plugins\DotNetTools\treeext.c(255,49): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]
```
my fix - just replace `PH_CLR_JIT_PRESENT` up to ` PH_CLR_CORELIB_PRESENT` in to this strings and build is success.

Updated source files asmpage.c , main.c , treeext.c in to archive [**DotNetTools.zip**](https://github.com/processhacker/processhacker/files/7025060/DotNetTools.zip)

**Comment by VictorVG** [comment]
I try test updated plug-in - work success.

**Comment by dmex** [comment]
>  just replace PH_CLR_JIT_PRESENT up to PH_CLR_CORELIB_PRESENT in to this strings and build is success

No. The entire implementation has changed so don't 'replace' flags with other flags.

**Comment by VictorVG** [comment]
Understood. I thought you just renamed the flags. Now I will rebuild and see what will come out at the stand.

**Comment by VictorVG** [comment]
W/o fix DonNetTools build is failure...

**Comment by dmex** [comment]
> W/o fix DonNetTools build is failure...

Yes

**Comment by VictorVG** [comment]
Ok, I wait...

**Comment by VictorVG** [comment]
I apologize, but at the moment on version v3.0.8825.4298 (13Ad82D), the assembly of this plugin fails with ERROR C2065: Ph_CLR_JIT_PRESENT: undeclared Identifier in to:

Windows: Windows NT 6.1.7601.0
WindowsSDK: 20348 (16.11.31603.221)
VisualStudio: VisualStudio/16.11.1+31613.86

Building... 3.0.8825.4298 (13ad82d) [master]

```
[00:00] Building ProcessHacker (x32)...
[01:08] Building ProcessHacker (x64)...
[02:14] Building Plugins (x32)...
[ERROR] (1) .\plugins\DotNetTools\asmpage.c(1293,102): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]
.\plugins\DotNetTools\main.c(137,44): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]
.\plugins\DotNetTools\treeext.c(255,49): error C2065: PH_CLR_JIT_PRESENT: undeclared identifier [.\plugins\DotNetTools\DotNetTools.vcxproj]

```

**Comment by dmex** [comment]
Yep.

**Comment by VictorVG** [comment]
It seems that the Warriarant that I try collecting and the plugin works - in Far Manager I was covered .iso image in which Far calls the .NET subplacin of its OBServer plugin, and visually compared the output on the DotnetTools plugin tabs - it seems the same, it can use the proposed patch if not need the plugin alteration?

![Compare](https://user-images.githubusercontent.com/906886/130787265-3591687b-2e5d-4373-bd40-3431aa305a4d.png)

![compare2](https://user-images.githubusercontent.com/906886/130787270-e8930d36-3cbb-4b12-b46f-4cf3ce41ed95.png)

**Comment by dmex** [comment]
> visually compared the output on the DotnetTools plugin tabs - it seems the same, it can use the proposed patch

Nope.

**Comment by VictorVG** [comment]
Need something different?

**Comment by dmex** [comment]
No. You need to wait for the update.

**Comment by VictorVG** [comment]
Yes, i see. Big thanks!
