### ISSUE TITLE
The latest version starts to crash

### ISSUE THREAD

**Issue by inaryart** [processhacker/processhacker#958]
**Describe the bug**
dump file:
[ProcessHacker.exe.16536.zip](https://github.com/processhacker/processhacker/files/7027621/ProcessHacker.exe.16536.zip)

**To Reproduce**
Just start it

**Expected behavior**
everything is ok
**Screenshots**
na

**Desktop (please complete the following information):**
 -  10.0.19042.985

**Additional context**
na

**Comment by inaryart** [comment]
No, I no longer crash immediately after restarting, but once my machine runs for too long, it crashes again.. here are the three recent crashes:
[CrashDumps.ZIP](https://github.com/processhacker/processhacker/files/7070092/CrashDumps.ZIP)

**Comment by dmex** [comment]
Try updating to the latest nightly build r4330

If it crashes again, there's a new button for 'NormalDump' which you can upload that will include filenames causing the crash.

**Comment by inaryart** [comment]
No buttons appear when it crashes.you can send the debug version here so that you can analyze the reason more easily
[CrashDumps.zip](https://github.com/processhacker/processhacker/files/7106614/CrashDumps.zip)

**Comment by dmex** [comment]
> No buttons appear when it crashes

How are you generating these dump files without the exception dialog?

**Comment by inaryart** [comment]
Yes, it is captured by the system. In the `C:\Users\user\AppData\Local\CrashDumps\` directory
