### ISSUE TITLE
dll

### ISSUE THREAD

**Issue by Drkalleheds** [processhacker/processhacker#959]
when i inject the dll into my game nothing happens but when my friends does it with the exact same dll it happen things

**Comment by dmex** [comment]
> for my friends it works completely fine

No idea. Your friends might be pulling your leg... That feature was never designed for cheating and as such games very easily detect that feature and disable it.

> i inject the dll into my game

Process Hacker is not designed to bypass anti-cheat. So you'll get banned almost instantly trying to use it that way... Ask whomever created that DLL for some other tool.

**Comment by Drkalleheds** [comment]
the discord they had is gone and my friends isn't pulling my leg i was at his place but i will just figure it out myself

**Comment by dmex** [comment]
The game is probably blocking it or you haven't installed the vcredist runtime from MS.

**Comment by Drkalleheds** [comment]
where do i download th vcredist?


Den mån 23 aug. 2021 kl 17:15 skrev dmex ***@***.***>:
