### ISSUE TITLE
Crash due to 75b931fcbcd6dcd3e107a338bda2c68571051fa9

### ISSUE THREAD

**Issue by xnoreq** [processhacker/processhacker#960]
**Describe the bug**
Starting PH as administrator, clicking the main menu bar causes a crash.
Starting PH as administrator, pressing Ctrl+F causes a crash.

**Desktop (please complete the following information):**
 - Win 10 Pro x64, 19043.1165

**Additional context**
Reverting only 75b931fcbcd6dcd3e107a338bda2c68571051fa9 fixes the crash.

**Comment by dmex** [comment]
> Reverting only 75b931f fixes the crash

I haven't checked in all the files for those features yet. Keep using the older revision for now, I'll fix the build issues this week.

**Comment by VictorVG** [comment]
Duplicate Issues #944 , and fixed in to v3.0.8817.4290 Git e068524d .
