### ISSUE TITLE
Process filter changed

### ISSUE THREAD

**Issue by nekret** [processhacker/processhacker#961]
One of our technicians noticed they could no longer filter by username in the process list.

Doing a little digging I found this commit that looks like it may have been disabled.
https://github.com/processhacker/processhacker/commit/db118b735ffb0d414d26b70a2b17975abe94f4db

Is there any way we could get this back or an option to turn it back on?

**Comment by dmex** [comment]
>  I found this commit

The commits prior changed the structure layout and broke the search... I forgot to re-enable the filter once that was fixed.

Good catch, I'll be fixed in the next nightly build👍
