### ISSUE TITLE
DLL INJECTION SHOW

### ISSUE THREAD

**Issue by MakeTesterX** [processhacker/processhacker#965]
Hi guys I'm here to ask you a question, is there any way to see the dlls that injecti?

**Comment by jxy-s** [comment]
@MakeTesterX it is really hard to directly answer your question. It is quite a broad one. There are a number of injection techniques to get code executing in a target process (even some that don't even involve a module "DLL" being loaded).

From a "what DLL shouldn't be here" perspective, a trivial approach: If you have a list of modules you expect to be loaded (e.g. known imports and all dependencies of those modules) you could then compare the modules that are loaded in the process to that list. But this is just the tip of the iceberg. You won't find a complete solution to your problem in Process Hacker, but it may be a tool to aid your investigations on this topic.

Finally, the issue tracker is for reporting bugs or feature requests - not for generic questions. Please refrain from using it as such in the future 😄.
