### ISSUE TITLE
Strings are suddenly messing up in the recent versions

### ISSUE THREAD

**Issue by egortech** [processhacker/processhacker#968]
**Describe the bug**
Process Hackers suddenly start to display corrupted strings in main windows and some other windows. I don't know what causes this problem right now.  Restarting the application fixes the problems.

**To Reproduce**
Unknown

**Expected behavior**
Process Hacker should display text correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/13813684/131190649-b42c9a67-87fe-4704-b0a6-32ec9b008ea2.png)

![image](https://user-images.githubusercontent.com/13813684/131190973-5e5ae686-8007-4d0c-891e-801bf91f5872.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Version 10.0.22000.168
 - Process Hacker Version 3.0.4306

**Additional context**
Problems occur at least of the previous two Process Hackers and preview OS builds. I think that the custom font that I selected cause this problem. At least only text with this font (Cascadia Code) messed up.

**Comment by dmex** [comment]
I can't reproduce any problems with that font.
