### ISSUE TITLE
Please, help me: v3.0.8836.4309 (b04da3f) - v3.0.8839.4312 (54c15f0) build filed in to .\phlib\emenu.c(475,75): error C2065: PhThemeWindowForegroundColor: undeclared identifier

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#971]
Windows: Windows NT 6.1.7601.0
WindowsSDK: 20348 (16.11.31603.221)
VisualStudio: VisualStudio/16.11.1+31613.86

Building... 3.0.8836.4309 (b04da3f) [master]

[00:00] Building ProcessHacker (x32)... [ERROR] (1) .\phlib\emenu.c(475,75): error C2065: PhThemeWindowForegroundColor: undeclared identifier [.\phlib\phlib.vcxproj]

grep find:
```
.\phlib\emenu.c

475:                themeBrush = CreateSolidBrush(PhThemeWindowForegroundColor); // LEAK (dmex)

.\phlib\theme.c

175:COLORREF PhThemeWindowForegroundColor = RGB(28, 28, 28);
547:        themeBrush = CreateSolidBrush(PhThemeWindowForegroundColor);
2345:                                SetDCBrushColor(hdc, PhThemeWindowForegroundColor);

```
but

Windows: Windows NT 6.1.7601.0
WindowsSDK: 20348 (16.11.31603.221)
VisualStudio: VisualStudio/16.11.1+31613.86

Building... 3.0.8839.4312 (54c15f0) [master]

[00:00] Building ProcessHacker (x32)...
[ERROR] (1) .\phlib\emenu.c(475,75): error C2065: PhThemeWindowForegroundColor: undeclared identifier [.\phlib\phlib.vcxproj]

May be declared "PhThemeWindowForegroundColor" in phlib\include\emenu.h similar to the ad in phlib\theme.c ?

**Comment by VictorVG** [comment]
Ok, I wait

**Comment by dmex** [comment]
It was already fixed?

**Comment by VictorVG** [comment]
Yes! Big thanks! v3.0.8842.4315 Git-e37bb696 build and work is success.
