### ISSUE TITLE
In the Services tab, cannot change a service's startup type

### ISSUE THREAD

**Issue by skycommand** [processhacker/processhacker#989]
**Describe the bug**
Process Hacker's main UI has several tabs: Processes, Services, Network, Disk, and Firewall. In the Services tab, Process Hacker lists Windows services and allows the user to change their configuration, e.g. their startup type, recovery actions, and triggers.

As of the latest nightly build, 3.0.4351, it no longer saves changes to the startup type of a Windows service.

**To Reproduce**
1. Open Process Hacker
2. Go to the Services tab
3. Pick a random service and take note of its "Start type" column. In this example, I'd pick `wuauserv` (Windows Update) whose "Start type" is "Demand start (trigger)".
4. Double click on `wuauserv`.  The "wuauserv Properties" dialog box shows up.
5. Change the "Start type" to Disabled.
6. Click OK.

**Expected behavior**
The "Start type" column of the Windows Update service must now say "Disabled."

**Actual behavior**
Nothing happens

**Screenshots**
N/A

**Desktop**
 - OS: Windows 10
 - Version: 21H1 (19043.1165)

**Additional context**
N/A

**Comment by dmex** [comment]
> no longer saves changes to the startup type

Fixed in the latest nightly build 👍
