### ISSUE TITLE
QUESTION - VC++2019 v16.11.2 : v3.0.8887.4360 Git-4a247ea0 - something does not work out assembly x86-64. Maybe I'm missing something?

### ISSUE THREAD

**Issue by VictorVG** [processhacker/processhacker#990]
Build log for CustomBuildTools if rebuild  .\tools\thirdparty\thirdparty.sln :

> Windows: Windows NT 6.1.7601.0
> WindowsSDK: 20348 (16.11.31603.221)
> VisualStudio: VisualStudio/16.11.2+31624.102
> 
> Building... 3.0.8887.4360 (4a247ea) [master]
> 
> [00:00] Building ProcessHacker (x32)... OK
> [00:56] Building ProcessHacker (x64)... ERROR
> 
> [Error] (1) phlib.lib (PCRE2_STUDY.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (PCRE2_NEWLINE.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (PCRE2_EXTUNI.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (PCRE2_COMPILE.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (pcre2_auto_possess.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (MXML-Private.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (MXML-Node.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (MXML-File.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (MXML-ATTR.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (printbuf.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (linkhash.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (json_tokener.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (json_object.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\ProcessHacker\ProcessHacker.vcxproj]
> phlib.lib (TLSH_WRAPPER.OBJ): Error LNK2047: The module comprises processing errors (EH) C++ or complex EH metadata, but it is not compiled using /Guard:EHCONT. [.\Tools\peview\peview.vcxproj]
> phlib.lib (TLSH_WRAPPER.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (TLSH_IMPL.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (fuzzy.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (MXML-Private.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (MXML-Node.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (MXML-File.Obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (MXML-ATTR.OBJ): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> phlib.lib (linkhash.obj): Warning LNK4291: The module may contain "__except" (structured exception handling), but it is not compiled using /Guard:EHCONT; Conservative metadata will be created. [.\Tools\peview\peview.vcxproj]
> .\Bin\release64\peview.exe: Fatal Error LNK1386: Failed to create metadata for some modules that are not compiled using /Guard:EHCONT; Use /Force:Guardehcont for forced layout. [.\Tools\peview\peview.vcxproj]

I try revert rebuild - x86 can't build:

> Windows: Windows NT 6.1.7601.0
> WindowsSDK: 20348 (16.11.31603.221)
> VisualStudio: VisualStudio/16.11.2+31624.102
> 
> Building... 3.0.8887.4360 (4a247ea) [master]
> 
> [00:00] Building ProcessHacker (x32) ...
> [ERROR] (1) hashprp.obj: error LNK2001: unresolved external symbol _PvGetTlshBufferHash@12. [.\tools\peview\peview.vcxproj]
> hashprp.obj: error LNK2001: unresolved external symbol _fuzzy_hash_file@8. [.\tools\peview\peview.vcxproj]
> hashprp.obj: error LNK2001: unresolved external symbol _PvGetTlshFileHash@8. [.\tools\peview\peview.vcxproj]
> hashprp.obj: error LNK2001: unresolved external symbol _fuzzy_hash_buffer@16. [.\tools\peview\peview.vcxproj]
> .\bin\Release32\peview.exe: fatal error LNK1120: unresolved external items: 4 [.\Tools\peview\peview.vcxproj]

and failure next task... I'm assuming the cause of the problem is mine, right?

**Comment by dmex** [comment]
>  rebuild .\tools\thirdparty\thirdparty.sln

Have you executed `\Tools\thirdparty.cmd`?

**Comment by VictorVG** [comment]
Aha! Here's what I missed - I have an old copy of this script customized for my edition of the compiler. I'll correct it now. Thanks a lot for the tip!

**Comment by VictorVG** [comment]
Something I was overjoyed early - even after updating the sources and rebuilding the x64 library, I still can't build it with the same errors. Obviously, I am missing something, but what I don’t understand ...

**Comment by VictorVG** [comment]
v3.0.8890.4363 Git-263f33c1 - build success. Big thanks! I was sure that this was my mistake and I reviewed everything for myself, but I could not find anything that could cause it ...
