### ISSUE TITLE
[Enhanacement] DarkMode view for UI via Options / Plugins

### ISSUE THREAD

**Issue by QuantuMatrix** [processhacker/processhacker#993]
I would like to see the inclusion of dark mode. This could be done through a plugin or directly through the settings.

Currently, there are not alternative ways to have a dark mode process viewer (either Process Hacker or Windows Task Manager)

Would love to help build out this new feature to help support the ongoing upkeep of this project.

**Comment by dmex** [comment]
The nightly builds have included a dark mode for some time. You can enable it via the options window:

![image](https://user-images.githubusercontent.com/1306177/133485521-f10f428d-e695-40b3-88ee-4edb9bee0958.png)

Nightly builds are here:
https://processhacker.sourceforge.io/nightly.php

**Comment by QuantuMatrix** [comment]
Fantastic! That wasn't quite obvious to me when combing through the settings. Thanks @dmex!
