### ISSUE TITLE
Advanced Search Processes Filter

### ISSUE THREAD

**Issue by Zack-src** [processhacker/processhacker#994]
**Is your feature request related to a problem? Please describe.**

When I use the process search bar, I would like to be able to access the results of a search with the module names.

**Describe the solution you'd like**

For example when I search for "Cortana" in the process search bar, Process Hacker shows me all the processes that have a module containing the name "Cortana".

**Describe alternatives you've considered**

Add an option if my idea consumes too much cpu or ram or if the search takes too long

**Additional context**
Screen Example : https://prnt.sc/1s7kfwt

**Comment by dmex** [comment]
> access the results of a search with the module names

This is what the `Find Handles or DLLs` option does already?
