### ISSUE TITLE
Save Tray Menu Choice

### ISSUE THREAD

**Issue by VykosX** [processhacker/processhacker#995]
I really like the mini window with system information that pops up when you click the tray icon, however it always defaults to CPU usage. Please make it so it saves the last selection for what information to display so that next time it's interacted with, it displays that instead of always the CPU usage. That way I could have it showing memory usage whenever I open it instead. =3

Thank you!

**Comment by dmex** [comment]
> however it always defaults to CPU usage

This is because you're only using the CPU usage tray icon. You need to add the tray icon for memory usage then when you move the mouse over that icon it'll display memory usage by default.

**Comment by VykosX** [comment]
Thank you very much!

**Comment by dmex** [comment]
👍
