### ISSUE TITLE
GPU Nodes all show the same graph

### ISSUE THREAD

**Issue by joshwiker14** [processhacker/processhacker#998]
When I open the gpu nodes view in system information, all the graphs show the same data. I do not think all the data is supposed to be the same, and it used to show different graphs before. I'm not sure when this issue started. I noticed it a few weeks ago. I'm also not sure whether my gpu drivers could be causing this. Regular task manager still shows gpu data correctly.
Process hacker is running as administrator.

my process hacker version is : 3.0.4365
My gpu : Nvidia GeForce GTX 1660 SUPER
My driver version: 471.11

![image](https://user-images.githubusercontent.com/5994403/133948459-ee488930-192b-4325-8c1d-5ce9cdacf647.png)
![image](https://user-images.githubusercontent.com/5994403/133948615-fa245138-2554-44a3-8807-84d9f3e55b87.png)

**Comment by aor2021** [comment]
Try to reinstall Process Hacker.

**Comment by dmex** [comment]
Try enabling `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` with setting 1

**Comment by joshwiker14** [comment]
> Try to reinstall Process Hacker: https://processhacker.sourceforge.io/

Unfortunately, even after removing my settings as well, this did not fix it.

**Comment by joshwiker14** [comment]
> Try enabling `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` with setting 1

This worked. Thank you!

**Comment by joshwiker14** [comment]
> Try enabling `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` with setting 1

This worked! Thank you. I can't seem to figure out why it stopped working though.

**Comment by valepakh** [comment]
> > Try enabling `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` with setting 1
> 
> This worked! Thank you. I can't seem to figure out why it stopped working though.

I updated PH some time ago and also noticed that this stopped working.
